### ISSUE TITLE
Optimize B2 access

### ISSUE THREAD

**Issue by fd0** [restic/restic#1000]
This is continuation of the discussion started in https://github.com/restic/restic/issues/512#issuecomment-306041907

TL;DR: restic causes a lot of `b2_list_file_names` API calls which are expensive. We're discussing ways to lower this count.

**Comment by kurin** [comment]
So right now `b2_list_file_names` won't get called a lot: this was fixed for reads, and writes moved to `b2_download_file_by_name` (hereafter DFBN).

This happens on writes because restic calls object.Attrs(), which issues a DFBN and then a `b2_get_file_info`.

DFBN and GFI are class B API calls, which is something like .4c/10k calls (as opposed to LFN, which is .4c/1k).  This makes it relatively cheap: you can call Attrs() 12k times before you pay 1c.

I'm not familiar with the internals of restic but it appears to me that, during a backup, each file system object (file or directory) consumes one Attrs->Write pair.  If the need to call Attrs() can be removed, then uploads would be effectively free (the `b2_upload_*` APIs are all free, as iirc is input bw).

There's another question, though, about optimizing for time.  I suspect the time to restore is dominated by roundtrips to b2, rather than b2 egress bw.

**Comment by aksdb** [comment]
I think currently v0.7 is kinda unusable (yeah, slightly exaggerated) with B2.
I backup ~350000 files, size 16GB in sum.
The initial backup was fine, but taking snapshot burns through Class B Transactions. It cost me 27000 such transactions and I just reached 60% of the snapshot.
Wouldn't it be possible to work with a local cache? To not do API lookups over and over again?

**Comment by fd0** [comment]
We're working on adding a client-side cache for metadata, so MUCH less data is requested from the repo. For now, you can use `restic backup --force`, which instructs restic not to use any existing metadata but re-read and re-hash all files locally. That should reduce the number of requests a lot.

**Comment by aksdb** [comment]
Ah nice. Then you can probably consider my problem solved :-)
restic is really great! Thanks for all your work!

**Comment by jsissom** [comment]
FYI, I backed up a large data set to B2:

Current Files: 463,275
Current Size: 2,461.2 GB

It took many days to do it, but it worked and my data is there.  My data set doesn't change much so I assume my first snapshot after the initial data load would be pretty fast.  A local cache would be awesome if it sped things up even more.

**Comment by fd0** [comment]
We're working on that, and it's almost ready. See #1040.

**Comment by phunni** [comment]
What are the implications of using `restic backup --force`?

**Comment by fd0** [comment]
With `restic backup --force`, restic won't load any meta data (except the index files) from a previous backup from the repo. So that avoids the costly transactions for B2, at the cost of having to re-read and re-hash all files locally. It still won't save any blobs (parts of files) that are already in the repo.

**Comment by kurin** [comment]
Could restic be modified to pull metadata from a particular repo object, or how coupled is the metadata to the objects?

**Comment by rumpuslabs** [comment]
Most of this thread is referring to uploads, and on restic 0.8.1 I'm not seeing a lot of Class B transactions during upload, but during `building new index for repo` as a result of `restic forget <...> --prune`, restic chews through $0.03 worth of Class B transactions. If this happens every day (likely with `--keep-daily`) I will be spending more on Class B transactions than on storage ($0.02/day)... Is there a possibility to optimize an index rebuild to not use so many Class B transactions?

**Comment by ifedorenko** [comment]
Have you tried master? #1541 is supposed to reduce number of repository file load requests during index rebuild by ~3x compared to 0.8.1.

**Comment by fd0** [comment]
This issue has been resolved mostly in #1623, so I'm closing this issue. Please give the code in the master branch a try! You can find a beta here: https://beta.restic.net/restic-v0.8.2-14-gbe020080/
