### ISSUE TITLE
Corrupted index if prune fails at PUT request because of HTTP error 413

### ISSUE THREAD

**Issue by snc** [restic/restic#1032]
## Output of `restic version`
```
restic 0.6.1
compiled with go1.8.3 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
`restic --password-file restic.key forget -d 14 --prune`

## What backend/server/service did you use?
Minio behind NginX Proxy with `client_max_body_size 64m;`

## Expected behavior
Pruning the backup

## Actual behavior
Pruning was interrupted

## Steps to reproduce the behavior
Have a backup which produces a bigger index than the configured `client_max_body_size`.

## Do you have any idea what may have caused this?
NginX rejected the PUT request:

`2017/06/14 03:16:23 [error] 44#44: *19418996 client intended to send too large body: 154789219 bytes, client: *.*.*.*, server: ..., request: "PUT /backup/restic/index/123666bf3f20a1174f3ade36706523ea82dee8589986885e029f9efd2a576624 HTTP/2.0", host: "..."`

## Output of `restic check`
```
Create exclusive lock for repository
Load indexes
pack 1031ddb3 contained in several indexes: {20b29622 8727bcdc}
pack 0030e25a contained in several indexes: {8727bcdc fbbf70f8}
pack 26e5eaf8 contained in several indexes: {732604da b2b85545}
pack 63d5d5d0 contained in several indexes: {06913126 b3f50206}

run `restic rebuild-index' to correct this
Check all packs
pack 59338439dd8e2c3d4f774e910acdb1e22a66efcbe812a5dd90309d2125e309fa: does not exist
pack ...: does not exist
...
pack 003d4dc2c51bf14faa17ea64a6fb245dc1250ef22a7d66744900ab22ed45c453: not referenced in any index
pack ...: not referenced in any index
...
Check snapshots, trees and blobs
error for tree 2dd33bfe:
  The specified key does not exist.
error for tree ...:
  The specified key does not exist.
...
Fatal: repository contains errors
```

## Additional informations
The following backup produced many `error loading tree: The specified key does not exist.` messages but finished with `snapshot af93d3c1 saved`.

Another `forget -d 14 --prune` resulted in:
```
1 snapshots have been removed, running prune
counting files in repo
building new index for repo
[2:54] 100.00%  20561 / 20561 packs

repository contains 20561 packs (1298962 blobs) with 108.481 GiB bytes
processed 1298962 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 14 snapshots
The specified key does not exist.
```

## Output of `restic rebuild-index`
```
counting files in repo
[1:44] 100.00%  20561 / 20561 packs
finding old index files
saved new index as 42c413a0
remove 95 old index files
```

After running `restic rebuild-index` the check command reports no errors anymore.

I know that the 64MB limit was quite low, after increasing it the prune worked as expected.

Question is if this case can be handled by restic to prevent index corruption?

**Comment by fd0** [comment]
Thanks for raising this issue. I'm not sure what the exact timeline was, can elaborate on that a bit?

What I'm guessing is:
 * `restic backup` successful
 * `restic forget --prune`, uploading a new index failed because of the upload limit of 64MB
 * `restic check`, many error messages regarding non-existing pack files
 * `restic backup` again, error messages, but backup seemed to be successful
 * `restic rebuild-index` successful, everything working now

Is that correct?

**Comment by snc** [comment]
Timeline was:

* `restic backup` successful
* `restic forget --prune`, uploading a new index failed because of the upload limit of 64MB
* increased upload limit
* `restic backup` again, error messages, but backup seemed to be successful
* `restic forget --prune` again, resulting in

```
1 snapshots have been removed, running prune
counting files in repo
building new index for repo
[2:54] 100.00%  20561 / 20561 packs

repository contains 20561 packs (1298962 blobs) with 108.481 GiB bytes
processed 1298962 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 14 snapshots
The specified key does not exist.
```

* `restic check`, many error messages regarding non-existing pack files
* `restic rebuild-index` successful, everything working now
* `restic check` again, no errors

**Comment by fd0** [comment]
Thanks for the clarification. I'm glad that restic recovered so well :)

What happened here is approximately the following:
 * `prune` couldn't upload a new index. At that point, it had already removed pack files, wrote still used data into new pack files, uploaded those new pack files successfully and removed the old index files. Important: All needed data was still present, in the repository, there just wasn't any index present.
 * `backup` then saw a snapshot for the directory/file to be saved, but since there was no index it couldn't load any information on the state of the files/dirs at the time of the last bakup. It reported this, albeit in a way that is hard to decipher. It also uploaded all data to the repository again. So you ended up with a lot of duplicate data.
 * `prune` again, it starts by building a new index from scratch, so it should've found all data. I'm not completely sure what went wrong here, it probably was unable to find a tree object (directory) from an older snapshot. Hm.
 * `check` just reported that there are pack files which are not referenced in any index
 * `rebuild-index` created a new index from scratch which covers all pack files.
 * `check` is then able to find all referenced data.

So, I'm going to mark this as a bug, and we'll change the following for `prune`:
 * Only remove any data AFTER successfully uploading new pack files AND the new index.
 * Maybe improve the error message

I'll also try to reproduce the situation.

**Comment by snc** [comment]
I don't think that it really uploaded all data again. The backup after the failed prune used the snapshot from the last backup (the one right before the failed prune). Normally the backups take ~30min, the one after the failed prune took ~40min. I also checked the network statistics and I don't see any peeks.

**Comment by fd0** [comment]
Hm, maybe you're right.
