### ISSUE TITLE
Whether to support speed limit？

### ISSUE THREAD

**Issue by james0479** [restic/restic#1041]
It is easy to load the system and its consumption of memory, serious, multiple servers almost can not connect。Whether it can be like rsync limited speed function, bwlimit parameters。Looking forward to your reply

**Comment by fd0** [comment]
Hey, thanks for raising this issue. Since you haven't filled out the issue template I don't know what your situation is and can only make a vague guess.

There are two different things at play, both are tracked already:
 * Limiting the network bandwidth for backup is tracked in #232 
 * Limiting the IO bandwidth used for the backup is tracked in #322 

So I'm going to close this issue as a duplicate, please subscribe to the other issues if you'd like to be notified. Thanks!
