### ISSUE TITLE
Support --json flag with backup command

### ISSUE THREAD

**Issue by tamalsaha** [restic/restic#1063]
We would like collect info about a backup action from script. But --json flag is not supported for `backup` command. Can this be supported?

**Comment by fd0** [comment]
Good point, I can add this when I refactor the archiver.

**Comment by xcezzz** [comment]
Hi,

I actually had already started this since we planned to wrap restic within a GUI application.

Although a bit off from being worthy of a pull request, my fork allows for --json and will output data in the format...

```json
{
"type":"archive",
"duration":332406583,
"directories":28,
"files":324,
"completed":130878418,
"total":11437998853,
"bps":0,
"completed_bytes":130878418,
"items_done":106,
"items_total":352,
"total_bytes":11437998853,
"eta":0,
"errors":0,
"seconds":0
}
```

type: switches between "archive" and "scanner" to differentiate what process it is in the middle of... 

Currently though you should be aware that sometimes output buffering within the console or whatever you plan on having read this information can cause it to delay and then burst with so much info... using unbuffer from expect fixes this.

https://github.com/xcezzz/restic/tree/json-backup-status

@fd0 in an effort to help out with this what would you recommend being done so that I can get this merged in as it seems to be something a lot of people want...

**Comment by middelink** [comment]
I think you should integrate that progress_output.go file into cmd_backup. It is completely private to the backup function. E.g. it is not a generic helper function.
Also you need to sync and remove some debugging? That commented out return looks suspicious.

Oh, and for commenting it's easier if you make it a PR on this repo...

**Comment by whereisaaron** [comment]
The JSON output idea for non-interactive use is a nice idea, but could it be without line breaks please? That way is also suitable for non-interactive logging output also.

**Comment by agrover** [comment]
Yeah, I'm looking at adding support for Restic to [DejaDup](https://wiki.gnome.org/Apps/DejaDup) (Restic's cmdline is tantalizingly close to Duplicity, which is currently used by DejaDup) but I need something that can be parsed while running, so either incremental json or some other way for programmatic interaction is needed to do this reasonably.

**Comment by jasperjorna** [comment]
What is the latest status on this? I see that there is a`--json` flag for 'some' commands, but `backup` doesn't seem to be supported as of `0.9.4` yet?

**Comment by fd0** [comment]
Ah, this should have been closed! Support for streaming JSON status for `backup` was added in #1944, which is contained in master but not in any release yet. But all the [beta binaries](https://beta.restic.net/?sort=time&order=desc) have it.

I'm closing this issue, the next release of restic will include support for it. Thanks!
