### ISSUE TITLE
Restic - Not compatible with Swift Container ACL

### ISSUE THREAD

**Issue by rossmartyn04** [restic/restic#1096]
## Output of `restic version`

restic 0.7.0 (v0.7.0-12-g637de01)
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

./restic -r swift:restic_backups:/backup snapshots

## What backend/server/service did you use?

OpenStack Swift -  (Memset Memstore /w RW permissions on 'Container'.)

Container : restic_backups
Read ACL: tenant:restic
Write ACL: tenant:restic

## Expected behavior

List snapshots!

## Actual behavior

unable to open repo at swift:restic_backups:/backup:
Account(): Operation forbidden

## Steps to reproduce the behavior

Create a container with a swift user, allow Read/Write permissions to container only.

## Do you have any idea what may have caused this?

Logs from swift proxy:

swiftproxy proxy-server.... HEAD /v1/AUTH_tenant HTTP/1.0 403 - goswift/1.0 tenant:restic%AUTHTOKEN - - - TXID 0.0002 - -

It looks like Restic is trying to run a head on the account, rather than the container its self.

It would be useful for Restic to support non-admin users.

Able to replicate using Curl.

curl -v -X HEAD -H 'X-Auth-Token: TOKEN' https://proxy1.provider.com/v1/AUTH_tenant_uuid/ Returns - 403

curl -v -X HEAD -H 'X-Auth-Token: TOKEN' https://proxy1.provider.com/v1/AUTH_tenant_uuid/restic_backups Returns - 204

**Comment by analbeard** [comment]
I'm also seeing this problem - it would be good to be able to use Swift credentials with the lowest privilege possible!

**Comment by fd0** [comment]
Hey, thanks for raising this issue. Originally, we used a lookup on the account to test if the server supports byte ranges (code provided by a contributor, not be me), but turns out this check is not reliable (see #1084 for details), so we'll remove it anyway. It sounds like this could also resolve this issue. If you'd like to check that, just remove these two blocks and recompile restic: https://github.com/restic/restic/blob/master/src/restic/backend/swift/swift.go#L94-L101

Please report back!

**Comment by rossmartyn04** [comment]
That seems to have done the trick! That's great news! I'll look forward to this being removed. Thanks for the quick turn around!

**Comment by fd0** [comment]
I think this is resolved in 0.7.1, so I'm going to close this issue.
