### ISSUE TITLE
Compare snapshots

### ISSUE THREAD

**Issue by scoddy** [restic/restic#11]
Implement feature to compare two or more snapshots, show differences of files + size
- Show added files/directories
- Show deleted files/directories
- Show modified files/directories 

Use case: find a specific version of a file, compare directory structure of multiple snapshots, etc.

**Comment by fd0** [comment]
Whoops, that was the wrong issue, reopened.

**Comment by silvio** [comment]
I need this feature too.

I would prefer a git like syntax. Like this:

* View of one snapshot
```
$ restic snaphots f406fb61
f406fb61  2015-08-12 10:00:03  develbox    /home/.../x
+x/a
+x/b
-x/c
```

* View of a diff bitween snapshots
```
$ restic snapshot 99edb339..f406fb61
f406fb61  2015-08-12 10:00:03  develbox    /home/.../x
99edb339  2015-08-11 18:00:02  develbox    /home/.../x
+x/a
-x/b
```

* To view files added/deleted till and since a snapshot we can take the same looklike git `id..` and `..id`.

* With a option like `-s` we can add some sattistic datas as is needed in #10.

**Comment by ckemper67** [comment]
An easy way to implement diff functionality may be to write all the metadata for a snapshot to a file, one line per entry. That is useful functionality in itself and it allows you to run the output through diff for easy comparison.

**Comment by fd0** [comment]
You can already do that by using the `ls` function:
```shell
$ diff -au <(restic ls -l 3a12314) <(restic ls -l af0ebba)
```
