### ISSUE TITLE
Enhancement: Add a snapshot IDs directory to the FUSE mount

### ISSUE THREAD

**Issue by McKael** [restic/restic#1102]
Currently we can see snapshots by hosts, date and tags.
It would be nice to be able to browse snapshots per ID in a FUSE mount, with  a special directory.

E.g.: `ls -l /mnt/restic/ids/3662613c`

**Comment by fd0** [comment]
Nice idea!

**Comment by maxkueng** [comment]
In order to better support automation I think it would make sense if `ls -l /mnt/restic/ids` would use the long versions of the IDs since this is what `restic snapshots --json` outputs.

Another option would be to use the short IDs but add the short ID as an additional field to the `restic snapshots --json`  output.

**Comment by fd0** [comment]
Hm, interesting. Let's discuss this with @mungomat, since he did the PR.

**Comment by McKael** [comment]
Thanks @mungomat !
