### ISSUE TITLE
Restic restore ignores $RESTIC_REPOSITORY

### ISSUE THREAD

**Issue by Niondir** [restic/restic#1109]
## Output of `restic version`
```
manager@srv1:~$ restic version
restic 0.7.0
compiled with go1.8.3 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)

```
manager@srv1:~$ restic restore --target /var/data latest
Fatal: Please specify repository location (-r)

manager@srv1:~$ restic help restore
The "restore" command extracts the data from a snapshot from the repository to
a directory.

[...]

  -r, --repo string            repository to backup to or restore from (default: $RESTIC_REPOSITORY)

manager@srv1:~$ echo $RESTIC_REPOSITORY
/var/restic
```

## What backend/server/service did you use?
All local

## Expected behavior
No need for `-r` option

## Actual behavior
Error when not specifying `-r` even if `$RESTIC_REPOSITORY` is set.

## Steps to reproduce the behavior
See above.

## Do you have any idea what may have caused this?
no.

**Comment by fd0** [comment]
Hey, thanks for raising this issue. I'm unable to reproduce it, though. Did you export `RESTIC_REPOSITORY`? You can check with:

```
$ sh -c 'echo ${RESTIC_REPOSITORY:-unset}'
```

**Comment by Niondir** [comment]
Ah great, now I understand what export does ;) I guess restic had no chance.

**Comment by fd0** [comment]
Heh, glad we could find the issue. :)

**Comment by Xetera** [comment]
Just leaving this here hoping that it might help another lost soul but my issue was having to use `sudo` because I didn't have permissions to restore the backup in the location I chose and I didn't realize that overrides previous variables with the root user's.

`sudo -E restic restore ...` was the solution in my case to prevent `$RESTIC_REPOSITORY` from being overridden, though if possible, you should probably just fix the permissions issue instead 🙂
