### ISSUE TITLE
Upgrading from 0.3.3

### ISSUE THREAD

**Issue by AlexDunmow** [restic/restic#1111]
I can't find any documentation on upgrading Restic. Will my repos be backwards compatible? Is there anything I should know before making this change?

**Comment by fd0** [comment]
Hey, you can use restic directly, in regards to the structure of the repo, nothing has changed. Except when you're using a repo stored in s3, the directory names have changed, but the old ones still work just fine. You can use the new `migrate` command if you'd like to migrate to the new names. Otherwise, have a look at the release notes of each release from 0.3.3 on.

I'm going to close this issue as your question is answered, please feel free to leave a comment! Especially, let us know if something does not work :) thanks!
