### ISSUE TITLE
Progress is unclear about what is being uploaded during backup

### ISSUE THREAD

**Issue by soamaven** [restic/restic#1135]
1) I do a full root back up as `sudo` using `restic` to a remote NAS. It takes way long than I would think it should given the backup is supposed to be incremental. I have 1.4 GiB that have changed, yet `restic` is uploading the full size of the snapshot. The backup directory does not increase in size by the full backup size (37 GiB), but by the expected size of the changed files (1.4 GiB). So, why am I uploading the entire back up, taking forever, only to save the incremental changes?

2) The progress should indicate what it is uploading. Something like:
`[32:48] 100.00%  19.757 MiB/s  37.971 GiB / 37.962 GiB ` **changes** ` 834110 / 834111 items  0 errors  ETA 0:00`

Am I just doing something wrong? The documentation provides no guidance here, and I couldn't find any other similar issues, open or closed. 

## Output of `restic version`
```
$ restic version
restic 0.7.0 (v0.7.0-37-g6c053530)
compiled with go1.8.1 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
```
$sudo restic -r sftp:user@1host:/path_to/restic_backup backup / -e /path_to/exclu_list.txt -x -p /path_to/passwd.txt
```

## What backend/server/service did you use?
sftp

## Expected behavior
```
$sudo restic -r sftp:user@host:/path_to/restic_backup backup / -e /path_to/exclude_list.txt -x -p /path_to/passwd.txt
using parent snapshot 80d2833d
scan [/]
scanned 86574 directories, 747537 files in 0:35
[1:11] 100.00%  19.757 MiB/s  1.39 GiB /1.39 GiB  834110 / 834111 items  0 errors  ETA 0:00 
duration: 1:11, 19.75MiB/s
snapshot 735e57f4 saved
```

## Actual behavior
```
$sudo restic -r sftp:user@host:/path_to/restic_backup backup / -e /path_to/exclude_list.txt -x -p /path_to/passwd.txt
using parent snapshot 80d2833d
scan [/]
scanned 86574 directories, 747537 files in 0:35
[32:48] 100.00%  19.757 MiB/s  37.971 GiB / 37.962 GiB  834110 / 834111 items  0 errors  ETA 0:00 
duration: 32:48, 19.75MiB/s
snapshot 735e57f4 saved
```

## Steps to reproduce the behavior
1) implement `restic` backup using file structure from previous backup

## Do you have any idea what may have caused this?
No.

**Comment by fd0** [comment]
Hey, thanks for the report. This is actually a user interface story: restic prints (a bit misleading, I admit) the amount of data it has processed and the speed at which it processes data. That is, as you have noticed, not the same as the metric in which you're interested: The amount of changed/new data, and the upload throughput to the repository.

Sometime we'll get around to reworking the user interface and the archived, and I'm sure this will get addressed. Thanks!

**Comment by soamaven** [comment]
So, the processing combined with the uploading of incremental changes occurred at a speed of ~19MiB/s? Any way to speed up the processing?

**Comment by fd0** [comment]
I'm trying to answer your questions one by one:
> So, the processing combined with the uploading of incremental changes occurred at a speed of ~19MiB/s?

Roughly, yes. Whereas "processing" means "restic looks at the files and only uploads them if they have changed".

> My upload speed is on the order of 2.7MiB/s, so at that rate, sending 1.4GiB would have taken 8:55. I would expect that this is my bottleneck. What is taking so long?

This is a limitation restic currently has: For your use case (limited by upload speed) restic is slow because it detects that there has been a previous snapshot, and incrementally loads metadata from the repo as it is needed. Depending on the latency to the remote that waiting time for metadata to arrive sums up to quite a lot of time, so the overall process is not as fast as it could be. We're currently working on that (see #1040). In the meantime, you can try running `restic backup --force`, which will not load any metadata from the repo. Instead, all files will be read and hashed again locally, so restic can decide which blobs are not present in the repo any more. This will cause much more CPU and IO load locally, but may be faster.

> I did look at my system upload totals, only 1.6 GiB was been uploaded for my session, so, yes, restic did only upload the changes. Any way to speed up the processing?

Try `restic backup --force` and report back.

> And what does the ~19MiB/s indicate if not the bottleneck?

Roughly it's the amount of data processed (looked at, not necessarily read) divided by the runtime. That's mostly only accurate for the initial backup.

> I thought the processing speed was indicated by:
> scanned 86574 directories, 747537 files in 0:35 ?

That is an entirely different phase: restic walks the directories to be saved and counts the files and sums up the size. There's no processing involved here at all.

**Comment by soamaven** [comment]
Thanks for the detailed explanation, If this was in the documentation, I apologize. Maybe it should be more clear in the progress bar, or the documentation.

I used the `--force` option but got the same result, just with more CPU usage. Do you think I will have better results with a REST server? Planning on implementing that soon.

**Comment by fd0** [comment]
I think that this is not in the documentation, and we plan to rework the progress reporting anyway.

The REST server can give you a bit more speed (sftp is a pretty bad protocol for transferring large amounts of data concurrently), but don't expect miracles.

**Comment by MichaelEischer** [comment]
@soamaven The misleading bandwidth information has been removed quite some time ago and restic prints backup statistics when run as `--verbose`. Showing the real upload bandwidth would then be tracked in #1581. Did I miss anything or can we close this issue?

**Comment by MichaelEischer** [comment]
Closing this issue as the remaining part is tracked in #1581.
