### ISSUE TITLE
restic restore --path doesn't seem to work as expected

### ISSUE THREAD

**Issue by mbiebl** [restic/restic#1165]
## Output of `restic version`

restic 0.7.1
compiled with go1.8.3 on linux/amd64

I use restic to backup two folders: /mnt/data and /home/michael. 
```
# restic snapshots
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
...
a1d6b768  2017-08-17 19:07:25  pluto               ┌── /mnt/data
                                                   └── /home/michael
```
I tried to restore the latest snapshot for the /mnt/data folder using the following command:
```
restic restore latest --target /tmp/restore --path /mnt/data
```
restic tried to restore both /mnt/data and /home/michael.
Either I have misunderstood the documentation on how --path is supposed to be used (in which case I would appreciate some clarification) or --path is not working as expected.

**Comment by fd0** [comment]
Ha, interesting case, thanks for reporting it. The `--path` parameter is indeed meant for something else: When you don't specify a specific snasphot Id to restore, restic will try to restore the latest snapshot. When you have several different directories saved (as separate snapshots, e.g. `/foo` and `/bar`) in the repo, restic needs to decide which one is the latest snapshot. So in order to restore the latest snapshot of all the snapshots that contain `/foo`, you can use `restic restore --path foo [...]`. So `--path` is only to restrict the snapshots that are considered when finding the latest snapshot.

In order to only restore the dir `/mnt/dat` from the backup you'd work with `--include` like this:
```
$ restic restore --targe /tmp/restore --include /data
```

You can find the correct path for `--include` by running `restic ls latest` (which also has the `--path` option). Due to #549, the prefixes `/mnt` and `/home` are not saved in the repo.

Did that help?

**Comment by mbiebl** [comment]
That seems to do the trick, thanks.
Needless to say, that using --include /data is a bit odd when the original path was /mnt/path, i.e. I hope #549 is fixed soon.

**Comment by MichaelEischer** [comment]
Closing this as the issue seem to be resolved.
