### ISSUE TITLE
Optimization for Linux: Figure out if using posix_fadvise and posix_fallocate work

### ISSUE THREAD

**Issue by fd0** [restic/restic#117]

**Comment by cfcs** [comment]
posix_fallocate(1) is essentially a compatibility wrapper for fallocate(2) -- on Linux -- for the filesystems that support fallocate - glibc manpage for the fallocate(1) wrapper:
- As of the Linux Kernel v2.6.31, the fallocate system call is supported by the btrfs, ext4, ocfs2, and xfs filesystems. [cfcs: perhaps also tmpfs/ramfs, although I haven't tested]

If you're going to create custom go bindings, perhaps you could have a compiler switch / macro for Linux builds that uses fallocate(1). if possible, and returns a static "not implemented" error code otherwise, so you don't have to jump into glibc and parse ENOSYS ("syscall not implemented") error codes en masse?

BTW: Bear in mind that EOPNOTSUPP ("syscall implemented, but not for this filesystem") could potentially be returned for some files, but not others, since the datasets being archived could reside on different filesystems.

fallocate(2) is like creating a sparse file with ftruncate(2), but with a guarantee that the space is available (if it succeeds). When posix_fallocate(1) is used on an unsupported filesystem, or another OS which doesn't implement this feature, it falls back to actually writing null blocks to disk (as well as reading them back to ensure it worked!), which can be quite expensive and seems a bit unnecessary in this case.
Might as well just get the error when writing the actual data (|pwrite(2)| x n)
instead of ( |pread(2) x pwrite(2) x pwrite(2)| x n)?

**Comment by fd0** [comment]
Thanks for your explanation. I just created this issue to remind myself (or somebody else) to look into it.

**Comment by ThomasWaldmann** [comment]
posix_fadvise with DONTNEED for all input data read might be much more interesting than posix_fallocate for output data.

**Comment by fd0** [comment]
Braindump from reading a bit about fadvise:
 * https://github.com/borgbackup/borg/issues/158
 * http://insights.oetiker.ch/linux/fadvise/

**Comment by zcalusic** [comment]
I would strongly advise (sic!) against using posix_fadvise DONTNEED! Because it would hit and discard useful cache data from beneath the running applications and bring more trouble than good.

The Linux page cache (at least) is very efficient at discarding once read data (it is in so called inactive page cache), so lets not interfere with excellent Linux kernel mechanisms and running applications.

In most cases twiddling with posix_advise parameters is bad.

**Comment by fd0** [comment]
We're already using `favise` to tell the kernel that we don't need the data any more. I've done benchmarks and this is extremely helpful, otherwise the kernel tends to swap out memory of other processes in order to increase the cache size. I have no idea why it does that, but `fadvise` helps a lot. See #487

**Comment by fd0** [comment]
I'm going to close this issue as `fadvise` is implemented and it's not looking like we're going to need `fallocate`.
