### ISSUE TITLE
Find lock files

### ISSUE THREAD

**Issue by mnesrine** [restic/restic#1264]
We use Restic with Minio Server, and from time to time we have a lock.
Can i found a lock file in Minio server ? 
If i remove it from server with 'rm' will unlock the system or we must use Restic command to unlock ?

Thanks.

**Comment by fd0** [comment]
I'm not sure if you can just remove a file in the data directory of the Minio server. From restic's point of view you can remove the lock after making sure that it is indeed an old lock. It'd be interesting to know though why the locks were left in the repo in the first place.

I'm going to close this issue since your question is answered. Please feel free to add further questions. Thanks!
