### ISSUE TITLE
"error loading tree: ReadFull(<data/22a6ed12a6>): EOF" during backup

### ISSUE THREAD

**Issue by armhold** [restic/restic#1278]
I got a screenful of `error loading tree:ReadFull()` warnings on my first backup since upgrading to the local cache feature in master. The repo is local, 199GB in size, and has around 35 snapshots, dating back to `2017-08-12`.

## Output of `restic version`

```
restic compiled manually
compiled with go1.9 on darwin/amd64
```

Built from:
```
git rev-parse HEAD
bff1039e3aac4995580b4cd334576ae1d133f1b2
```
with no local changes.

## How did you run restic exactly?

`restic -r /Volumes/backup1/restic-repo backup ~ /Volumes/data1 --hostname george-iMac --exclude-file ~/restic-excludes`

## What backend/server/service did you use?

Local.

## Expected behavior

Backup should complete without warnings.

## Actual behavior

On my first backup since upgrading to the `local-cache` enhancement, I got a screenful of warnings like:

```
scanned 133964 directories, 511998 files in 1:52
error loading tree: ReadFull(<data/22a6ed12a6>): EOFB  299805 / 645962 items  0 errors  ETA 0:40 
error loading tree: ReadFull(<data/22a6ed12a6>): EOFB  299847 / 645962 items  0 errors  ETA 0:40 
error loading tree: ReadFull(<data/22a6ed12a6>): EOF
```

## Steps to reproduce the behavior

Not reproducible thus far- subsequent backups to the same repo complete without any warnings. I also tried on a few smaller "test" repos that I had around, and no warnings.

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No.

**Comment by armhold** [comment]
In https://github.com/restic/restic/pull/1040#issuecomment-331863195 @fd0 asked me to check the size of `data/22/22a6ed12a6`. It looks fine, I think?

```
ls -l data/22/22a6ed12a61fda8da3996364c35e87daab758a103f72b1766fedebf57a987915 
-r--------  1 armhold  staff  4246570 Sep 22 08:24 data/22/22a6ed12a61fda8da3996364c35e87daab758a103f72b1766fedebf57a987915
```
I tried `cat pack 22a6ed12a6 | strings` and that completed without warnings. It does seem to have some valid data in it.

**Comment by fd0** [comment]
Ah, thanks a lot for the comprehensive report! That verified my hunch, it's a concurrent access problem when the cache is busy downloading a file. It goes like this:

It happens when restic is busy downloading a pack file and a second read request comes in for the same file. The cache then thinks the file is already there (it is, but it's empty) and then the read error happens.

But it won't hurt or anything, the backup progress will worst-case just re-read the files. And as soon as the file download is complete, it's gone anyway.

So, I'll add a bit of code to block the second request until the first is done, then serve the cached content.

**Comment by armhold** [comment]
"Downloading a pack file"- my report is against a local repo. I'm guessing you mean that in an abstract way, but just want to be clear.

**Comment by fd0** [comment]
The cache is also used for a local repo (we cannot know if the repo really is something remote), unless disabled with `--no-cache`. So "downloading a pack file" here means "copying a pack file to the cache".
