### ISSUE TITLE
Question: Is there a way to skip whole creation of a snapshot if *any* files were locked during its creation?

### ISSUE THREAD

**Issue by thumbline** [restic/restic#1347]
I couldn't find the answer or a flag that would allow for it.
Basically, how to perform a snapshot **only when** none of the files were busy or locked?

**Comment by fd0** [comment]
There's no such switch. What does "busy or locked" mean exactly?

**Comment by thumbline** [comment]
I would love to actually provide a patch, if I figure out how to rollback the snapshot. As far as I understood it cannot be just undone, there should also follow the pruning process. Is that correct?

**Comment by fd0** [comment]
Unfortunately you did not fill out the issue template, so I've got no idea which OS you're using. For restic, the general policy is to report the error to the user and carry on, so that's exactly what happens: restic tries to read a file, that fails, it reports the error and goes on.

The error sounds like you're using restic on Windows. Are you aware that you can use a volume shadow copy (VSS) and backup that? so you don't run into any locking problems.

**Comment by thumbline** [comment]
Thank you @fd0. I'll do that for now
