### ISSUE TITLE
restic prune is slow

### ISSUE THREAD

**Issue by gransear** [restic/restic#1348]
## Output of `restic version`
restic 0.7.3
compiled with go1.8.1 on linux/amd64

(actually running github master)

## How did you run restic exactly?
restic prune -o b2.connections=40 --repo b2:bucket:/path

## What backend/server/service did you use?
backblaze b2

## Expected behavior
complete the task in a reasonable time

## Actual behavior
Prune is very slow, at this speed it will take 7 days to complete.

> will delete 2440 packs and rewrite 19141 packs, this frees 31.369 GiB
> [30:42] 0.29%  56 / 19141 packs rewritten
> 

## Do you have any idea what may have caused this?
It looks like prune do not use multiple connections, lsof shows only two connections to B2 despite the parameter b2.connections=40

**Comment by gransear** [comment]
And prune didn't complete due to error

> unexpected end of JSON input41 packs rewritten
> Copy
> github.com/restic/restic/internal/repository.Repack
> 	src/github.com/restic/restic/internal/repository/repack.go:43
> main.pruneRepository
> 	src/github.com/restic/restic/cmd/restic/cmd_prune.go:274
> main.runPrune
> 	src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
> main.glob..func15
> 	src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
> github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
> 	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:650
> github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
> 	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:729
> github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
> 	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:688
> main.main
> 	src/github.com/restic/restic/cmd/restic/main.go:69
> runtime.main
> 	/usr/lib/go-1.8/src/runtime/proc.go:185
> runtime.goexit
> 	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197
> [12:28:24] 6.15%  1178 / 19141 packs rewritten
>

**Comment by fd0** [comment]
You're right, this is indeed something we we need to improve. Thanks for opening the issue.

**Comment by karl-gustav** [comment]
@gransear Does it take a long time before you get the progress output? I just get the "password is correct" message and then nothing, been waiting days now...

**Comment by fd0** [comment]
@karl-gustav it should definitely not take days, hm. Can you please rebuild restic and create a debug log ([instructions](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs)) and upload it somewhere? Please make sure to replace any sensitive details included in there (authentication tokens, passwords etc) before posting it. You can abort if it takes too long, the debug log should be written regardless.

**Comment by karl-gustav** [comment]
@fd0 I'll rebuild and test as soon as I get home from work!

**Comment by karl-gustav** [comment]
@fd0 Here is a copy of the log that was produced by the debug build: https://gist.github.com/karl-gustav/9a2c5a2bb9c1d4ef0b59c581076887ac ( with personal stuff replaced by `<removed>`)

**Comment by fd0** [comment]
Hm, at the point the log ends restic is still loading and decoding index files. They should already be cached locally. Can you try re-running with `-o b2.connections=20`?

**Comment by karl-gustav** [comment]
@fd0 here is the log with `-o b2.connection=20`. And I had forgotten that I had done the backups as root and therefore probably couldn't use the cache as a non root user, so this time I ran it as root again. https://www.dropbox.com/s/znnfu54wffj3you/restic2.debug.log?dl=0 (136MB)

**Comment by karl-gustav** [comment]
@fd0 by chance I checked the screen session that restic was running in and now it has percentages :+1: 29% to be exact :-D

So the whole reason for the slowness was then most likely the fact that I ran `prune` as a non root user.
But does this mean that I will never be able to run the `prune` command on another computer than the one I run the backups from?

**Comment by fd0** [comment]
> But does this mean that I will never be able to run the prune command on another computer than the one I run the backups from?

Not at all. When restic is run as a different user, it should recreate the cache and get the job done. The exception to this is if the cache dir is not writable for the current user, then it prints an error (and everything will take ages). Did you run `prune` with the cache enabled before? If not, the first `prune` may take longer, the subsequent ones will be much faster (independent of the user/computer you run it on).

I can see from the debug log that the cache is still being populated as `prune` runs, so please be a bit patient and report back when it finishes.

How large is that repo? It looks like you have quite some snapshots in there, at least there are 145 index files... after the prune is done, they will be combined into one.

**Comment by karl-gustav** [comment]
@fd0 That's the the thing, I _don't_ get the error message when he can't use the cache, I only get the "Password is correct" message. The repo finished OK \o/ It's a bit under 300GB, and less than 10 snapshots, but I probably had a lot of aborted prunes and maybe aborted backups (and aborted cleanups from those again). I don't know when the index files are created, but if any of those things creates the index files it would probably explain it :-/ 

PS: Super happy with your work, it has been a lifesaver now that crashplan has discontinued their home plans :-)

**Comment by fd0** [comment]
> I don't know when the index files are created, but if any of those things creates the index files it would probably explain it :-/

Index files are created during backup, even when the backup is aborted. So I'm glad you figured it out.

> PS: Super happy with your work, it has been a lifesaver now that crashplan has discontinued their home plans :-)

Thanks!

**Comment by fd0** [comment]
I'm going to close this issue for now, @gransear can you please test again with 0.8.0? The first `prune` will be slow, the next ones will be much better. Please report back if prune is still very slow. Thanks!

**Comment by gransear** [comment]
I'm testing it with master, 0.8.0 was useless because of pipe broken errors, that interrupt the progress. I still can't complete purge due to one threaded nature of pack rewrites. Is it possible to at least to remember the progress of pack rewrites? Right now if I stop restic prune half-way, it will do each rewrite (and then some) again.

**Comment by batmat** [comment]
Given I stumbled into this from Google, I'm going to leave a comment here about how I made my pruning much faster :) (and why I think I will not bother about prune anytime soon).

Writing this for two reasons: 1) to possibly help others and 2) hopefully get confirmation/advice from @fd0 that it can be a good strategy and that it will not lose data (or how to possibly do some things better).

I wanted to run `restic prune` both as an experiment, and somehow to cleanup my initial testings from a few weeks ago that I had called `restic forget` on since.

-----

So, given my understanding was that the pruning process is somehow an optimization/cleanup of the remote data, I assumed that having the actual backed up data locally wouldn't be necessary. IOW, that I could actually `prune` from another machine.
Also, as IIUC this is an operation that is mostly latency induced, I thought I'd try using a VM in the Cloud to get a much higher bandwidth than on my home network.

Hence I provisioned a VM in the Cloud, added the right ``export``s for `RESTIC_REPOSITORY`, `RESTIC_PASSWORD` and so on, and then ran `restic prune` from there.

* On my laptop, from my home network where my upload is really low, it had taken ~10 hours to reach <50% of the prune process before I stopped it
* On the Cloud VM (hosted in an OVH VPS), it took 115 minutes.
* The data is ~ 270 GB, hosted in [Google Cloud Storage Coldline](https://cloud.google.com/storage/docs/storage-classes#coldline).

![image](https://user-images.githubusercontent.com/223853/53695664-b027f500-3dbe-11e9-8f86-337670d4d6b9.png)

-----

### Conclusion
Given most of the backup backends are generally optimized for upload costs, and **very** expensive for download, if your goal is to run a long lived backup, I think running `prune` is going in most cases to be a _unnecessary waste of money and time_.

In my case, **because** I had backed up many things that I then excluded after I fine tuned my backup process during my initial tinkering with `restic`, I saved ~12GB. 

From what the Google Cloud billing console tells me, the overall pruning cost was ~0.58€ (because IIUC `restic` needs to download, recompute, and reupload many packs). I.e. As Coldline is `0.007$` per GB the saving per month is going to be `12*0.007=0.084$`. This means it will take me 7+ months to compensate the cost of the pruning... 

And again, given we're talkinig about <1$ for roughly a few hours of work/thinking, I don't think I earned anything else really than an interesting experience/insight around data backup (which is nice, still :)), but nothing from a financial perspective.

Note that if you plan to have a very varying set of data, and you plan to forget anything else than a few days, then `prune` might make sense to you.

If you're like me and plan to keep data forever or so with exponential intervals, probably you don't want/need to call `prune` ever.

For my own case, given this experience, I _think_ I will possibly call this once a year or so, or in very special case, and using the same technique as described above. But really, I'd advise people to not necessarily bother about pruning data :-).

Hope this helps.

**Comment by DurvalMenezes** [comment]
@fd0: 
> Not at all. When restic is run as a different user, it should recreate the cache and get the job done. The exception to this is if the cache dir is not writable for the current user, then it prints an error (and everything will take ages). Did you run prune with the cache enabled before? If not, the first prune may take longer, the subsequent ones will be much faster (independent of the user/computer you run it on).

I'm [planning on running `restic prune` on a Google Compute Engine VM so as to speed it up](https://forum.restic.net/t/restic-backup-is-taking-longer-and-longer-to-run-best-way-to-run-restic-prune/1788); can I just copy my local "~/Library/Caches/restic/" up to that VM so as to avoid having `restic prune` initially having to build the cache?
