### ISSUE TITLE
too many files scanned when using `backup --one-file-system / /srv`

### ISSUE THREAD

**Issue by evgeni** [restic/restic#1356]
migrating from obnam here, so please tell me if I am just holding restic wrong.

## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?

```
root@ippai:~# RESTIC_PASSWORD_FILE=/…/password RESTIC_REPOSITORY=sftp:…:/backup/ restic backup --exclude-caches --one-file-system /srv
using parent snapshot 7e9ebd90
scan [/srv]
scanned 49631 directories, 781689 files in 1:46
[12:36] 100.00%  70.240 MiB/s  51.857 GiB / 51.857 GiB  831330 / 831320 items  0 errors  ETA 0:00 
duration: 12:36, 70.21MiB/s
snapshot 0120871a saved

root@ippai:~# RESTIC_PASSWORD_FILE=/…/password RESTIC_REPOSITORY=sftp:…:/backup/ restic backup --exclude-caches --one-file-system /
using parent snapshot 230795e1
scan [/]
scanned 4520 directories, 43720 files in 0:12
[0:58] 100.00%  26.283 MiB/s  1.489 GiB / 1.489 GiB  48239 / 48240 items  0 errors  ETA 0:00 
duration: 0:58, 25.84MiB/s
snapshot e9dd928b saved

root@ippai:~# RESTIC_PASSWORD_FILE=/…/password RESTIC_REPOSITORY=sftp:…:/backup/ restic backup --exclude-caches --one-file-system / /srv
scan [/ /srv]
scanned 103784 directories, 1607160 files in 0:30
/: name collision for "srv", renaming to "srv-1".203 GiB  1710953 / 1710944 items  0 errors  ETA 0:00 
[53:46] 100.00%  33.387 MiB/s  105.204 GiB / 105.203 GiB  1710965 / 1710944 items  0 errors  ETA 0:00 
duration: 53:46, 33.38MiB/s
snapshot 178ddc19 saved
```

## What backend/server/service did you use?
SFTP

## Expected behavior

Creating a snapshot for `/` and `/srv` at the same time should take as much time as first creating one for `/` and then a second one for `/srv`.

## Actual behavior

It seems restic scans the files in `/srv` twice, thus prolonging the overall backup time.

## Steps to reproduce the behavior

1. have two mountpoints (`/` and `/srv`)
1. `restic backup /`
1. `restic backup /srv`
1. `restic backup / /srv`

## Do you have any idea what may have caused this?

No

## Do you have an idea how to solve the issue?

No

## Additional information

```
restic snapshots
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
230795e1  2017-10-15 14:38:37  ippai                   /
7e9ebd90  2017-10-15 14:51:54  ippai                   /srv
0120871a  2017-10-15 17:58:05  ippai                   /srv
e9dd928b  2017-10-15 18:43:00  ippai                   /
178ddc19  2017-10-15 18:45:29  ippai               ┌── /
                                                   └── /srv
```

It seems that `178ddc19` was created without any parents (which kinda makes sense, as the dir list is different).

**Comment by fd0** [comment]
Oh, interesting corner case, thanks for the report. This case (saving `/` and `/srv`, which is already included in `/`) is not addressed in the code as far as I know.

What's your use case? Why did you run restic the way you did? It feels like I'm missing something here.

**Comment by evgeni** [comment]
Thanks for the quick reply!

I want to backup / and /srv, but not all the funny special mounts (/dev etc). That's why I use --one-file-system. And I pass both folders to save a second backup run for the other mount.

**Comment by legrostdg** [comment]
Same problem here!

**Comment by matthijskooijman** [comment]
I think I'm also running into this problem, where the scan found more than double the files that were actually backed up. I have the same usecase as @evgeni, but also have some directories bindmounted in other places, which makes them show up twice.

If this is not what `--one-file-system` is intended for, then what does it do exactly?

**Comment by fd0** [comment]
This is one of the things that `--one-file-system` should cover. I'm not sure this issue is still relevant, we've completely replaced the restorer code starting with 0.9.0. Can you confirm it is still an issue (can you please describe your case)?

**Comment by fd0** [comment]
It may have been resolved (accidentally) in #1855, but I think the issue described by @matthijskooijman is a different one than the original issue: This issue is about restic **reading** and saving data twice. The other issue seems to be that with the current archiver (as of 0.9.2), only the scan is run twice...

**Comment by matthijskooijman** [comment]
@fd0, looking more closely at the original post's output, indeed it seems that backed up data twice whereas my issue only the scanning. Since these are related enough, I'll continue here, if you'd rather open a new issue, let me know.

Let me share my observations: I did a backup run of `/ /home /containers /data` with `--one-file-system`, with some excludes for `/sys`, `/dev`, etc, resulting in scanning about 3mln files (at this stage I also noticed it scanned more GB than I had files in the system, which was a bit curious). On the second run, I added some excludes for cache directories, and removed the excludes for `/sys`, `/dev`, etc, assuming `--one-file-system` would cover that. That run scanned over 4mln files, which seemed even more curious. The result of that second run is (I snipped some intermediate index and file read errors):

matthijs@tika:/etc$ sudo restic backup / /home /containers /data --one-file-system --verbose --cache-dir=/data/backup/restic --repo sftp:somewhere:/somepath --exclude-file /etc/restic/excludes --exclude-caches --password-file /etc/restic/tika.key
open repository
repository xxxx opened successfully, password is correct
lock repository
load index files
using parent snapshot 1d28e138
start scan on [/ /home /containers /data]
start backup on [/ /home /containers /data]
Files:        2109 new,  6679 changed, 2391315 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:   3858 new
Tree Blobs:      1 new
Added to the repo: 630.930 MiB

processed 2400103 files, 0 B in 2:57:18
snapshot cb1ff753 saved
context canceled3 files 103.581 GiB, total 4424251 files 185.083 GiB, 4 errors
```

Here, the number of scanned files is 4.4mln, but the number of new + changed + unmodified files is only 2.4mln, which seems to show the bug I'm seeing.

Note that the paths listed to backup are all filesystem roots. In addition, I have a bunch of bindmounts, binding (subdirs of) / and /data into /containers.

As for `--one-file-system`, I would think it works like this: Before recursing into a directory, run a stat on the directory. If the filesystem identifer of the directory is different from its parent directory, do not recurse into the directory. This should apply both for scanning as for backing up.

Writing this, I realized this approach does not work when a filesystem is bindmounted on a subdirectory of itself, which would show the same filesystem id on parent and subdirectory (in some cases, this might even cause an infinite recursion?). It seems the `mountpoint` utility from util-linux solves this by reading mountpoints from `/proc/self/mountinfo`, falling back to the above approach when it is not available. I guess restic could adopt a similar approach, essentially putting the contents of `mountinfo` into the exclude list might even be sufficient already.

Looking at the [current implementation](https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/sys-utils/mountpoint.c#n60), I see that, for each path that is considered for backup, restic looks up through the hierarchy (e.g. when considering /path/to/bar, it considers /path/to/bar, /path/to, /path and /) until if finds a path that was specified on the commandline. If found it compares the filesystem id of the path under consideration with the filesystem id of the commandline-specified path, excluding the path if the ids are different.

This sounds like a rather inefficient approach, requiring a lot of extra stat calls. Also, I can see how this fails: In my case, when traversing `/`, it comes upon `/data`. When considering it, it finds that `/data` is also on the commandline, and the filesystem id matches, so it is accepted and recursion continues. Later, `/data` scanned again, because it is on the commandline.

To solve that, I guess you can either adopt the approach above (compare the fsid with the parent), or keep track of what commandline argument is being recursed and compare each candidate's fsid with the fsid of the comandline argument. This might require passing some extra state around, but also seems like the most efficient approach (not requiring any additional stat calls for parent directories). And of course adding the "look at `/proc/self/mountinfo`" might be even better, though it probably makes sense to also implement the fallback (and perhaps a separate cli flag and/or a warning when `mountinfo` is unavailable).

A quick search shows no ready-made "isMountpoint" functions for Go, but I did find these mountinfo parsers: https://github.com/fntlnz/mountinfo/blob/master/mountinfo.go https://github.com/mindreframer/golang-devops-stuff/blob/master/src/github.com/dotcloud/docker/pkg/mount/mountinfo_linux.go

**Comment by fd0** [comment]
Thank you very much for the detailed analysis! I agree with you, this could be the problem. I'd prefer to try without reading `/proc/self/mountinfo`, so we can be as portable as possible.
