### ISSUE TITLE
s3.retry backoff strategy

### ISSUE THREAD

**Issue by lloeki** [restic/restic#1424]
Using `-o s3.retry=42` allows one to change the retry count. What kind of retry strategy is implemented? Is it linear or exponential backoff? It would be fair enough to at least document it, even better if it can be adjusted as an option.

**Comment by lloeki** [comment]
@samonzeweb that one might be of interest to you.

**Comment by fd0** [comment]
The code in the current master branch has two different retries: The s3 library we're using (minio-go) retries requests (or part of requests, I'm not sure) and I don't know what the policy there is. On a higher level, restic also retries failed backend requests, for all backends. In this case, an exponential backoff strategy is used, max 10 tries, max interval 1 minute and max elapsed time 15 minutes.

Since this is more of a question I'm closing this issue for now.
