### ISSUE TITLE
Backup to Google Cloud Storage slows down over time

### ISSUE THREAD

**Issue by mikhailian** [restic/restic#1432]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/386

## How did you run restic exactly?
 RESTIC_PASSWORD=zzz ~/bin/restic -r gs:xxx:/ backup photo

## What backend/server/service did you use?
Google Cloud Storage

## Expected behavior
A constant backup speed 

## Actual behavior
The backup starts at over 20 MiB/s, then the speed degrades over several hours down to 800 KiB/s after which restic stops with a 503 backend error.

I wonder whether I am the only one seeing this.

## Steps to reproduce the behavior
Backup 0,5 Tb of photos  to Google Could Storage

**Comment by fd0** [comment]
Thanks for the report. No, you're not the only one. The reason is that the progress bandwidth you're seeing does not really reflect what's going on. At first, restic reads data and creates new files to be uploaded to the repo. That's the phase when it seems to be very fast. Then it starts uploading the data, which takes some time. During that time, creating new files to upload stalls, so the overall bandwidth display (which is just the average, bytes processed divided by time) starts to drop. Eventually, it settles to something that approaches the real bandwidth over time.

I'm going to close this issue, we know about it and will probably just remove the bandwidth display.

**Comment by mikhailian** [comment]
You could also split bandwidth  progress  into upload/download.  This will also give a hint at different stages of the backup process.

Offtopic: I've seen your Brussels GDG presentation in 2016, and it's nice to see how restic is being picked up all over the world as the backup tool of choice.  Good job.

**Comment by fd0** [comment]
Uh wow, thanks, that was a long time ago!
