### ISSUE TITLE
Restic and usage cpu

### ISSUE THREAD

**Issue by scialo** [restic/restic#1442]
## Output of `restic version`
0.73

## How did you run restic exactly?
nice -n 19 restic -r $myrepository backup $myfolder

## Expected behavior
When i check with command top, restic use 185,0% of CPU.

**Comment by pvgoran** [comment]
Again, you did not specify what's wrong with the current restic behaviour that you experience, and what would be the expected (correct) behaviour.

**Comment by rawtaz** [comment]
@scialo What is the actual problem you are having?

**Comment by scialo** [comment]
No problem, thanks

**Comment by fd0** [comment]
So, I'm gonna guess here: You've run restic with `nice` and saw 185% CPU usage.

That's expected for two reasons:
 1. restic uses multiple CPUs/cores if available, and the percentage is relative to one core. So if you have two cores and a program uses both the whole time, the CPU usage would be 200%.
 2. `nice` only tells the OS: "if there's another program that can be run at any given moment, prefer the other program". So if there isn't any other program, the OS will just run restic. So you see restic at the top of the list of active processes probably because at that moment there was no other CPU intensive program to run.

That's only as far as we can help you without any in-depth description.

**Comment by scialo** [comment]
Thanks very much.
