### ISSUE TITLE
option to check subset of repository data blobs

### ISSUE THREAD

**Issue by ifedorenko** [restic/restic#1497]
## Output of `restic version`

    restic 0.8.0
    compiled with go1.9 on darwin/amd64

## How did you run restic exactly?
`restic check --read-data`

## What backend/server/service did you use to store the repository?
any remote backend

## Expected behavior
I have 50Mbps Internet connection and 1TB remote backup repository.  I'd like to be able to check a subset of data blobs for few hours every night, but still check each blob at least once a month.

## Actual behavior
There is no way to limited how much work `check --read-data` does. In my case, repository data check will take more than 2 days to complete when using all available Internet connection bandwidth, and much longer if I throttle download speed.

## Steps to reproduce the behavior
run `restic check --read-data`

## Do you have any idea what may have caused this?
This is a feature request, not a bug report.

## Do you have an idea how to solve the issue?
One way to implement this is to introduce two new `check --read-data` flags: total number of blob "buckets" and index of the bucket to check. Blobs can be assigned to buckets based on the first byte of blob's sha256, for example. My desired check schedule (or any other periodic check schedule) can be trivially implemented in bash or other scripting language. I can try to provide a pull request that implements this idea, if you are interested.

## Did restic help you or made you happy in any way?

go looks weird to a java developer :-)

**Comment by fd0** [comment]
That's a nice idea, thanks for reporting it! We need to come up with a good partition algorithm though, to ensure that it is guaranteed that each blob is checked.

**Comment by ifedorenko** [comment]
If `totalPartitions` is the total number of partitions and `currentPartition` is the partition to check (`0 <= currentPartition <  totalPartitions`),  then each block can be assigned to a partition by simple `(id[0] % totalPartitions) == currentPartition` check on the first byte of the block id. https://github.com/ifedorenko/restic/commit/3a91af94cfedda3c752530e93684454858db6065 implements this approach and I can open pull request if you a interested. I am still debating if I want a separate `restic check-data` command, however...

**Comment by yorkday** [comment]
I have been testing the --read-data-subset command and believe there may be an issue and a possible enhancement option.

**Possible issue:**
When choosing a large number of totalPartitions for a small backup, and checking only one partition, the command may not actually test any data.  For example, in a small 10Mb backup, I choose to test a single random partition out of totalPartitions = 100 (effectively testing a random 1%).  The test did not appear to validate any data - perhaps because the partition had no blocks assigned?
Ideally the solution would ensure every partition points to a particular backup block, so the read subset actually reads something.

**Possible Enhancement:**
There are definitely use cases to validate the entire backup set, or programmatically work through chunks of the backup set (which the tool already performs).  I'd also like the option to set a limit in size of the --read-data-subset command.  So, I would like to test 1% of my backup, but stop once I reach a certain size (e.g 1GB).  This ensures for very large backups, or backups that change significantly in size over time, I have the flexibility to verify small samples of the overall backup, without constantly having to change my totalPartitions value to a higher or lower number to cap the test size.

**Possible Perfect Enhancement**
Ideally I'd like the restic to have the ability to verify all of my backup data, over a period of time.  The current solution doesn't work if I am constantly adding to the backup, the blocks assigned to each partition could change on each run, so I would end up revalidating data I already recently validated, or miss data.  So, for example, I'd like Restic to sample 1% on each run, and guarantee after 100 runs, that 100% of data has been validated, regardless if the overall backup size has changed.

Please keep up the great work - love this tool!

**Comment by ifedorenko** [comment]
> Possible Perfect Enhancement
> Ideally I'd like the restic to have the ability to verify all of my backup data, over a period of time. The current solution doesn't work if I am constantly adding to the backup, the blocks assigned to each partition could change on each run, so I would end up revalidating data I already recently validated, or miss data. 

I don't believe this is accurate. Packs are assigned to partitions based on pack's SHA checksum, which does not change over time. Calling `--read-data-subset` for all subsets is guaranteed to test all packs that existed during the first invocation. The new packs are guaranteed to be checked by the end of the second iteration of `--read-data-subset` over all subsets.

**Comment by yorkday** [comment]
Hi @ifedorenko 

Thanks for the response.  What I am requesting is an ability to verify a percentage of data each time I run a backup, so that over a longer period of time, I can guarantee I have tested 100% of the data.  I am also trying to avoid revalidating data all the time.

**Scenario:**
Initial backup size = 100MB
Daily delta = 10MB
Daily read-data-subset = random/10

Day 1:
Backup = 110MB
Daily read-data-subset = 5/10

Day 2:
Backup = 120MB
Daily read-data-subset = 8/10

Day 25:
Backup = 350MB
Daily read-data-subset = 4/10

Over time, the partitions become larger and larger as more blocks are written to the repository.  After 10 days, even if I sequentially checked 1 partition each day, I would not have verified 100% of my repository after 10 days, because of the additional 100MB of data written.

In the end, I guess this comes down to the confidence that you place in the backup tool and the target repository durability.  Personally I place pretty high confidence in AWS S3 (my target), but I am looking to verify the backups regularly with the tool - without repeating validation of already validated data.

**Comment by ifedorenko** [comment]
If you sequentially check one partition each day (out of 10 total partitions), current implementation guarantees each pack files will be checked at least once within 19 days it was first created, and exactly once every 10 days after that.

What I think is missing, is the ability to check pack files immediately after they are first created. This way restic can guarantee pack files are correctly uploaded to the backend (which is useful in itself), and also that each pack file is checked at least once every 10 days. WDYT?

**Comment by yorkday** [comment]
Hi @ifedorenko I think we're in agreement on the pack check methodology.
I agree pack verification would be nice to do.  I would also like to see it 'pushed down' and run on the cloud, rather than pulling all the data back over my internet connection to do it.  Checksumming data in place at both locations should be sufficient.
The issue I see with performing partition checks periodically is that you will continually revalidate partitions that have already been validated previously.
Restic seems to have great backup, restore and encryption capability, we're both looking to just improve the backup validation capabilities.

**Comment by fd0** [comment]
I think we can close this issue, did we miss closing it when merging the PR? I'll close it now. Please feel free to add further comments :)
