### ISSUE TITLE
Support hard links

### ISSUE THREAD

**Issue by fd0** [restic/restic#152]
At the moment, restic saves enough meta data to restore hard links, but this is not implemented yet.

**Comment by fw42** [comment]
More context: When backing up a directory that contains two or more files with the same inode (on the same filesystem), restoring the backup will create two files with identical content (rather than only one file and hardlinks to that file's inode).

This issue can be closed when there is a config option (enabled by default I would suggest) that is smart enough to only create one inode when restoring a backup like this.

Need to think about the rare corner case of inodes being identical by coincidence (because the source files were on different file systems -- marginally related to https://github.com/restic/restic/issues/47).

**Comment by fd0** [comment]
We could add `stat.Dev` to the meta data, that should uniquely identify the device containing the file:

    struct stat {
        dev_t     st_dev;         /* ID of device containing file */
        [...]
    }

    [...]
    The st_dev field describes the device on which this file resides.  (The
    major(3) and minor(3) macros may be useful to decompose the device ID in this
    field.)

(from `stat(2)`)

**Comment by fw42** [comment]
[os.SameFile](https://golang.org/pkg/os/#SameFile) might be useful

**Comment by fd0** [comment]
Nice method, I wasn't aware of it. Unfortunately it won't help. In order to detect hard links during backup, we need to maintain a list of all files (tuples of (inode, dev)) seen so far.

**Comment by fawick** [comment]
For *nix, wouldn't it be sufficient to maintain a list of only the files for which the value of `nlink_t` in `struct stat` is greater than 1?

**Comment by fd0** [comment]
I think we already have all the metadata recorded, but the restore part is missing.

**Comment by jgfrm** [comment]
What I have right is support for hard links using the restic restore command.
It requires a repository change since the dev id of the file has to be stored to resolve inode collisions (two files with the same inode id but on different file systems).
Also, the solution supposes that all hard links for a file are included in the backup and are restored. If not, a warning is raised during the restore that hard links are missing.

I also had a look to see if hard links can be supported by restic mounts.
So far, I have not found an efficient solution.
During file creation, a file plus all the hard links have to be created. For that purpose, there should be a list of all files with hard links. One option could be to traverse the back up tree, but this time consuming. Another option could be to store a map of files and hard links during the backup already.

**Comment by fd0** [comment]
Let's start with archiving/restoring hard links, and then solve the fuse mount. Please submit a pull request so we can discuss the code :)

**Comment by fd0** [comment]
FYI: PR #763 is almost ready.

**Comment by fd0** [comment]
Aaaand it has been merged! Thanks a lot to @jgfrm!

**Comment by pvgoran** [comment]
Excellent!
