### ISSUE TITLE
Restore of one file (--include) reads all files in the snapshot

### ISSUE THREAD

**Issue by phillipp** [restic/restic#1520]
## Output of `restic version`
restic 0.8.0 (v0.8.0-23-g812ce4b-dirty)
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
restic -r restic-repos/areligious_shortcliffe restore -t /tmp/restic-restore --include apache2-mpm-itk_2.2.22-1ubuntu1.11_amd64.deb 633d3782

## What backend/server/service did you use to store the repository?
Local dir

## Expected behavior
Restic reads the metadata, top level tree data files and the actual file to restore

## Actual behavior
Restic reads all data in the snapshot

## Steps to reproduce the behavior
Make a snaphot of a few million files, try to restore just one.

## Do you have any idea what may have caused this?
It seems like excluded directories are still walked

## Do you have an idea how to solve the issue?
Do not walk excluded directories

## Did restic help you or made you happy in any way?
It is a great tool to write data into a repository, but getting the data out in an efficient way is surprisingly hard.

**Comment by phillipp** [comment]
I just discovered that it works that way I want it to, if I add a slash plus the top-level directory to the directory:

Working:
```
restic -r restic-repos/areligious_shortcliffe restore -t /tmp/restic-restore --include /debs/apache2-mpm-itk_2.2.22-1ubuntu1.11_amd64.deb 633d3782
```

Not working:
```
restic -r restic-repos/areligious_shortcliffe restore -t /tmp/restic-restore --include debs/apache2-mpm-itk_2.2.22-1ubuntu1.11_amd64.deb 633d3782
```
or
```
restic -r restic-repos/areligious_shortcliffe restore -t /tmp/restic-restore --include /apache2-mpm-itk_2.2.22-1ubuntu1.11_amd64.deb 633d3782
```

I was wondering if this is my fault or if restic should warn if you don't add a slash to the include argument and therefore will ignore the include/not use it like expected?

**Comment by fd0** [comment]
This behavior is somewhat documented in the manual: https://restic.readthedocs.io/en/latest/050_restore.html#restoring-from-a-snapshot

If you're passing restic a realtive path (or a single file name) to `--include`, it needs to traverse the whole snapshot to see if the file is maybe in there several times. If you only want a particular file, you need to pass in the absolute path (as saved in the snapshot) to `--include`, e.g. by first listing the snapshot with `restic ls` or so. The strange path layout is #549, we're working on it.

The option `--include` takes a relative path so that you can use `--include foo/secret.txt` to restore all files called `secret.txt` which are located in a directory called `foo`. On the other hand, `--include /work/foo/secret.txt` will only restore the file `secret.txt` from the directory `/work/foo` in the snapshot.

I'd say it's not a bug and we can close this issue, what do you think?

**Comment by phillipp** [comment]
That makes sense 100%. I agree, not a but, just a misunderstanding.

Thanks for the explanation!
