### ISSUE TITLE
Wrong mode in restorer_test case #3.

### ISSUE THREAD

**Issue by is** [restic/restic#1537]
https://github.com/restic/restic/blob/99f0fce67308bedf164bb04b324b92e28a206300/internal/restic/restorer_test.go#L190-L199

for non-root user, the file can not be to created in the dir with 0555 mode.
so the case will always failed in non-root user.
```sh
is@uai:/tmp$ id
uid=1003(is) gid=1003(is) groups=1003(is)
is@uai:/tmp$ mkdir m0
is@uai:/tmp$ chmod 0555 m0
is@uai:/tmp$ cd m0/
is@uai:/tmp/m0$ ls
is@uai:/tmp/m0$ touch a
touch: cannot touch 'a': Permission denied
```

```
is@uai: go test internal/restic/restorer_test.go
....
--- FAIL: TestRestorer (0.00s)
    --- FAIL: TestRestorer/#03 (0.00s)
    	testing.go:30: using low-security KDF parameters for test
    	restorer_test.go:266: snapshot saved as 6bc733fc
    	restorer_test.go:297: start_____restore "/tmp/restic-test-448289122"
    	restorer_test.go:277: restore /dir to /tmp/restic-test-448289122/dir
    	restorer_test.go:277: restore /dir/file to /tmp/restic-test-448289122/dir/file
    	restorer_test.go:288: restore returned error for "file" in dir /tmp/restic-test-448289122/dir/file: OpenFile: open /tmp/restic-test-448289122/dir/file: permission denied
    	restorer_test.go:334: unexpected error for /tmp/restic-test-448289122/dir/file#file found: OpenFile: open /tmp/restic-test-448289122/dir/file: permission denied
    	restorer_test.go:340: unable to read file dir/file: open /tmp/restic-test-448289122/dir/file: no such file or directory
.....
```

**Comment by fd0** [comment]
Uhm, which commit of the restic repo is that? The branch you're working on for the concurrent restorer? I've only just yesterday added the test case, it should exactly test restoring a directory which was not writable during backup. It works with the old restorer:
```
$ git describe
v0.8.1-31-g99f0fce6

$ go test -v -run 'TestRestorer$/03' ./internal/restic
=== RUN   TestRestorer
=== RUN   TestRestorer/#03
--- PASS: TestRestorer (0.00s)
    --- PASS: TestRestorer/#03 (0.00s)
    	testing.go:30: using low-security KDF parameters for test
    	restorer_test.go:265: snapshot saved as 4f9cdc81
    	restorer_test.go:276: restore /dir to /tmp/restic-test-982702141/dir
    	restorer_test.go:276: restore /dir/file to /tmp/restic-test-982702141/dir/file
PASS
ok  	github.com/restic/restic/internal/restic	0.004s
```

This is the commit that makes it work: b8620429e27ce28c565f657359b4a93b72c42837

The new restorer must also be able to do that, people will have directories saved in the repo which have read-only modes, and they should be restored correctly by restic.

The basic idea was that I've just moved "creating" the directory at the end (so that the intermediate directories are created with the default modes, and set to the target modes afterwards).

I think we can close this issue, what's your take on this?

**Comment by is** [comment]
Oh, I understood the case. I will modify the new concurrent restorer to pass this case.
