### ISSUE TITLE
Issue with '-o sftp.Command' and plink

### ISSUE THREAD

**Issue by Confuset** [restic/restic#1553]
## Output of `restic version`
restic 0.8.1
compiled with go1.9.2 on windows/amd64

## How did you run restic exactly?
`.\restic_0.8.1_windows_amd64.exe init -o sftp.command="sftp.bat" -r sftp:test:bla:bla`

sftp.bat
```
@echo off
"C:\Program Files\PuTTY\plink.exe" -s -l backup-user -i C:\Users\po\.ssh\id_rsa.ppk 192.168.0.36 sftp
```

## What backend/server/service did you use to store the repository?
sftp on ArchLinux on RaspberryPie 3

## Expected behavior
Handle username, host and  path correctly in sftp command.

## Actual behavior
host:path is used as a foldername on the backend.

## Steps to reproduce the behavior
Use plink.exe to establish sftp connection.
Use the sftp backend: `sftp:test:bla:bla` (use whatever you like as username, host and path…its accepted because sftp-connection is already established)
SSH into backend and checkout home folder of user (you will find a folder bla:bla as the repo)

## Do you have any idea what may have caused this?
The problem seems to be that restic is using host:path as foldername in case of '-o sftp.command'

## Do you have an idea how to solve the issue?
Only use the path element when connection is already established with '-o sftp.command' or make them optional as they are not need as far as i see it.

## Did restic help you or made you happy in any way?
Not yet ;-) But looking up to it.

**Comment by fd0** [comment]
Hm, I'm not sure I understood you correctly. From my point of view it works as expected. On most systems, the default `ssh` command is useful so you don't need an `sftp.command` at all. But some options for establishing the connection (like user and host name) are so common that the're built into the `sftp` backend syntax.

When you specify an `sftp.command`, the user and host name in the `sftp` backend specification (`sftp:[user@]host:path`) will be ignored. That's fine from my point of view.

You wrote that you've specified an custom sftp command, and the repo was `sftp:test:bla:bla`. restic will parse the host name (which is ignored) as `test`, and the target directory on the remote server as `bla:bla`, since it's a realtive path it will be relative to the user's home directory on the server.

You then also wrote that you found a folder `bla:bla` on the server, which contained the repo. As far as I can see right now, restic exactly behaves as it should be.

In the `Actual Behavior` section you wrote something different, that `host:path` is used as the folder name on the server (which would be `test:bla:bla` in your case).

Did I get anything wrong?

**Comment by Confuset** [comment]
Sorry for this late Response.

Now I feel a bit stupid. As I spend days to figure out whats wrong and newer came to the conclusion that I was assuming something wrong.
I also reread the docu about this and I have to admit that you can read this behaviour in there. Even though it is not as clear as the describtion above.

Maybe you should rephrase the behaviour in the docs..

**Comment by fd0** [comment]
Heh, thanks for the feedback! Does it work for you now?

Do you have a proposal on what to change in the docs exactly? What would you like to read there?

**Comment by Confuset** [comment]
Now. I reread the docu again and again, and since I know now what mistake I made it really is difficult to wrongfully read it again. So everything is there, which explaines the behaviour. Mh.
Maybe it was just OSI-Layer 8 and RTFM
:-)
