### ISSUE TITLE
is restic support use --keep-last and --keep-daily together

### ISSUE THREAD

**Issue by gongmingbin** [restic/restic#1562]
is restic support use --keep-last and --keep-daily together?  **and** or **or** ? for example:

```bash
restic forget --keep-daily  10  --keep-last 10
```

the kept snapshots are that satisfy last 10 and in 10 days ? or the kept snapshots are satisfy only one condition?

**Comment by rawtaz** [comment]
@gongmingbin There's a dry run option to the `forget` command:

`-n, --dry-run             do not delete anything, just print what would be done`

You can use it to run your command and see what would be done, without having it done.

**Comment by fd0** [comment]
I've built an example for you, let's say I have an hourly backup for a directory for the last couple of days:

```
$ restic snapshots
[...]
ID        Date                 Host        Tags  
----------------------------------------------------------------------
502d4a5d  2018-01-17 00:01:02  mopped      
3f810aca  2018-01-17 01:01:02  mopped      
a5828f0c  2018-01-17 02:01:02  mopped      
d3646597  2018-01-17 03:01:02  mopped      
56302763  2018-01-17 04:01:02  mopped      
213558ab  2018-01-17 05:01:02  mopped      
194c98f8  2018-01-17 06:01:02  mopped      
[...]
44c7c35e  2018-01-19 05:01:02  mopped      
bf473f50  2018-01-19 06:01:02  mopped      
c446308a  2018-01-19 07:01:02  mopped      
1af5ec53  2018-01-19 08:01:02  mopped      
41f66504  2018-01-19 09:01:02  mopped      
890f46c8  2018-01-19 10:01:02  mopped      
730b62f6  2018-01-19 11:01:02  mopped      
bb787c55  2018-01-19 12:01:02  mopped      
59018a09  2018-01-19 13:01:02  mopped      
----------------------------------------------------------------------
62 snapshots
```

When you run restic with `--keep-last 10` and `--keep-daily 2`, this is the result:

```
$ restic forget --dry-run --keep-last 10 --keep-daily 2
[...]
keep 11 snapshots:
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
573c701b  2018-01-18 23:01:02  mopped                  /home/fd0/work
19f1ad8d  2018-01-19 04:01:02  mopped                  /home/fd0/work
44c7c35e  2018-01-19 05:01:02  mopped                  /home/fd0/work
bf473f50  2018-01-19 06:01:02  mopped                  /home/fd0/work
c446308a  2018-01-19 07:01:02  mopped                  /home/fd0/work
1af5ec53  2018-01-19 08:01:02  mopped                  /home/fd0/work
41f66504  2018-01-19 09:01:02  mopped                  /home/fd0/work
890f46c8  2018-01-19 10:01:02  mopped                  /home/fd0/work
730b62f6  2018-01-19 11:01:02  mopped                  /home/fd0/work
bb787c55  2018-01-19 12:01:02  mopped                  /home/fd0/work
59018a09  2018-01-19 13:01:02  mopped                  /home/fd0/work
----------------------------------------------------------------------
[...]
```

I find it confusing to talk about "and" and "or" here. restic follows the policy you give it:
 * `--keep-last 10` means the newest ten snapshots will be kept
 * `--keep-daily 2` means the latest snapshot for the last two days (for which a snapshot exists) will be kept
 
restic then goes through all the snapshots available and marks which ones will be kept. The snapshot `59018a09` for example will be kept because it is within the last ten and because it is the latest snapshot of a day within the last two days.

So, in a sense you could say that the conditions for keeping a snapshot are combined via **or**.

I think this answers your question, so I'm closing this  issue. If you have follow-up questions (or I wasn't clear enough), please add a comment.

For these types of questions [the forum](https://forum.restic.net) is a much better place, we're using the GitHub issue tracker for tracking bugs and features.

**Comment by gongmingbin** [comment]
Thank you! @fd0 But I found --keep--xx not working.
Here is my local snapshots
![image](https://user-images.githubusercontent.com/9658013/35182731-23c54d04-fe15-11e7-991d-6805064bdab8.png)
when i run 

```
restic forget --dry-run  --keep-yearly 10
```
result is:
![image](https://user-images.githubusercontent.com/9658013/35182774-f635776e-fe15-11e7-99d9-85b6ac63b09f.png)
is this a bug or something wrong with me?
my system is  macOS 10.13 Darwin 17.0.0.

**Comment by dimejo** [comment]
You told restic to keep 1 snapshot per year for 10 years. Since you only have snapshots from 2018 and `306e3a4a` was the last snapshot from 2018 restic is keeping only this one.

How many snapshots per period do want to keep? Maybe we can help you with the policy.

**Comment by gongmingbin** [comment]
@dimejo , sorry,Maybe I misunderstood. is the --keep-yearly 10 mean than restic will kept all then snapshots than is from last 10 ago to now? for my example, the three snapshots was in the last 10 years, way not all of them will be kept?
I just want to kept The past n year snapshots.

**Comment by fd0** [comment]
@gongmingbin I think restic does exactly what you asked it to do. Did you find the section in the manual that covers removing snapshots according to a policy? https://restic.readthedocs.io/en/latest/060_forget.html#removing-snapshots-according-to-a-policy

Is there anything unclear?

**Comment by gongmingbin** [comment]
Thank you very match!！ I misunderstand for my bad English and reading doc carelessly! Thank you for your patient answers again!
