### ISSUE TITLE
add --ctime option to only check new files based on ctime (on filesystems that support it)

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#1585]
`restic backup` is very cpu/memory intensive. I guess it calculates checksums of each file at every backup. It would be nice if it was able to only check new files based on ctime. Some files may not be backed up if the clock changes, but it may be an acceptable compromise for a (I guess) hugely improved cpu usage/backup time. I've not found this bug report in the issues, so please tell me if it is a duplicate!

**Comment by fd0** [comment]
> restic backup is very cpu/memory intensive. I guess it calculates checksums of each file at every backup. 

That's not the case: restic only reads the contents of a file if it has changed since the last time it was read. This is based on the mtime of the file, and it works very well.

> It would be nice if it was able to only check new files based on ctime.

That's not such a great idea, the `ctime` is not a good indicator when the content has changed. We're using the `mtime` for that.

How did you run restic exactly? Since you did not fill out the issue template I don't have any information about the concrete situation.

I'm closing this issue for now, we can reopen it and try to find out why restic seems to re-read your files when you provide more information. Please feel free to add comments, thanks!

**Comment by legrostdg** [comment]
Sorry about the incomplete bug report. The cpu/memory was so high I assumed there was an algorithmic problem in restic. I finally did a `rebuild-index` & `check` and my backup time went from 2h using almost 100% of the cpu and 80% of the memory to 19min with a completely bearable cpu/memory usage. So, the issue is in fact probably memory leaks somewhere. I guess the new archiver code may fix these...

**Comment by d3zd3z** [comment]
> ... the `ctime` is not a good indicator when the content has changed... We're using the `mtime` for that.

I don't know if this will get seen, as this is closed, but...

Whatever problems `ctime` has for change indication, using `mtime` is strictly worse. The `ctime` is *always* updated when the contents of the file change. Using `ctime` results in occasional instances where a file will be rehashed when it doesn't need to be.

The `mtime` can be set arbitrarily by the user (`ctime` cannot), and there are common scenarios, such as package managers, and other backup utilities that will explicitly set the `mtime`. I have personally had incorrect data backed up because the tool I was using assumed if the inode, size, and mtime were the same, the file hadn't changed.

**Comment by fd0** [comment]
That's interesting, can you provide a bit more details? For which OS and/or file systems is that the case?

Which backup programs or package managers behave like you described (change a file, but reset the mtime)?

For the record, restic checks the modification timestamp (`mtime` I guess), size and inode: 

https://github.com/restic/restic/blob/45a48eb4a8605f4f953f3767d3c730342d486f80/internal/archiver/archiver.go#L449-L463

**Comment by smlx** [comment]
> That's interesting, can you provide a bit more details? For which OS and/or file systems is that the case?

This behaviour is defined in POSIX - e.g. for [futimens](http://pubs.opengroup.org/onlinepubs/9699919799/functions/futimens.html):

> _Upon successful completion, futimens() and utimensat() shall mark the last file status change timestamp for update..._

> Which backup programs or package managers behave like you described (change a file, but reset the mtime)? I'm trying to understand why these programs would do such a thing...

There was a [bug in Debian](https://lists.debian.org/debian-security/2017/01/msg00014.html) that caused this behaviour in some cases, but I believe that it has been reverted..
