### ISSUE TITLE
make tests run faster

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#1656]
`TestRebuildIndex` & `TestRestore` slowness make Debian reproducible builds fail:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/restic.html (TestRebuildIndex)
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/restic.html (TestRestore)

The package is also not buildable on mips & mipsel because `TestCheckRestoreNoLock` & `TestParallelSaveWithDuplication` are too slow (this prevents the package from migrating to testing) :
https://buildd.debian.org/status/fetch.php?pkg=restic&arch=mips&ver=0.8.3%2Bds-1&stamp=1519747618&raw=0 (TestParallelSaveWithDuplication)
https://buildd.debian.org/status/fetch.php?pkg=restic&arch=mipsel&ver=0.8.3%2Bds-1&stamp=1519748266&raw=0 (TestCheckRestoreNoLock & TestParallelSaveWithDuplication)

**Comment by fd0** [comment]
Soo, what can we do for that? Does Debian need to run the tests, is that really necessary?

**Comment by stapelberg** [comment]
I looked into this a little bit and noticed that setting `TMPDIR=$(mktemp -d /dev/shm/restic.XXXXXX)` helped tremendously to reduce the test time on our ARM porter box, where /tmp is not `tmpfs`.

However, the 4G of `tmpfs` are exhausted during a restic test run:
```
[…]
=== RUN   TestBackup
Copy: write /dev/shm/restic.2KFSRL/restic-temp-check-796600311: no space left on device
[…]
```

This seems excessive. Why do the tests require so much disk space and I/O?

**Comment by fd0** [comment]
I'll take a look. The particular test hasn't been modified in a long time though...

**Comment by fd0** [comment]
Hm. I can't reproduce it. In my manual tests here (on `amd64` though), the data stored in the temp dir does not exceed 200MiB.

We have several (sort of) "end to end" tests where we extract a tar with some test data, make several backups of it while simulating error conditions or special cases with file permissions. Afterwards, the checker is run and all data is verified. This all uses temp files where possible to reduce memory usage. The temp files are removed as soon as they aren't needed any more, typically when the test function returns.

These tests were never meant to be run by distributions...

**Comment by stapelberg** [comment]
> Hm. I can't reproduce it. In my manual tests here (on amd64 though), the data stored in the temp dir does not exceed 200MiB at each point in time.

What’s your parallelism level? The command line which was used on the Debian porterbox is:

```
go test -vet=off -p 4 github.com/restic/restic/cmd/restic github.com/restic/restic/internal/archiver github.com/restic/restic/internal/backend github.com/restic/restic/internal/backend/azure github.com/restic/restic/internal/backend/b2 github.com/restic/restic/internal/backend/gs github.com/restic/restic/internal/backend/local github.com/restic/restic/internal/backend/location github.com/restic/restic/internal/backend/mem github.com/restic/restic/internal/backend/rest github.com/restic/restic/internal/backend/s3 github.com/restic/restic/internal/backend/sftp github.com/restic/restic/internal/backend/swift github.com/restic/restic/internal/backend/test github.com/restic/restic/internal/cache github.com/restic/restic/internal/checker github.com/restic/restic/internal/crypto github.com/restic/restic/internal/debug github.com/restic/restic/internal/errors github.com/restic/restic/internal/filter github.com/restic/restic/internal/fs github.com/restic/restic/internal/fuse github.com/restic/restic/internal/hashing github.com/restic/restic/internal/index github.com/restic/restic/internal/limiter github.com/restic/restic/internal/list github.com/restic/restic/internal/migrations github.com/restic/restic/internal/mock github.com/restic/restic/internal/options github.com/restic/restic/internal/pack github.com/restic/restic/internal/pipe github.com/restic/restic/internal/repository github.com/restic/restic/internal/restic github.com/restic/restic/internal/test github.com/restic/restic/internal/walk github.com/restic/restic/internal/worker
```

> 
> We have several (sort of) "end to end" tests where we extract a tar with some test data, make several backups of it while simulating error conditions or special cases with file permissions. Afterwards, the checker is run and all data is verified. This all uses temp files where possible to reduce memory usage. The temp files are removed as soon as they aren't needed any more, typically when the test function returns.

Even 200 MB strikes me as much. Why are the files to back up not just 1 byte files?

> These tests were never meant to be run by distributions...

How else can we verify your code runs on all our release architectures? :)

**Comment by stapelberg** [comment]
By the way, here are the timings:

Without TMPDIR on tmpfs:
 started at Fri Mar  9 21:45:58
 exited abnormally with code 1 at Fri Mar  9 22:01:35

With TMPDIR on tmpfs:
 started at Fri Mar  9 23:17:11
 exited abnormally with code 1 at Fri Mar  9 23:24:26

The latter is more than twice as fast as the former. The more disk i/o you can avoid, the faster the tests will get.

**Comment by fd0** [comment]
> Even 200 MB strikes me as much. Why are the files to back up not just 1 byte files?

For a backup program, archiving directories containing only 1 byte files is a rare corner case. For example, this means that each file as archived in the repository would consist of exactly one data blob. And there'd be only one or two pack files in the repo, which is also uncommon.

I agree though that most tests probably won't need a large data set. I'll have a look.

> How else can we verify your code runs on all our release architectures? :)

That is an excellent argument I haven't thought about, thanks! :)

Sometimes Go making cross-compilation so easy tricks me into forgetting that just because it compiles and the tests pass on my architecture does not imply it runs correctly on other architectures.

> What’s your parallelism level? The command line which was used on the Debian porterbox is: `[...] go test -p 4`

I did not set the parallelism level by hand, which means it's set to `GOMAXPROCS`, which is 4 on my machine (real quad-core, not hyper-threading). We don't use `t.Parallel()` anywhere, so it's only tests for separate packages run in parallel by `go test`.

I've tried to reproduce the issue on a Raspberry Pi3 (running 32 bit Arch Linux on 4.14.24, Go 1.10, 1GiB RAM). Using the command line you pasted above (running through `time` and setting a `TMPDIR` manually and using `-p 1`), this is the result I get:
```shell
$ TMPDIR=/dev/shm/restictest /usr/bin/time go test -vet=off -p 1 github.com/restic/restic/cmd/restic github.com/restic/restic/internal/archiver github.com/restic/restic/internal/backend github.com/restic/restic/internal/backend/azure github.com/restic/restic/internal/backend/b2 github.com/restic/restic/internal/backend/gs github.com/restic/restic/internal/backend/local github.com/restic/restic/internal/backend/location github.com/restic/restic/internal/backend/mem github.com/restic/restic/internal/backend/rest github.com/restic/restic/internal/backend/s3 github.com/restic/restic/internal/backend/sftp github.com/restic/restic/internal/backend/swift github.com/restic/restic/internal/backend/test github.com/restic/restic/internal/cache github.com/restic/restic/internal/checker github.com/restic/restic/internal/crypto github.com/restic/restic/internal/debug github.com/restic/restic/internal/errors github.com/restic/restic/internal/filter github.com/restic/restic/internal/fs github.com/restic/restic/internal/fuse github.com/restic/restic/internal/hashing github.com/restic/restic/internal/index github.com/restic/restic/internal/limiter github.com/restic/restic/internal/list github.com/restic/restic/internal/migrations github.com/restic/restic/internal/mock github.com/restic/restic/internal/options github.com/restic/restic/internal/pack github.com/restic/restic/internal/pipe github.com/restic/restic/internal/repository github.com/restic/restic/internal/restic github.com/restic/restic/internal/test github.com/restic/restic/internal/walk github.com/restic/restic/internal/worker

restic/restic/internal/worker
ok      github.com/restic/restic/cmd/restic     363.582s
ok      github.com/restic/restic/internal/archiver      90.480s
ok      github.com/restic/restic/internal/backend       10.573s
ok      github.com/restic/restic/internal/backend/azure 0.019s
ok      github.com/restic/restic/internal/backend/b2    0.018s
ok      github.com/restic/restic/internal/backend/gs    0.043s
ok      github.com/restic/restic/internal/backend/local 6.685s
ok      github.com/restic/restic/internal/backend/location      0.037s
ok      github.com/restic/restic/internal/backend/mem   5.801s
ok      github.com/restic/restic/internal/backend/rest  0.120s
ok      github.com/restic/restic/internal/backend/s3    0.048s
ok      github.com/restic/restic/internal/backend/sftp  12.737s
ok      github.com/restic/restic/internal/backend/swift 0.111s
ok      github.com/restic/restic/internal/backend/test  9.690s
ok      github.com/restic/restic/internal/cache 6.551s
ok      github.com/restic/restic/internal/checker       24.832s
ok      github.com/restic/restic/internal/crypto        2.766s
ok      github.com/restic/restic/internal/debug 0.073s [no tests to run]
?       github.com/restic/restic/internal/errors        [no test files]
ok      github.com/restic/restic/internal/filter        1.419s
ok      github.com/restic/restic/internal/fs    0.035s
ok      github.com/restic/restic/internal/fuse  33.905s
ok      github.com/restic/restic/internal/hashing       0.660s
ok      github.com/restic/restic/internal/index 260.385s
?       github.com/restic/restic/internal/limiter       [no test files]
?       github.com/restic/restic/internal/list  [no test files]
?       github.com/restic/restic/internal/migrations    [no test files]
?       github.com/restic/restic/internal/mock  [no test files]
ok      github.com/restic/restic/internal/options       0.024s
ok      github.com/restic/restic/internal/pack  0.111s
ok      github.com/restic/restic/internal/pipe  0.087s
ok      github.com/restic/restic/internal/repository    41.658s
ok      github.com/restic/restic/internal/restic        44.791s
?       github.com/restic/restic/internal/test  [no test files]
ok      github.com/restic/restic/internal/walk  4.662s
ok      github.com/restic/restic/internal/worker        0.014s
1208.29user 62.11system 7:05.20elapsed 298%CPU (0avgtext+0avgdata 270616maxresident)k
36165inputs+85024outputs (17major+2146775minor)pagefaults 0swaps
```

Max storage used in `/dev/shm/restictest` was 238MiB total (Go build result plus restic test), with 57MiB for Go build result and 178MiB for restic tests.

I've identified one test (in `internal/archiver`, `TestParallelSaveWithDuplication`, which I disabled above) which uses a large amount of memory (> 800MiB). Disabling that allowed me to successfully run all tests on my smaller Pi3

So, from my point of view, there are several things we could do:
 * Remove/Rework the `TestParallelSaveWithDuplication`, exclude/remove it in the Debian package
 * Have a look at all tests and decide if they really need a repo and/or files stored on the disc, and then reduce the size where possible
 * In order to keep extensive tests which use a lot of i/o in the code base (we will probably have at least one or two of those), skip extensive tests when `testing.Short()` is set. Then, downstream distributions could use `go test -short` to skip those extensive tests. Would that work for you?
 * We could also mark several tests as "integration" tests which are not run by default. Maybe that's better?

Thoughts?

**Comment by stapelberg** [comment]
Thanks for looking into this.

I would recommend to proceed as follows:

1. Make tests use less resources and complete faster. This should suffice to fix the problem entirely.
2. If required (e.g. as a short-term workaround, or because certain tests can’t be made less resource-intensive), exclude them from -short runs as you mentioned. We can use this in Debian, but would prefer not to.

Marking tests as not running by default seems like a last-resort thing to me, so I’d recommend against that for now.

The machine I tested on was https://db.debian.org/machines.cgi?host=eller, which is mipsel, not ARM (I misspoke earlier).

**Comment by fd0** [comment]
Thanks for the clarification and your recommendation, I'll have a look at the tests.

**Comment by fd0** [comment]
I've implemented first measures in #1669, it should already be much faster now. I've reduced the amount of data that is generated/processed in the test and even removed two tests. All without reducing code coverage :)

**Comment by fd0** [comment]
Since 0.9.1 is already migrated to testing, I think the tests run fast enough. Can we close this issue @legrostdg?

**Comment by legrostdg** [comment]
You're right, let's close this.
