### ISSUE TITLE
RFE: add a --this-host option to commands that can filter on --host

### ISSUE THREAD

**Issue by larsks** [restic/restic#1658]
This isn't a bug report, so I hope that is' okay to ignore the template.

I'm writing some scripts to manage my restic backups, and I find that for regular repository maintenance (such periodically running `restic forget`), I want both to filter with `--tag <sometag>` and `--host myhostname`.

This seems so common that I found myself wishing that restic had `--this-host` option that would be the same as specifying `--host <the name of this host as it is known to restic>`.  So intead of something like:

    HOSTNAME=$(uname -n)
    restic forget --tag mytag --host $HOSTNAME ...

We could just write:

    restic forget --tag mytag --this-host ...

**Comment by rawtaz** [comment]
I think it's a bad idea to introduce an additional argument just for this. It pollutes the arguments and adds code+maintenance for very little reason (IMO).

You can just do this, you don't have to save it in a variable first:
~~~
restic forget --tag mytag --host `hostname` ...
~~~

So in short, adding another argument that just does the same as replacing your hostname with `hostname` seems unnecessary, but that's just my opinion.

We can find a ton of these "shortcuts" to make arguments and various features for, there's no end to that. Let's not go down that route, but instead keep things plain and simple, and let the rest of the system/context provide the flexibility to match each individual environment.

**Comment by dimejo** [comment]
Out of curiosity: How many different hosts have access to 1 repository?

**Comment by larsks** [comment]
@dimejo The answer of course depends on your particular environment, but given that the `--host` option exists I think we can assume that in many cases the answer is "> 1",

**Comment by larsks** [comment]
> I think it's a bad idea to introduce an additional argument just for this.

@rawtaz I think it's a bad idea that a forget operation will by default affect hosts other than the current host.   This is the sort of behavior that can lead to unexpected data loss, which with a backup program should not be the path of least resistance.

But I also sense that I'm on the wrong side of this particular argument.

**Comment by rawtaz** [comment]
@larsks Hmm, but even if your suggestion was implemented, the forget command would by default possibly affect other hosts, if you do not provide your suggested argument. So to prevent the default affecting of other hosts, you need to provide e.g. the `--host` or the suggested `--this-host` arguments.

So there are two issues:

1. A concern that `forget` affects snapshots for other hosts than the one you run the `forget` command on.
2. An opinion that it's messy to write a command subsitution instead of an actual hostname, in the restic command line.

Regarding # 1, I guess you already know that restic will group snapshots on host and path by default (see the `--group-by` argument to `forget`). So if you have e.g. 20 snapshots in total for two different hosts, where one of the host owns the last 10 snapshots and the other one the 10 snapshots before that, and you then run e.g. `forget --keep-last 5`, it will not keep only 5 snapshots for one of the hosts, it will keep 5 snapshots for each host (10 in total). In a way this is a safety measure that helps with this concern.

**Comment by larsks** [comment]
Also, I may be wrong about the behavior I thought I saw, so I am re-confirming that right now.

**Comment by fd0** [comment]
Thanks for the feedback. I'm with @rawtaz here, I think a separate option is not necessary. By default, restic will treat  snapshots from different hosts separately. This can be changed by setting `--group-by` to e.g. `tags,paths`, please see the help and the manual for details.
