### ISSUE TITLE
Build new cache during check

### ISSUE THREAD

**Issue by fd0** [restic/restic#1665]
During `check`, the cache is disabled for safety reasons, which means restic will access blobs stored in pack files as it needs them. When several blobs of a single pack file stored in the repo are needed one after another, restic accesses the same file in the backend several times. For some cloud-based backends (like B2), this behavior is billed, each download file transaction costs a very small amount of money.

Instead, we could change the behavior of `check`: Do not use the existing cache, but create a new one in a temporary directory. This means that the whole file is downloaded when the first blob is accessed, but then all further blobs in the same file can be read locally.

Shouldn't be hard to do, this is just a reminder issue to actually try that.

**Comment by ifedorenko** [comment]
This cache is for directory packs only and should not grow too big, right? 

Most systems have limited temporary directory space available, so the cache will need to capped at certain capacity if you plan to cache all data packs. Which in turn implies some packs may need to be downloaded multiple times during check, which in turn may need some optimization of how restic chooses pack download order.

FYI, I am working on concurrent restorer implementation where I plan to employ transient capped cache of downloaded data packs. Hope to submit (very rough) draft for discussion in the next few days.

**Comment by fd0** [comment]
Yes, the cache should not grow indefinitely, but adding such logic sounds complicated and error-prone, hm.

I'm looking forward to your idea for the restorer!

**Comment by kamudadreieck** [comment]
I would like to note, that even if you specify `--with-cache --cache-dir /tmp/empty-folder/` , restic check does not seem to populate the cache correctly, since the same blobs are requested very often, and the cache directory is too small (~50mb) in comparison to the one on the machine which does the backups (~1.6gb).
The `.cache/<id>/data` folder is empty.

Unfortunately I did not log the requested ranges on the rest-backend, but I assume that even some ranges are downloaded multiple times. The most frequently requested blob was queried about 2 million times with an average response size of 800 bytes.
I do not know if overlapping ranges are possible, but if not, then some has to be downloaded multiple times.

**Comment by fd0** [comment]
Overlapping ranges aren't relevant, so I assume there's a bug.

**Comment by fd0** [comment]
I found the issue, it'll be fixed in #1696
