### ISSUE TITLE
consider making some operations password-less (if possible)

### ISSUE THREAD

**Issue by doudou** [restic/restic#1666]
This is a feature suggestion, that it could be helpful (and I'm guessing probably harmless security-wise) to permit having some operations without providing the repository password

The setup I have is as follows: a bunch of backup clients that restic into a centralized backup server. The server then uploads the restic data offsite. So far, the clients need knowledge about the repository password, but the server doesn't. The clients don't know anything about the offsite storage credentials, only the server does.

So far, an unauthorized party that gets root access on one of the laptops would also get access (from the server) to historical data for this particular client. To get more (e.g. offsite storage credentials), he/she would need to break into the backup server itself.

Under this architecture, I would have liked to have at least two operations "repo-password" less to be able to run them on the server:
- prune
- snapshots list (only snapshot dates), to ensure that all clients do backup regularly

Would one or the other be possible under the current architecture of restic ? If not, could it be possible (especially for prune) to do the expensive operation on the server (find what is used), and the actual pruning by the client ?

**Comment by fd0** [comment]
Hey, thanks for the suggestion.

> Would one or the other be possible under the current architecture of restic? If not, could it be possible (especially for prune) to do the expensive operation on the server (find what is used), and the actual pruning by the client?

No, that's not possible with the way the repository is structured and encrypted. One of the basic ideas for restic is that **all** data in the repo must be properly encrypted, so that attackers who have access to the files in the repo are unable to decrypt the data and modifications can be detected by the client.

Making operations like `prune` or even accessing snapshots not require the repo password would imply storing this data in unencrypted form in the repo. That's a large change to what we do right now.

Restic does not offer making unencrypted backups for a reason: We want to concentrate on having encrypted backups. There were cases in the past where programs which had an option to disable encrypted could be tricked into saving unencrypted data although they were configured to encrypt all data before.

At the moment, you can either decide to trust a machine (then it can have the repo password and run operations like `prune`), or not trust a machine (then don't give it the repo password). There's no trust level in between those two, at least not for now. Implementing one may happen at some point, but I don't see this for the near future. We have a lot of work to do until we may eventually get there :)

Implementing a mode where backups aren't encrypted at all is tracked in #1018. Please subscribe over there if you'd like to be notified of any (eventual) progress.

I'm closing this issue for now, please feel free to add further comments. Thanks!
