### ISSUE TITLE
restic as archiving solution

### ISSUE THREAD

**Issue by m4nn** [restic/restic#1674]
Hi,

Thank you for all the hard work and effort put into restic, especially the complete and concise documentation, oft overlooked.

I was wondering if restic could be used as an archive solution, so my use case would be a fixed directory structure containing various files, once backed up to a restic repository, the files would be deleted from the local server. Over time new files shall be added, which then would need to be merged with the remote restic repository. After reviewing the documentation I am unclear as to how I could do this, is this use case feasible with the current version?

If not, then two possible implementations could be:

1. Unidirectional (one-way) pushing of data to an existing snapshot.
2. Ability to merge two or more snapshots.

Appreciate any feedback.

**Comment by rawtaz** [comment]
Hi,

Is there any specific reason you didn't post this in the forum instead? The issue template you saw when editing your message explicitly asks for this, so I'm curious if there's something we need to improve to get this type of usage question into the forum instead of in issues.

Every time you back up files to your repository with restic, a snapshot is created. This snapshot is a (browsable) copy of the backed up files at that point in time. Next time you make a backup, a new snapshot is created, containing the files you backed up that time.

These snapshots does not go away by themselves, you have to tell restic to forget about them when/if you want to. And you can restore from them at any point in time, but when you do so, you select which snapshot you want to restore from, and get the files from that snapshot alone, not other snapshots.

If you want to just throw new files and changes of files onto one and the same repository, a sync solution is probably better, because they often have a way to "merge" the new content onto the already synced one (i.e. syncing but without deleting files from the target that no longer exist on the source, which is what I suppose you mean).

Please note, though, that you can mount the restic repository and browse the snapshots using your regular file browser, in case that helps.

**Comment by m4nn** [comment]
> Is there any specific reason you didn't post this in the forum instead? The issue template you saw when editing your message explicitly asks for this, so I'm curious if there's something we need to improve to get this type of usage question into the forum instead of in issues.

My sincerest apologizes, quite clearly I overlooked that, I am more than happy to close the issue and create a forum thread instead? Please advise.

**Comment by m4nn** [comment]
> If you want to just throw new files and changes of files onto one and the same repository, a sync solution is probably better, because they often have a way to "merge" the new content onto the already synced one (i.e. syncing but without deleting files from the target that no longer exist on the source, which is what I suppose you mean).

From my limited understanding what I was hoping for is something like the below:

`restic -r /backup backup /home/data -s 12c40cd4`

In the above example, the ability to pass a preexisting snapshot specified by the snapshot id. restic already does diffs to determine incremental backup, so I thought it wouldn't require too much work to implement, of course I speak as a layman.

**Comment by rawtaz** [comment]
No worries, just wanted to know.

That is exactly what restic does. It only backs up the data that actually changed, and only the parts of the files that actually changed. It automatically find the parent snapshot to use, you don't have to specify it (but you can if you want to).

I suggest you try it out and see how it works :)

**Comment by fd0** [comment]
Thanks for the question, and the (already complete) answer by @rawtaz. Restic is meant to be a backup program, which is a use case slightly different from an archiving system. You can certainly use restic as something similar to an archiving system, but we won't add any features (with high probability) which are not needed for a backup system. Modifying snapshots is one of those things. We may at some point implement a function which allows removing files from snapshots (in case you saved files that should not have been in the repo in the first place), but that's about it in terms of modifying a snapshot's files and folders.

I'm a fan of the "one tool one job" philosophy, and we had a similar discussion already for a "sync folders between machines" use case, which we also declined to implement.

So, if you can live with the fact that restic will present "snapshots" for a directory with a timestamp at which the snapshot was taken, and you're find with searching for a file you're looking for in the snapshots, then you can already use restic as an archiving system.

I hope this answers your questions (together with what @rawtaz already wrote). I'm going to close this issue for now, please feel free to add further comments (or start a new thread in the forum :smile:).
