### ISSUE TITLE
Implement Argon2id

### ISSUE THREAD

**Issue by ExoUNX** [restic/restic#1677]
I currently find the current KDF (scrypt) implementation adequate, however I think it would be nice to move to a KDF that will most likely be supported much longer and more widely used. Argon2id is also a more safe and versatile than scrypt.

I believe switching the primary KDF will be safe as long as we check the hash string for the correct KDF and use the appropriate KDF. The current KDF method would be renamed and only used for validation (if needed.)  

I would be more than glad to implement Argon2id and deprecate scrypt myself and share the test builds if the project would be willing use Argon2id.

Edit:

Sorry, I forgot to link to GoDoc. Argon2 is supported.

https://godoc.org/golang.org/x/crypto/argon2

**Comment by bowensong** [comment]
Please describe why changing the KDF would make restic better?

Because from what I can tell, changing the KDF now will not improve the security (because scrypt is not broken) or affect the speed of backup (KDF is only used once before the backup starts).

**Comment by fd0** [comment]
Thanks for the suggestion and your offer to work on restic!

Adding the actual implementation is not much work, modifying the repository format in a backwards-compatible way is much more work.

I think scrypt is adequate for the foreseeable future. Adding a second KDF will introduce additional complexity and may introduce new bugs. In my opinion, increasing the complexity just because it would be nice does not convince me.

I'm closing this issue for now, please feel free to add further comments. Thanks!
