### ISSUE TITLE
Upper bound for scrypt parameters?

### ISSUE THREAD

**Issue by LouisChrist** [restic/restic#1697]
The scrypt parameters selected by restic seem not to comply with [RFC 7914](https://tools.ietf.org/html/rfc7914#section-2). According to RFC 7914 `N` has to be smaller than `2^(128 * r / 8)`. All my keys have the parameters `N = 2^18` and `r = 1`, but `2^18 > 2^(128*1/8) = 2^16`.

This restriction was not part of the original [scrypt paper](https://www.tarsnap.com/scrypt/scrypt.pdf) which might be the reason why the go implementation of scrypt works with these parameters. But it might be a good idea to implement this restriction to ensure future compatibility.

I came across this problem because i tried to access a repository from python code. I used the [cryptography](https://github.com/pyca/cryptography) package which is based on openssl. Based on the documentation and on my testing, it seems that openssl complies to RFC 7914 and doesn't accept the parameters generated by restic.

**Comment by fd0** [comment]
Huh, that's interesting. We're using github.com/elithrar/simple-scrypt for calibration, I think this should be fixed there. @elithrar what's your take on this issue?

**Comment by fd0** [comment]
I've tried to ask Colin, maybe he answers :) 
https://twitter.com/resticbackup/status/980074778525659137

**Comment by elithrar** [comment]
Hi there - simple-scrypt was based on the scrypt paper.

I’m happy to take a PR to be RFC-compliant, but we should still be able to verify non-compliant params+keys.

**Comment by cperciva** [comment]
Huh.  The /8 in there looks like a typo.  Sorry about that...

**Comment by fd0** [comment]
@cperciva thanks a lot for chiming in! So, basically @LouisChrist found a typo in the RFC? Which is implemented by OpenSSL? Awesome :laughing:

**Comment by LouisChrist** [comment]
Thanks for the quick responses.

I read thought the related openssl source code and it indeed checks for `N < 2^(128 * r / 8)`.

```C
/*
* Need to check N: if 2^(128 * r / 8) overflows limit this is
* automatically satisfied since N <= UINT64_MAX.
*/

if (16 * r <= LOG2_UINT64_MAX) {
    if (N >= (((uint64_t)1) << (16 * r)))
        return 0;
}
```
If it is a typo in the RFC, I think this issue can be closed.

**Comment by FiloSottile** [comment]
Oh, I didn’t know about the RFC upper limits. @cperciva could you briefly explain / point to a discussion of the rationale for them? Both for personal curiosity and to update my post. I can also file an errata if the RFC has a typo.

Tangentially, r != 8 looks weird, and I think is due to a misunderstanding of its meaning in simple-scrypt. I’ll open an issue over there later.

**Comment by cperciva** [comment]
Ok, now I'm confused.  I was thinking that value was because we were reducing values mod N and needed to make sure they were large enough, but that doesn't make any sense -- it would be saying that N must be less than 2^1024.  I think I need to go back to my RFC co-author (aka. the guy who took my paper and translated it to RFC-speak) and see if he has any recollection of where that limit came from...

**Comment by elithrar** [comment]
Thanks to @LouisChrist PR (almost merged), I should have a fix for r = 8 in simple-scrypt within the day. I'll tag a new minor release (v1.3.0) and update this thread once done.

**Comment by elithrar** [comment]
Fixed in v1.3.0 of simple-scrypt: https://github.com/elithrar/simple-scrypt/releases/tag/v1.3.0

**Comment by fd0** [comment]
Great, see #1702

**Comment by fd0** [comment]
Merged.

**Comment by MichaelEischer** [comment]
Closing this as it seems to be resolved with the scrypt library update.
