### ISSUE TITLE
godoc developer documentation

### ISSUE THREAD

**Issue by fw42** [restic/restic#173]
https://godoc.org/github.com/restic/restic

Is kinda incomplete. We should add a package description and documentation for every public function and method as well as some examples on how to use the restic package API.

[golint](https://github.com/golang/lint) can be used to generate a list of undocumented (but exported) functions or variables.

**Comment by fd0** [comment]
Good point, thanks for creating this issue. It's not super critical, but valuable.

Maybe we can add just a few words to the top-level package that describes what restic is and referers to the project page at Github, just as a placeholder until the documentation is complete (and this issue is closed).
