### ISSUE TITLE
Unable to find out a way how to restore latest snapshotted version of stdin file

### ISSUE THREAD

**Issue by tarelda** [restic/restic#1884]
## Output of `restic version`
restic 0.9.1 compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?
I started with snapshotting three files into repository with commands like this:

```
restic backup --stdin --stdin-filename file1
restic backup --stdin --stdin-filename file2
restic backup --stdin --stdin-filename file3
```
Repeated it few times and ended up with repository of this structure: 

```
/ # restic snapshots
repository 4a4f668c opened successfully, password is correct
ID        Date                 Host          Tags        Directory
----------------------------------------------------------------------
be759f8f  2018-07-14 17:00:37  6da6660d210c              /file1
1fdf12cb  2018-07-14 17:00:39  6da6660d210c              /file2
297c1c29  2018-07-14 17:00:41  6da6660d210c              /file3
f5526524  2018-07-14 17:00:46  6da6660d210c              /file1
69429b2a  2018-07-14 17:00:48  6da6660d210c              /file2
1dd50860  2018-07-14 17:00:50  6da6660d210c              /file3
----------------------------------------------------------------------
```

## What backend/server/service did you use to store the repository?
S3 (Minio)

## Expected behavior

Typing restic dump latest file2 should get me dump of latest snapshot of this file. 

## Actual behavior

```
/ # restic dump latest file2
repository 4a4f668c opened successfully, password is correct
cannot dump file: path "file2" not found in snapshot
```

Worth noting is that latest file added (file3) is restored like it should be.

**Comment by fd0** [comment]
This is a user interface issue, restic is working as it should. I'll try to explain. When `latest` is passed to `restore` or `dump` as the snapshot ID, restic uses the latest snapshot which matches the criteria. In your case, there were no criteria, so restic selects `1dd50860`. Unfortunately, this snapshot does not have `file2`, but `file3`. The result is the error message you saw: restic is unable to find the requested file.

There are two solutions for what you're trying to do:
 * Use the snapshot ID instead of `latest`: `restic dump 69429b2a file2`
 * Give restic the path it should use to find the latest snapshot: `restic dump --path /file2 latest file2`

Please let us know if it works!

**Comment by tarelda** [comment]
@fd0 indeed both works. 
When I tried to find a way to retrieve backup based on path I was typing --path /, which didn't work, so I assumed that this is a wrong way to do this. I think that clarification in doc could do wonders here. I mean, I had no idea that path option has to be exact path as in Directory column and that in case of stdin files it is their name.

**Comment by fd0** [comment]
I've added a bit more text to the section, please have a look here: https://github.com/restic/restic/commit/64d27eed868812dfab1b9842c95db943ebf71951

https://restic.readthedocs.io/en/latest/050_restore.html#printing-files-to-stdout

**Comment by tarelda** [comment]
Looks good. Huge thanks for that 👍

**Comment by Alwaysin** [comment]
@fd0 Just a minor typo:
```The path must match the pat**c**h printed in the “Directory”```
