### ISSUE TITLE
B2 Application keys once again

### ISSUE THREAD

**Issue by cuspat96** [restic/restic#1923]
### Dear Diary
Today i tried to test new function introduced in #1914 but unfortunately the terminal spit out an error.

Output of `restic version`
--------------------------
`restic 0.9.1 (v0.9.1-96-g247d2b72) compiled with go1.10.2 on linux/amd64`

How did you run restic exactly?
-------------------------------
``` 
export B2_ACCOUNT_ID="<myAccID>"
export B2_ACCOUNT_KEY="<**NEW APPLICATION KEY CREATED ON BACKBLAZE**>"
export RESTIC_REPOSITORY="b2:<myname>"
restic snapshots 
```

The output is:
`Fatal: create repository at b2:<myname> failed: b2.NewClient: b2_authorize_account: 401: Invalid authorization`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
This version of restic should work with new application keys as of Pull request merged in #1914

Actual behavior
---------------
Throws an error with any command - init new repo, show snapshots etc.

Steps to reproduce the behavior
-------------------------------
1. Use bucket created earlier in backblaze, before Backblaze intoduced Application Keys
2. Create new Master Key(maybe not required)
3. Create Application Key with access to all buckets, read-write
4. Use that Application Key as B2_ACCOUNT_KEY variable

Do you have any idea what may have caused this?
-----------------------------------------------
Nope actually. Or maybe I'm doing something wrong(more likely)

Do you have an idea how to solve the issue?
-------------------------------------------
Niet

Did restic help you or made you happy in any way?
-------------------------------------------------
I replaced almost all of my backup solution with restic. It's reeeeealy great. Thank you all for your hard work.

**Comment by fd0** [comment]
An application key consists of a `B2_ACCOUNT_ID` (which is longer than the master account ID) and a `B2_ACCOUNT_KEY`. Only setting the latter won't get you access to your data ;)

Did you set both?

Since this came up two times today, I think we should improve the docs on that. What did you read? Did you find the section in the manual?

**Comment by cuspat96** [comment]
Yeah that was the issue. After changing `B2_ACCOUNT_ID` to `applicationKeyId` provided by backblaze with the application key and it's working.

So to use the new B2 Application Keys you have to set:
`B2_ACCOUNT_ID=<applicationKeyId>` (not the master account ID
`B2_ACCOUNT_KEY=<applicationKey>`

The docs really need some touchups to explain it a little more clearly :)

**Comment by fd0** [comment]
I've tried to make it clearer, can you please have a look? 
https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#backblaze-b2

**Comment by fd0** [comment]
If you have ideas for improving the help text even more, please create a PR!

I'm closing this issue for now.

**Comment by ndarilek** [comment]
Sorry to hijack this issue, but when did the account ID change from being the master account ID, to being the application key ID? And did this involve an internal Restic change?

I ask because I'm having some issues with this, but am using [Stash](https://github.com/appscode/stash) which appears to be on V0.8.0. Wondering if something related to the interface with B2 has changed since then so I can poke them about an upgrade.

Thanks.

**Comment by fd0** [comment]
The new "application keys" were introduced by Backblaze in 2018, then we updated the https://github.com/kurin/blazer library to support them.
