### ISSUE TITLE
restic vs camlistore

### ISSUE THREAD

**Issue by alexkoch01** [restic/restic#193]
Although restic seems like a very good project, could you explain in a nutshell how it differs from Camlistore in scope of "backups" which Camlistore advertizes as well as a use case. What more features in this domain does restic offers compared to Camlistore?

**Comment by fd0** [comment]
From my point of view, the most important different is that restic is a program specialized in doing backups. You can also use camlistore for backup, and it will also work well due to the deduplication. restic is heavily influenced by camlistore concerning the deduplication and storage.

However, there are several things that set restic apart from camlistore:

 * Efficiently figure out what needs to be backed up. When doing an "incremental" backup (i.e. there is an old backup of the same directory), restic checks the timestamps and only reads those files that have changed or are new.
 * Better algorithm for Content Defined Chunking: restic uses Rabin Fingerprints instead of the adler32-based rsync algorithm that camlistore and bup use. Rabin fingerprints and their properties have been studied quite well, I really like this approach much better because of the sound algebraic basis. The adler32-based algorithm looks really strange to me, having two different `uint32` that are used to sum up bytes in an arbitrary way (probably Andrew Tridgell in his phd thesis about rsync).
 * The chunk size for CDC is better suited for backups. Restic uses blocks of about 1MiB, whereas camlistore uses 8KiB, so restic needs to deal with a lot less blocks. That makes it more efficient.
 * At the moment, restic only supports symmetric cryptography, and doesn't rely on GPG or the OpenPGP format. I think that this is a big plus, because the crypto-related code is small and can easily be audited. The code that is used in restic has already been reviewed by two people besides me. Maybe we'll add asymmetric cryptography later (for a discussion of use cases see #187).

I think these are the main points. Anything to add?

**Comment by fd0** [comment]
I think this is answered now.
