### ISSUE TITLE
Restic & rclone

### ISSUE THREAD

**Issue by urezdaye** [restic/restic#1957]
Version: 0.9.2 with go1.10.3
-----
Command Ran: ```restic -r rclone:foo init``` - foo is webdav, using https, username/password

Rclone config: ```<webdav_url>, vendor: 'other', username/password```

Running command did not create repository on webdav server, created locally. Digging into the error deeper, shows failure: x509 certificate signed by unknown authority. No way to use rclone ```--no-check-certificate```

What backend/server/service did you use to store the repository? Webdav
----------------------------------------------------------------

Expected behavior
-----------------
Expected to 

Steps to reproduce the behavior
-------------------------------
1. Rclone config <to https webdav>
2. ```restic -r rclone:foo init```
3. Folder foo is in directory, in location where I ran the command in terminal.

Do you have any idea what may have caused this?
-----------------------------------------------
x509 certificate signed by unknown authority

Do you have an idea how to solve the issue?
-------------------------------------------
Allow x509 certs signed by keychain.

Did restic help you or made you happy in any way?
-------------------------------------------------
It hasn't helped yet because I am trying to backup my mac. Excited with the possibilities though. Cheers.

**Comment by stevesbrain** [comment]
Just to confirm, the command you ran was (for example):

`rclone serve restic --addr localhost:8889 --user foo --pass s3kr1t remote:bucket/path --no-check-certificate`

And this did not work? If that's the case, I'd be thinking more that it's an issue with rclone (as in, `rclone` is the one responsible for the `--no-check-certificate` flag) so might be a question for them, rather than `restic` (as all `restic` cares about is connecting to your `rest:http://localhost:8889` backend)

**Comment by stevesbrain** [comment]
In this example, is "example" a remote that already exists in rclone? For example, for me to back up to a new bucket under an existing "b2" remote, I'd do the following (ignoring the fact we can use b2 directly in restic, of course :P)

```bash
# First, just showing that I have a remote named "b2" with a type of "b2"
:: [stevesbrain@duck] ~
$ rclone config
Current remotes:

Name                 Type
====                 ====
b2                   b2

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q

# restic looking at rclone remote, named "b2", with bucket specified after name
:: [stevesbrain@duck] ~
$ restic -r rclone:b2:new-restic-testic-bucket init
enter password for new repository:
enter password again:
created restic repository e42457c745 at rclone:b2:new-restic-testic-bucket

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

# Rclone listing contents of said bucket
:: [stevesbrain@duck] ~
$ rclone ls b2:new-restic-testic-bucket/
      155 config
      454 keys/de3154ea742fde34960bfad944c4fad29baf84de9eeabf23984e890b8d6c8936
```

From your example, it looks like you're trying to do `rclone:remote` but not providing a path - which may or may not work, depending on your bucket type.

**Comment by urezdaye** [comment]
I have the same thing that you have:
> rclone config

```
Name                 Type
====                 ====
remote          webdav

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> e

Choose a number from below, or type in an existing value
 1 > remote
remote> 1
--------------------
[remote]
type = webdav
url = https://foo.bar/mnt/urezdaye
vendor = other
user = urezdaye
pass = *** ENCRYPTED ***
--------------------
So on and so forth
```
When I run the command it fails with:
```
restic -r rclone:remote:backup init
rclone: 2018/08/17 11:58:24 Failed to create file system for "remote:workbackup": read metadata failed: Propfind https://foo.bar/mnt/urezdaye/backup: x509: certificate signed by unknown authority
Fatal: create repository at rclone:remote:backup failed: error talking HTTP to rclone: context canceled
```
When I change the command to:
```
restic -r rclone:remote\backup init
```
The repository "backup" is created within the directory I was running the commands (example if I was in directory "desktop" my repository is on my desktop, not in my webdav folder.

Thoughts and thanks for helping!

**Comment by fd0** [comment]
The issue here is that rclone tries to verify the certificate of your server but fails to do so.

You have two different options here:
 * rclone can be configured using environment variables, see [the documentatio](https://rclone.org/docs/#environment-variables). Passing `--no-check-certificate` is equivalent to setting `RCLONE_NO_CHECK_CERTIFICATE=true`.
 * configure how restic calls rclone, this is described in [the restic manual](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone): Pass the option `-o rclone.program="rclone --no-check-certificate"` to restic

Either of those should work.

I'll close this issue for now, as it is more of a question, please feel free to add further comments. Thanks!

**Comment by urezdaye** [comment]
That seemed to fix this issue. Thanks! Ran into another one - I'll work on that. Also, would my comments be helpful if I were to capture this as documentation for rclone for the community?

**Comment by fd0** [comment]
Sure, the best would be to add an example and a bit of text to the manual...
