### ISSUE TITLE
version command doesn''t print the version (FreeBSD)

### ISSUE THREAD

**Issue by danielb2** [restic/restic#1958]
Output of `restic version`
--------------------------

restic compiled manually compiled with go1.10.3 on freebsd/amd64

How did you run restic exactly?
-------------------------------

restic version

Expected behavior
-----------------

actually output the version info (0.9.2)

Actual behavior
---------------

prints the version of go only

Steps to reproduce the behavior
-------------------------------

restic version

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

Did restic help you or made you happy in any way?
-------------------------------------------------
yes

**Comment by mholt** [comment]
What is the actual, complete output of the `restic version` command? I get this when I manually compile it:

```
$ ./restic version
restic 0.9.2 (v0.9.2-30-g49d95e9a) compiled with go1.10.2 on darwin/amd64
```

**Comment by danielb2** [comment]
``` bash
$ restic version
restic compiled manually compiled with go1.10.3 on freebsd/amd64
```

on MacOS it looks different:

``` bash
$ restic version
restic 0.9.1 compiled with go1.10.3 on darwin/amd64
```

**Comment by mholt** [comment]
How did you build restic?

**Comment by danielb2** [comment]
I tried two options: `pkg install restic` and just building it from ports. the pkg installed version was 0.9.1 and latest ports 0.9.1, neither showing the actual version number when running the version command

**Comment by mholt** [comment]
Ah -- so you didn't build restic yourself; you're using a release. Interesting. Maybe there's a little glitch in https://github.com/restic/restic/blob/49d95e9a50d318a896a9d0f909a5395711c001d2/build.go#L332 for freebsd when releases are made.

**Comment by fd0** [comment]
Hm, that would be unexpected because we're not doing anything special here. I think what was meant here is "the ports one is compiled locally, while the pkg one is compiled by the project". In both cases, it looks like they are using `go build` directly, not our `build.go` script, they don't seem to use the binaries we provide. Here's the makefile for the ports:
https://svnweb.freebsd.org/ports/head/sysutils/restic/Makefile?revision=476987&view=markup

When using `go build`, the version string variable remains at the default setting (`compiled manuall`). We're setting it to a meaningful value within `build.go`, consisting of the contents of the file `VERSION` and the output of `git describe` (if available).

I can imagine that setting the version in the source code to the same value as the file `VERSION` (which is updated when I make a release, see [here](https://github.com/restic/restic/blob/master/scripts/release.go#L276)), so people running `go build` (including distributions) get a meaningful version string without having to do anything.

How do you do that for Caddy?

**Comment by fd0** [comment]
Ah, totally forgot that: thanks for the report!

**Comment by fd0** [comment]
The Debian project sets the version string during package build: https://salsa.debian.org/go-team/packages/restic/blob/master/debian/rules#L19

**Comment by mholt** [comment]
Ah, I see -- I didn't realize that using that method to install restic just ran `go build` instead of the build program.

> How do you do that for Caddy?

I don't -- if they run `go build` I don't have any version information. The build program pulls the version information from `git`.

**Comment by fd0** [comment]
@legrostdg btw, this means that you don't need to set the version manually for the Debian package any more, starting from the next release we do (these lines [here](https://salsa.debian.org/go-team/packages/restic/blob/master/debian/rules#L18-20))

**Comment by legrostdg** [comment]
@fd0 ok, should be fixed in https://salsa.debian.org/go-team/packages/restic/blob/a95a552d/debian/rules#L21-23

**Comment by fd0** [comment]
cool, thanks!
