### ISSUE TITLE
Periodically store a snapshot while the backup is still running

### ISSUE THREAD

**Issue by AndreKR** [restic/restic#1964]
Currently I'm using `restic 0.9.2 compiled with go1.10.3 on windows/amd64`.

I just tried out restic and I have started a backup to B2. I expect the backup to take about 2 weeks. (I have 512 kbps upstream and about 50GB to backup.)

I see that the index is written periodically, so uploaded blobs don't get lost. However, the snapshot is not written until the very end of the backup. If something would happen during those two weeks, I would have a hard time to recover *any* data from just the collection of blobs.

My suggestion is that restic should periodically write the snapshot (tag it `incomplete` or `preliminary`) just as it does with the blob index.

This was also [discussed](https://forum.restic.net/t/feature-to-create-incomplete-snapshots/654) (not by me) on the forum.

**Comment by dionorgua** [comment]
I'm not sure that it was mentioned in discussion, but there is easy enough workaround.. 
If your backup speed is limited by network connection it might be reasonable to split initial backup to a few subdirs and backup them independently. Once all parts are uploaded just create new snapshot all data. It'll be faster, than new upload, because restic will just rehash everything.

**Comment by mholt** [comment]
@dionorgua That's not really a satisfying workaround, though, because it involves a lot of effort, and is error-prone.

I do agree it would be nice if restic could be configured somehow to make partial snapshots available, in case backups take a long time (I have 1 Mbps upload, so my initial backups take months).

**Comment by yorkday** [comment]
Or the solution is we all get faster internet speeds ;)

I'm lucky enough to have 10Mbps upload at home.  But my local library is 50/50Mbps.

I agree with OP though, would be good for restic to provide some robustness by checkpointing as it goes for backups, especially say beyond 1 day of backup.

**Comment by mholt** [comment]
If checkpoints/partial snapshots are cheap, then I'd vote for every hour or so.

**Comment by yorkday** [comment]
Or align to the same frequency as writing the index - if this is already done periodically?

**Comment by AndreKR** [comment]
> If checkpoints/partial snapshots are cheap

Well, mine isn't complete, but if you already have a large backup, why don't you have a look at the size of your snapshop files.

**Comment by mholt** [comment]
Yeah, snapshot files are small -- it's the incomplete index I'm wondering about.

**Comment by AndreKR** [comment]
But the incomplete index is _already_ stored under [certain conditions](https://github.com/restic/restic/blob/d708d607fab766121d06ac64af55362daeb52a60/internal/repository/index.go#L69).

**Comment by fd0** [comment]
Indeed, restic uploads a new index file at least every 15 minutes to record the blobs that have been uploaded. When the process is aborted, the next instance of restic can download the index file and will then know what's already in the repo. This worked very well for us so far.

But you're right, when no `restic backup` process ever completes, users cannot restore anything. I agree that it would be technically possible and a great feature to have intermediate snapshots, so that at least the part which has already been uploaded can be accessed and restored.

On the other hand, I would make the already very complex archiver code even more complex. That's what I'm worrying about.

I'll think about this for a bit. :)

**Comment by dimejo** [comment]
With PR #2056 beeing merged, can this issue be closed?

**Comment by fd0** [comment]
Oh, good idea, thanks! I think the `recover` command sufficiently addresses this use case. :)
