### ISSUE TITLE
Feature request: "Restore newer/missing datasets" / "synchronize"

### ISSUE THREAD

**Issue by cfcs** [restic/restic#200]
It would be useful to have a feature that allows restoring files/datasets that are not currently in a "checked out" state locally while avoiding doing "double work" by downloading data that already resides in the local target directory.

This feature would enable asynchronous synchronization of files between multiple machines (not necessarily online at the same time), enabling users to have a full, shared, encrypted backup on an untrusted (always online) machine that the individual machines can sync from/to when they are online.

I envision an implementation that resembles the `restore` command that:
1) Takes a designated (local) target directory
2) loops over all snapshots - pseudo-code:

``` bash
for snapshot in `./restic list snapshots|egrep -o '[a-f0-9]{64}'`
  do ./restic ls $snapshot
done
```

3) Checks if any of the files in the snapshots are newer than what currently resides in the target directory, or if there are files present in the snapshot that do not exist in the local checkout.
4) Selectively does a `restic restore $snapshot` to extract the files

**NOTE:** One issue that could arise from the implementation of this feature is that it becomes impossible to delete a file as long as the snapshots still exists on the remote end.
A mechanism to "ignore" specific files/trees that you do not want restored / have been deleted would probably be desirable. This is already on the drawing board: https://github.com/restic/restic/issues/86

Thoughts? :-)

**Comment by fd0** [comment]
I like this feature, it could replace `unison` in my current setup, but it's rather far away from the core function of restic (namely: saving and restoring backups accurately). We'll leave this issue open for later.

**Comment by tf198** [comment]
I've got some proof of concept code for this for you to have a look at.  In my case I want to sync both a directory containing 100K+ images and a 2GB database file with minor changes each day.
My approach is:
* Move the current file out the way
* Run the chunker on it
* If all the chunk IDs match then just move it back and continue
* Start the restore but check the chunk index before using the repo.
* If it matches then copy the bytes from the current file rather than the repo

In my tests with a 2GB direcory across a network with about 3MB/s transfer the initial restore takes 13 minutes.  If I modify a few files and then restore again it comes down below 1 minute with the network saturated for the first 30 seconds while it pulls the metadata and then 30 seconds of CPU as it checks all the existing files.

https://github.com/restic/restic/compare/master...tf198:sync_restore
I haven't created a pull request yet as it is a bit rough and ready but I can't see it having too many adverse effects. Comments welcome...

**Comment by MichaelEischer** [comment]
The part with only downloading what has changed could be handled using #3425, besides that it would mostly be a question of deciding which files to overwrite and which not. Currently, overwriting existing files is a bit of a mess, especially if files are not writable by the current user.
