### ISSUE TITLE
Unable to create lock in backend

### ISSUE THREAD

**Issue by carlonluca** [restic/restic#2014]
Output of `restic version`
--------------------------
```
restic 0.8.3
compiled with go1.10 on linux/amd64
```

How did you run restic exactly?
-------------------------------
restic -r [...] backup [...]

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Restic repo is stored in a SMB share mounted via cifs.

Expected behavior
-----------------
The backup procedure should start.

Actual behavior
---------------
An error related to locks is returned:

`Fatal: unable to create lock in backend: load <lock/44825f7067>: invalid data returned`

I listed the locks in the locks directory and there were many locks. I removed all those locks and the above command started properly.

Steps to reproduce the behavior
-------------------------------
Not sure about this. Happens frequently anyway that locks remain in the directory, preventing any possible restic procedure from starting.

Do you have any idea what may have caused this?
-----------------------------------------------
I think this happens when a previous backup procedure fails for some reason. Locks remain in the locks directory and no other restic process can start.

Do you have an idea how to solve the issue?
-------------------------------------------
Remove all the existing locks. This is simple, but not good from a user's perspective.

Did restic help you or made you happy in any way?
-------------------------------------------------
Of course.

**Comment by fd0** [comment]
Thanks for the report! This is obviously a very bad user experience, and we should improve that. This bug will track it. The issue here is that when restic locks the repo, it looks at all the other locks, and for one of them (`44825f7067`) it read data back from the repository which does not match the SHA256 hash used for the file name.

If it happens again: Can you please check if the file is empty and test with `sha256sum` if the hash of the file really does not match the file name? The underlying issue may be the same as for #1999...

**Comment by Fuzion24** [comment]
I'm running into a similar-ish issue with restic locking during a backup after a failed backup:

```
Remove(<lock/3ac072125d>) returned error, retrying after 6.600543178s: sftp: "Failure" (SSH_FX_FAILURE)
```

It just retries this over and over.

**Comment by fd0** [comment]
@Fuzion24 that's a different issue, unfortunately `sftp` does not return proper errors in some situations. The most common one is that the permissions on the files/dirs in the repo on the server are wrong. Can you check that you really have write access?

**Comment by Fuzion24** [comment]
Hard drive was failing and remounting r/o.

**Comment by fd0** [comment]
Cool, glad you figured it out. It's a pity that the sftp server doesn't just pass through the error codes from the OS...

**Comment by rawtaz** [comment]
@carlonluca (or anyone else for that matter), Is this still happening with restic 0.9.6? I'm inclined to close it unless it's still a problem (in which case it needs to be triaged).

**Comment by stappersg** [comment]
(Reporting my observation and workaround)

Encountered the _lock_   on server `a`, being told the lock is from server `b` by PID _PID_.
At server `b` was process _PID_ not any more present in process table.

Removed the lock at server `a` with
```
restic -r type:URL -p /file/with/passwd unlock
```

Server `a` and `b` are both  Ubuntu 18.04,  both have restic version 0.8.3.

**Comment by rawtaz** [comment]
@stappersg What is the actual problem you are reporting or commenting on?

The way I understand what you wrote, you found that there was a lock in the repo, created by server `b`, and you solved that by unlocking the repo from server `a`. I don't see anything odd with that - sometimes locks are left in the repo, e.g. when a backup run doesn't complete (e.g. due to broken connection or some other reason causing restic to end prematurely). I don't see how this is related to what this issue is originally about (unable to create lock in the backend in the first place). Please clarify.

**Comment by stappersg** [comment]
(Reporting my observation and workaround in other words)

With  restic version 0.8.3 I did encounter this lock issue.
My websearch resulted into #1450 and this #2014.

Then I could not resist to add  here `restic   unlock`  as workaround for my problem of having an old version.

Please consider my postings here as a  _thank you for restic_.

**Comment by rawtaz** [comment]
@stappersg I see :) Thanks!

I'm closing this issue for now since there's no feedback and we very rarely get reports of this, so I don't think it's a very common problem.
