### ISSUE TITLE
Does restic support Windows, Mac and Linux?

### ISSUE THREAD

**Issue by cmcginty** [restic/restic#2016]
I couldn't find any platform information on the doc page. It would be super helpful to tell users what systems you support.

**Comment by dimejo** [comment]
While it is not specifically stated, the [release page](https://github.com/restic/restic/releases/) and the [installation page](https://restic.readthedocs.io/en/stable/020_installation.html) imply that restic supports Windows, MacOS, Linux and BSD. As restic is written in Go, restic can be compiled on any operating system that is supported by Go.

**Comment by fd0** [comment]
Since restic supports the three major OS (and a few smaller ones) I think it's sufficient as is. What would you expect? A sentence in the README stating that restic supports Linux, macOS and Windows?

**Comment by xacrimon** [comment]
@fd0 I think it would fit and clear this up.

**Comment by LinusT** [comment]
I agree that just a clear statement of formally "Supported Platforms" would help.

When it comes to windows support I think Restic falls a bit short since it does not support Windows Shadow Copies which is the defacto mechanism for how to back-up files in use. To do this optimally (1) would require using the formal API's. But it would violate the principle of using 100% pure go.

Alternative 1 is to run a shell script before execution of restic 
or (neater) 2 have restic detect a file lock issue and then trigger the shadow copy as needed.
For both these scenarios you will in essence run a script/command line with a source directory/drive and get back a mounted alternative path that files should be backed up from instead. To make the backups make sense restic needs to support re-rooting the backup sources ie backup files/directories under path-to-shadow-copy/** as if it was path-to-source/** . 

I think alternative 1 would be quite quick to implement. But we also need a documentation piece for the script to run pre and post backup. It is also a bit of a hassle when attempting to backup from multiple sources/drives in the same backup job. This is quite common on windows since few uses soft links to unify filesystem.

Alternative 2 would be a refinement with a better user experience (especially for the less tech sawy desktop users and people backing up cross multiple drives). It should not necessarily that much complex to implement.

**Comment by mholt** [comment]
@LinusT See https://github.com/restic/restic/issues/340 for updates on VSS support. (I think creating shadow copies on-the-fly will be slower than just making one of the drive and then using that. Takes about 1-2 seconds in my VM to create a shadow copy.)

**Comment by LinusT** [comment]
Thanks @mholt, realized after the fact that this issueis closed. I'll follow up on #340 instead.
Just to clarify my intent on #2 was to let restic 
- when file-cannot-be-opened 
- if file does not belong to shadow copy 
- initiate shadow copy on the volume in question
- retry file-open

- at the end of backup, remove all opened shadow copies

This would be automatic in a good ux sense imho
Perhaps with an option for shadow-copy=auto/always/never.
Many of my backups run cross multiple volumes so initiating shadow copies cross all, and remapping and destroying turns into quite a bit of shell scripting, that I think we should consider letting the backup tool handle.
