### ISSUE TITLE
Support 2tb of Photoshop files about 1-4gb each?

### ISSUE THREAD

**Issue by nicedreams** [restic/restic#2021]
How well is restic with large Photoshop and *.tiff files that are minimum 1gb and higher each?  Should I look at another solution for this type of backup?

Thinking restic split these down to compress and encrypt it all might not be reliable or painfully slow.

I guess a comparable question would be if you can backup 4GB MKV movies files using Restic or is that not efficient?  I hoping someone has tried this for movies at least so will let me know about large art files.

Am I better off with an rsync mirror (incremental) backups for this one scenario?  The server is a Xeon with 8GB ECC ram, but 5 years old.  I've got 2TB of files I need to backup for this art shop client.

**Comment by mholt** [comment]
Hi, welcome to the restic issues! (This would probably be a better fit for the forum: https://forum.restic.net since it's more of a question than a bug or feature. For future reference.)

I regularly back up files that are close to 10 GB in size using restic. Works great. Especially with a beefy server like that, you should be fine. In fact, restic's even faster with fewer large files than it is with lots of smaller ones (that's my experience, I might empirically be wrong, feel free to correct me).

Restic does not compress -- it deduplicates -- and the algorithm for "splitting" (chunking and packing) the files is very efficient, speed-wise.

I say go for it -- give it a trial run on a subset of your files if you're nervous -- and see how it goes.

**Comment by fd0** [comment]
Indeed, this would have been better in the forum. Thanks @mholt for answering the question! I'm closing this issue for now, the question has been answered.
