### ISSUE TITLE
Restic attempts to read /proc even after excluding

### ISSUE THREAD

**Issue by RaghavSood** [restic/restic#2083]
Output of `restic version`
--------------------------
restic 0.9.2 compiled with go1.10.4 on linux/amd64

System is Ubuntu 18.10

How did you run restic exactly?
-------------------------------

I performed an initial full system backup to backblaze using directly from my shell using:

    /etc/restic/restic --cache-dir=/etc/restic/cache --exclude={/etc/restic/cache,/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp,/var/run,/var/lock} --tag automated backup /

This backup had no issues.

Now, I am running using the following cronjob:

    45 * * * * . /etc/restic/.restic-env; /etc/restic/restic --cache-dir=/etc/restic/cache --exclude={/etc/restic/cache,/dev,/media,/mnt,/proc,/run,/sys,/tmp,/var/tmp,/var/run,/var/lock} --tag automated  backup / 2>> /etc/restic/restic.err >> /etc/restic/restic.log

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Backblaze

Expected behavior
-----------------

The cronjob makes a tiny incremental backup as it was run a few minutes after the full system backup

Actual behavior
---------------

Despite excluding /proc, the cronjob restic attempts to read from some subdirs in /proc (see attached restic.txt)

Steps to reproduce the behavior
-------------------------------

 - Run a full backup as described above
 - Run an incremental backup via cron

Do you have any idea what may have caused this?
-----------------------------------------------

No.

Do you have an idea how to solve the issue?
-------------------------------------------

No.

Did restic help you or made you happy in any way?
-------------------------------------------------

So far, I'm not particularly heartbroken about the errors. The backup job still appears to be running, and hopefully works. 

[restic.txt](https://github.com/restic/restic/files/2568591/restic.txt)

**Comment by fd0** [comment]
The output of restic you attached shows:
```
bash: /restic: No such file or directory
unknown command ",/var/run,/var/lock}" for "restic"
unable to open cache: MkdirAll: mkdir /home/raghavsood/.cache/restic: permission denied
```

Are you sure the line in the crontab you pasted is the really the one matching the output?

I don't know what caused the error in the first line, but the second line tells me that something with your cron file is wrong. You're relying on the shell to expand the `--exclude={foo,bar}` into `--exclude=foo --exclude=bar`, but restic complains that it was passed the suffix of the string `as a separate command-line argument `,/var/run,/var/lock}`. So I suspect the expansion did not happen at all. Can you check if there's maybe a space before the `,/var/run` in the exclude line?

This is the most likely cause for the issue you describe: restic gets passed the prefix of the string (`--exclude={/etc[...]`), which is never considered because there are no files/paths starting with a curly brace (`{`), so restic will not exclude anything.

Besides, I'm wondering: you did specify `--cache-dir=/etc/restic/cache`, but restic still tries to use `/home/raghavsood/.cache/restic`. What's up with that?

**Comment by RaghavSood** [comment]
Right, apologies for the first few lines. The errors you mentioned regarding the cache and the shell expansion are from a previous set of runs before the initial backup. I had added the `restic` user to backup without sudo as mentioned in the docs, but it still tried to use my homedir for cache. The expansion errors were because I had a random linebreak in the command initially.

The errors for the run I am referring to start from `error: open /proc/1/auxv: permission denied` and carry to the end of the file.

**Comment by RaghavSood** [comment]
Interestingly, I just ran it again directly from bash, and it completed just fine. Looks like running from cron is the differentiating factor.

**Comment by RaghavSood** [comment]
@fd0 is right, it was a bash expansion issue. Cron was defaulting to `sh`, and adding `SHELL=/bin/bash" to my crontab fixed it.

Might be worth mentioning on [this](https://restic.readthedocs.io/en/stable/080_examples.html?highlight=exclude#backing-up-your-system-without-running-restic-as-root) page, since that's where I go the curly-brace syntax from. Happy to do a PR if needed.

**Comment by fd0** [comment]
> Happy to do a PR if needed.

Please do! That may help many other users as well :)
