### ISSUE TITLE
Adding progress indicator to pack counting operation

### ISSUE THREAD

**Issue by kusalananda** [restic/restic#2159]
Output of `restic version`
--------------------------

```
restic 0.9.4 compiled with go1.11.4 on darwin/amd64
```
and
```
restic 0.9.4 compiled with go1.11.4 on openbsd/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Show approximate time remaining when counting packs during e.g. `restic prune --forget` and `restic forget`.

What are you trying to do?
--------------------------

On a backup repository I'm working with, these operations take in excess of 20 minutes (80000 packs), and it would just be a nice feature to have seeing that this sort of thing is already implemented for `restic backup` (which is quicker).

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, it's a backup program that is simple to use in scripts, and that requires _minimal_ configuration. I'm also relying on the fact that it does not need to be installed on a remote server to be used (with backing up using `sftp://`).

**Comment by fd0** [comment]
Thanks for the suggestion :)

**Comment by MichaelEischer** [comment]
From what I understand, this issue is about the "counting files in repo" step in prune/rebuild-index. This calls `backend.List` to get a list of all existing pack files. The problem with a progress bar is that we don't know the number of packs before. In `prune` it would be possible to use an approximation based on the packs contained in the repository index. However, that is not feasible for `rebuild-index`. What would work in all cases is showing the number of already found pack files. This would yield a progress bar like this:
`[hh:mm] 12345 packs found`

@kusalananda I'm not sure I fully understand the problem. You just mention that `prune` takes more than 20 minutes. I would expect he counting step to take less than a minute and the much slower blob listing step already has a progress bar.

**Comment by MichaelEischer** [comment]
The "collecting packs for deletion and repacking" has a progress bar by now.
