### ISSUE TITLE
Ability to tweak chunk pack size

### ISSUE THREAD

**Issue by saikpr** [restic/restic#2291]
Output of `restic version`
--------------------------
➜  ~ restic128mb version
restic 0.9.5 compiled with go1.11.1 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Restic has https://github.com/restic/restic/blob/master/internal/repository/packer_manager.go#L39
and https://github.com/restic/restic/blob/master/internal/restorer/filerestorer.go#L30 which specify approximate pack size which restic tries to target.

A good number of remote data storage have a limitation on the number of files, I have run into issues with Google Team Drive, and PUR based storage at work (it is full flash system, with glusterfs over the top). It should be reasonable to update the pack size on a repo level to enable varied use-cases.

What are you trying to do?
--------------------------
Either store the target pack size in the repo metadata or allow user to pass the parameter while backup (and maybe try to figure out the appropriate size for cache at the time of restore, for now a simple option to be given both times should work well)

Did restic help you or made you happy in any way?
-------------------------------------------------
Thank fully I haven;t had to restore data in an emergency, but I have tried to restore data as a disaster recovery exercise which provides comfort that restic has my back.

**Comment by saikpr** [comment]
I can take a stab at it, if these are the correct places for patching.

**Comment by saikpr** [comment]
@ifedorenko @fd0 let me know what you think, or it is not worthwhile to maintain it as an option?

**Comment by ifedorenko** [comment]
There is already #2195 that removes restorer dependency on any specific pack size. Can't comment on archiver side of things or whether such an option is generally a good idea.

**Comment by olifre** [comment]
It's actually not only the "number of files issue" - with these small pack sizes, in low latency high bandwidth situations (e.g. multiple Ceph-RGWs in the same GBit/s ethernet as the client), it's impossible to saturate the link since the RGW servers will be saturated by the flood of small requests first. 
Shuffling rclone in between does not help here, since it can only further segmentize to parallelize uploads, which it will not even do for such small packs.

**Comment by CristianCantoro** [comment]
I come from https://github.com/restic/restic/issues/1071, I am using a Google Team Drive as storage - a shared Google Drive space, with `rclone` as backend. Team drives have a limit in the number of files that can be stored. In my case, the limit is 400k files and I have around 6 TB of data to backup.

I would also like to add that my use case consists of quite big files, already compressed. The total size of the data I would like to back-up is ~6.1TB for 97465 files, meaning an average size of 62 MB per file.

I have hit the limit pretty squarely and I am getting this error:
```
Post request put error: googleapi: Error 403: The file limit for this
shared drive has been exceeded., teamDriveFileLimitExceeded
```

The right chunk size for my use case should be 50MB or 100MB, would that make sense?

**Comment by JsBergbau** [comment]
Another thing to take into consideration:
Suppose you have a 5 MB file, like a large Document you work a lot on. Since you work a lot on the changed data is distributed on a lot of pack files. So if you have 100 MB pack file size, which seams reasonable and if the data is distributed on 20 pack files, then 20 * 100 MB = 2GB data needs to be downloaded to restore the 5 MB file (!). As far this is my observation with restserver. I think it is the same with S3 backend and even perhaps with file backend. Who can tell more about the different behaviour with different backends?

To cut a long story short, with larger packfiles restore behaviour should be changed so only relevant parts of pack files are fetched. S3 support this https://stackoverflow.com/questions/36436057/s3-how-to-do-a-partial-read-seek-without-downloading-the-complete-file for restserver probably this needs to be implemented.

**Comment by MichaelEischer** [comment]
> To cut a long story short, with larger packfiles restore behaviour should be changed so only relevant parts of pack files are fetched.

restic already only downloads a part of a pack file: the download starts at the first blob necessary for restoring and ends at the last blob necessary from the pack file. That is it essentially cuts of the start and end of a pack file which is not required. This obviously still can include lots of unnecessary blobs between start and end. But it should be possible to improve on that by improving the selection of file ranges to download.

> Who can tell more about the different behaviour with different backends?

All backends should be able to request file parts as described above.

**Comment by Myridium** [comment]
So, `restic` is not meant for backing up small files `<1 KiB`? (impossible to do efficiently due to minimum `chunk` size being too large)

Is there an alternative available?

**Comment by JsBergbau** [comment]
Hi Myridium, I think you missunderstood something. Multiple files can be packed into a single pack file, see https://restic.readthedocs.io/en/latest/100_references.html#pack-format
With larger packsize more of these small files will be included in one pack file.

**Comment by Myridium** [comment]
> Hi Myridium, I think you missunderstood something. Multiple files can be packed into a single pack file, see https://restic.readthedocs.io/en/latest/100_references.html#pack-format With larger packsize more of these small files will be included in one pack file.

I don't think you understood my comment.
