### ISSUE TITLE
Support custom B2 endpoints

### ISSUE THREAD

**Issue by OJFord** [restic/restic#2300]
As a member of the 'Bandwidth Alliance', Backblaze waives the B2 egress fee if accessed from CloudFlare:
https://www.backblaze.com/b2/solutions/content-delivery.html

It'd be nice if restic supported configuring the B2 endpoint (e.g. `mydomain.com`) - then the only B2 fee would be for storage itself.

**Comment by dimejo** [comment]
AFAICT rclone supports this [since v1.47](https://rclone.org/changelog/#v1-47-0-2019-04-13). Have you tried using restic in combination with rclone?

**Comment by OJFord** [comment]
I haven't, but looks like you're right. Still think it'd be nice if it were first-party supported though.

**Comment by dimejo** [comment]
> Still think it'd be nice if it were first-party supported though.

Well, I would generally agree that repository locations should work well and be updated (within a reasonable time) as long as they are supported. But I wouldn't expect this to happen soon as the developers seem to have less spare time lately and development of restic has slowed down within the last months.

Since restic and rclone work together so well and rclone is supporting so many different backends (with lots of options) I'd personally propose dropping every backend besides `local` in future major versions of restic (e.g. 1.0) to make it easier for the developers. But @fd0 probably wants to keep them for backwards compatibility.

**Comment by MichaelEischer** [comment]
B2 by now has a free egress of three times the storage size. That should be enough for most use cases. Otherwise, use rclone if necessary. The library which we use to access B2 doesn't seem to support custom B2 download endpoints.
