### ISSUE TITLE
Add feature for randomized restore testing with failure reporting

### ISSUE THREAD

**Issue by geekpete** [restic/restic#2332]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

- Add a feature for randomized restore testing.
- Perhaps with parameters to filter only testing specific folders/files/filetypes or specific date ranges.
- Provide a restore test report with both top level summary and detail sections, provide the ability to output the report in json format

Until this is a native feature, something similar would be easy enough with a script, but a native feature would be great for baked in best practice for backup restore testing.

What are you trying to do?
--------------------------

Backups are only real if they're able to be restored.
Regular restore testing is key.
A simple way to schedule restic to run in restore testing mode and provide a report if/when restore tests fail would be a great feature that goes hand in hand with due diligence.

Did restic help you or made you happy in any way?
-------------------------------------------------

Great tool!

**Comment by ifedorenko** [comment]
`restic check --read-data-subset ...` is meant to implement rolling check of all files in the repository. It does not write files to filesystem, but verifies the repository has all data needed to restore the files first, then reads subsets of the files data from the repository and verifies data checksum. This should cover both repository corruption due to bugs in restic as well as bit rot and other problems with the repository storage. 

What additional problems do you expect the proposed new "random subset restore" to detect? I supposed "manually check restored files" can detect bugs in `check` itself... Do you plan to check restored files "externally", i.e. inspect manually or using external scripts?

Also see #2186, which talks about checking random data subset, as opposed to rolling check implemented by `--read-data-subset`

**Comment by geekpete** [comment]
Thanks, I'd overlooked the check function when used with read-data which should allow full and randomized testing of actual data testing fairly neatly.
More granularity might be a nice addition for users backing everything up but only wanting to guarantee that specific data is checked more thoroughly if some data is considered more important/critical than other data. In theory you could just use separate or additional repos for this and perform full checks on that data regularly though.
