### ISSUE TITLE
Backblaze (B2) 401 when invoking backup command

### ISSUE THREAD

**Issue by pcgeek86** [restic/restic#2339]
I'm trying to set up Restic on my Raspberry Pi 3B+ with a 2TB external USB magnetic disk attached. I am using Backblaze application keys to initialize a repository and initiate a backup. Repository initialization against my Backblaze bucket works correctly, and I can drill down into the `config` file that's created, using the B2 web UI. However, when I attempt to invoke the `restic backup` command (see below for details), I get an error saying that the repository doesn't exist at the specified path.

* Raspberry Pi 3B+
* Raspbian OS: `Linux pidev 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux`
* `restic 0.9.5 compiled with go1.12.4 on linux/arm`

### Initializing Repository Works Fine

```
> restic --repo b2:xxxxxxxxx:childpath/ init
enter password for new repository:
enter password again:
created restic repository xxxxxxxxx at b2:xxxxxxxxx:childpath/

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```

### Backing up doesn't work

```
restic backup --repo b2:xxxxxxxx:childpath/ /path/to/local/disk
Fatal: unable to open config file: Stat: b2_download_file_by_name: 401:
Is there a repository at the following location?
b2:xxxxxxxxxx:childpath/
```

**Question**: Is the Backblaze integration currently in a working state with the latest Restic version?

**Comment by Prof-Bloodstone** [comment]
I'm currently using
```
$ restic version
restic 0.9.5 compiled with go1.12.4 on linux/amd64
```
Haven't had any issues with backblaze - creating backups, pruning etc works fine for me.
Notice that it's on x64 binary. Will try on RPi when I have time.

**Comment by MichaelEischer** [comment]
The B2 integration has been successfully used with application keys, see e.g. #3450, #2172.

**Comment by andras-tim** [comment]
> The B2 integration has been successfully used with application keys, see e.g. #3450, #2172.

I have a daily backup to B2, but today night I had this issue with `restic 0.12.1 compiled with go1.16.6 on linux/amd64` on Ubuntu Focal.

As I read the suggested tickets, so I have to use a non-restricted app key, but... I used the current config for approx. a year and the 0.12.1 is also used for weeks too...

#### However, I found the root cause:
I have to re-generate the B2 key to get some extra permissions. So the repo restricted old key capabilities differ from the fresh generated:

* **old:** `deleteFiles`, `listBuckets`, `listFiles`, `readBuckets`, `readFiles`, `shareFiles`, `writeFiles`
* **new:** `deleteFiles`, `listBuckets`, `listFiles`, _`readBucketEncryption`_, `readBuckets`, `readFiles`, `shareFiles`, _`writeBucketEncryption`_, `writeFiles`
