### ISSUE TITLE
Restic Backup Report

### ISSUE THREAD

**Issue by kayvanaarssen** [restic/restic#2341]
Don't know if there is an issue or topic of this, but i could not find it.

Is there a solution implemented for Restic to send a Backup Report to an email in case of errors, information or succes?

And maybe some kind of daily report for backups etc.

**Comment by frittentheke** [comment]
Certainly some script calling restic or using the REST api to query for info for that mail is possible.

But having restic print out a configurable human readable report (that could be piped to an email sending tool of your choice) would be nice.

I am old school myself and would love an email after my cron .. eh systemd-timer is done with the backup.

**Comment by pmatuszy** [comment]
log to file and send it

**Comment by rawtaz** [comment]
Usually whatever tool/system you use to run/automate/schedule restic will make sure to send the output from restic to whatever reporting system you have, e.g. a mail when you run it using cron.

So I don't really see why this should be in restic - restic is a backup program, and it already outputs a report of the backup run. Use that output and send it however you want. If you want more specific reporting you need to script or wrap that anyway, and can then use the existing commands in restic to know what snapshots there are or similar.

Daily reports isn't really applicable since there's no restic server - restic runs when it backs up or similar, so it doesn't know about other backups during the day. To aggregate that, you'd need to script something that lists the snapshots made during the day. I think the possibilities are already in restic to do what you need.

Am I missing something here, or can we close this issue?

**Comment by pmatuszy** [comment]
IMHO you can close but I didn't start it in the first place.

**Comment by MichaelEischer** [comment]
Closing this issue as there should be already enough output provided by restic to implement this feature request via scripting.
