### ISSUE TITLE
Option for restic restore to delete local files not in snapshot

### ISSUE THREAD

**Issue by tesujimath** [restic/restic#2348]
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Add a command line option to `restic restore`, say `--delete`, which causes restic to delete any local files not in the snapshot.

What are you trying to do?
--------------------------

I want to restore the directory (the whole of which has been backed up by restic) to a snapshot. Which ought to be able to delete anything which was added since the restic snapshot was created. (I am used to this kind of behaviour from snapshots in ZFS, for example.)

The particular case I am considering is a WordPress installation. I took a restic backup prior to installing some plugin, which I then realise is garbage, so I want to revert. Which should also mean, delete any new files which got installed. Say I have 100GB in my WordPress directory. It’s ridiculous that I have to delete everything, and let restic restore it all from the snapshot. Restic is already scanning the filesystem (to work out what to restore), so should be easy for it to say, hmm, a new file or whole subdirectory not in my snapshot, perhaps the user would like to delete it?

Did restic help you or made you happy in any way?
-------------------------------------------------

Yes, in general I am loving restic.  Who'd have through there was space for innovation in this area?  Good job!

**Comment by rawtaz** [comment]
Forum reference to the same discussion: https://forum.restic.net/t/how-to-delete-files-not-in-snapshot/

**Comment by ifedorenko** [comment]
I think this falls into more general "incremental restore" usecase, where restic needs to decide what to do with files already present in the target directory.

> Restic is already scanning the filesystem (to work out what to restore)

Just for the record, restic does not scan the filesystem during restore... unless I completely misremember the code.

**Comment by tesujimath** [comment]
Yes, you're right. I had a look at the code yesterday, and was surprised to see it doesn't actually look at the local files. That would seem to be another enhancement worth making. Why fetch files from the backup if the same thing already exists locally?

Once that improvement is made, this feature seems like a small addition, and it would be nice to have.

**Comment by ifedorenko** [comment]
Incremental restore isn't trivial. Restic needs to decide whether to keep new/modified local files or delete/replace them with snapshot version, which likely means user-configurable option(s). And restic will need to read&checksum local files to determine if they are modified. And for restore of modified files, restic most likely needs to work at blob level to save on network and disk i/o. All doable, of course, just somebody needs to do the work and convince the project owner this is a priority.

**Comment by jmontleon** [comment]
This was my attempt at implementing a --delete option. So far I haven't noticed problems with basic testing.

**Comment by jrevillard** [comment]
Any progress so far here ? I think this is a really important feature..

**Comment by rawtaz** [comment]
@jrevillard Can you explain your specific use case, and why you think it is really important?

**Comment by jrevillard** [comment]
Hi @rawtaz ,

Well, when I want to restore a directory in a specific point of time, I expect to have only the files that were present at that time and not the other ones.

Concretely speaking, I just have an issue with this and my Postgres backups: We have a script which do full Postgres backup (tar.bz2 format) and we backup those files using restic. We also have a script which restore the last full backup available. Last week, I wanted to restore from restic and use the script and I spent hours trying to understand why my restoration was not good. This was simply due to the fact that the directory I was restoring using restic was still containing newer backup... and this is something that I did not expect at all.

Best,
Jerome

**Comment by eprigorodov** [comment]
There can be a workaround via `restic mount` and `rclone sync`:
```
$ nohup restic mount <mount_dir> &
$ rclone sync <mount_dir>/ids/<snapshot_id>/ <target_dir>/
$ fusermount -u <mount_dir>
```
`rclone sync` will delete local files that aren't present in the snapshot.
 
This combo can also work faster because `restic restore` always downloads the full snapshot, whereas `rclone sync` only copies differences.

**Comment by baurmatt** [comment]
Be aware that `restic mount` is a lot slower than `restic restore`. See https://forum.restic.net/t/performance-differences-between-restic-dump-mount-restore/3878/5

I've opened https://github.com/restic/restic/issues/3406 to get this fixed.

That being said, I like the idea of `restic restore --delete`! Can we please get this implemented? :)

**Comment by nickchomey** [comment]
I'm new to restic and very surprised to see that this isn't a feature, especially a few years after it has been reported. In fact, I can't even understand the use-case for _not_ deleting files that don't exist in the snapshot... That seems to be the real edge-case. I hope this can get addressed soon!

**Comment by cameronbraid** [comment]
What about supporting a `per snapshot incremental` restore. So instead of trying to work out what files have changed by comparing to what's on disk, why not just allow restore changes between two snapshots.

So you can do a full restore from one snapshot, then incremental restore from that snapshot to the next, and repeat for all remaining snapshots

**Comment by MichaelEischer** [comment]
> So you can do a full restore from one snapshot, then incremental restore from that snapshot to the next, and repeat for all remaining snapshots

That sounds like it is rather easy to use in a wrong/unexpected way. It is much easier to use if `restic restore` just restores a folder to the state that matches the given snapshot.

**Comment by asdffdsazqqq** [comment]
hi, thanks,
think about it from a less technical user.
i get hit by ransomware, or do a stupid `rm *`, now i just want simple stupid command to recover from that.
the lack to restore, so that the source is a mirror of the snapshot, seems strange to me, as coming from a veeam mindset.

1. restore to a tempdir, assuming enough free space.
2. now have to choose how to do the mirror,
2a. move/delete the dest dir and then move the restore files from tempdir to dest dir.
2b. figure out and learn, rsync, robocopy, rclone, etc....
--- on linux, `rsync`
--- on windows, `robocopy`, tho, it does not compare contents after copy, so then use `rclone check --download`.

imho, i luv rclone, but might be a good choice, as rclone does not save much of the metadata that restic saves.
let me know if you think different, as i could be wrong.

if restic does not want to implement this feature, 
perhaps we can come up with a rsync command and add that to the docs.
or 
`restic restore --mirror`  which will have restic run rsync.
note: tho i lack linux skill to craft that rsync command, i would be great if someone could share a tested such a command.

thanks, david

**Comment by luckydonald** [comment]
Some thoughts on this:
It would need to adhere to the same file/dir restrictions as it did for backup.

For example I might have an include-file for my backup listing the following:
```
/home/user/desktop
/var/lib/docker/volumes
/mango.png
```
then I don't want it to delete anything outside of those paths.

I'm not sure if the includes/excludes are part of the backup metadata and could be loaded from there.
If there's no metadata (or additionally to metadta) it could make sense to give the command flags to (further) restrict (or broaden) the deletion reach. Using the same flags as the backup command means you could also use the same include list file.

**Comment by MichaelEischer** [comment]
Include / exclude paths are not stored in snapshots in a way that would be usable for the `restore` command. I've implemented the `--delete` option such that it only removes files that match the `--include` or `--exclude` filters (without filters, all files in the target directory may be deleted).

**Comment by luckydonald** [comment]
@MichaelEischer that's great, and straight forward to use. Awesome.

Is this nee flag and also the filter behavior updated in the docs?
I was unable to locate the changes to the docs in this PR, are those happening somewhere else?

**Comment by MichaelEischer** [comment]
@luckydonald https://restic.readthedocs.io/en/latest/050_restore.html#delete-files-not-in-snapshot

**Comment by luckydonald** [comment]
Beautiful! Thanks!
That feature makes me very happy.


One last question, is there some kind of `--no-preserve-root` protection if I backup and `restore --replace` the `/` dir directly? Like `rm` has?
 Is that something to think about?

**Comment by luckydonald** [comment]
@MichaelEischer

**Comment by MichaelEischer** [comment]
Currently there isn't, but it might be a good idea to only allow `/` + `--delete` if an include/exclude is also specified.
