### ISSUE TITLE
Allow default umask to be overridden

### ISSUE THREAD

**Issue by monkeyhybrid** [restic/restic#2351]
Output of `restic version`
--------------------------

restic 0.9.5 compiled with go1.12.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

Restic should allow its hard coded umask (0077) to be overridden by a user specified umask.

What are you trying to do?
--------------------------

Access repo files (raw data, not decrypted) by a non-root user other than the user that runs Restic, and without having to chmod/chown the repo files after each backup.

Restic creates all repo related files with permissions that allow only the Restic user to read/write said files (no group permissions), effectively using a 0077 umask, and ignoring whatever umask the Restic user has set in their environment.

This prevents things like extended ACLs, using setfacl, from being applicable. If we want another process, running as a different, non-root user, to copy or process these files in some way, it can not do so without the files being chown/chmod'd after each backup. Being able to set custom extended ACLs would solve this, but without a customisable umask, it can't work.

I understand why Restic defaults to a tightened umask, but it should be able to be overridden by the user if required.

Did restic help you or made you happy in any way?
-------------------------------------------------

Restic makes me happy every day.

**Comment by cdhowie** [comment]
[Related forum post](https://forum.restic.net/t/change-permissions-on-repository-files/1391).

**Comment by nununo** [comment]
+1
I am also interested in this for a very similar purpose.

**Comment by tree68505** [comment]
+1
Very well put issue description. This is also an issue if you want more than one user to create snapshots for a repo. For example, having one locked-down backup-only user for scheduled backups and still allowing for normal user(s) to manually create snapshots is difficult to implement and maintain.

**Comment by NeoPolus** [comment]
+1 this would also simplify some use cases: local backups being made as root (sudo restic backup...), and then another computer making backups to the same repo using a given user ('backup_user'). Currently this requires to do a recursive chown (to give back access to the backup user) after every local backup (as files would be root readables only after a local 'sudo restic backup').

**Comment by JsBergbau** [comment]
I have the same problem:
restic backups from multiple machines to network share //server/resticbackup
also Server backups to this repo. 
Despite not writing directly to repo on Server, but also via mounted cifs share `sudo mount -t cifs -o user=backupuser,password=...` restic somehow gets the real drivepath and creates files as owner root instead of `backupuser` as all the other machines do.
Since each machine has its own password this caused even backup to fail because they couldn't read the key file in restic/keys of server.

**Comment by juergenhoetzel** [comment]
I would also prefer restic to follow the umask settings:

https://github.com/juergenhoetzel/restic/commit/132ef6e38122ab805860db9ac9a518aba359ad57

On the other hand, some users may rely on the hardcoded permission bits. 
Another explicit command flag  could allow backward compatible behavior.: `--respect-umask`.

**Comment by DanielG** [comment]
I have a slightly different proposal to allow this use-case.

@juergenhoetzel's patch makes it so only the umask controls what r/w mode bits are cleared for both directory and file modes. This pretty much requires adding a command line option for users that are unaware of this change but that don't want their (albeit encrypted) data to be acessible to their primary group by default.

```diff
@@ -23,4 +23,4 @@ var Paths = struct {

  // Modes holds the default modes for directories and files for file-based
  // backends.
- var Modes = struct{ Dir, File os.FileMode }{0700, 0600}
+ var Modes = struct{ Dir, File os.FileMode }{0777, 0666}
```

I propose relaxing only the file creation mask and leaving the directory creation mask as-is:

```diff
--- a/internal/backend/paths.go
+++ b/internal/backend/paths.go
@@ -23,4 +23,4 @@ var Paths = struct {
 
 // Modes holds the default modes for directories and files for file-based
 // backends.
-var Modes = struct{ Dir, File os.FileMode }{0700, 0600}
+var Modes = struct{ Dir, File os.FileMode }{0700, 0660}
```

Since the directory mode doesn't allow the execute bit (search permission) to be set regardless of umask the files don't need to also have empty group permissions to not allow the group access by default. In other words if the execute bit on the containing directory isn't set this a file can't be accessed even if it were otherwise read/writable due to it's own mode. 

The upside of this is that the sysadmin can choose to change the directory permissions to allow group access since all repo directories are created at init time and not touched again after that.

A user that is particularly concerned about group access could then still restrict the umask to force restic to create files which only the user can access.

With this patch and umask=022 we'd get these modes:

```
drwx------ 1 user user data
-r--r----- 1 user user data/bf/bfe68fae5c...
drwx------ 1 user user index
-r--r----- 1 user user index/b1e4765438...
drwx------ 1 user user keys
-r--r----- 1 user user keys/d507adeaf5...
drwx------ 1 user user locks
drwx------ 1 user user snapshots
-r--r----- 1 user user snapshots/361a98262e...
-r--r----- 1 user user config
```

Notice how the `x` bit isn't set for group access on the directories so trying to access these as a different user in the `user` group will fail:

```
$ su -l someuser
$ newgrp user
$ cat data/bf/bfe68fae5c...
cat: data/bf/bfe68fae5c...: Permission denied
```

**Comment by MorgothSauron** [comment]
I'm having a battle with the restic cache because it uses hardcoded file mode in the source code. A battle because it took me a while to find why ACL were not applied properly on cache file created by restic.

To be honest it is not up to the application to set file permissions. On Linux/UNIX it should be manageable by the user with the `umask`. If it has to be made by restic then there should be options to override the defaults.

**Comment by DanielG** [comment]
> To be honest it is not up to the application to set file permissions. On Linux/UNIX it should be manageable by the user with the `umask`. If it has to be made by restic then there should be options to override the defaults.

In the particular case of the chache files that are stored per-user anyway I don't really see why those should be anything other than mode 700? What's your use-case?

**Comment by MorgothSauron** [comment]
@DanielG I'm overriding the cache directory (`--cache-dir`) so my user and root use the same cache. Depending on the backup I run (home directory vs. system files) I may run it as my user or root via `sudo` / `doas`. The cache is never used by more than one command at a given time, so there is no risk of "conflict". Since the permission is hardcoded my user will have problem reading the cache if a previous backup was run as root. Whatever the use case, I still think that the application should not hardcode file permissions. Same applies to repository files. It should be possible to control file permission with `umask` and/or ACL (`setfacl`).

**Comment by DanielG** [comment]
Ah I see. So I assume you get a speed advantage from sharing the cache. I suppose that makes sense.

Looks to me like the cache code at least only restricts the directory permissions so you should be able to `chmod g+rw` the directory one-time and have it work after that no? I'm assuming the cache files are never re-written, but I'm not sure about that point.

**Comment by MorgothSauron** [comment]
@DanielG To be honest I wasn't looking for any performance improvements. I was simply looking to put files for my backup scripts together and control file access with standard *nix permissions. I did try to setup a backup group, but with the hardcoded 700 permission it was a matter of time before a new file to be created with wrong permission. I didn't want to do a regular `chmod` on files because, in my opinion, the files should already have the right permission based on `umask`.
