### ISSUE TITLE
restic does not detect rclone termination

### ISSUE THREAD

**Issue by shane-kerr** [restic/restic#2381]
Output of `restic version`
--------------------------
```
restic 0.9.5 compiled with go1.12.4 on linux/arm
```

How did you run restic exactly?
-------------------------------
```
GOGC=20 nice -n 19 ionice -c 3 restic -r rclone:jotta:xxx --password-file xxx.passwd backup --one-file-system -v /mnt/xxx
```

In one case the system had 2 Gbyte of RAM, and the Linux out-of-memory (OOM) killer terminated the rclone process, and in a second case the system had 1 Gbyte of RAM and the OOM killer terminated the rclone process.

In both cases, restic just hung, doing nothing.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Jottacloud, but I saw identical behavior using the sftp backend.

Expected behavior
-----------------
restic should detect that rclone has died and exit with an error.

Actual behavior
---------------
restic sat there quietly, doing nothing.

Steps to reproduce the behavior
-------------------------------
It seems like you can get similar results just by killing the rclone process by hand.

Do you have any idea what may have caused this?
-----------------------------------------------
restic ignoring SIGCHLD and/or pipe file descriptor closes.

Do you have an idea how to solve the issue?
-------------------------------------------
Detect the error and exit.

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is awesome. I am nervous to have built all of my backups around it, but so far so good! 😂👍

**Comment by cfbao** [comment]
I've seen the same problem on Windows but was too lazy to report.
When I hit `ctrl+C`, rclone would terminate, but restic would hang indefinitely.

**Comment by julianbrost** [comment]
Instead of exiting, restic could also try to restart rclone. Some are using the rclone backend to do stuff like accessing repos over SSH (see for example https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone) and this would allow to recover from a broken SSH connection.

I'm not sure if this would be a good idea in all cases where rclone exits unexpectedly, though normally this should not happen. In case of OOM, it might help or might not. Maybe this could be encountered with some limit like if the program exits more than 5 times in a minute, it's probably broken and restic should exit.
