### ISSUE TITLE
Issue request template: Ask 'How', not 'Did'

### ISSUE THREAD

**Issue by jtagcat** [restic/restic#2410]
In issue templates you get asked a question: `Did restic help you or made you happy in any way?`
Change it to: `How did Restic make your day better today?`
Shorter is better, as it doesn't make you read as much.
Though yes/no question `Did` is also shorter. Up for discussion.

**Comment by fd0** [comment]
Ok, let's try that!

**Comment by rawtaz** [comment]
IMHO it's not a great change. Wording it like this puts an assumption in the mouth of the one being asked the question. It might not be the case that restic made their day better, and "us" telling them that it did is a recipe for disaster relation wise ;)

It's like when you have to agree to something on the website, which in practice you *don't* actually agree with, but you *have* to press that darn button in order to be able to use the site, and the button is named like "Okay, thanks!" or "Okay, sounds good!".

Also it's not needed. Everyone understands that if it did, they should write how/why.

**Comment by fd0** [comment]
Hmhmhm. I can see the assumption now. Maybe we can split the questions into two, like:
"Did restic help you today? Did it make you happy in any way?"

**Comment by rawtaz** [comment]
That or what was before works, they're pretty much the same :)
