### ISSUE TITLE
Question: Can I backup to Github repo?

### ISSUE THREAD

**Issue by Keemaaa** [restic/restic#2416]
Hello,

Is there any way to backup to github ripo?

Best regards

**Comment by ZacharyDuBois** [comment]
I mean, you could backup locally into a directory with a git repository, commit the files, and push them but I don’t see a great way to do that without a botch like that.

**Comment by brualan** [comment]
You can't and you shouldn't
1. Git isn't a very good tool to "backup" binary files. You should use tools for what they ment to do.
2. If you need to backup you're code or text notes -- you're already doing it by `git push`ing
3. Using GitHub as a "backup storage" is extremely bad technical decision. This usecase is rare, insecure, with bad performance (because restic and git would keep history of files changes, so backup size would grow at least 2x as fast).

@rawtaz I suggest to close this issue, because of the points written above

**Comment by MichaelEischer** [comment]
As @brualan has explained, GitHub would make for a very bad "backup storage". In addition, GitHub repositories are intended to store code or some projects, not your personal backup.
