### ISSUE TITLE
Add Storage space flag

### ISSUE THREAD

**Issue by wuast94** [restic/restic#2431]
Would be nice to add max diskspace limit to avoid disk full condition like #1153

I add a comment there but this thread is old so I make a new. 

I have a one drive storage with 1tb and want to backup multiple backups there. So it would be nice to add this flag to limit theax backup size.

**Comment by rawtaz** [comment]
@wuast94 Thank you for sharing this concern. I understand it's can be a problem when you're tight on disk space.

However, for practical reasons I'd like to ask you to close this issue, as we already have the one you referenced active, and with more discussion as well. This duplicate one only causes more overhead, which makes for less time to attend other issues (including the one you referenced).

Thanks!

**Comment by wuast94** [comment]
I see you referenced this issue there so I will Close it :)

**Comment by kibiz0r** [comment]
Given that #1153 has been closed, without adding the "max repo size" flag requested in this issue, can we reopen this one?

That issue was more about how filling the disk would put restic into an inoperable state, which is now fixed as of #3481.

There were a number of participants in #1153 that were interested in something more like a feature (automatically purging old snapshots when necessary to accommodate the new one) than a bugfix (ensuring an operable state in extreme FS conditions).

I'll state my own use case here, but I can move elsewhere/delete it if needed:

Personally, I'd like the backup operation to be able to carve out whatever space is necessary for it to successfully complete.

Right now, I'm compensating for this by using an aggressive "forget" policy, but I'm still afraid of the scenario where my nightly backups are continually failing because my heuristic wasn't aggressive enough and I need to manually intervene now. (And on the flip side, I'm potentially missing out on having a lot more snapshots at my disposal because I need to have such an aggressive policy.)

**Comment by MichaelEischer** [comment]
@kibiz0r Please just create a new issue, that's easier to manage than resurrecting very old issues.
