### ISSUE TITLE
 usability enhancement: storing information about excluded files and warn the user when they try to restore them

### ISSUE THREAD

**Issue by pabs3** [restic/restic#2451]
Output of `restic version`
--------------------------
```
restic 0.9.5 compiled with go1.12.7 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
When doing a backup, restic could have an option to store information about files or paths that were excluded from the backup and then restic restore could display a warning if the user tries to restore those directories and restic mount could return errors trying to read them.

What are you trying to do?
--------------------------
I was recently trying to restore a directory, nothing was being restored and I couldn't work out what was going on until I tried --path in addition to --include, which told me no snapshot includes that path, it was then I figured out that it was excluded. If restic had the feature above, I would have spent less time trying to figure out what was going on.

**Comment by MichaelEischer** [comment]
Returning read errors in `restic mount` would be very confusing as it will look like a folder/file exists which turns out to be broken.

> restic restore could display a warning if the user tries to restore those directories

I don't think that this will be as useful as hoped for. restic could only provide a warning when trying to restore files that explicitly match some of the exclude patterns. However, an exclude pattern is quite often a _pattern_ such that it will be impossible to tell whether some path does not exist because it was excluded or because it just didn't exist in the first place.
As an additional problem `--include` accepts patterns and not filenames which leads to additional complications. Then result would be that restic will warn users in some cases about excluded file but not others, with no obvious reason why a warning is shown in some cases but not others. So I think we should close this issue.

**Comment by MichaelEischer** [comment]
Closing for now as I don't see a way how restore could determine the necessary information.
