### ISSUE TITLE
read-only snapshots function complains about storage size issues (B2)

### ISSUE THREAD

**Issue by tbm** [restic/restic#2477]
This is with restic 0.9.4 from Debian.

I've exceeded the free storage on my B2 cloud system and haven't yet added a credit card to get more storage.  So backups are failing.  Fair enough.

But I just wanted to check which snapshots to remove and did a `restic snapshots`.  To my surprise, this also fails and I'm not sure why since `snapshots` should be  a ready-only function, isn't it?

```
restic snapshots
repository 80ac4657 opened successfully, password is correct
found 1 old cache directories in /home/tbm/.cache/restic, pass --cleanup-cache to remove them
Save(<lock/514eaf255f>) returned error, retrying after 270.018741ms: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
Save(<lock/514eaf255f>) returned error, retrying after 573.556576ms: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
Save(<lock/514eaf255f>) returned error, retrying after 1.327633127s: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
Save(<lock/514eaf255f>) returned error, retrying after 1.359631059s: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
...
```

**Comment by tbm** [comment]
It seems `prune` isn't possible either.  It's not a problem in this case since I can just add a credit card to get more storage, but I think restic should allow me to remove snapshots to get within the storage limitation...

```
restic forget --prune --keep-last 20 --keep-hourly 48 --keep-daily 14 --keep-weekly 8 --keep-monthly 12 --keep-yearly 75
repository 80ac4657 opened successfully, password is correct
found 1 old cache directories in /home/tbm/.cache/restic, pass --cleanup-cache to remove them
Save(<lock/df547b4976>) returned error, retrying after 577.594093ms: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
Save(<lock/df547b4976>) returned error, retrying after 560.30065ms: Close: b2_get_upload_url: 403: Cannot upload files, storage cap exceeded. See the Caps & Alerts page to increase your cap.
```

**Comment by rawtaz** [comment]
Maybe restic is trying to create a lock file, and this is what fails? Try adding `--no-lock` to the restic command (see `restic help snapshots`).

Pruning a repository involves writing some files, for natural reasons. This means that you need disk space. If you have zero disk space free, there's really not much restic or any other software would be able to do.

**Comment by tbm** [comment]
Same with the official binary of 0.9.5.

**Comment by tbm** [comment]
> Maybe restic is trying to create a lock file, and this is what fails? Try adding --no-lock to the restic command (see restic help snapshots).

Yes, that works, thank you!

> Pruning a repository involves writing some files, for natural reasons. This means that you need disk space. If you have zero disk space free, there's really not much restic or any other software would be able to do.

Can you explain why?  It's not obvious to me why deleting snapshots involves writing files.  Also, could restic remove files before creating new files or would that be a bad idea in case restic gets interrupted.

**Comment by tbm** [comment]
Side question:

```
      --no-lock                   do not lock the repo, this allows some operations on read-only repos
```

Why do read-only ops create a lock file to start with?  If the op is read-only, why have a lock file?

**Comment by rawtaz** [comment]
> Can you explain why? It's not obvious to me why deleting snapshots involves writing files. Also, could restic remove files before creating new files or would that be a bad idea in case restic gets interrupted.

I'm not great at explaining that technical stuff, I'm just a user like you. But in short, imagine that you have some data blobs in the repo, and then a file that tracks for which snapshots which of those blobs are used. If you want to remove one of the snapshots, and then prune the blobs that only that snapshot used, you will need to rewrite/replace that file which kept track of which snapshot used that blob. So, you will need to create a new file.

This was a simplification, prune rewrites a lot of stuff as part of its work, and it simply does new disk space to do that. It does it in a conservative way in order to make sure your repo doesn't end up in a corrupt state.

I recall that there was some work done in the `prune-aggressive` branch, that makes the prune remove as much unused stuff as it can before starting to write new files, but I cannot recommend it because I don't know how old it is.

In your case I agree, just buy more space and keep better track of your disk usage in the future.

> Why do read-only ops [like `snapshots`] create a lock file to start with? If the op is read-only, why have a lock file?

Good question! Sorry, I don't know why that is. Someone else will have to answer this. That question would be a good reason to join the forum, where this type of discussion belongs. It's at https://forum.restic.net.

As issues here on GitHub are for requesting new features or reporting bugs, I'll take the liberty to close this issue now. Feel free to add more comments, or even better continue the discussion in the forum (you can reference this issue there). I hope you don't mind.

**Comment by fd0** [comment]
> Why do read-only ops create a lock file to start with? If the op is read-only, why have a lock file?

Good question! Locking is a tricky thing. Restic tries to set a lock even for read-only commands so that other read-write commands know that another instance is currently trying to read from the repo. Imagine you're running `restic restore` (which leaves a non-exclusive lock file in the repo) and your daily cronjob runs `restic forget --prune` which happens to remove exactly the snapshot you're currently restoring. Without a lock file, `prune` may remove data you still need for the `restore` operation.

I hope this makes it a bit clearer! :)

**Comment by tbm** [comment]
@rawtaz @fd0 thanks for your replies!
