### ISSUE TITLE
Will Restic apply for sync between S3‘s data？

### ISSUE THREAD

**Issue by xytnba** [restic/restic#2494]
Does Restic only backup the local data？
If I want to backup minio’s data to my S3, I want use Restic.
How can I do with it?
I love to use Restic to backup my data~

**Comment by dimejo** [comment]
Yes, restic only supports backup of local data. You can circumvent this restriction by locally mounting (e.g. with [rclone](https://rclone.org/)) your data and go from there. Note that this might be slow. Note aswell that you might need to add `--ignore-inode` to your backup command for subsequent backups because FUSE based filesystems tend to change inodes on every re-mount which slows restic down.

PS: Use the forum if you have a question rather than a bug or feature request.

**Comment by rawtaz** [comment]
@xytnba Why did you put this question here in an issue, when you are clearly informed in the issue template that questions of this nature is something you should put in the [forum](https://forum.restic.net/)? This issue tracker is for feature requests and bug reports, not usage questions.

That said, if you are talking about syncing data from one repository to another you can use `rclone`, as @dimejo suggested. If your goal is to have two copies (backups) of your data, I would however instead recommend that you do two separate backups with restic - one to your Minio and one to your S3. With this setup, you don't risk possible corruption of your first repository being replicated to your second repository, so your chances of having a working backup to restore are higher.

**Comment by dimejo** [comment]
> That said, if you are talking about syncing data from one repository to another you can use rclone, as @dimejo suggested. If your goal is to have two copies (backups) of your data, I would however instead recommend that you do two separate backups with restic - one to your Minio and one to your S3. With this setup, you don't risk possible corruption of your first repository being replicated to your second repository, so your chances of having a working backup to restore are higher.

If I understood correctly @xytnba wants to use data which is stored remotely as source for the backup.
