### ISSUE TITLE
How to back up TrueCrypt containers?

### ISSUE THREAD

**Issue by baobabKoodaa** [restic/restic#2506]
I was really excited about Restic, but decided not to try it after discovering this in the documentation:

> Please be aware that when you backup different directories (or the directories to be saved have a variable name component like a time/date), restic always needs to read all files and only afterwards can compute which parts of the files need to be saved. When you backup the same directory again (maybe with new or changed files) restic will find the old snapshot in the repo and by default only reads those files that are new or have been modified since the last snapshot. This is decided based on the following attributes of the file in the file system:
> 
> Type (file, symlink, or directory?)
> Modification time
> Size
> Inode number (internal number used to reference a file in a file system)

The way TrueCrypt containers work on Windows is that the size and modification time remain unchanged even if the contents of the container change. If I interpret the documentation correctly, this means that Restic will silently fail to backup TrueCrypt containers, keeping only the original version of the container, while behaving to the user that the (incremental) backup was successful. If the user is backing up a large number of files, they will be unlikely to notice this failure (until later, when they actually need their backup!)

I'm guessing file contents are not checked due to efficiency reasons. I realize it might be too much to ask that file contents should be checked when creating incremental backups. I don't know what's the proper way to mitigate this issue. Maybe add a warning or something?

**Comment by rawtaz** [comment]
Please see the `-f, --force` argument to `restic backup`.

**Comment by baobabKoodaa** [comment]
Thanks for the fast answer!

If it's okay to ask a general question in this ticket, is there a "best practices" of using Restic documented anywhere? I wasn't able to find anything like that, and I'm hesitant to try Restic because I fear that if I don't put in the time to become a "Restic expert" then I will just step onto a trap and end up with data loss.

**Comment by rawtaz** [comment]
Honestly, this entire issue is a usage question, so you should have posted it in the forum instead (as mentioned in the issue templates).

Best practice? I mean, everyone has their own use cases, so "best practice" is hard to define IMO. But what do I know.

You don't need to be a restic expert. Just try it out, back up some of your stuff and see what you think. No reason to not try it :) Many people are using it in production, why wouldn't it work for you?

**Comment by baobabKoodaa** [comment]
Sorry if I posted this in the wrong place. The part of the documentation that I referenced in OP does not mention the `-f` flag as a mitigation to this issue, so it was reasonable for me to assume that such a feature does not exist (hence the feature request on GitHub). But it's good to hear that the feature is already there, and my followup question was indeed a usage question as you noted.

Why am I hesitant to try Restic after this? Well, I noticed the TrueCrypt container issue with blind luck. If I would have "just tried" Restic, I would have been happily doing Restic backups for years, and then that one time when I would have needed to use my Restic backups, I would have noticed that Restic had actually failed to back up a portion of my files (the TrueCrypt containers).

Now I know how to avoid this particular issue, but I can't really know how many other "traps" like this there are. Without a documentation that explains "this is how you can safely do backups with Restic" I might just fall into a different trap and end up with data loss :/

**Comment by rawtaz** [comment]
> Sorry if I posted this in the wrong place. The part of the documentation that I referenced in OP does not mention the -f flag as a mitigation to this issue, so it was reasonable for me to assume that such a feature does not exist (hence the feature request on GitHub).

No worries. We should probably turn this issue into a documentation update suggestion, to add a note about the `-f` flag like you said.

There is actually a related issue I created just the other day, see bullet point 1 in #2503 - If we create that "Change detection" subsection it might be a place to put things like notices about TrueCrypt and what not.

> If I would have "just tried" Restic, I would have been happily doing Restic backups for years, and then that one time when I would have needed to use my Restic backups, I would have noticed that Restic had actually failed to back up a portion of my files (the TrueCrypt containers).

Maybe. But I mean, the options here are that a) restic works as it does now (try to detect changes based on common practices) or that it 2) always re-reads files.

If you have a specific software that actively "hides" change information from the system, then restic cannot be expected to detect this when operating as in option 1. It's completely unreasonable. So the alternative would then be that restic operates as in option 2, but that would be extremely inefficient, and given that what TrueCrypt does is not normally how the filesystem is used, it's just not the way to go. Better then to work with awareness so that people using specialized software like TrueCrypt knows about it.

If you were to back up only the TrueCrypt container, you would probably have noticed that restic says no files changed, and acted on that, but I understand if you back up many other things at the same time and wouldn't explicitly notice the TrueCrypt part as it's then not clearly visible.

> Now I know how to avoid this particular issue, but I can't really know how many other "traps" like this there are. Without a documentation that explains "this is how you can safely do backups with Restic" I might just fall into a different trap and end up with data loss :/

There are no "traps" really. I see what you mean, but restic works and works well. If you have specialized software on your system, then you need to be and are now aware of it, but do you really have other things behaving like TrueCrypt?

A simple way to move forward would probably be to simply try it - after all, you should always try to restore once in a while to make sure things work as you intend. Backups are never in place until you actually tried restoring from them. So, if you follow *that* best practice, which is probably the only one you need in the first place, you will detect any anomalies or unexpected cases.

**Comment by baobabKoodaa** [comment]
Everything you said makes perfect sense. I can't think of anything else that might be causing problems on my setup besides TrueCrypt, so I'm guessing it should be safe to try Restic.

I started thinking about your suggestion on restoring from backup as a test, and I realized I don't know how to do that properly. I don't want to overwrite my files with the restore, because if there was a problem with either the backup or the restore, then I would have data loss. I also don't have enough disk space to duplicate all of my data in 3 places (the "main" location, the "backup" location, and the "restored" location). I could make some tests with a small amount of data, but of course that doesn't tell me if actual backups work or not (for example the TrueCrypt issue would not have been uncovered by quickly testing restore with a small amount of data). If I do a full restore from backup to a 3rd location, how do I verify that the restored data matches the original data?

The README says that "restic enables you to easily verify that all data can be restored." This would be preferrable to actually duplicating my data into 3 locations. I tried to look up the docs for how to do this, but I didn't find anything? The closest thing I found was "run `restic check` to verify that all data is properly stored in the repository. You should run this command regularly to make sure the internal structure of the repository is free of errors." It sounds like this command doesn't actually verify that the data matches to data in another location. Does Restic actually allow you to verify that all data can be restored? As in, all the data that you're trying to back up.

**Comment by smlx** [comment]
you could check the data in restic manually by using `restic dump latest <truecrypt file> | sha265sum`, and comparing it to the hash of the original file

**Comment by ProactiveServices** [comment]
Depending on your threat model, you may wish to have your container software not preserve the modification timestamp of your containers. This way, restic will be able to see when containers are modified. With VeraCrypt, this option is available under `Settings->Preferences`.

**Comment by baobabKoodaa** [comment]
> Depending on your threat model, you may wish to have your container software not preserve the modification timestamp of your containers. This way, restic will be able to see when containers are modified. With VeraCrypt, this option is available under `Settings->Preferences`.

Ah, I did not realize it was a configurable option. Thanks!

**Comment by baobabKoodaa** [comment]
> you could check the data in restic manually by using `restic dump latest <truecrypt file> | sha265sum`, and comparing it to the hash of the original file

It would not be feasible to manually check every single file one by one. I do think any backup software should include the possibility to verify that the backup was successful.

**Comment by rawtaz** [comment]
> If I do a full restore from backup to a 3rd location, how do I verify that the restored data matches the original data?

If the restore was successful the data should be proper. If you feel it isn't, or want to verify this (which is never a bad idea, of course), you naturally need to do that with a known good set of the data, and that is outside of the scope of restic (or any other backup software). One obvious option is to simply compare the restored data with the original data. I'm not sure what other answer you are looking for.

> The README says that "restic enables you to easily verify that all data can be restored." This would be preferrable to actually duplicating my data into 3 locations. I tried to look up the docs for how to do this, but I didn't find anything?

But you did (find something)! - What you wrote below:

> The closest thing I found was "run restic check to verify that all data is properly stored in the repository. You should run this command regularly to make sure the internal structure of the repository is free of errors." It sounds like this command doesn't actually verify that the data matches to data in another location. Does Restic actually allow you to verify that all data can be restored?

I have an intention of improving the docs on about the `check` command soon. But that's the one you should run. If you run it without `--read-data` it will just check the integrity of the metadata in the repository - that is, all the files that keep track of the structure in the repo, the snapshots, the deduplication, etc. If you want to make sure that there hasn't been any bitrot or other corruption in the actual data blobs in the repository, you can use the `--read-data` argument to `check` - this will read all the data in the repository and verify that it's what it should be.

The reason this works is that restic stores files with the hash of them, so it can easily hash a file's contents and compare it with the name it should have, and if they match, then the file contains what it should contain. If on the other hand the filename and the current hash of the file contents doesn't match, there's been some corruption happening. Restic has actually uncovered a lot of hardware malfunctions this way.

To more specifically answer your question; If you run a successful `check --read-data` then your data should be possible to restore, because restic has in practice read all of it and verified that it's okay :)

By the way, also notice the `--read-data-subset` argument, it might be useful if you have a large repository.

> As in, all the data that you're trying to back up.

Restic can only `check` the data that you *have* backed up, so I'm not entirely sure what you mean by checking data that you are *trying* to back up.

**Comment by rawtaz** [comment]
@baobabKoodaa Thanks a lot for highlighting this case with e.g. TrueCrypt. I've edited #2506 to include updating the documentation such that these things become more apparent and clearer.

I'm closing this issue for now because it's become a usage discussion. You're very welcome to continue discussions or ask questions (about this or other things) in [the forum](https://forum.restic.net) - there's more people active there for this type of topic. And don't forget to let us know in there when you got started with restic! 👍

**Comment by baobabKoodaa** [comment]
> One obvious option is to simply compare the restored data with the original data. I'm not sure what other answer you are looking for.

I mean sure I can write a program that verifies that the created backup matches the original files. I just thought that this functionality should be included in any backup software.

> Restic can only check the data that you have backed up, so I'm not entirely sure what you mean by checking data that you are trying to back up.

Well, we just covered one instance where the user might say "I want to back up these files", and then Restic backs up _only some of the files_ and tells the user that the backup is successful when in fact it partially failed. Running the `check` in this instance would not reveal the failure. Restic could verify that the backup was correct by comparing the data in the backup to data in origin.

> I'm closing this issue for now because it's become a usage discussion. You're very welcome to continue discussions or ask questions (about this or other things) in the forum - there's more people active there for this type of topic. And don't forget to let us know in there when you got started with restic!

Thanks for the discussion, and good to hear that TrueCrypt issue will be highlighted in the documentation.
