### ISSUE TITLE
Restic Prune Failure

### ISSUE THREAD

**Issue by oscar-admin** [restic/restic#2561]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

Describe the issue
------------------
counting files in repo
building new index for repo
[3:54] 100.00%  14453 / 14453 packs
repository contains 14453 packs (77460 blobs) with 68.689 GiB
processed 77460 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 2 snapshots
[0:20] 100.00%  2 / 2 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
doing 'prune' failed.

**Comment by rawtaz** [comment]
Sorry, but I'm closing this issue because you didn't bother to fill out the issue template that you were presented with when you created the issue. Please edit this issue to make the information complete, then we can re-open it. Thanks.

That said, this error has been reported many times before, I can highly recommend searching in the restic forum to see how others dealt with it.
