### ISSUE TITLE
restic forget --keep-* options must interpret -1 as "forever".

### ISSUE THREAD

**Issue by drzraf** [restic/restic#2565]
Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.13.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
`restic -r swift:backup:/aeus/restic forget --keep-weekly -1 --keep-within 2m`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
`openstack swift`

Expected behavior
-----------------
Keep all snapshots within 2 months, keep once per week for earlier period.

Actual behavior
---------------
Keep all snapshots within 2 months. Delete all from the earlier period.

Do you have an idea how to solve the issue?
-------------------------------------------
I'm coming from borg, and found that most options match (which is nice). The `forget` command clearly match `borg prune` one.
But when it comes to say `keep one snapshot per hour/day/week/month`, borg support the value `-1` which is far better than hardcoding a "max" like  --keep-weekly 9999.
I'm quite sad that, while I relied  on the same behavior, `restic` not only ran the cleanup but dropped all my previous backups by misinterpreting `-1`.
At the **very** least, `restic` must bail-out and warn about unknown value.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It forgot about all my backups older than 2 months because I (apparently mistakenly) typed `--keep-weekly -1 --keep-within 2m`

**Comment by MichaelEischer** [comment]
Interpreting `-1` as forever seems safe. Anyone up for a PR?

**Comment by thndrbrrr** [comment]
Hi @MichaelEischer!

I'm in the process of creating a PR for this. A few questions:

* Implementing `-1 == forever` for `--keep-last n`, `--keep-hourly n` is straightforward. However, at the same time I'd suggest to prevent the use of negative values *less* than `-1` because that would again lead to unwanted effects. Does that sound acceptable? What I've implemented so far ([see here [WIP!]](https://github.com/restic/restic/compare/master...thndrbrrr:restic:forget-opts-neg1-means-forever-issue-2565)) is a check that returns error `negative values other than -1 are not allowed for --keep-* options`, but before I continue down this road I thought I'd ask how you folks feel about this approach.
* The case is less clear for durations. What's the equivalent of `-1` for durations?  Something like `--keep-within-weekly -1m` is a valid `restic.Duration` from what I can tell, but it's a stretch to say that it should mean "forever" in this context. It gets even weirder with durations like `--keep-within 2y-3m` ... so how should durations with negative values be handled? I'd recommend considering any duration containing a negative value invalid in this case. I'd update my current code to produce a different error message, for example something like `negative values in durations are not allowed for --keep-within* options`.

I've always been of the opinion that the more destructive an operation, the less ambiguous the allowed options should be ...

Thanks!

**Comment by thndrbrrr** [comment]
[Submitted a PR](https://github.com/restic/restic/pull/4234) that:
* implements this for `--keep-last n`, `--keep-hourly n` etc,
* but makes no changes to the behaviour of `--keep-within*`.
