### ISSUE TITLE
Support MS Windows

### ISSUE THREAD

**Issue by fd0** [restic/restic#26]

**Comment by ThomasWaldmann** [comment]
While I don't need it personally, I'ld like to see windows support because it's always a pain to support the existing crappy windows backup software. Also, I use some crappy windows imaging software.

So, I'ld offer testing something that can create and restore windows full-disk images. It could be based on linux (boot-cd) or winpe or both. Biggest issue there is software-raid support.

**Comment by fd0** [comment]
I've removed windows support in e0fbd83a2d756d04ec1df3108fe5b9c69f0f183f for now, until the base is stable enough an someone volunteers to do it.

**Comment by klauspost** [comment]
I wouldn't mind helping here. There is probably some work needed to have [UNC path](https://en.wikipedia.org/wiki/Path_(computing)#Uniform_Naming_Convention) support, since the Go runtime doesn't do that by itself.

**Comment by fd0** [comment]
Feel free to give it a try :)

It may be a good idea to start with the basics, and add UNC path support later.

**Comment by fd0** [comment]
This has been implemented with #259 by @klauspost
