### ISSUE TITLE
Trust the contents in the index during the creation of the first snapshot

### ISSUE THREAD

**Issue by thejinx0r** [restic/restic#2632]
Output of `restic version`
--------------------------
restic 0.9.6 (v0.9.6-135-ga307797c-dirty) compiled with go1.14 on linux/amd64

What should restic do differently? What are you trying to do?
----------------------------------------------------------------------------------

Restic should trust the contents of the index when creating the first snapshot.
My understanding is that restic normally only calculates a hash of blobs for files that have changed.
So if a file has not changed on the disk, the file will not be scanned.

If that's correct, then this behaviour is not seen upon creating the first snapshot.
I have a large ish backup to perform (~40TB) and it seems like when I stop/start the process, it will retry calculating the hashes of all 40tb of data, even though it hasn't changed. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I like that it's command line and much more pleasant to use than duplicati and duplicacy

**Comment by aawsome** [comment]
When doing a backup with an already-present snapshot (with the same paths as you want to backup), restic knows the tree and subsequently the following subtrees to load from the repository as it is stored in the snapshot. Then it can compare if a file has changed or not and if not just use it from the repo.

If there is no snapshot, there is no way for restic to check if a file has changed. It would need to get the tree where the file is, but to access the tree it needs to know the hash of its contents. That is, after restic computes the hashes of all files in the tree it can compute the tree ID and then knows that the tree is already present. Without knowing where to start, this can only be done bottom-up, i.e. from the hashes of all tree contents.

I did not really get what your expected behavior is. Can you please specify your test case more accurately and state what you expect restic to do differently?

**Comment by MichaelEischer** [comment]
@thejinx0r If I understand you correctly, you want restic to continue interrupted backups from where you stopped the last run. Then this issue is a duplicate of #2280.

**Comment by thejinx0r** [comment]
@MichaelEischer 
Agreed that it's a duplicate.
