### ISSUE TITLE
Fast prune: skipping rewrite / sparse files

### ISSUE THREAD

**Issue by RubenKelevra** [restic/restic#2693]
Hey guys,

first of all, restic is a pretty neat tool for backup - thanks for all the effort you put into it!

I did some testing, and ended up with a lot of excludes and removed some delta backups.

While a backup with restic is extremely fast, the prune operation, on the other hand, is extremely slow, because data which already exist on the server is downloaded and uploaded again to rewrite pack files.

Is there any option to skip the rewrite all together? I'm interested to just clean up and delete old packs that don't hold any valuable data since the complete prune takes way to long.

I understand, that it's impossible to move blocks from one file to a different one, via SFTP, but since restic is only interested in removing stuff from the packs, why not just write zeros in the files?

Either the filesystem can handle sparse files and will punch holes or it might do compression, like btrfs, zfs, etc.

Since ssh can use compression for its connections, the zero write commands can be very bandwidth cheap, since only offsets are transmitted instead of data.

I think there are more backends than just file:// and sftp:// which could be optimized that way, to avoid reading and writing all the data we already stored in packs.

`restic 0.9.6 compiled with go1.14 on linux/amd64`

**Comment by MichaelEischer** [comment]
Restic is designed to _never_ modify any files stored in the backup repository, except deleting them (I think it's not even possible to modify files on some of the supported backends). Overwriting parts of a pack files with zeros would just cause restic to regard them as damaged. To avoid that, restic would have to modify the pack header, hash the modified pack (which requires downloading it) to update the filename, and then also to rewrite an index file with the new pack filename.

The problem with prune being slow because it rewrites lots of packs is already tracked in #2547 and several other issues. There's also PR #2513 which adds commands that allow you to only rewrite pack files with more than e.g. 20% deleted blobs, just make sure that `restic check` does _not complain about errors_ before using that PR.

If that solves your request, please close this issue.

**Comment by RubenKelevra** [comment]
> Overwriting parts of a pack files with zeros would just cause restic to regard them as damaged. To avoid that, restic would have to modify the pack header, hash the modified pack (which requires downloading it) to update the filename, and then also to rewrite an index file with the new pack filename.

Well, but it would at least save the upload part of the same data again.

Since most people have much more download bandwidth than upload bandwidth this could save a lot of time.

It also avoids that the backend has to store the data a second time, writes on the medium, which might be associated with cost - as well as cut the total bandwidth use in half since there's no need to upload anything again.

In the case of a local filesystem, the speed increase would be massive, since we can punch holes in the files with fallocate instead of actually writing any data.

**Comment by MichaelEischer** [comment]
This cannot work for several backends: S3 does not offer any way to modify files except uploading a new version. B2 allows you to copy parts of an existing file to a new one (but in that case you could just as well assemble a new pack without gaps). The block blobs in Azure also don't seem to allow you to just drop specific byte ranges and so one.

My steps to modify a pack also missed one step that would be required to make this crash-safe: prune always uploads a new pack, then modifies then index and removes the old pack afterwards. And that would require another upload of the pack file. There's no way to avoid that unless you were able to atomically modify the pack header, punch the hole in the file, rename the pack and replace the index file. That would basically support for a filesystem transaction which, as far as I am aware of, not supported by any of the backends.

**Comment by RubenKelevra** [comment]
> This cannot work for several backends: S3 does not offer any way to modify files except uploading a new version. B2 allows you to copy parts of an existing file to a new one (but in that case you could just as well assemble a new pack without gaps). The block blobs in Azure also don't seem to allow you to just drop specific byte ranges and so one.

Well, I'm not really interested in cloud services. And just because a specific backend does not support this operation, doesn't really mean it's a blocker for the rest.

> My steps to modify a pack also missed one step that would be required to make this crash-safe: prune always uploads a new pack, then modifies the index and removes the old pack afterwards. That is it would always require an upload of the pack file. There's no way to avoid that unless you were able to atomically modify the pack header, punch the hole in the file, rename the pack and replace the index file. That would basically support for a filesystem transaction which, as far as I am aware of, not supported by any of the backends.

Well, move is atomic. You can calculate the byteranges, upload them as a simple list to the server. Then move the file you like to modify and punch the holes. If there's a crash, you can just punch all holes again to complete this operation.

Afterward, you download the file, generate the new checksum and move the file to the new location.

**Comment by aawsome** [comment]
@RubenKelevra I did not fully get which problem you like to solve..

If your problem is "prune is too slow because it downloads a lot of things", the main reason is that `prune` downloads **all** pack files to rebuild the index from scratch (twice, I think). And yes, it additionally downloads and re-uploads all packs that need a repack. In my judgement however, the first point is usually the dominating one.

To remedy this, try out #2513. Using the commands of this PR results in

- Only using the contents of snapshot and index files and tree pack files for determining what to delete/repack (i.e. use only potential already-cached file contents)
- Specify various criteria whether to repack or not a pack file and also allow to not repack any pack file but only delete completely unused files
- Altogether this makes the "cleanup" **very very** fast if you are willing to accept partly used packs and still *very* fast if you imitate the repacking options of `prune`

I know that #2513 is still not perfect and more work and tests are needed, but, IMO, this is the way to solve the most severe issues with prune.

About your proposal with writing sparse files:
Thinking about a solution how to minimize traffic when deleting (few) blobs from the repository and generate a new interface between "backup client" and "storage", I would actually prefer a different solution: Make an REST interface that allows to query/store/get/delete blobs just by its blob ID. This is what e.g. borg does and would be IMO a much more natural approach.

**Comment by RubenKelevra** [comment]
> * Specify various criteria whether to repack or not a pack file and also allow to not repack any pack file but only delete completely unused files

Yeah, that alone would be nice. And maybe repack some of the packs when they got really "empty".

> About your proposal with writing sparse files:
> Thinking about a solution how to minimize traffic when deleting (few) blobs from the repository and generate a new interface between "backup client" and "storage", I would actually prefer a different solution: Make an REST interface that allows to query/store/get/delete blobs just by its blob ID. This is what e.g. borg does and would be IMO a much more natural approach.

Well, I just see no need to actually download and rewrite complete files, when you just want to remove single blobs from the file. From a filesystem perspective, there's hardly any overhead when punching holes in files. Ext4 and XFS can actually even collapse ranges in files, which is extremely fast compared to a rewrite and would hardly leave any overhead.

On BTRFS, for example, you can write a shadow copy of the file with cp --reflink=always and punch the holes in the copy of the file.

> @RubenKelevra I did not fully get which problem you like to solve..

Well, I got two servers and two USB drives where I like to write my backups, while I have a somewhat fast throughput of new files, which disappear again on the filesystem I like to backup.

So I need to clean up the space again periodically, to not run out of storage.

Since I don't want to copy from one server to the other one, avoiding potentially copying an error from one server to another one, I have to download and upload quite a lot of data, just to clean the restic repo up - which is far from ideal :/

Previously I used ZFS snapshots and transferred the deltas to both servers, but I switched to BTRFS on my systems recently, and don't really trust it's snapshot system fully.

So I decided to give restic a go.

**Comment by MichaelEischer** [comment]
> Well, I'm not really interested in cloud services. And just because a specific backend does not support this operation, doesn't really mean it's a blocker for the rest.

It looks rather different when you approach that question from a code maintenance perspective: Right now, restic has a uniform interface for its backend implementations which keeps the maintenance overhead for each backend low. Adding special functionality just for e.g. the local and sftp backend together with a widely different prune implementation (which in total might end up with thousands of additional code lines), poses the question whether the costs outweigh the possible benefits.

> Well, move is atomic. You can calculate the byteranges, upload them as a simple list to the server. Then move the file you like to modify and punch the holes.

Punching holes is not enough. It is also necessary to modify the pack header to accurately reflect which blobs it still contains. And if that fails halfway during the operation restic would need a way to rollback / redo the modifications which requires a journal file. That just adds a gigantic amount of further complexity along with necessitating a change of the repository format.

In case prune shouldn't violate the strong "recommendation" that every used blob must be contained in an index, it will be necessary to journal the updates of the index files. This just complicates things even further (e.g. restic would need to replay the journal before being able to even read from the repository or replay the modifications in memory 😨 ).

Although punching holes into files is an interesting idea, I don't see how that could be added to restic at an acceptable level of additional complexity. It also conflicts with the philosophy that pack files should never be modified once they were written.

> Make an REST interface that allows to query/store/get/delete blobs just by its blob ID. This is what e.g. borg does and would be IMO a much more natural approach.

That would be basically a reimplementation of restic to work in a way similar to borg. At that point it's easier to just use borg. It is a fundamental design decision of restic to not require "smart" data storage.

@RubenKelevra My understanding is that the actual problem you want to solve is to reduce the write amplification of prune. And for that the simplest solution is to either just delete completely unused packs or to just rewrite those with e.g. 50% unused blobs.

**Comment by MichaelEischer** [comment]
I'm closing this for now, as I don't see a way to implement this without changing some of the fundamentals of restic (especially the rule to never modify a file once it's written). A faster prune implementation could rather look like e.g. #2718.
