### ISSUE TITLE
Improve performance for restoring and mounting

### ISSUE THREAD

**Issue by tharrisone** [restic/restic#270]
I went to mount my snapshots and it took 20 minutes to show me the listing of the snapshot directories and after that I tried to just copy some folders over and that never finished. 

Restoring is also very very slow but I believe I spoke to you before about that 

I'm on a 70mb line, connected to a ramnode ubuntu server and I get very good speeds.

**Comment by fw42** [comment]
Interesting. Thanks for the bug report. I assume when you say "mount", you mean Fuse? The Fuse feature is pretty new and not super well tested yet.

Can you give some more details? How big is your repository? How many snapshots? How many files? How big are the files? (Lots of small ones or a few big ones?) etc.

How do you "mount" your repository exactly? How do you access it? using the local backend and nfs/ssfs or something like that? or using the sftp backend?

**Comment by tharrisone** [comment]
I used the restic mount command and my repository is pretty big.. I do 
hourly backups via cron the size of the snapshots are only around 1gig 
or so.  The files are lots of small files and there are around 215 
snapshots.

**Comment by fd0** [comment]
Thanks for the bug report and for describing the details of your use case.

I think I know what causes the delay here: For each snapshot, restic creates an index that maps plaintext blobs to storage locations (in pack files). When the repository is mounted, restic loads all indexes from the remote repository and parses them. This can be made more efficient:
 * Locally cache indexes and use those instead of loading them from the remote repo
 * Have a local master index that combines all the known indexes. If a new index is detected, merge it in.

This is not yet implemented, restic is a rather young project.

Restoring (with `restic restore`) is slow because it is not yet done concurrently. Up to now I've worked on getting the backup perform really well (because that's what's mostly used), but restore will follow.

**Comment by fd0** [comment]
So, this is resolved in the master branch! There's now a local metadata cache which enormously improves speed. I'm going to close this issue :)
