### ISSUE TITLE
Option for newlines after each progress update

### ISSUE THREAD

**Issue by FrederikNS** [restic/restic#2706]
Output of `restic version`
--------------------------

restic 0.9.6 compiled with go1.13.4 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I would like the ability to print a newline at each progress log update.

What are you trying to do?
--------------------------

I'm running restic in Kubernetes, where I'm using the native methods for reading the logs (`kubectl logs <restic pod>`). Unfortunately in Kubernetes a log line is only presented when the line is terminated with a newline. That means that when I run any restic command, and progress output is continually printed, I cannot see it. I only see the final progress line written.

I ran a `prune` to clean out some cruft from my backup repository, and I even ran it in verbose mode, but I couldn't see anything but the 3 first lines of log for a while:

    created new cache in /root/.cache/restic
    counting files in repo
    building new index for repo

I waited and waited, and was concerned if anything was actually happening, until ~49 hours later I finally got the next log line:

    [48:58:16] 100.00%  581951/581951 packs

It's pretty clear to me that restic has continually printed progress log, but as there never was a newline, I just couldn't see it until it was done.

I haven't tried yet, as I'm still waiting for the prune to finish, but I suspect that the `--json` parameter would actually give me the progress report in separate lines, but it would also be very nice to have a non-json "print newline for each progress update" mode.

I haven't tried, but I suspect that the same behaviour would happen for plain Docker without Kubernetes.

Bonus request: If this log output method could be controlled via an Environment Variable, it would be even easier to handle in my setup.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yes, restic seems to be a brilliant backup solution, and fits my usecase very well.

**Comment by rawtaz** [comment]
Is restic doing something that is unconventional in how it outputs its progress?

If not, wouldn't it be better if Kubernetes is fixed to handle this type of (from what I can tell common) progress bar? I have a hard time thinking we should add a switch to work around a problem in Kubernetes. I mean, adding a flag just to control one little character in the output seems pretty crufty/dirty to me.

At the very least, let's see if the `--json` output works for you, if you don't mind.

**Comment by FrederikNS** [comment]
Well, it's not exactly "unconventional"... Plenty of CLI tools does it, however it sort of goes against the [12-factor application guidelines](https://12factor.net/logs), which specified "one event per line". It also makes it impossible to collect that kind of log in a unified log collection system like EFK/ELK.

I will definitely be testing out the `--json` option once my prune finishes.

**Comment by FrederikNS** [comment]
The prune finally finished, so I tried running it again with `--json`, and the behaviour of command didn't change at all. It's still printing non-json log messages, and progress messages are still overwriting the same line, with no newlines.

So any kind of progress reporting doesn't work in all docker environments. You can only get the progress if you run the commands interactively.

**Comment by rawtaz** [comment]
That's odd, and something that should be investigated (why `prune --json`doesn't output JSON). Perhaps it's simply not implemented (the help text for the *global* flag `--json` says "for commands that support it").

We'll have to think about the other thing, implementing a flag to control a single character in the output seems rather ugly to me.

**Comment by MichaelEischer** [comment]
Yep, the prune command does not yet support JSON output.

@FrederikNS You could try to run restic as follows: `restic prune | tr '\r' '\n'`. You would probably also want to set the environment variable `RESTIC_PROGRESS_FPS=1`.

Would #2436 or one of the suggestions in #1455 solve your problem?

**Comment by FrederikNS** [comment]
> @FrederikNS You could try to run restic as follows: `restic prune | tr '\r' '\n'`. You would probably also want to set the environment variable `RESTIC_PROGRESS_FPS=1`.

I didn't at all consider simply replacing the carriage returns with newlines... I'll give that a try. But yes that should be exactly what I want.

> Would #2436 or one of the suggestions in #1455 solve your problem?

#2436 is a very vague description of what I want, but @whereisaaron's first suggestion in #1455 is exactly what I'm requesting. The switching on whether stdin is a tty is also how many other Unix tools handle this, and would make the usage much simpler in docker.

**Comment by FrederikNS** [comment]
Quick follow-up question, can the `RESTIC_PROGRESS_FPS` be set to values below 1?

For my prune, a log line every second is probably overkill, my prune takes about 4 days to complete, which would result in around 345,600 lines of log. Something like every 10 seconds would be more than sufficient. Can I simply set the value to `0.1`?

**Comment by MichaelEischer** [comment]
Sorry for the late reply. `RESTIC_PROGRESS_FPS` is currently interpreted as an integer so you can't go below one refresh every second. You could try to pipe the output of restic through `uniq -` to remove a few duplicates. Besides that the only option is to patch the progress bar yourself: https://github.com/restic/restic/blob/070d43e2902dd4bd45dc0c1d73de785d7aacf27f/internal/restic/progress.go#L27

You could replace that with `minTickerTime = 1000*time.Second / time.Duration(fps)` and remove the `if fps > 60` above.

**Comment by MichaelEischer** [comment]
restic actually wasn't printing '\r' instead of '\n' but rather nothing at all except the final status update. #3058 (accidentally) changed this such that the current master branch now prints progress updates, which are already separated by newlines. I can't make any promises yet on whether that behavior change will stick or not.

**Comment by plumbeo** [comment]
I'm adding here a slightly changed version of my comments in PR #3112.

The current behaviour (only one line printed at the end) looks a lot more sensible to me. `--quiet` disables it but it also silences other output that one may generally want in a log file so it’s not a good solution. Interim updates are something that is necessary when using a software interactively (because they show that the software is still working as expected and allow the user to roughly estimate how much work is left to do) but are useless when one is just interested in receiving a final status report (say an email, that’s my case) or is logging information to eventually be able to check it later.

In that case a user may very well want to have the most output possible (increasing verbosity) but 900 almost identical lines, one per second on a simple 15 minutes run, don’t tell anything useful and only drown relevant information in a sea of noise.

As far as I know this is the behaviour of most software who has progress bars, I may be wrong but I can’t remember seeing interim updates in non-interactive usage.

What I care about in this case is not disk space, it's attention, which is a quite more valuable commodity: since every task with a progress bar outputs a part of those 900 lines what you get is a lot of almost identical lines interspersed with the few lines you were actually interested in, and what would have been a short email visible in its entirety even on a smartphone display and checked in a couple seconds becomes a long email that must be browsed carefully.

Multiply that for N clients sending M emails every day every time restic runs, or exporting the logs to a central server, and suddenly this is not something you can just work around by scrolling past it with a quick flick of the mouse anymore. I may be wrong but I think that this use case is more common than the occasional time when one has to check the log file live when restic is running.

IMHO the default for non-terminal outputs should go back to not printing the progress bar interim updates, as it was before, and the feature should be explicitly enabled with a specific option, but I suppose the opposite would be good too as long as it's possible to completely disable the extra output.

Tying it to the verbosity levels, for example enabling it when `--verbose=2` or `-vv` are used, would be a possibility too, but I see two problems with it: the first is that it must be done carefully because right now the verbosity levels are treated a bit inconsistently (basically `--verbose` and default are the same thing, see PR #3009 for more details), the second is that somebody may want the interim updates without the extra details that come with higher verbosity level (like the list of every deleted pack, for example).

**Comment by fd0** [comment]
We've decided to revert this behavior back to what it was before, #3194 tracks this

**Comment by MichaelEischer** [comment]
#3199 changes the progress bar output on non-interactive outputs back to it's previous behavior, but allows using `RESTIC_PROGRESS_FPS` to override the default. `RESTIC_PROGRESS_FPS=1` will print one line per second, `RESTIC_PROGRESS_FPS=0.01666` one per minutes and so on. Sending a `SIGUSR1` signal to restic will also cause it to print the current progress. These two output controls also work when passing `--quiet` to restic. This is probably most interesting in combination with the `SIGUSR1` signal.

**Comment by FrederikNS** [comment]
Sounds good! Being able to set restic to post an update every few minutes would solve my use-case. Thanks!
