### ISSUE TITLE
Storage Backend: WebDAV

### ISSUE THREAD

**Issue by MirkoDziadzka** [restic/restic#277]
Please add the possibility to add to a Webdav server

**Comment by fd0** [comment]
Thanks for the suggestion!

**Comment by schorsch3000** [comment]
:+1:  for webdav, my isp gives me 2TB webdav-storage for free, perfect for backups :)

**Comment by smidm** [comment]
As a work around it should be possible to mount webdav location to a local directory and create restic repository there. In linux e.g. gvfs or davfs.

**Comment by schorsch3000** [comment]
@smidm i'Ve tried that, using davfs, is unusabe slow :(

**Comment by osminog** [comment]
good feature, I'm looking forward for this

**Comment by mgumz** [comment]
https://godoc.org/golang.org/x/net/webdav might be worth a try but (the same with *sftp backends etc) i am not convinced that something fuse-based (either on linux or something like http://www.expandrive.com/ ) isn't better suited to provide something filesystemish.

**Comment by jim3ma** [comment]
+1

**Comment by rawtaz** [comment]
I suggest closing this because WebDAV support is available through the rclone backend. Let me know what you think with thumbs up/down reactions :)

**Comment by rawtaz** [comment]
Closing because there's support for WebDAV as backend through the rclone backend.

**Comment by ksteinb** [comment]
One suggestion from me:

use restic for Backup:  https://restic.readthedocs.io

it encrypts and has many Backends and is due to its "increment forever" strategy and deduplication  very economical in terms of storage and is very very fast .  For webdav you could use the rclone backend for example.

I for my part use Backblaze (its much cheaper then AWS)
