### ISSUE TITLE
Add command line option to read password from a file

### ISSUE THREAD

**Issue by MirkoDziadzka** [restic/restic#278]
would be great if rustic could read the encryption password from a file instead of the environment

**Comment by fd0** [comment]
Thanks for the suggestion. What's your use case? Did you know that you can use the environment variable `RESTIC_PASSWORD` to tell it the password?

Btw: It's called "restic", not "rustic".

**Comment by MirkoDziadzka** [comment]
Sorry for the typo in the name, it was not intentiaonally.

Environment variables may be shown  in the ```ps``` outputs and sometimes the ```ps``` output of a system tends to be written to log files for diagnostic reasons of unrelated stuff. Which is not a good place for a password to end up.

**Comment by fd0** [comment]
Hm. Logging the environment of current processes may be a reason to add this function.

@fw42 what do you think?

**Comment by fw42** [comment]
Yeah he's right, I think environment variables are a bad place to store passwords. We should discourage that (possibly completely remove that feature).

**Comment by episource** [comment]
Passing the password using an environment variable is nice for scripting. While a more secure alternative is always good, support for the environment variable RESTIC_PASSWORD shouldn't be dropped needlessly. Finally it's fine according to the threat model:
> General assumptions:
> The host system a backup is created on is trusted. This is the most basic requirement, and essential 
> for creating trustworthy backups.
(https://github.com/restic/restic/blob/master/doc/Design.md#threat-model)

**Comment by fw42** [comment]
it's okay-ish when used like this:
```
export RESTIC_PASSWORD=foo
restic ...
```
but not when used like this:
```
RESTIC_PASSWORD=foo restic ...
```
if there is no way to allow one but not the other then I would say to remove it completely, but ymmv

**Comment by rawtaz** [comment]
I'd say keep the environment variable way too. It can be useful for quick tests and what not.

I think people should be able to know what each of these two things do and make an educated decision. We cannot make the entire restic built to suit only people that have no clue what they're doing. If the documentation clearly points to using a file for permanent storing of the password then most people would go with that. I don't think this is a problem.

**Comment by fd0** [comment]
> it's okay-ish when used like this:
> 
> export RESTIC_PASSWORD=foo
> restic ...
> 
> but not when used like this:
> 
> RESTIC_PASSWORD=foo restic ...
> 
> if there is no way to allow one but not the other then I would say to remove it completely, but ymmv

Both use cases are the same regarding restic: The password will end up in that proc's environment and `ps e` will list it. `export` is a shell keyword, signalling the shell that this variable should be passed on to newly spawned processes.

I'm a bit torn here: On the one hand, `ps` can only read the environment (via `/proc/PID/environ`) for processes running as the same user (or `ps` is called as root), so `ps` has the same "trust level" as the restic process itself. That's what the section in the threat model is about. After all instead of calling `ps` someone could also just send SIGSEGV to the running restic process to dump the memory and extract the password (or even the raw encryption keys) from that.

On the other hand I think systems that regularly log all processes together with the environment are a pretty special case, that's not a common thing I've come across so far. Therefore we could add the possibility to read the password from the file. Or disregard this use case as too obscure.

At the moment I'm in favor of adding an option to read from a file (especially since it's really not much added code), but I still consider storing the password in an environment variable secure in most usual environments.

We should definitely add a section in the user manual about storing the password when the backup is run by a script.

Agree @fw42?

**Comment by fw42** [comment]
> Both use cases are the same

you are right, I didn't get that... In that case I think neither should work :-)

But if you think documenting the possible dangers of this is good enough then sure, no big deal.

**Comment by fd0** [comment]
Great, then we have a plan. :)

**Comment by eripa** [comment]
Just FYI, one could also put the password in a file by using shell expansion, some like this:

    echo 'superSecretPassw0rd' > restic_password
    chmod 0400 restic_password
    RESTIC_PASSWORD=$(cat restic_password) restic -r repository_path snapshots

**Comment by MirkoDziadzka** [comment]
Yeah, but this would it also part of the environment of the restic process. Which is my original problem with the environment variable approach.

**Comment by fd0** [comment]
Another thing might be password managers like the apple keychain and the likes, maybe they need to execute a command? What do you think about having an option to read the password from a file and another one reading from a command?

**Comment by jannic** [comment]
If you can read the password from a file, an allow for special files like /dev/fd/..., you could use the bash feature "Process Substitution" to read the password from a command's output:
restic --password-file <(password-generating-command) ....

**Comment by juergenhoetzel** [comment]
> would be great if rustic could read the encryption password from a file instead of the environment

*restic* can already read passwords from *stdin* 
I just use this shell script. Instead of a `HEREDOC` you could also redirection from a file:


```bash
#!/bin/bash
export RESTIC_REPOSITORY=/mnt/restic
restic backup ~/<<EOF
mypassword
EOF

```

So i don't have a need for a *read-password-from-file* feature: Did I miss something.
