### ISSUE TITLE
Allow quotes in environment variables

### ISSUE THREAD

**Issue by ProactiveServices** [restic/restic#2814]
restic 0.9.6 compiled with go1.13.4 on windows/amd64

It is common (and advised) practice to enclose path names with double quote marks in Windows. Restic does not tolerate quotes in environment variables so one has to use the `set "varname=<path name with spaces>"` syntax, which is a somewhat esoteric method of using spaces to environment variables; users are less likely to be able to work around the problem using this method. It is also inconsistent behaviour: passing arguments to restic on the command line permits quotes.

**Comment by cfbao** [comment]
I don't think this is an accurate characterization of the problem.

From restic's point of view, it's treating command line arguments and environment variables in the exact same way - there should be no surrounding quotes. The same is true for the vast majority of command line tools.

When passing arguments on the command line, it's the shell and low level language runtime's responsibility to pre-process arguments grouping and character escaping.
So when you enter `restic backup "C:\directory to backup"` on the command line, restic only sees the 2nd argument as `C:\directory to backup`, without the surrounding quotes.

Allowing extra quotes in environment variables would actually mean treating env vars and cmd args differently, and deviating from the norm. More problematic, is the fact that the quote character `"` is allowed in filenames on Linux. This would mean restic needs to introduce a whole set of escaping rules, with huge amount of unnecessary complexity and almost certainly some breaking changes.

The only problem that I see, is the fact that Windows batch script sucks, and you're not yet familiar with it.
`set "varname=value with spaces"` is just the standard syntax and a fact of life when you do any amount of non-trivial batch scripting. It seems like a stretch to expect restic to accommodate quirks in a particular scripting language while also breaking the norm.

Personally, I'd recommend using PowerShell instead of cmd/batch script on Windows.

**Comment by MichaelEischer** [comment]
@ProactiveServices Do you have an example which you expected to work but that didn't? I agree with @cfbao that you need some quoting/escaping to help the shell figure out whether a space is part of a parameter or a separator. If the explanation solves the problem, please close the issue.

**Comment by ProactiveServices** [comment]
Having thought about it I agree that escaping is the proper way to go here.
