### ISSUE TITLE
Feature Request: backup source in multiple steps into 1 snapshot

### ISSUE THREAD

**Issue by despiegk** [restic/restic#301]
usecase
- a large repository needs to be backed up, its too hard to do it in 1 go (failure forces to restart from 0)
- or different source directories are part of the same backup
    - today if we do multiple backups from different sources then the result is different snapshots with different content so its not really 1 backup

goal 1
- if we could specify for different sources to go in same snapshot then it would be possible to backup from multiple locations to 1 destination snapshot

goal 2
- for a big backup set we could do the backup in e.g 10 steps, now its 1 big step, if it fails we need to restart from scratch

just an idea

thx

Kristof

**Comment by fd0** [comment]
Hi, thanks for your report and thoughts.

There already is an issue about resuming interrupted backups #59, so that interrupted transfers especially are resumed (and not restarted from the beginning at it is the case right now).

Making sure that the data does not change while restic takes a backup is (unfortunately) outside the scope of what restic is able to do, you could achieve that by e.g. creating a snapshot with LVM and making a backup of that snapshot...

**Comment by fd0** [comment]
I'm closing this issue now, if you have any feedback for me, please add another comment. thanks.
