### ISSUE TITLE
Data blobs seem to be missing, aborting prune to prevent further data loss!

### ISSUE THREAD

**Issue by unclesamwk** [restic/restic#3023]
# [Edit by @MichaelEischer] **See [this comment](https://github.com/restic/restic/issues/3023#issuecomment-724978137) for instructions to recover damaged packs.**

repository 575e9064 opened successfully, password is correct
counting files in repo
building new index for repo
[0:01] 100.00%  101845 / 101845 packs
repository contains 101845 packs (1070217 blobs) with 424.769 GiB
processed 1070217 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 29 snapshots
[1:17] 100.00%  29 / 29 snapshots
Fatal: [<data/a5c66b46> <data/0263dd34> <data/c30d23a3> <data/b6219ef4> <data/5d320c9c> <data/47effa2a> <data/9d6ee6a3> <data/0d681206> <data/43902c2b> <data/a0057fa2> <data/f91d6a50> <data/7cba5fe6> <data/355d43a3> <data/2e9feb61> <data/c87cc3ed> <data/8104ef95> <data/128ee5a4> <data/5b75af0b> <data/94633e1c> <data/ec6aa989> <data/f876e05c> <data/be58954b> <data/c9ffe20e> <data/991c4a30> <data/48594d83> <data/2dc03dbc> <data/6d8fe121> <data/09840332> <data/33b40ab4> <data/222e85bd> <data/dd3bd177> <data/c6bc4445> <data/e5cf426d> <data/812e4cee> <data/4c99865e> <data/edeaff56> <data/d81d207c> <data/674fd0cd> <data/2a8e8c07> <data/22bebce6> <data/0ac47ee6> <data/5c0cd1a2> <data/6aa4f020> <data/868c7214> <data/be560cf2> <data/7330f83c> <data/88a3ff3b> <data/41f8a329> <data/f2dc6ab9> <data/13f65cd0> <data/cb9eadb7> <data/0a733e91> <data/e66af3e4> <data/b90c76b6> <data/2bcb6e6f> <data/f273499b> <data/294cc8f5> <data/301f2084> <data/7adf05af> <data/e3a60adb> <data/58ce1d25> <data/9fe36716> <data/020dbd1d> <data/9ac14d3a> <data/1d70f084> <data/90752236> <data/ad3a6190> <data/91da8cc7> <data/c00ebb0e> <data/cac4a750> <data/04d91469> <data/67eaea1b> <data/5e9d64b5> <data/bf86fc21> <data/e3c6e99b> <data/242ec3b3> <data/35354808> <data/9caa443c> <data/daa96050> <data/767638bc> <data/d5b17efd> <data/1cad7845> <data/92e59720> <data/cbb2db03> <data/dd91ca2d> <data/44d44449> <data/acb667c2> <data/025b7630> <data/acecc383> <data/eea62998> <data/3031267e> <data/b841096c> <data/c9000183> <data/506e076d> <data/a2eb0732> <data/bf0b9874> <data/3b1c6115> <data/f2984878> <data/026282d0> <data/429e1cf9> <data/027f0e01> <data/d4bf6073> <data/1877465e> <data/123aad11> <data/a57a748e> <data/b46dc499> <data/2c266d43> <data/cf08e3f6> <data/78650f91> <data/a691b49b> <data/32e22aed> <data/21dc4ae2> <data/dce17c97> <data/03bd6674> <data/ce5c53d5> <data/5fe04c53> <data/b06eafd3> <data/b666ffd6> <data/916bb531> <data/ce658f67> <data/f6ab04f9> <data/84e43d89>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose

**Comment by rawtaz** [comment]
You forgot to fill out the rest of the issue template that you were presented with when opening the issue. Please do that, so we get the proper information about your setup.

**Comment by MichaelEischer** [comment]
@unclesamwk I've a few further questions in addition to the issue template: Did something unexpected happen before the prune run? Do you run `check` on the repository from time to time? Is this the first prune run since upgrading to restic 0.10.0?

**Comment by xoxys** [comment]
I see the same behavior on one of my repositories. I can answer the question for my setup:

> Did something unexpected happen before the prune run?
No, nightly backups were running fine for ~ 1 week; a few days ago it starts to report the "Fatal: [<data/5ad9c4ac> <data/a9f1d358> <data/43633b09>] not found in the new index. Data blobs seem to be missing, aborting prune to prevent further data loss!"

Do you run check on the repository from time to time?
Yes, its part of the nightly backup. Check runs before the backup command.

Is this the first prune run since upgrading to restic 0.10.0?
No, the repo was initialized with restic v0.10.0

Let me know if you need more information. My repo is still in this "error" state.

**Comment by xoxys** [comment]
Now I have the same behavior on a second repo. I'm a bit confused about how this happens

**Comment by MichaelEischer** [comment]
@xoxys Which backend are you using? Did you notice any warnings/errors during backup runs? Did previous prune runs return errors? Which errors does `restic check` report or aren't there any?

**Comment by xoxys** [comment]
@MichaelEischer I'm using Minio S3 backend. No there were no errors or warnings, backups are still running fine, just the prune command is failing. Backups are running since ~ 1-2 weeks now once a day, I had no issues with daily prune runs in the past. I'll start the check command now. Will post the results when ready.

**Comment by xoxys** [comment]
Maybe I have to add that I'm using resticprofile as a wrapper for restic. But afaik it is just translating a profile config into restic commands. Right now backup jobs are configured to:

1. Check repository
2. Backup
3. Forget prune repository

The two failing repos are just failing at the last step daily check +  backup are still successfull

**Comment by MichaelEischer** [comment]
If check completes successfully, could you try running `prune` a second time? (forget --prune probably won't do anything, as it only runs prune when snapshots were removed).

**Comment by xoxys** [comment]
Ceck command finished, no errors:

```
using temporary cache in /tmp/restic-check-cache-843151623
repository 2276d4e4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-843151623
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found
```

**Comment by xoxys** [comment]
Prune finished with errors:

```
repository 2276d4e4 opened successfully, password is correct
found 2 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
counting files in repo
building new index for repo
[26:40] 100.00%  6174 / 6174 packs
incomplete pack file (will be removed): 9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
repository contains 6173 packs (21187 blobs) with 30.540 GiB
processed 21187 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 7 snapshots
[0:00] 100.00%  7 / 7 snapshots
Fatal: [<data/83bdfca4> <data/36543b46> <data/0dce226f> <data/d8ada74a>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

**Comment by xoxys** [comment]
Any idea how to repair such a repo? I would like to prevent to remove all snapshots if possible.

**Comment by MichaelEischer** [comment]
Sorry for the late reply, I've got side-tracked with too many PRs.

I'm really wondering why prune complains about missing blobs, whereas check seems to be happy. Could you run `check --read-data` which will also download and check every pack file in the repository? If that doesn't complain about a broken pack file, then please remove the cache for the repository in `/root/.cache/restic/2276d4e4[...]` and run prune again.

Can you check the sha256 hash for the file stored in the repository at `data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917`? That could be the file that should contain the four missing blobs. Please run `restic find --show-pack-id --blob 83bdfca4 36543b46 0dce226f d8ada74a` to find out which pack file should contain the missing blobs.

Is the Minio S3 connection using HTTPS (that is TLS as transport encryption)?

**Comment by xoxys** [comment]
No worries :) Minio is using HTTPS, right. I've already used the find command, the result was every snapshot is affected and the corresponding file is still part of the source data on the host. Let me run the commands again and document it here this time.

**Comment by xoxys** [comment]
Ok current state for the check command:

```
using temporary cache in /tmp/restic-check-cache-219356123
repository 2276d4e4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-219356123
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
read all data
Pack ID does not match, want 9559868a, got cc061de6
[14:27] 100.00%  7604 / 7604 packs
Fatal: repository contains errors
```

What's the next step with this result?

**Comment by xoxys** [comment]
That's the find command result:

```
repository 2276d4e4 opened successfully, password is correct
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.4/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1ca1ff43 (2020-11-07 21:35:10)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.5/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1e5246c4 (2020-11-08 21:24:32)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.2/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 22d6a5c4 (2020-11-05 21:35:52)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.6/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 5de2a5eb (2020-11-09 21:32:01)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.3/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 78434cf1 (2020-11-06 22:28:04)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.1/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot cd3d9f07 (2020-11-04 21:59:30)
Object belongs to pack 9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
 ... Pack 9559868a: <Blob (data) 36543b46, offset 0, length 1419761>
Note: cannot find pack for object '83bdfca4', unable to parse ID: invalid length for hash
Note: cannot find pack for object '0dce226f', unable to parse ID: invalid length for hash
Note: cannot find pack for object 'd8ada74a', unable to parse ID: invalid length for hash
```

**Comment by xoxys** [comment]
And the checksum of the file 

```
cc061de6ef215357cb8f9b53a43561190702c5808d4f1e9cb1b52f449580af62  /data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917

```

**Comment by MichaelEischer** [comment]
> Ok current state for the check command:
> `Pack ID does not match, want 9559868a, got cc061de6`

The pack ID after "want" is the one also reported by prune as incomplete. So that's the pack file with the missing blobs.

> `Note: cannot find pack for object '83bdfca4', unable to parse ID: invalid length for hash`

It looks like find is unable to properly handle multiple blobs in one call. Can you run
`restic find --show-pack-id --blob 83bdfca4` and also once with `0dce226f` and `d8ada74a`? I'd expect it to also report the same file(s) as damaged.

How large is the `9559868a[...]` pack file? Are you able to look up a date when it was created? Right now it looks like the file for some reason failed to upload correctly without restic receiving/noticing an error. I'd like to investigate a bit whether we can find out how that pack file ended up damaged.

To repair the repository, there are two possible routes. But first, if you still have the backup file (which by now is probably in `/var/lib/backup/backup.7/piwik.sql.gz`), copy it to a safe place where it won't be modified in the meantime.

Route 1: This allows investigating the damage to the pack file and might work even without the original file. It's safe in that There's a [debug-1999](https://github.com/restic/restic/tree/debug-1999) branch which contains the functionality to extract all intact parts of a damaged pack file. You can use it as follows:
- Build the debug-1999 branch using `go build -tags debug ./cmd/restic`
- Run `restic debug examine --extract-pack <id-of-broken-pack-file>` to extract all blobs in the damaged pack file into the current folder (-> it's best to use a temporary folder to reduce the chaos). The packfile must still be located in the proper place inside the repository, but it is not necessary for it to be contained in the repository index (i.e., there's no need to run `rebuild-index`, please **do not** run that command right now) The option `--try-repair` can be used to try to repair a single bit flip, and `--repair-byte` tries to repair a full byte at once (but is also much slower). This step won't modify the repository at all
- For the later steps you can use a normal restic binary (version >= 0.10.0) if you want to
- Move the damaged pack file out of the repository, create a backup of the index and run `restic rebuild-index`
- Then run `restic backup .` in the folder which contains the extracted blobs
- Now with a bit of luck `restic check --read-data` should no longer report errors or only a few ones
- If the missing blobs are part of a file of which you still have the original, then run `restic backup <original-file>`, which will recover the missing blobs.

Route 2: Requires to original file (and is a subset of the steps of route 1)
- Move the damaged pack file out of the repository, create a backup of the index and run `restic rebuild-index`
- Then run `restic backup <original-file>`, which will recover the missing blobs.

(Route 3: Use the experimental repair command from #2876 to remove the damaged file from the snapshot.)

**Comment by xoxys** [comment]
Thanks a lot for all the work and the detailed instructions!

> How large is the 9559868a[...] pack file? Are you able to look up a date when it was created? 

Thats how it looks like `-rw-rw---- 1 root root 2.0M Nov  4 21:59 data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
`

> Can you run
restic find --show-pack-id --blob 83bdfca4 and also once with 0dce226f and d8ada74a? I'd expect it to also report the same file(s) as damaged.

Sure. You are right, seems to be the same files.

```
# 83bdfca4
repository 2276d4e4 opened successfully, password is correct
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.4/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1ca1ff43 (2020-11-07 21:35:10)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.5/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1e5246c4 (2020-11-08 21:24:32)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.2/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 22d6a5c4 (2020-11-05 21:35:52)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.6/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 5de2a5eb (2020-11-09 21:32:01)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.3/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 78434cf1 (2020-11-06 22:28:04)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.7/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 9d504c09 (2020-11-10 21:11:45)
Found blob 36543b466fbe949b723fab38dcc2b3d683a49142968faa1179187ea6ef27c476
 ... in file /var/lib/backup/backup.1/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot cd3d9f07 (2020-11-04 21:59:30)
Object belongs to pack 9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
 ... Pack 9559868a: <Blob (data) 36543b46, offset 0, length 1419761>

# 0dce226f
repository 2276d4e4 opened successfully, password is correct
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.4/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1ca1ff43 (2020-11-07 21:35:10)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.5/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1e5246c4 (2020-11-08 21:24:32)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.2/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 22d6a5c4 (2020-11-05 21:35:52)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.6/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 5de2a5eb (2020-11-09 21:32:01)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.3/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 78434cf1 (2020-11-06 22:28:04)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.7/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 9d504c09 (2020-11-10 21:11:45)
Found blob 0dce226f1f469cdc802e857593a8c0a886805ff9a988898b20a42400c25e2142
 ... in file /var/lib/backup/backup.1/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot cd3d9f07 (2020-11-04 21:59:30)
Object belongs to pack 9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
 ... Pack 9559868a: <Blob (data) 0dce226f, offset 1419761, length 961634>

# d8ada74a
repository 2276d4e4 opened successfully, password is correct
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.4/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1ca1ff43 (2020-11-07 21:35:10)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.5/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 1e5246c4 (2020-11-08 21:24:32)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.2/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 22d6a5c4 (2020-11-05 21:35:52)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.6/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 5de2a5eb (2020-11-09 21:32:01)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.3/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 78434cf1 (2020-11-06 22:28:04)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.7/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot 9d504c09 (2020-11-10 21:11:45)
Found blob d8ada74adfda960f28aac65a45ba6653715b385c0e4cc22251e53dc2cb6a2784
 ... in file /var/lib/backup/backup.1/piwik.sql.gz
     (tree 9cc6c7414dd9ab2164511eb92fc734642397bd3aaaef881f3177edaf45297d86)
 ... in snapshot cd3d9f07 (2020-11-04 21:59:30)
Object belongs to pack 9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917
 ... Pack 9559868a: <Blob (data) d8ada74a, offset 3170343, length 3361033>
```

I would really like to go route 1if that helps to debug it a bit more but it may take a bit until I find the time to dig into it.

**Comment by MichaelEischer** [comment]
> Thats how it looks like `-rw-rw---- 1 root root 2.0M Nov 4 21:59 data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 `

Are that smooth 2.000000 MB? According to the find output that file should have at least 6.4MB, so it looks like it was just truncated. When comparing it with the snapshots it looks like that pack file was write approx. at the start of a backup run. Do you have a logfile for the backup run on the 4th of November?

> I would really like to go route 1if that helps to debug it a bit more but it may take a bit until I find the time to dig into it.

As the pack file only has 2 instead of >6MB, route 1 probably won't be that useful after all. It would have allowed determining how the damage looks like, but with that file size its obvious that it was (probably) just truncated. So I think it's best to just follow the more standard 'Route 2'. Make sure that you grab a copy of the piwik backup file before it's aged away. Any chance you have server logs from the minio server for the upload of the `9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917` file?

**Comment by xoxys** [comment]
> Are that smooth 2.000000 MB?

No, sorry it's 2097152 Byte.

> Do you have a logfile for the backup run on the 4th of November?

Sadly not.

> Any chance you have server logs from the minio server for the upload of the `9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917` file?

Minio log level is set to `error`  and there was nothing logged for this day. But the traefik in front of Minio has logged `[04/Nov/2020:21:29:39 +0000] "GET data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 HTTP/1.1" 206 591 "-" "-" 1936622 "minio@docker"`

**Comment by xoxys** [comment]
Missed some parts, that should be the full proxy log for this file and day:

```
[04/Nov/2020:23:02:57 +0000] "GET data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 HTTP/1.1" 206 591 "-" "-" 2047199 "minio@docker"  193ms
2020-11-04 21:29:39 +00:00 
[04/Nov/2020:21:29:39 +0000] "GET data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 HTTP/1.1" 206 591 "-" "-" 1936622 "minio@docker"  339ms
2020-11-04 20:59:44 +00:00 
[04/Nov/2020:20:59:44 +0000] "PUT data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 HTTP/1.1" 200 0 "-" "-" 1918343 "minio@docker"  12810ms
```

**Comment by MichaelEischer** [comment]
2097152 is actually 2 * 1024 * 1024, so that counts as even number too ;-) .

Thanks for the log snippets. 

> [04/Nov/2020:20:59:44 +0000] "PUT data/95/9559868a828fd99b99d71243273550d7abc0d617b9f909a4850eb2f00662f917 HTTP/1.1" 200 0 "-" "-" 1918343 "minio@docker"  12810ms

Although "200 OK" as HTTP status code is usually a good sign, it isn't in this case. It means that something went horribly wrong and nobody noticed. That sort of leaves three possibilities for how the file could have been truncated:
- restic for some reason only uploaded a part of the file _and_ also indicated a too short ContentLength
- minio lost half of the file but acknowledge the successful receipt of the file
- Something in-between messed up the content length and transfer

I don't see how the first case could happen, unless seeking to the end of the pack file to determine its length failed. (Which seems to be rather unlikely. And it would somehow have to end up returning exactly 2MB instead of the real file size).
I hope that traefik doesn't tamper with the content-length header (it's not covered by the the S3 request signature) or alter the body encoding, as that would be a opportunity to truncate an upload. That would leave option two, but I really hope that not to be the case, someone must have had a look at the error handling in Minio...

restic currently does not enable the content-md5sum header in the minio S3 library. That might have helped, but I'm just not too happy that that would require loading the full pack into memory before uploading.

**Comment by xoxys** [comment]
> 2097152 is actually 2 * 1024 * 1024, so that counts as even number too ;-) .

Ouch... that hurts :D

Ok looks like debugging becomes more and more complicated. As I'm not that happy with my current Minio setup at all I'll switch to B2 and see how that will perform on a daily basis.

**Comment by fd0** [comment]
@harshavardhana would you mind having a look here? Any ideas how the file might have been truncated?

**Comment by rawtaz** [comment]
@xoxys B2 isn't exactly trouble free given reports we've had here over time. What about using restic's [rest-server](https://github.com/restic/rest-server) instead, if you don't want to use Minio which should be working fine?

**Comment by xoxys** [comment]
-.- that are bad news. I try to find a setup without a self-hosted backup server...

**Comment by rawtaz** [comment]
Well lots of people still use B2 so it's not like it doesn't work. What about S3?

**Comment by xoxys** [comment]
S3 is a bit too pricey...

**Comment by xoxys** [comment]
What about backblaze s3 API? Or does it not make any difference? Maybe we should discuss this somewhere else to not clutter the issue history

**Comment by harshavardhana** [comment]
> @harshavardhana would you mind having a look here? Any ideas how the file might have been truncated?

How easy is it to reproduce?

**Comment by xoxys** [comment]
Afaik nearly impossible. Running restic on 50 servers with the same minio backend since weeks only two got these "random" error state

**Comment by dimejo** [comment]
@xoxys:
> S3 (AWS) is a bit too pricey...

I can recommend Wasabi, we have been using it for quite some time without issues. Prices are comparable to B2.
