### ISSUE TITLE
Add option to skip missing files in backupset

### ISSUE THREAD

**Issue by gunzola** [restic/restic#3089]
Output of `restic version`
--------------------------
0.10.0

What are you trying to do? What problem would this solve?
---------------------------------------------------------
For doing backup of "live" systems, sometimes files are removed from that system.
In this particular case we are attempting to backup Splunk events. Splunk sometimes cleans up events where retention period has run out. This causes an ongoing backup to stop with errors:
error: lstat /ops/splunk/var/lib/splunk/data/db/db_1600609772_1600588173_4573/rawdata/journal.gz: no such file or directory
Fatal: unable to save snapshot: Lstat: stat /ops/splunk/var/lib/splunk/data/db/db_1600609772_1600588173_4573/rawdata: no such file or directory

In our scripted backup we first create a list of files to backup, and then call restic with --files-from parameter.

**Comment by rawtaz** [comment]
Thanks for your use case report. The behavior you're seeing is due to the change in https://github.com/restic/restic/pull/2546 . It's considered an error if you tell restic to back up a file, and that file cannot be backed up.

If you have data that is changing during backup, have you considered using a snapshot in your filesystem to make it consistent before backing up? That's probably a more proper solution than telling restic to ignore missing files that you told it to back up. If you use the proposed option/flag, you may get bitten by it some day when files you expect to be there aren't.

LVM, ZFS and BTRFS has snapshot features, as well as other filesystems.

**Comment by gunzola** [comment]
Hi rawraz

Thanks for your reply. I Was not aware of that LVM was supporting snapshots.. That's probably the way to go here.
Thanks for your help.
