### ISSUE TITLE
How to install restic if not available on apt? Explanation needed for restic binaries.

### ISSUE THREAD

**Issue by tronics** [restic/restic#3146]
Hello,

I have restic running on a couple of servers it is fantastic.

Now I have one legacy intranetserver on Debian 8.
Somehow I cannot install with apt-get install restic.

1) What repository do I have to add to make this work?
2) I downloaded the binary tar.gz. And found an explanation about updating it. But I find no way to run it and I am confused why there is also a docker folder inside. I thought I would get just a script and a few libraries.

Thank you.

**Comment by rawtaz** [comment]
> 1. What repository do I have to add to make this work?

The packages in various operating system distributions and other package systems/collections is not something the restic project maintains. You'd have to ask whoever is maintaining the packages for your system.

> 2. I downloaded the binary tar.gz. And found an explanation about updating it. But I find no way to run it and I am confused why there is also a docker folder inside. I thought I would get just a script and a few libraries.

The documentation for the official binaries is right here in the restic documentation:  https://restic.readthedocs.io/en/latest/020_installation.html#official-binaries

It says "You can download the latest stable release versions of restic from the [restic release page](https://github.com/restic/restic/releases/)." and "There’s both pre-compiled binaries for different platforms as well as the source code available for download. Just download and run the one matching your system.", which is accurate.

Restic is just one single binary, so all you have to do is download it, make sure it's executable, and then run it. You probably downloaded the *source code* (which includes the docker folder) instead of the binary, so I suggest that you go to the above linked releases page and download file beginning with "restic" in its name instead of the source code. Pick the one for your operating system and platform.

By the way, this is a purely "getting help" type of question, and we kindly ask that those are asked in the [https://forum.restic.net/](https://forum.restic.net/). Thanks!
