### ISSUE TITLE
Allow automatic exclusion of cache directories

### ISSUE THREAD

**Issue by teknico** [restic/restic#317]
I need to exclude specific directories from the backup, and could not find a way to do so.

Rather than adding cumbersome lists, an easy and widespread way is supporting the [Cache Directory Tagging Standard](http://fileformats.archiveteam.org/wiki/Cache_Directory_Tagging_Standard).

I currently use [Obnam](http://obnam.org/) and this is the one thing preventing me from switching to Restic. Which is quite impressive, both theoretically and practically: thank you for it.

**Comment by fd0** [comment]
Agreed, it is a good idea to include this (and it's easy to do). I think this feature should be disabled by default and enabled with an option, similar to `tar`. From `tar(1)`:

       --exclude-caches
              Exclude  contents  of directories containing file CACHEDIR.TAG, except for the tag file
              itself.

       --exclude-caches-all
              Exclude directories containing file CACHEDIR.TAG and the file itself.

       --exclude-caches-under
              Exclude everything under directories containing CACHEDIR.TAG

I'm thinking about adding an option `--exclude-caches` that excludes the contents (recursively) of directories which contain a `CACHEDIR.TAG` file.

**Comment by teknico** [comment]
It sounds good, thanks!

It's not a problem but out of curiosity, what's the rationale of having it disabled by default?

I'm also not sure I understand all the differences among the three tar options, oh well...

**Comment by fd0** [comment]
We can discuss this of course, but I think a backup program should try to archive and restore EVERYTHING, this includes cache directories. If the user consciously decides not to archive cache dirs, that's fine with me, but shouldn't be the default. What do you think?

**Comment by teknico** [comment]
It should obviously try to archive and restore everything the user tells it to, not *everything*. :-)

The [standard description](http://www.brynosaurus.com/cachedir/spec.html) used to include instructions to applications to automatically manage the tag files, and also the following (it has been unreachable for a while):

"Data backup, transfer, or synchronization software, if configured to do so, may interpret the presence of a cache directory tag in a directory as a command to exclude that directory automatically (including any subdirectories) from the backup or transfer operation. I leave it to the designers of such applications to decide whether this "auto-exclude" behavior should be the default or only adopted when specifically requested by the user. A bit of conservatism is probably warranted in the short term, but automatically excluding cache directories by default could improve efficiency and ease-of-use in the longer term.

For maximum robustness against accidental data loss, any tool that has built-in support for cache directory tags is strongly encouraged to verify that any file it finds named CACHEDIR.TAG is a regular file and actually contains the 43-byte header specified above, before concluding that the file is indeed a cache directory tag."

Not much to add, I leave the decision to you, I'm fine either way.

**Comment by mafgh** [comment]
While this is not cache directory specific I really like the `--exclude-if-present filename` option duplicity has:
> Exclude directories if filename is present. This option needs to come before any other include or exclude options.

It will exclude folders recursively, for example with `--exclude-if-present .nobackup`

    /foo
    /foo/bar
    /foo/bar/.nobackup
    /foo/bar/baz
    /foo/quux

it will skip `/foo/bar` but backup `/foo` and `/foo/quux`

**Comment by teknico** [comment]
The means to exclude directories from the backup are actually already there, see #226 (follow-up in #233). At first I didn't even realize that each subcommand has its own options: added mention to the manual in https://github.com/restic/restic.github.io/pull/19 .

**Comment by rawtaz** [comment]
I think such an argument like --exclude-caches is just horrible. And by that I don't mean @fawick's work in PR #1170, but the approach in general.

First of all, we already have the option to exclude stuff. If someone has e.g. `~/.cache`, then excluding that is just one (existing) argument away. We don't need to introduce an additional argument and support a very specific file for this specific case.

Second, this proposed argument is about caches. There's a bunch of other files/directories that might come up as "unwanted" too. Like, what's next, `--exclude-temp`, `--exclude-vendors` and `--exclude-cats`? It's naturally impossible to predict what stuff people might want to exclude, and while caches is a common thing, it's not common enough to warrant adding a specific argument for it to restic. Way better to make the current exclude (and include) features flexible and very usable.

Third, on a note related to the second one, what @mafgh mentioned seems like a much much better idea if we want an argument that supports excluding flagging/tagging directories using a file in them. The `--exclude-if-present <filename>` is way more generic and the way to go if we want this type of feature (exclude by adding a file) at all. Not to mention; It could be made to accept multiple filenames if needed (and to take it even further, it could be made to look for some specific text specified in this argument, in the beginning of the file, to make sure it's really a proper exclude file).

Fourth, but still, even if we were to have this proposed feature (the ability to exclude a directory by adding a certain file in it), what about files? Someone might want to exclude all files of some specific names, and that's not something you can do with the proposed feature - you still have to use the regular exclude arguments for that. So again we end up with the proposed feature just covering a small part of users' needs on the topic of excluding things.

Fifth, somewhat minor detail, but the choice of `CACHEDIR.TAG` for the filename is very unfortunate as it's so specific. I can't imagine what the person designing that was thinking, or rather how short-sighted they were in that moment. Relating to the second point above, it's simply not a good name for that file.

Simply put, we already have what we need to exclude directories, so lets make sure that works well, and if we really need to be able to exclude _directories_ (again, this will not work for files - we still have to use the regular excludes for that), then at least make it generic like the `--exclude-if-present` suggested earlier. Don't "hard-code" the cache aspect of this new feature, it would be a bad design choice.

My take is; Don't convolute it, keep it simple and clean. Use the current exclude features, script it if there's a lot to exclude. Don't include this proposed argument, because it is too specific and not common enough of a use case.

Finally, a question: @teknico, you wrote that the lack of this feature was the one thing keeping you from using restic. If that is really the case, what do you think about the `--exclude-if-present` suggested earlier? Would that satisfy your need/requirements equally well (or even better, considering how much more flexible it is)?

**Comment by rawtaz** [comment]
Just look at the `tar` manual snippet @fd0 pasted - _Three_ arguments, just for excluding _caches_. Sure, it can be used for other things too, but then not in a proper way - better then to do it the right way from scratch.

**Comment by mathstuf** [comment]
> Fifth, somewhat minor detail, but the choice of CACHEDIR.TAG for the filename is very unfortunate as it's so specific. I can't imagine what the person designing that was thinking, or rather how short-sighted they were in that moment. Relating to the second point above, it's simply not a good name for that file.

Is that a reason to ignore a spec that someone wrote up and is now supported in multiple projects. The amount of stuff just on Github for supporting or handling it [is non-zero](https://github.com/search?q=%22cachedir.tag%22&type=Issues). I use it for excluding things which should generally be ignored by backups such as build directories (of which there are many and listing them explicitly would be…troublesome, even by scripted standards). Looking, it seems to be used by at least `ccache`, `fontconfig`, and `notmuch` for their directories.

> Don't include this proposed argument, because it is too specific and not common enough of a use case.

Well, if #16 were implemented…

> what do you think about the --exclude-if-present suggested earlier?

Part of the `CACHEDIR.TAG` spec is that it must begin with specific content to help avoid false positive detection.

**Comment by rawtaz** [comment]
If there are better ways to do this, I don't think that following up on a bad design just because more than zero projects use it is that great of an idea, if that's what you're asking. Not sure, since out of all the things I wrote, you picked the least important part to question. I can only assume that you agree with the other points then ;-)

Good point, a config file would be very useful to meet the use case in here. It could specify all the folders/files that should be excluded, or specify the name of a file to use as the "exclude tag", possibly also with content that has to be in that file for it to apply.

Yes, I know that's in the specification, a very specific content at the start of the file. I also briefly mentioned that this can be defined in the `--exclude-if-present` argument, if need be.

**Comment by mathstuf** [comment]
Personally, I don't care about excluding individual files or "just a single directory", so the other points weren't as salient to me. I'm also not *too* worried about it being called `--exclude-caches` since those are (by definition) just stored results of other, slower processes and therefore not of much use in a backup. The `temp` and `vendor` are just more specific kinds of caches to me, so I, personally, see that as a strawman.

What I want is a way to tell backup programs that certain directories are "I don't care". It would be nice that programs can do this themselves (only really possible via a shared spec like `CACHEDIR.TAG`) as well as me doing it for things like build trees.

I'm not too concerned about the way it gets implemented. If you want it to be more generic, fine. Maybe a commented out section in the default configuration file could show how to use it to implement the `CACHEDIR.TAG` exclusions?

**Comment by rawtaz** [comment]
I see your use case, and for that I think the `--exclude-if-present` and corresponding config directive would be the best option, rather than hard-coding a filename in an additional argument specific to that filname.

Indeed, having a default config file contain helpful comments is a good idea! Could carry an example that adheres to that specification, sure.

**Comment by dionorgua** [comment]
Some general switch like `--exclude-caches` makes sense sometimes. For example on Windows there is special `FilesNotToBackup` registry key that contains exclude patterns for backup apps ([see here for details](https://msdn.microsoft.com/en-us/library/windows/desktop/bb891959(v=vs.85).aspx)). Maybe it makes sense to create list of usually-ignored dirs that will be platform-specific (like `/var/cache`, `/home/*/.cache` for *nix, `/Library/Caches` + `/Users/*/Library/Caches` on Mac).

But I agree that for CACHEDIR.TAG is better to use something like `--exclude-if-present` (and it's probably ok to ignore CACHEDIR.TAG content). Or alternatively allow `--exclude-if-present` with any file, but check for proper signature if user called `--exclude-if-present CACHEDIR.TAG`. 

And in any case restic should backup this `CACHEDIR.TAG` file (or whatever is passed to `--exclude-if-present`) due to two reasons:
1. Just to save information that this dir was excluded.
2. In case of data loss and restore, 'missing' `CACHEDIR.TAG` files will require additional effort from end-user to restore such 'exclude' rules.

**Comment by mathstuf** [comment]
> Or alternatively allow --exclude-if-present with any file, but check for proper signature if user called --exclude-if-present CACHEDIR.TAG.

At that point, I don't see why not just support it with a named flag if there's going to be a "magic value". The suggestion was to be able to match a filename with a "magic" content prefix for exclusions.

> Maybe it makes sense to create list of usually-ignored dirs that will be platform-specific (like /var/cache, /home/*/.cache for *nix, /Library/Caches + /Users/*/Library/Caches on Mac).

I'd rather look up using metadata (like the registry, xattrs, etc.) than hard-coded paths. `~/.cache` is just the default location; the real location is `$XDG_CACHE_HOME`.

> And in any case restic should backup this CACHEDIR.TAG file (or whatever is passed to --exclude-if-present) due to two reasons:

I agree; I'll have to see what `obnam`'s behavior with this was (FWIW, the author of `obnam` also wrote the `CACHEDIR.TAG` spec).

**Comment by mathstuf** [comment]
`obnam` does not backup `CACHEDIR.TAG`. I don't see an explicit rationale other than how the exclusion logic works (it asked about the directory and could only return a boolean, not a "also back up this path").

**Comment by rawtaz** [comment]
Just to clarify my thinking on `--exclude-if-present`:

Syntax: `--exclude-if-present <filename>[:<content>]`

Specify that directories having a specific file (regardless of content) in it should be excluded: `--exclude-if-present heyMaThisIsMyExcludeTagFile.tag`

As the user is completely free to specify the filename in question themselves (as opposed to the pesky CACHEDIR.TAG filename), it's *extremely* unlikely that they will manage to end up in a situation where a directory has that filename without the intention to exclude it from the backup. However, if that were to be considered a risk, for some reason:

Specify that directories having a specific file with specific content *at the start of the file* in it should be excluded: `--exclude-if-present heyMaThisIsMyExcludeTagFile.tag.tag:youllNeverFindThisContentInANormalFile`

Like with tags, multiple entries can be supported, either by multiple instances of the argument, or by just separating multiple `<filename>[:content]` parts with a `,` on the command line, e.g. `--exclude-if-present fileA:contentA --exclude-if-present fileB,contentB` or `--exclude-if-present fileA:contentA,fileB,contentB`.

And to be super clear; One can quote the content to be looked for in the file, if need be. But I find it extremely unlikely that anyone would start using exclude tag files with content that is too complex to be used on the command line. Won't happen, and if it does, then just use the config file instead.

Each of these examples should of course have a corresponding syntax in the/a config file, when there's support for one.

The examples are obviously exaggerated, but they hopefully do give a hint that it's very possible to create a flexible version of what was proposed initially in this issue.

**Comment by fd0** [comment]
Thanks for your comments!

One point that was not brought up yet is:

The exclude rules that we already have in place are *direct* excludes: Users can instruct restic to exclude `.config/chromium` or `*.go`. Both patterns match on the name of the file to be excluded.

The central point of this feature is that it allows *indirect* excludes: A file (e.g. `CACHEDIR.tag`) in the same directory make restic exclude all files in that dir (and subdirs). This can be achieved with e.g. a shell script that writes an exclude file and then runs restic, but I think it's a good idea to directly support this to make it easier for users.

I'm convinced it is a good idea to add a feature to indirectly exclude files. It should be easy to use and it should be compatible with the cachedir tag standard (because it exists for quite a while and many backup programs support it). We can, additionally, allow some flexibility. And I'd like to offer only one additional command-line option, not three (like `tar`).

So, I'd like to propose: We add `--exclude-caches [filename[:content]]`. By default, `filename` is set to `CACHEDIR.tag` and `content` to `Signature: 8a477f597d28d172789f06886806bc55`. If content is unset, e.g. `--exclude-caches foobar`, then the presence of the file `foobar` is sufficient.

The option should be off by default. When it is switched on and the exclude file is present in a directory, all other files and subdirs are excluded, but the exclude file itself is saved. This should be a good default setting. For other, more advanced use cases people can still write a shell script and use the direct exclude function.

Comments/Thoughts?

**Comment by fd0** [comment]
Alternative implementation detail: Add `--exclude-if-present filename[:content]` and make `--exclude-caches` a shortcut for `--exclude-if-present "CACHEDIR.tag:Signature[...]"`.

**Comment by rawtaz** [comment]
I thought it was understood by everyone that we're talking about "indirect" excludes (like you describe them @fd0). At least I do :) I agree the "exclude tag file" or what to call it should be backed up, but not the rest of the content (files/directories) in the directory the file resides in.

I agree we should have support for this type of exclusion. I do however not agree that we should support the CACHEDIR.TAG specification. It's a poorly designed specification, at least in the context of how restic could support indirect exclusion.

We do not need to support that specification just because some others have decided to do so - we can do better. The very key goal should be to support "indirect exclusion" by file. That is what we should focus on, rather than supporting some specific specification that just happens to exist and cover *some* of this goal. I say again; The specification is poorly designed and *only covers part of the goal/feature we're trying to reach*, and doesn't have to be something we support just because some others do.

In general I'm all for keeping things simple and code bases clean, and in this case, adding the `--exclude-caches` with specific support for CACHEDIR.TAG adds specific code and a specific argument, for something that we already could have `--exclude-if-present` do. I don't think it's worth it, I think it bloats the code and opens up a can of worms in the sense that we'll end up in discussions later on about adding this and that other case-specific feature/argument as well, when we already have a working solution that could be used instead, just to save a few characters on the command line or in some script. Surely someone will want the `--exclude-cats` argument some day.

That said, the important thing is that we primarily go for the flexible and dynamic `--exclude-if-present` instead of just hardcoding support for the specification with some argument. So if people feel strongly about supporting the very specific CACHEDIR.TAG specification and thereby opening the can of worms, then sure, I'd say the best compromise is to implement `--exclude-if-present <fileName>[:content]` properly, and then to make everyone happy make `--exclude-caches` an "alias" for `--exclude-if-present CACHEDIR.TAG:"Signature: 8a477f597d28d172789f06886806bc55"`, just like summarized in @fd0 summed it up in his post right before this one. Just to be clear; I don't think there needs to be any options to the `--exclude-caches` in this case - if someone wants to adjust the name or contents of the CACHEDIR.TAG file, they should instead use the more proper `--exclude-if-present-` argument :)

By the way; I'm not sure why people call that CACHEDIR.TAG specification a *standard*. It's a specification, which the author named a standard in the title of the document, but what "official" organ actually dubbed this a standard? There's no RFC for it AFAIK. I'm open to being informed of the reasons this is an actual standard, but until then I'd say it's a proposed specification and at most a convention in *some* software.

It might sound like I'm grumpy but I just really don't like bad design and when I see it possibly going into clean and nice software like restic, I'm doing what I can to not make that happen in a bad way. I care a lot about clean code and interfaces. Let's hope we can settle on the suggested compromise/alternative implementation summed up by @fd0!

**Comment by fd0** [comment]
Ok, I decide we proceed this way:
 * Add `--exclude-if-present filename[:content]`
 * Add `--exclude-caches` as an abbreviation of `--exclude-if-present "CACHEDIR.tag:Signature [...]"

Thanks for all your input and thoughts!

**Comment by mathstuf** [comment]
FWIW, "it's ugly" is not a reason to not support a widely adopted specification (where there is nothing else). That leads to browsers being able to say "this JS API is stupid, we're ignoring it. As I said above, I don't care how it is supported, as long as it is. I think a config file with a stanza for it would be sufficient, but if that is coming later, an alias might be better.

**Comment by rawtaz** [comment]
There's a difference between these two things:

- Ignoring a specification because of whatever reason, and not implementing/offering something else, equivalent or better.
- Ignoring a specification because a better solution is implemented and offered, a solution that also takes into account the feature that is ignored (just with a different syntax on the command line, but still covering all of what the specification suggested).

I'm suggesting the latter of the above. It will provide 100% support for your CACHEDIR.TAG file, but in a much better way than the hardcoded approach. And it seems like you'll even get a shortcut to it (`--exclude-caches`).

So to me it seems you got exactly what you want :) But to answer your concern; If what you are offering is something better than and also compatible with what you are ignoring, then that's pretty okay of a reason to ignore it, no?

Yeah, let's hope someone takes the time to write config file support, assuming @fd0 supports that.

**Comment by fawick** [comment]
I'm going to update #1170 according to @fd0's decision.
