### ISSUE TITLE
Make IO-parallelism configurable

### ISSUE THREAD

**Issue by episource** [restic/restic#322]
**Restic version:**  5de36df 
**Observed behavior:**
IO-parallelism is hard coded. E. g. [defaultParallelism = 40 (checker.go:50)](https://github.com/restic/restic/blob/5de36dfdf09726287521f47b20b0c80a682c2a37/checker/checker.go#L50).

The hard coded parallelism might be well chosen for solid state disks, but is not always benefical and could slow down IO-operations or cause other issues. In practice I'm observing issues checking a repository on a samba/cifs mounted network location: IO errors due to NT_STATUS_INSUFF_SERVER_RESOURCES. Reducing [defaultParallelism (checker.go:50)](https://github.com/restic/restic/blob/5de36dfdf09726287521f47b20b0c80a682c2a37/checker/checker.go#L50) solves these issues but requires code changes.

**Expected behavior:**
IO-Parallelism should be configurable with a command line parameter. E. g. `restic --max-parallel-io 10 [...]`. This option should be available for backup, restore and check operations.

**Related:** Reducing IO parallelism might also resolve #313. Exhausting resource consumption as reported in #300, #316, #298 might also be related to high IO-parallelism.

**Comment by fw42** [comment]
Instead of exposing this to the user with a configuration parameter, I think it would be more useful to try to come up with an (automatic) way of determining an ideal value. This needs to be a sane (potentially automatic) default, but most users can't make an educated choice for this value by themselves and it will just make the command line user interface more confusing, imho.

**Comment by episource** [comment]
Consider splitting help output into a reduced basic and an advanced section: `restic help` shows a reduced basic help text where as `restic help --advanced` shows all available options. Any user happy with restic's defaults reads the reduced help section, only.

**Comment by fw42** [comment]
"Advanced settings" are a total anti-pattern, in my opinion. Sane defaults and convention over configuration are much more useful and lead to better usability in the long-term, in my experience.

**Comment by fd0** [comment]
I also don't like "advanced settings", however tempting that may be. I see you point @episource that there should be a way to either manually or automatically select the IO parallelism. #313 is not affected because the fuse backend doesn't limit the amount of parallel IO operations, that comes from the kernel.

**Comment by julianbrost** [comment]
We recently into the same issue on a VM host which doesn't have too much spare I/O performance. Running restic with its default parallelism (which now is 10) results in a significant overall performance degradation.

I don't think that automatically determining a level of parallelism will ever work in all cases, as one could try to optimize for fast backups (higher parallelism as long as the storage can handle it) or minimal impact on I/O performance (maybe even parallelism = 1).

Do you have any strong objections against adding a command line flag now? It could still be combined with some auto-detect mechanism for the default value in the future. If there's no way to control the level of parallelism, we would have to decide between maintaining a patched version of restic or not using it at all.

**Comment by pvgoran** [comment]
@julianbrost Did you try assigning IO priority to the restic process?

**Comment by julianbrost** [comment]
@pvgoran Yes, tried to run it with ionice. Solves the issue with high I/O load but the backup takes forever (about 24 hours instead of 5).

**Comment by fd0** [comment]
> Do you have any strong objections against adding a command line flag now?

Yes: first we need to finish the new archiver code (see #1494), then we can tackle this. I'll keep it in mind while writing the code.

**Comment by pmkane** [comment]
Just a +1.  The defaults for fileReadConcurrency and SaveBlobConcurrency aren't high enough for our systems.

Similarly, workerCount in restorer/filerestorer.go requires bumping up to extract the maximum performance from high throughput network interfaces and disks.

**Comment by whereisaaron** [comment]
I agree @pmkane I think the [hard-coded workerCount = 8](https://github.com/restic/restic/blob/master/internal/restorer/filerestorer.go#L24) is artificially slowing down our restores.

I don't think we should bust out any extra command line options until we are sure that they are useful and effective for everyday users. But we should be able to add various experimental `--options` keywords to enable runtime configuration of anything that might be useful for tuning. We could even prefix them so everyone knows the option could get deprecated, e.g. '--option restore.experimental.workercount=32`. The option names don't have to be short or pretty. Us tinkerers just want to be able experiment with tuning without recompiling every time.

@fd0 would you consider attaching tuning settings like this to `--options` keywords rather than hard-coding them? With just a sanity range check and a warning that these are 'at your own risk' settings?

**Comment by slava-vishnyakov** [comment]
Same here. I have a single core VM, restic just destroys it during backup. Loadavg spikes to 30+, system becomes totally unresponsive, even when run with `nice -n 19 ionice -c 3`

**Comment by cipriancraciun** [comment]
I'm using `restic` to backup some old HDD's (as in classical rotating disks) where the default parallelism just kills the performance due to the fact that the OS has to fetch files from all over the platter.

In my experience for such a use-case the best parallelism value is `1`, i.e. no parallelism...

So, a configurable flag would be nice.

----

Although not strictly related to this issue, but in my experience when reading multiple files in parallel, sorting by `inode` is a good compromise, because most likely files with "close" inodes were written "together".  Meanwhile for other "disks" (especially FUSE-based ones) where lexical ordering might cluster files together, having a random order works best.

For `ext4` one can even ask the file-system to indicate the first offset of the data on the disk, thus sorting by that one almost achieves the maximum bandwidth of the disk or array.

(I've implemented this in my `md5-tools`, if anyone is interested: <https://github.com/volution/md5-tools/blob/07b56d1393c451492e3ac3f8005cb3f6de6422ca/sources/lib/main_create.rs#L772-L785>.)

**Comment by MichaelEischer** [comment]
The concurrency for writing to the repository can be configured for all backends by now (not yet released).

**Comment by GrauBlitz** [comment]
> The concurrency for writing to the repository can be configured for all backends by now (not yet released).

Any update on this? I only can find information about the read concurrency in #2750 and [the docs](https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#file-read-concurrency).

Can I set both read and write concurrency to 1 with `local.connections`? I create HDD backups onto a HDD and the head is jumping all over the place and the performance is stagnating constantly...

**Comment by MichaelEischer** [comment]
`-o local.connections` controls the IO parallelism for the access to the repository, see https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#backend-connections . The read concurrency only applies to be the `backup` command.
