### ISSUE TITLE
Feature request: option to retry failed data exchange

### ISSUE THREAD

**Issue by cmeyer23** [restic/restic#3275]
Output of `restic version`
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Related to my issues in #3271 in which Backblaze B2 was serving corrupted data packs, it would be great if there was an option in restic to specify a number of times to retry downloading data from the repository in the event that the first attempt does not check out for consistency.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I am currently running a data consistency check on my repository (using `restic check --read-data`), and I am seeing many errors where the pack files checksums are not matching the expected values. However, if I manually download these packs again it seems, in every case so far, that the server is able to have fixed the errors for subsequent downloads. I would ultimately like to completely verify the consistency of the repository. With the current version of restic, it would seem to require another full `restic check --read-data` which takes a long time and costs a lot of download data. If instead I could specify a number of retries for each attempted data exchange, it is possible that the check might be able to correctly download the pack file within one execution of the `check` command, avoiding the need for another `check` which is going to re-validate a great deal of known-good data packs.

I can also foresee cases where `restore` and `prune` might become more robust if multiple attempts are made in the event of a consistency error.

The idea for this feature also comes from what I have seen with `rclone` in copying a large number of files to OneDrive, where many times the uploaded file checksum does not match the expected value, so `rclone` simply re-attempts the transfer a specified number of times. I'm not sure what verification `restic` performs on uploads, but presumably the retry-attempts feature would apply to uploads as well. I have never seen an upload fail with `restic backup`, so I don't know if this is because there is not an immediate consistency check on uploads, or if my uploads have just all been perfect, or if it is already doing a re-submit quietly behind the scenes.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is great and really I'm amazed at how graciously people respond to issues here. It gives me a lot of confidence in the tool and the community of support.

**Comment by MichaelEischer** [comment]
restic already retries failed uploads, there is also a PR to add fully integrity checks to the upload step #3246 . Downloads which fail to complete are also retried. The only missing part here is retrying downloads which are (partially) corrupted.

For `check --read-data` a stop-gap solution could be to just retry downloading pack files which fail to validate the first time. However, that would still have to ensure that possibly corrupted pack files are not served from the cache (this is related to #2533). 
For you current check run you could try PR #3203 which allows specifying which pack files to check.

There is also the question which type of data corruption restic should try to avoid: #2302 for example suggests to use the sha1 hash provided by B2 to verify file integrity (or alternatively check the files' sha256 hash). This would work for `check --read-data` or for files which are downloaded to the local cache as there restic downloads the full file and is thus able to the check it's hash.
However, this wouldn't solve the `incomplete pack file` errors caused by a broken download nor would is solve problems during `restore`. There restic only downloads a (small) part of the file which doesn't allow a full integrity check. Just retrying full downloads in case of a mismatching hash could be possible with reasonable complexity. However, extending retries for corrupted file parts to support all operations will require a few far-reaching changes.
