### ISSUE TITLE
Optimize garbage collector behavior

### ISSUE THREAD

**Issue by aawsome** [restic/restic#3328]
Output of `restic version`
--------------------------

restic 0.12.0 (v0.12.0-6-g70568c5b-dirty) compiled with go1.14.7 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

From time to time, users get trouble with memory usage of restic. There have been many improvements in the recent time which tackled the data structures and internal memory representation of those as well as algorithmic optimizations which also led to decreased memory.

However, in the forum there are still situations where users need to play around with the `GOGC` environment variable to squeeze out the least bytes of unused memory to let restic run successfully, see e.g. [here](https://forum.restic.net/t/restic-prune-runtime-cannot-allocate-memory/3660).

As restic is no real-time application, garbage collection runs do not hurt and can be done quite often without much trouble. So I want to discuss if we should implement more GC runs within restic. I can think of two approaches:

- Set the `GOGC` parameter to a (suitable) low value using [SetGCPercent](https://golang.org/pkg/runtime/debug/#SetGCPercent). This would however prevent users from manually setting it to an even lower value, if needed.
- Identify "critical" points in the program logic where a GC run would be able to remove lots of temporary used data and manually run `runtime.GC()`. This could be e.g. after loading the index into memory.

Both approaches can be implemented independently.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Optimize the memory usage profile. Improve the end-user experience. 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Keeps my data safe without any trouble for quite a long time now :+1:

**Comment by MichaelEischer** [comment]
> As restic is no real-time application, garbage collection runs do not hurt and can be done quite often without much trouble. So I want to discuss if we should implement more GC runs within restic. I can think of two approaches:

(soft) real-time application actually run the GC more frequent to avoid longer pauses. However, this increases the GC overhead, which is why batch applications traditionally use infrequent GC runs.

> * Set the `GOGC` parameter to a (suitable) low value using [SetGCPercent](https://golang.org/pkg/runtime/debug/#SetGCPercent). This would however prevent users from manually setting it to an even lower value, if needed.

It should be possible to only change the GOGC parameter, when it was not set by users.
 
> * Identify "critical" points in the program logic where a GC run would be able to remove lots of temporary used data and manually run `runtime.GC()`. This could be e.g. after loading the index into memory.

`runtime.GC()` might block the whole program, which could give the impression that restic hangs for a few seconds from time to time. Letting the Go runtime manage the GC overhead automatically seems much more manageable to me.

In any case we'd need some analysis on the performance impact this might have. The current memory-optimized index data structures contains lots of pointers which result in a lot of work for the GC (probably the mark phase).

**Comment by greatroar** [comment]
I think I've mentioned this before, but prune in particular could switch to a Bloom filter for keeping track of blobs in use. I've written a [Bloom filter package](/greatroar/blobloom) that is used for pretty much the same purpose in Syncthing. It allows capping either the false positive rate or the memory usage, and it's hash function-agnostic.

If it's acceptable that .0001 of unused blobs are erroneously kept, then blobs IDs can be stored in a Bloom filter using just 3.12 bytes per blob. That's a factor 10 smaller than the SHA-256s alone.

**Comment by MichaelEischer** [comment]
For prune it should also be possible to use a minimal perfect hashing function (MPHF) and combine that with a bit-vector which for each element states whether it should be kept or not (as for example in https://www.usenix.org/system/files/conference/fast17/fast17-douglis.pdf). In prune we can rely on the closed-world assumption that all blob ids are known beforehand just by looking at the index. And that makes it possible to construct and use a MPHF. However, I've no idea how complex these MPHF's are to implement.

It would be interesting to know how much memory restic uses over time. I'd expect the in-memory index to use the most memory, probably followed by the sets to track used and unused blobs.

**Comment by greatroar** [comment]
Re: MPH's, [go-boomph](https://github.com/dgryski/go-boomphf) makes them look pretty simple. However, its memory use is apparently not great, and the suggestions at dgryski/go-boomphf#3 for fixing them look like they'd introduce quite some complexity. (boomph doesn't do 32-byte keys and wants all its keys in an array, but that can be fixed.)

Otherwise, from scanning a few papers ([Botelho et al. 2012](https://www.itu.dk/people/pagh/papers/simpleperf-jour.pdf), [Botelho et al. 2013](https://www.usenix.org/system/files/conference/fast13/fast13-final100_0.pdf), [Limasset et al. 2017](https://arxiv.org/pdf/1702.03154.pdf), [Esposito et al. 2020](https://epubs.siam.org/doi/pdf/10.1137/1.9781611976007.14)), I get the impression that all state-of-the-art algorithms require rather large intermediate structures. Many of them are designed to use disk space.

**Comment by MichaelEischer** [comment]
> Otherwise, from scanning a few papers ([Botelho et al. 2012](https://www.itu.dk/people/pagh/papers/simpleperf-jour.pdf), [Botelho et al. 2013](https://www.usenix.org/system/files/conference/fast13/fast13-final100_0.pdf), [Limasset et al. 2017](https://arxiv.org/pdf/1702.03154.pdf), [Esposito et al. 2020](https://epubs.siam.org/doi/pdf/10.1137/1.9781611976007.14)), I get the impression that all state-of-the-art algorithms require rather large intermediate structures. Many of them are designed to use disk space.

I didn't look at how constructing these MPHs works before. But I guess you're right, it looks like it's necessary to sort / partition all entries at least once before building the MPHF.

**Comment by greatroar** [comment]
I did a very quick profile on a 700GiB repo that had already been pruned, so all blobs are in use. It shows that the indexMaps weigh in at nearly 40% of RAM usage (inuse_space), while the BlobSets in the function prune use more than 53%. So for the case where prune has little to do, optimizing those BlobSets makes sense (#3171?).

Aside from Bloom filters, it might be possible to cut the peak RAM usage by employing another custom chaining hash table, one that allows transferring entries from one table to another:

```go
type BlobSet struct { /*...*/ }

type BlobSetEntry struct { /*...*/ }

func (s *BlobSet) Delete() *BlobSetEntry
func (s *BlobSet) Insert(e *BlobSetEntry)
```

**Comment by greatroar** [comment]
I got something like this working last night, taking snippet of code from the indexMap, but with a method

```go
func (s *BlobSet) Move(b BlobHandle, other *BlobSet) bool
```

instead of a separate entry type. This requires some more updates around the codebase, but the first result is that putting 1e7 BlobHandles in a set allocates 547MiB vs. previously 1.36GiB. It's about 80% slower than before.
