### ISSUE TITLE
Windows: $ needs to be escaped in exclude file

### ISSUE THREAD

**Issue by C-Otto** [restic/restic#3329]
`restic 0.12.0 compiled with go1.15.8 on windows/amd64`

I'm running restic on a regular Windows 10 machine:

`restic.exe -r b2:foo:bar backup --use-fs-snapshot --exclude-if-present .nobackup --exclude-file C:\foo\exclude.conf C:\`

The exclude file contains a single line "C:\\$Recycle.bin". With this file, I still see files from that excluded directory being backed up.

As soon as I change this to "C:\\$$Recycle.bin", the files are excluded.

This is not documented, and doesn't make any sense to me (there is no $ substition in files, or in the windows CMD thingy).

**Comment by rawtaz** [comment]
It's expected behavior (in the sense that it's by design) and documented here: https://restic.readthedocs.io/en/stable/040_backup.html#excluding-files

*"Environment-variables in exclude files are expanded with [os.ExpandEnv](https://golang.org/pkg/os/#ExpandEnv), so `/home/$USER/foo` will be expanded to `/home/bob/foo` for the user `bob`. To get a literal dollar sign, write `$$` to the file."*

I do agree that it's a bit misleading in the sense that it says *environment variables* are expanded, so one could think that if there's no environment variable matching e.g. `$Recycle` (like in your case), no expansion should be attempted. But that's probably not how it works - if it sees a `$`, it tries to expand it, and if there's no matching environment variable, it results in the empty string.

The latter is mentioned in the documentation linked to in the quote:

*"ExpandEnv replaces `${var}` or `$var` in the string according to the values of the current environment variables. References to undefined variables are replaced by the empty string."*

So yeah, the documentation should be slightly adjusted to make this clearer.
