### ISSUE TITLE
File change detection on windows

### ISSUE THREAD

**Issue by Hoffenbar** [restic/restic#3353]
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on windows/amd64 (did not matter here, though)

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
From the docs: "On Windows, a file is considered unchanged when its path and modification time match, and only --force has any effect. The other options are recognized but ignored."
This is critical. What if someone changed the file and restored the modification time thereafter? That is a common practice e.g. for photos (when altering exif comments), where it's sometimes good to not rely only on exif timestamps, but keep the photos in cronological order in the filesystem already. So file size diffs must be taken into consideration, too. To be 100% sure to grab a changed file, one have to use checksums, but that would be super slow.... or maybe some filesystem internal flags of which I'm not aware right now....

What are you trying to do? What problem would this solve?
---------------------------------------------------------
I want to be sure that a file which content have changed is included in a snaphot, even if it looks unchanged at first glance.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Still testing it, and already using it in some scenarios. Very usefull!

**Comment by greatroar** [comment]
Actually, the size is taken into account, despite what the manual says. But when path, size and LastWriteTime match, you really need to use --force with current restic. This is exactly what it's for :)

Regarding possible optimizations, I don't see other information to go on in [windows.Win32FileAttributeData](https://pkg.go.dev/golang.org/x/sys/windows#Win32FileAttributeData).

An optimization that would work for some file formats would be to check the first chunk of a file and say "unchanged" when it matches what is in the parent backup. But that can still be expensive because an average block is 4MiB.
