### ISSUE TITLE
Google reports a GoVuln GO-2020-0018 github.com/satori/go.uuid 

### ISSUE THREAD

**Issue by LawrenceTattrie** [restic/restic#3417]
Output of `restic version`
--------------------------
12

How did you run restic exactly?
-------------------------------
This is not a runtime error. This is a source analyzer saying there is an issue

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
N/A for repository but 
[](https://www.theregister.com/2021/06/04/google_open_source_insights/)
says there is a google source analyzer which looks for dependency issues. So I thought why not try it on Restic:
 Google online 
https://deps.dev/advisory/GoVuln/GO-2020-0018?from=%2Fgo%2Fgithub.com%252Frestic%252Frestic
Expected behavior
-----------------
No dependent problems

Have no dependent problems

Actual behavior
---------------
There seems to be an older version of go.uuid that should be replace with a newer version.

There is a description of a problem which might occur:
"UUIDs generated using [`NewV1`] and [`NewV4`] may not read the expected number of random bytes. These UUIDs may contain a significantly smaller amount of entropy than expected, possibly leading to collisions."

Steps to reproduce the behavior
-------------------------------

open [](https://deps.dev/) type in "restic" select github.restic and run
Do you have any idea what may have caused this?
-----------------------------------------------
Slightly old version of uuid.

Do you have an idea how to solve the issue?
-------------------------------------------
Recompile with new version

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Wonderful backup. Less worry when Microsoft does a Windows update.

**Comment by vielmetti** [comment]
satori/go.uuid is not a direct dependency; it's brought in by the version of github.com/azure/azure-sdk-for-go that's in use by restic. The azure-sdk is available in a newer version which addresses this vuln, but I'm not sure about compatibility issues.

**Comment by vielmetti** [comment]
Looks like there's work being done in https://github.com/restic/restic/pull/3407 to address this.

**Comment by greatroar** [comment]
False alarm. The bug was introduced in satori/go.uuid@0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c, which is *after* the 1.2.0 that restic uses. That commit was never in any tagged version. See also the analysis from the folks at [Red Hat](https://bugzilla.redhat.com/show_bug.cgi?id=1954376).

**Comment by LawrenceTattrie** [comment]
Perhaps not "False Alarm" but is work to do? The Red Hat link shows comments:

> I've started a discussion on github.com/satori/go.uuid repo if that project should be used currently and everyone confirmed that this project was dropped long time ago. Everyone who use it in their code should switch to https://github.com/gofrs/uuid which is a fork to github.com/satori/go.uuid and is still supported.
So Engineering should be aware about this and stop using github.com/satori/go.uuid in favor of https://github.com/gofrs/uuid

**Comment by LawrenceTattrie** [comment]
Dang. Closed it but should not have. Will stop pushing buttons.

**Comment by greatroar** [comment]
There is nothing to do. v1.2.0 is perfectly safe. It's also the last version that has the API we need, so we can't upgrade to either a later commit or the version from gofrs (`uuid.NewV4` got an error return value, breaking the Azure SDK that uses it).

That Azure SDK should be replaced because it's outdated, but that's a separate issue.

**Comment by greatroar** [comment]
Here's my analysis of the situation:

* In v1.2.0, uuid.go gets randomness from the [safeRandom](https://github.com/satori/go.uuid/blob/f58768cc1a7a7e77a3bd49e98cdd21419399b6a3/generator.go#L199-L203) method, which calls crypto/rand.Read. That calls io.ReadFull, meaning it always returns an error if it gets too few bytes. Any such error causes safeRandom to panic.
* In satori/go.uuid@0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c, the RNG code was changed to use crypto/rand.Reader.Read, without the author noticing the difference in semantics (Reader.Read may return too few bytes without an error). This lead to satori/go.uuid#73, which was fixed by merging satori/go.uuid#75.
* Between the submission and acceptance of 75 (which took from April to October 2018), the author of that PR also erroneously filed a CVE for v1.2.0, even though the bug was introduced afterwards. The example code at 73 shows that they were using the new API; it doesn't even compile with v1.2.0 (that's satori/go.uuid#111).

**Comment by MichaelEischer** [comment]
I agree with the analysis of @greatroar . Instead of switching to a maintained variant of the `uuid` packages, let's just wait for #3407 to remove that dependency.

**Comment by MichaelEischer** [comment]
We've updated the dependencies in #3454 so this should be solved even though #3407 is not yet ready for merging.
