### ISSUE TITLE
Add restic to Wikipedia article on backup software?

### ISSUE THREAD

**Issue by schoettl** [restic/restic#3445]
https://en.wikipedia.org/wiki/List_of_backup_software

I could also quickly do it, if someone experienced provides the missing information:

Name: restic
License: BSD
Written with: Go
Runs on Windows
Runs on macOS
Runs on Linux
Has a GUI?
Has a CLI? yes
Last updated: June 2021

**Comment by yorkday** [comment]
There are some more answers here:
https://restic.net

Name: restic
License: BSD
Written with: Go
Runs on Windows: Yes
Runs on macOS: Yes
Runs on Linux: Yes
Has a GUI?: No
Has a CLI? Yes
Last updated: February 15, 2021 (suggest only going off latest released versions)

**Comment by schoettl** [comment]
Thanks. Added to wikipedia though I didn't specify specific GUIs.

**Comment by yorkday** [comment]
The Wikipedia edit has been removed as there is no dedicated page for rustic.  Suggest working within Wikipedia guidelines to get this addressed.

**Comment by schoettl** [comment]
Note: the revert of my change on wikipedia can be undone when an Wikipedia article for restic exists. I suggest
- restic or
- restic (backup software)

**Comment by rawtaz** [comment]
Already tried that (and in fact it was for the very same purpose as is being discussed here, to be able to link to it from that list of backup software on Wikipedia).

I wrote an informative, non-advertising, unbiased and well formatted article about restic, including sources that were prominent and notable as references to show that it was "a thing" out there in the real world. I made sure everything was according to article guidelines. Despite this, some editor refused the article, saying that it was lacking notable sources. Yeah right..., especially considering there's an endless ton of articles on Wikipedia that are lacking in both formatting, substance and references/sources more or less entirely. Having spent I think five or more hours on that article, I gave up and realized that Wikipedia moderation is highly inconsistent and there's little use in spending energy to write articles for Wikipedia. I didn't give up because of lack of effort, I gave up because there was really nothing more that could be reworked in the article. It was highly polished, and most references were indeed notable (at least to someone who knows what sources are notable in the field or context at hand - I guess the moderator didn't).

**Comment by kamillentee** [comment]
@rawtaz Seems like bikeshedding could be helpful to get your article released on wikipedia ;)

**Comment by schoettl** [comment]
Oh man, that's really annoying. I guess some moderators (not only wikipedia) just love the feeling of power. Hope your article gets released some day!

**Comment by rawtaz** [comment]
My article is no longer :) If someone wants to write one and see if it gets accepted by Wikipedia by all means go for it. But please try to formulate it such that we don't have to keep it up to date in a ton of places (e.g. version numbers, specific features, etc).

**Comment by ProactiveServices** [comment]
Before anyone else jumps into trying to bring back rawtaz's hard work, I strongly advise you to read up on the site's guidelines for independent sources, conflicts of interest et al. If you've ever contributed to an open source project in any way, then you automatically have a conflict of interest, according to their rules. You'll find that after spending hours poring over their guidelines (that often enjoy circular references and outright contradictions) it is not worth trying.

**Comment by fd0** [comment]
I'm closing this issue, it's not worth spending time on :)
