### ISSUE TITLE
some design questions

### ISSUE THREAD

**Issue by thkoch2001** [restic/restic#347]
Hi, saw the froscon restic talk and want to compare it to obnam which I'm currently using. I've some questions about the design. I'd have written this in a mailing list if there'd be one.?.

## Why packfiles?
What is the advantage of having packfiles instead of mapping one backed up file to one blob file? In Git packfiles combine similar files and thus reduce storage size. But this is not the case with restic packfiles. I guess it's about avoiding the overhead of seeking to many small files?

How do you decide which files to combine into one packfile?

## Why json?
Json as the format for index and tree files seems to be too verbose. Why not use a binary format here too? Or at least an ASCII based format like git trees?

## What's in the content array in trees?
The design document says that the content field of a tree node "contains a list with one plain text SHA-256 hash". Shouldn't this rather say that it contains a list of chunk hashes? Otherwise where is the mapping from the plain text hash to the hashes of the content chunks?

## Leaking content hashes?
It seems that an attacker with read access to the repository can find out, whether the repository contains the backup of a file with a certain SHA-256 hash if the data blob for this file is not contained in a pack. This could easily be avoided with "another layer of indirection" :-) by using arbitrary ids for the data blobs and encrypted index files that map hashes to data blobs. This would also allow to upgrade hash algorithms without the need to rewrite the whole repository.

## why not use uuid for the repository id?
Git annex uses uuids for the repository ids too. This might not make any difference, just caught my eye.

## version number might not be enough
Git annex also uses a version number to signal the features of a repository. In the end this is not enough and now it stores which features or configs are used in a particular repository.
https://git-annex.branchable.com/devblog/day_248__workload_tuning/

## authenticated?
What does it mean, a blob is "authenticated"? Same for the pack header? Why is it necessary?

## pack CRC over plaintext?
I understood the the MAC of data files is over the encrypted data. Thus the integrity can be checked without decrypting the data? In Pack files however the MAC is over the plain text? Why is this different. So one needs to decrypt the blobs in the pack file to verify them?

## Explain Crypto algos
Please explain or link to explanations about the used encryption, hash and CRC algorithms. Especially the following seems to be needed to understand restic:
- What's an initialization vector?
- What's Poly1305-AES?
Of course I found good informations in the net, but maybe you could give a summary of the parts that are important in the context of restic.

## gpg instead of password?
Wouldn't it be saver to use gpg to encrypt the keys files instead of just a user password? GPG can also encrypt to multiple recipients and thus a repository can be used from different machines with different GPG keys. Obnam does it that way.

Thank you for this interesting project! Good luck!

**Comment by fd0** [comment]
Hi,

thanks for your interest and questions, I'll try to answer them.

> I'd have written this in a mailing list if there'd be one.?.

Yeah, there isn't one. I did use mailing lists years back, but found that most people are not able to. In addition, I felt like handling another channel too much work (besides the GitHub issues and the IRC channel). So there isn't one.

> What is the advantage of having packfiles instead of mapping one backed up file to one blob file? In Git packfiles combine similar files and thus reduce storage size. But this is not the case with restic packfiles. I guess it's about avoiding the overhead of seeking to many small files?

Exactly. I started without pack files and measured that the overhead per blob (or small file) was huge, so pack files were introduced.

> How do you decide which files to combine into one packfile?

First, that's not on the "file" level, but rather on the "blob" level. Archiving a file means splitting it into blobs (by means of the CDC, see [this blog entry](https://restic.github.io/blog/2015-09-12/restic-foundation1-cdc/).

Afterwards, the blobs are collected and grouped into pack files as they come. There are a few rules (not more than 200 unfinished packs, where a pack is written to the repository and finished when it is between 4 and 16 MiB in size), you can find the code here: https://github.com/restic/restic/blob/master/repository/repository.go#L217

> Json as the format for index and tree files seems to be too verbose. Why not use a binary format here too? Or at least an ASCII based format like git trees?

JSON was deliberately chosen because of it's verbosity and widespread use. I think that this helped in quite a few places during development. A custom format was out of the question, I didn't want having to write my own encoder/decoder, and JSON was readily available in the Go standard library.

> What's in the content array in trees?

A file is split into blobs by the chunker (see blog article above) and these blobs are identified by their sha256 hash. So a file's content can be described by the list of sha256 hashes of the blobs it consists of. That's what in the `content` list is stored.

> The design document says that the content field of a tree node "contains a list with one plain text SHA-256 hash". Shouldn't this rather say that it contains a list of chunk hashes?

In the example you're talking about a directory contained one file called `testfile` which consists of only one blob of data, identified by its sha256 hash. You can think of this as the "ID" of the chunk. I think the wording is appropriate here.

> Otherwise where is the mapping from the plain text hash to the hashes of the content chunks?

The JSON structures always reference plaintext sha256 hashes (e.g. the hash of a blob of data, or the hash of the JSON representation of a tree). There is no explicit "mapping". In order to enable restic to find the plaintext blobs without having to download everything and re-calculating the sha256 hash, the list of plaintext hashes of the blobs in a pack is contained in the header of the pack. These are contained in turn in the index files.

> It seems that an attacker with read access to the repository can find out, whether the repository contains the backup of a file with a certain SHA-256 hash if the data blob for this file is not contained in a pack.

I'd be very surprised if that's possible. The plaintext sha256 hashes contained in the index files and the pack file's header are both encrypted, so attackers who do not know the password cannot decrypt anything. Did you read that the header of the pack is encrypted by itself? Did I miss something?

> This could easily be avoided with "another layer of indirection" :-) by using arbitrary ids for the data blobs and encrypted index files that map hashes to data blobs.

And this would also add a lot of unnecessary code complexity. I like to keep it simple where ever possible.

> This would also allow to upgrade hash algorithms without the need to rewrite the whole repository.

When such a drastic change like replacing the hash algorithm is needed, I think it may be warranted to rewrite the whole repository. I don't think that this is necessary in the foreseeable future, so I decided again to keep it simple.

> why not use uuid for the repository id?
> Git annex uses uuids for the repository ids too. This might not make any difference, just caught my eye.

Yeah, it's entirely possible to use a uuid. But in most cases (and I suspect that it's the case for obnam too), random uuids are used. And what's the real difference to 32 random bytes, except the peculiar formatting (with the dashes)?

> version number might not be enough
>
> Git annex also uses a version number to signal the features of a repository. In the end this is not enough and now it stores which features or configs are used in a particular repository.

Restic will not be configurable in every detail, but provide sane defaults that will work almost all users instead. When at some point in the future we need a new format, we'll increase the version number (and keep it backwards compatible).

> authenticated?
>
> What does it mean, a blob is "authenticated"? Same for the pack header?

A blob is authenticated because its ciphertext is "signed" with a message authentication code (MAC), so restic can authenticate the ciphertext ("verify its signature"). 

> Why is it necessary?

This is done so that no modified ciphertext is ever attempted to be decrypted or otherwise handled by complex functions. The restic threat model includes attackers that are able to modify files stored in the repository, and restic needs to be able to detect such tampering.

> pack CRC over plaintext?

I don't know what you mean. CRC is not a replacement for a MAC, and CRC isn't used anywhere in restic.

> I understood the the MAC of data files is over the encrypted data. Thus the integrity can be checked without decrypting the data?

Exactly.

> In Pack files however the MAC is over the plain text? Why is this different. So one needs to decrypt the blobs in the pack file to verify them?

That's wrong. Pack files a are a concatenation of encrypted blobs and an encrypted header, that's it. If the contents of a blob is to be verified, restic indeed needs to download and hash it.

> Explain Crypto algos
>
> Please explain or link to explanations about the used encryption, hash and CRC algorithms. Especially the following seems to be needed to understand restic:
>
>     What's an initialization vector?
>     What's Poly1305-AES? Of course I found good informations in the net, but maybe you could give a summary of the parts that are important in the context of restic.

I'm sorry and I really don't mean to sound harsh, but this is not a crypto 101 course and the design document isn't there to explain basic crypto vocabulary. An IV is a standard concept in cryptography and for the MAC algorithm the paper by Bernstein is linked, this is enough.

If you are not familiar with such basic concepts as an IV, the restic design document is never able to teach you all the (subtle) things that you need to know. There great introductions out there, please read them.

> gpg instead of password?
>
> Wouldn't it be saver to use gpg to encrypt the keys files instead of just a user password? GPG can also encrypt to multiple recipients and thus a repository can be used from different machines with different GPG keys. Obnam does it that way.

I've deliberately decided to stay away from GnuPG, although I use it regularly. The user interface is plain bad for new users and hard to use the right way. In addition, this introduces complexity and a dependency that I'd like to avoid. When you're trying to restore a backup because your hard drive just failed, you wouldn't want to fiddle around with your gpg setup.

If your questions are answered, please close this issue.

**Comment by fd0** [comment]
I'll close this for now, if you have other questions feel free to add a comment to this issue :)
