### ISSUE TITLE
Returns "permissions" on "ls" command

### ISSUE THREAD

**Issue by gallofeliz** [restic/restic#3542]
Output of `restic version`
--------------------------

0.12.1

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

restic ls with json output returns a "mode" property that is "Go" value. I need to have a standart property like "drwxr-w---" for example like the find command with a property called "permissions".

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I am developing a web frontend and this app give ability to list snapshots, show files, etc. I am not able today to display the permissions of files/directories.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

You love flowers :) Yes, I am developing a full backup app with a lot of features (repositories definitions, backups definitions, scheduling, watching, hooks, etc), but 95% of the job is made by restic. I investigated to find the backup of love but only restic has the flexibility I search. The world is better thanks to guys like you ! Congratulations !

Notes : original thread in https://forum.restic.net/t/restic-ls-understanding-file-mode-with-json/4371

**Comment by magandrez** [comment]
Hi,

May the below serve as a recap of the original thread linked above:

1. `restic ls --json` outputs filesystem permissions and additional modes (_setuid_ bit, _setgid_ bit, and _sticky bit_) in [numeric notation](https://en.wikipedia.org/wiki/File-system_permissions#Numeric_notation). That is, `"uid":1000,"gid":1000,"mode":2147484157`, where `"mode": 2147484157` is the numeric notation of the permission for a folder in the file system, as opposed to e.g.: `"mode":666` which would be the numeric representation of a permission for a file in the filesystem.
2. `restic ls` outputs filesystem permissions and additional modes using [symbolic notation](https://en.wikipedia.org/wiki/File-system_permissions#Symbolic_notation).
3. @gallofeliz would like `restic ls --json` to be consistent with `restic ls` that is, provide symbolic notation aside from the already present numeric one.
4. @torfason proposed that the JSON output for `restic ls` contain an extra item `"unix_infostring":"-rwsr-xr-x"` to represent the permission-and-mode information, on top of the already existing `mode`, `gid` and `uid`.
5. @rawtaz proposed to name the extra item mentioned above as `perms` instead of `unix_infostring`.

@gallofeliz @MichaelEischer is this correct?

If my understanding is correct, I would like to have a knack at this issue. I would suggest to implement it as @torfason has suggested with the naming proposed by @rawtaz.

**Comment by gallofeliz** [comment]
@magandrez, what I suggest is "ls" to be like "find". Please see an example :
```
sudo RESTIC_REPOSITORY=test/repositories/app2 RESTIC_PASSWORD=bca restic find test.txt --json | jq
```

partial outputs :
```
[
  {
    "matches": [
      {
        "path": "/sources/test.txt",
        "permissions": "-rw-rw-r--",
        "type": "file",
        "mode": 436,
        "mtime": "2021-10-01T12:38:04.55868911Z",
        "atime": "2021-10-01T12:38:04.55868911Z",
        "ctime": "2021-10-01T12:38:04.55868911Z",
        "uid": 1000,
        "gid": 1000,
        "user": "node",
        "group": "node",
        "device_id": 64769,
        "size": 11,
        "links": 1
      }
    ],
    "hits": 1,
    "snapshot": "21f18a8fffa22da851e3430097a88267532c169c83b6cbd711373c71ed4ef4e0"
  }
]
```

As you can see, in "find" command, there is already "permissions" property. I suggest to do the same with "ls".

Regards

**Comment by magandrez** [comment]
>what I suggest is "ls" to be like "find" [...]

@gallofeliz that's my aim.

**Comment by torfason** [comment]
Using `"permissions"` and aiming for as much consistency as possible between `ls` and `find` sounds awesome :-)
