### ISSUE TITLE
Mount in windows

### ISSUE THREAD

**Issue by tigerclawn82** [restic/restic#361]
Hi,
   As instructed in the User Manual, i have snapshot created and backup repository available. When i tried to mount the repository it gives following error.

```
D:\Workspace\Go-Ide\GOPATH\src\restic>restic.exe version
restic 0.1.0 (v0.1.0-148-g2c95772)
compiled at 2015-11-25 18:53:15 with go1.3.1

D:\Workspace\Go-Ide\GOPATH\src\restic>restic.exe -r D:\Restic-Backups mount D:\Restic-Mount
Unknown command `mount'. Please specify one command of: backup, cache, cat, check, find, init, key, list, ls, optimize, rebuild-index, restore, snapshots, unlock or version
```

Any help would be appreciated. 

Thanks

**Comment by fd0** [comment]
Unfortunately it is not possible to mount the repository on Windows. I'll add that to the manual.

**Comment by tseel** [comment]
Dokan (https://dokan-dev.github.io) provides a fuse library on windows which can be used.

**Comment by Matroschker** [comment]
I tried to use Dokan 1.0.0 on Win 10 Pro for mounting, currently I run into an [error](https://github.com/dokan-dev/dokany/issues/177).

**Comment by fd0** [comment]
I don't use windows and I have no idea what's happening here, sorry.

**Comment by Matroschker** [comment]
Ok, but can you explain what to mount exactly with dokan? Restic creates a directory structure, should be mounted the root folder or maybe the data folder?

**Comment by fd0** [comment]
As  far as I can see, dokan is a library for windows which implements something similar to fuse, but is not directly compatible.

For restic this means that someone needs to add the library to restic and write code to handle the dokan-specific file-system abstraction. I'm not using Windows, so someone else needs to step up to implement this.

Until dokan support is added to windows, this won't work.

**Comment by Liryna** [comment]
Hi @fd0 

It is true that dokan have is own file-system abstraction but also provide a FUSE wrapper.
Does restic use FUSE ? If it is the case, restic will have to be build with cygwin against the dokanfuse.dll and it should work by is own.

As exemple, there is a FUSE Mirror FS that is include in the repository that come directly from the libfuse repository that worked with dokanfuse.dll without changes.

**Comment by fd0** [comment]
If I understood the documentation correctly (sorry, only had a quick glance today), dokan is "API compatible" to fuse. Which means that when a project uses the original fuse API provided by libfuse, you can probably just compile it against dokan instead of fuse and it works.

However, restic does not use libfuse, but a Go implementation of the fuse protocol, as it is spoken between the userland program and the Linux kernel. So there is no libfuse in use in restic, therefore the compatibility layer can not be used.

I can understand that it would be neat to have a "drive" in windows that contains the backup data. But unfortunately until someone else steps up to implement it, this won't happen. Maybe #60 will help here.

In general, I'd like to avoid C libraries and keep restic in pure Go. Linking against e.g. dokan will have to be discussed before somebody implements it.

**Comment by Liryna** [comment]
Oh Ok I see thank for the clear answer. 

You are right, since bazil/fuse is directly talking to the kernel it is not possible to make it work with dokan.
