### ISSUE TITLE
As a user, I would like restic-backup to ignore EOL comments

### ISSUE THREAD

**Issue by sudoforge** [restic/restic#3705]
Output of `restic version`
--------------------------

```
restic 0.13.0 compiled with go1.18 on linux/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

When [collecting targets][0], `restic-backup` currently ignores lines that begin with a hash mark (`#`, aka pound sign/hashtag sign). I would like comments at the end of a line to be ignored, as well, such as:

```
# this line is ignored
/some/path/to/backup.foo
/another/path/to/store.bar # this comment will be interpreted as part of the filename
/bar/baz/potato.conf
```

What are you trying to do? What problem would this solve?
---------------------------------------------------------

My restic configuration is included in my dotfiles repository, which is exported out from a monorepo. I have a utility in that export process that supports stripping lines from files, so that I can explicitly remove lines during the export, preventing them from being available in the public destination.

Currently, to strip a specific line from my restic configuration, I need to do this:

```
# blah_blah:strip_begin
/some/private/path/foo.conf
# blach_blah:strip_end
/some/public/file.path
```

This is a minor inconvenience, since the tool supports stripping away lines that have a particular comment at EOL. It would be nice if `restic` played along with this, such as allowing:

```
/some/private/path/foo.conf # this comment should be ignored, but the path parsed
/some/public/file.path
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic helps me sleep soundly each and every night. Thank you for creating and maintaining what is, in my opinion, the _best_ deduplicating backup tool -- and keeping it open source!

[0]: https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L407

**Comment by fd0** [comment]
Thanks for leaving an issue for this!

The underlying problem here is that we cannot really know how users name their files and folders, so there may well be a folder called `foo # bar`. How do we escape that? I don't think we can just use a regex here. And then we'd create a change (with introducing EOL comments) that would require users to look at their include files and escape any `#` that really should be there.

I must say that I'm not convinced that this is a good idea, and I don't like the complexity it introduces compared to solving what you called a minor inconvenience.

**Comment by sudoforge** [comment]
yeah, i was talking this over with some colleagues and i came to the same conclusions - closing this.
