### ISSUE TITLE
Auto forget policy (keep-last) does not drop snapshots that are superseded by newer, larger snapshots

### ISSUE THREAD

**Issue by adam-ah** [restic/restic#3708]
Output of `restic version`
--------------------------
`restic 0.9.6 compiled with go1.12.12 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
sudo restic -r  /backup/backups/restic-repo forget --keep-last 2 --prune -p /pwlocation/resticpassword
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Locally mounted drive

Expected behavior
-----------------

When using the `keep-last` option restic should drop snapshots are superseded by new, larger snapshots, i.e., snapshots that contain folders from the old snapshots plus additional folders.

Very briefly, if the snapshots contain folders like this: 
Snapshot 1 folder `a`
Snapshot 2 folder `a, b`
and I want to keep the 'lastest only', then restic should drop Snapshot 1 as  Snapshot 2 contains the latest `a` as well. 

Actual behavior
---------------

Restic appears to identify the 'latest' snapshots only if they contain the same exact folders. Therefore, if adding new folders to the backups, old snapshots are never deleted. This is unexpected and can cause actual disk quota issues if not monitored closely. Adding new folders to the backup is expected.

Also, the **current behaviour goes against the recommended approach** of backing up multiple folders:

> fd0 Aug '17 It doesn’t really make any difference if you backup the folders separately or not
> ... If you’d ask me, I’d backup the folders in a single backup. 

source: https://forum.restic.net/t/how-to-properly-backup-multiple-folders/73/2

Given the problem described above, the recommendation should be to **add each folder to a separate backup** otherwise you cannot apply the auto-forget features.

Steps to reproduce the behavior
-------------------------------

- Create a backup with a set of folders
- Include additional folders to the backup
- Ask restic to keep the last N
- Old snapshots are never remove

Actual output from the server:

```
forget --keep-last 2 --prune
```
After running
```
8888f32f  2022-01-22 03:00:08  server-name             /etc
                                                       /home/user
                                                       /var/www

d9bd0316  2022-02-05 03:00:08  server-name             /etc
                                                       /home/user
                                                       /var/www

0cbc811f  2022-02-12 03:00:08  server-name             /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www

765fffb8  2022-02-19 03:00:08  server-name             /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www

c9be6720  2022-04-09 03:00:02  server-name             /new-added-folder
                                                       /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www

f47a7155  2022-04-10 18:11:29  server-name             /new-added-folder
                                                       /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www
```

Do you have any idea what may have caused this?
-----------------------------------------------

Did not go through the code.

Do you have an idea how to solve the issue?
-------------------------------------------

Did not go through the code.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I was happy when I discovered where all my disk-space is gone :)

**Comment by rawtaz** [comment]
I think there's just a slight misunderstanding about how the forget policies apply.

Restic first grabs the list of all snapshots and *groups* the snapshots into one or more groups depending on the hostname, tags and paths of each snapshot. By default it creates one group for every unique combination of hosts and paths (see `restic help forget` and the `--group-by` option there).

It then applies the specified policy (in this case `--keep-last 2` which means "keep the last two snapshots") to the snapshots in each group *separately*.  So the policy in this example effectively becomes "keep the last two snapshots in every group".

In your example above, you can see that you have the same server-name, no tags, and three unique combinations of paths in your snapshots. Hence, there will only be three (unique) groups of snapshots when forgetting, since it's only the paths of the snapshots that are different in this example.

The result is as you can see in your example output that for each group restic keeps the two most recent (last) snapshots.

Please see https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy for more information about this, and alos note that you can change which of host, tags and paths you want restic to use when grouping the snapshots, by making use of the `--group-by` option to the `forget` command.

**Comment by rawtaz** [comment]
> I have 6 snaphots, as per above, even though I asked to keep the last 2.

If you want that, add `--group-by host` and you will get what you want.

There's plenty of use case for grouping the snapshots, and removing that default behavior is neither an option nor a good idea. Imagine for example the following:

- You back up server A and B to the same repository, and it just so happens that you get the following list of snapshots as they go (note the different hostnames):

~~~
8888f32f  2022-01-22 03:00:08  server-A                /etc
                                                       /home/user
                                                       /var/www

d9bd0316  2022-02-05 03:00:08  server-A                /etc
                                                       /home/user
                                                       /var/www

0cbc811f  2022-02-12 03:00:08  server-B                /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www

765fffb8  2022-02-19 03:00:08  server-B                /etc
                                                       /home/user
                                                       /var/lib/docker/volumes
                                                       /var/www
~~~

- If restic did *not* group snapshots by default before applying the forget policies, and you ran forget with just `--keep-last 2`, you would end up with having only snapshots from one of the servers left after the forget command completed.

You might feel that this isn't an issue for you if you never back up more than one system to one and the same repository, and that's fine. But there's a reason for the design decision here, and it's in line with how restic tries to be as safe and proactive as possible in its defaults. In other words, it errs on the side of caution, which in the example above means to apply the policy to the groups rather than to everything. To quote the docs, "This is a safety feature to prevent accidental removal of unrelated backup sets".

It's clear in the documentation that grouping is done, but I think that the help text from `restic help forget` is quite bad for the `group-by` option, so we'll fix that. Other than that, the grouping which is the cause for what you feel is unexpected is very much by design, so I can't really agree that it's a bug, it works as intended. If there's anything to improve, it's the help text.

**Comment by adam-ah** [comment]
> If you want that, simply add --group-by host and you will get what you want.

Sorry, you already lost me here - I have exactly 1 host, group-by host cannot (and should not!) make any sense if I have a single host. Sounds like another _very_ surprising feature?

**Comment by rawtaz** [comment]
Are you even reading what I am explaining to you? You seem to think that your use case and situation here is the only one in the entire world. There are other users and other use cases than your specific use case.

As I've explained to you, the way the forget command *groups* snapshots *before removing them* is *highly intentional* and is a precaution. It's not going to change, sorry. But we will review the help texts, I completely agree that there's a need for improvement there.

**Comment by fd0** [comment]
> Sorry, you already lost me here - I have exactly 1 host, group-by host cannot (and should not!) make any sense if I have a single host.

By default, `restic forget` groups snapshots by the hostname and the set of paths. By specifying `--group-by host` you can tell restic to only group by hostname, which in your case means that it will consider the snapshots to be in one big group, despite the different set of paths.

In general, for a crucial operation such as `forget`, restic is written to be as conservative as possible. That's why it considers backups to be in different groups if the set of paths is not exactly the same. Consider the failure cases (e.g. for users who haven't read the docs and haven't looked at the actual output of `restic forget` in a while): removing snapshots (and the referenced data) unintentionally is usually much worse than running into a disk-full condition.

It was very surprising for me to discover that snapshot remove policy handling was super complex and way more complicated to get right than I imagined. We can for sure improve the documentation but I'm not convinced that it is a good idea to change the default grouping behavior. Even trying to be clever and grouping snapshots into the same group if the list of paths is a strict subset of other snapshots is not a good idea in my opinion.

**Comment by rawtaz** [comment]
Just a small side note on this topic; One can effectively disable grouping by using `--group-by ''` (that is, an empty value). This makes the policy be applied to all snapshots as one big pile.
