### ISSUE TITLE
Feature: diff between two repos

### ISSUE THREAD

**Issue by t3mf8h** [restic/restic#3713]
Output of `restic version`
--------------------------

restic 0.8.3 compiled with go1.10 on linux/amd64

and

restic 0.11.0 compiled with go1.15.3 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

diff currently can compare two snapshots in a single repo. 

restic diff snapshot-ID snapshot-ID

A good feature would be to compare two snapshots from two repos. Maybe specify it similar to Copying snapshots between repositories

restic -r /srv/restic-repo --repo2 /srv/restic-repo-copy diff snapshot-ID snapshot-ID

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I personally backup my data to at least 3 different servers.

For comparing backups of the same client to two or more remote servers with possibly different trust levels it would be nice to have a diff between the content of the last snapshot in two repos. 

That comparing could be done fully automatic by another machine from time to time and send an alert if one of the backups/repos is lost or corrupted. If this independent "other machine" is different from client and the repo servers it will add some more trust to the whole system.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

restic rocks!    I use it on Linux and Windows. 

3 or 4 times used to migrate home dirs after new installation of linux on new laptop hardware. Smooth. 

1 restrore after an SSD crash was helping me very well. It was a mix of a "some weeks old" image restore and some hours old restic repo. 

Mounting the repo as drive under linux is great to securely access client data of far away Windows systems.

**Comment by MichaelEischer** [comment]
Comparing snapshots between two arbitrary repositories cannot be implemented in a way that is fast (at least without changing the repository format). The problem is that two different repositories chunk their data differently and thus the same data results in different data chunks and therefore also directory metadata. Essentially the only solution would be to _completely_ download both snapshots and compare them byte-by-byte. It would be possible to compare the metadata only, but that's probably not what you have in mind, and it only gives an incomplete picture.

If on the other hand both repositories use the same chunker parameters and contain the same snapshot, then it's possible to just compare the "tree" hash included in a snapshot.

**Comment by t3mf8h** [comment]
OK - Thanks for the detailed explanations!

One can mount both repos using **restic mount** and fully compare the latest snapshots using a **rsync --dry-run**. This adds not only trust that both remote servers have valid and unchanged backups but also adds another layer of trust independent of restic based on rsync running on an other independent machine. 

Yes, this will be slow and consumes a lot of (network) bandwidth.  

A **rsync --dry-run** compare of a mounted latest snapshot of one repo against the client data freshly backed up also seems to me a prove that a restore will work (slow and bandwidth consuming also).
