### ISSUE TITLE
Permissions change on ext4fs triggers full file rescan

### ISSUE THREAD

**Issue by ethereal-engineer** [restic/restic#3723]
Sometimes, when using sync software like Resilio-Sync, it is needed to fix the permissions on directories and files so that the sync can to its job. The easiest way to do this is using `chown` and `chmod` with the recursive switch. Unfortunately, despite the file modification times being unchanged, this seems to present to `restic` as a modification requiring a full file rescan. As a result, the subsequent backup operation takes hours instead of seconds. Is it truly necessary to perform a full rescan for permission changes?

**Comment by fd0** [comment]
By default, restic does not look at the modtime (`mtime`), because that timestamp can be changed by software (e.g. dpkg does that). Instead, restic by default looks at the `ctime`, unfortunately the `ctime` is also updated when the permissions or other metadata is changed. If in doubt, restic will do the most conservative thing and re-read the whole file.

You could try with `restic backup --ignore-ctime`, then restic uses the `mtime` instead. Does that work?

**Comment by ethereal-engineer** [comment]
Hmmmm. Well, it provides options. But having been provided these options, the prudent one in me would rather change anything else than risk a file not being accurately backed up. I will give it some thought. However, this definitely addresses the ticket, so it can be closed. You guys have been exceptionally thorough in the design and execution of restic, which is why I chose it in the first place. Good job 👍🏻
