### ISSUE TITLE
`b2_download_file_by_name: 404` on Backblaze B2 repository init

### ISSUE THREAD

**Issue by solracsf** [restic/restic#3750]
```
# restic version
restic 0.13.1 compiled with go1.18 on linux/amd64
```
Repository is created, but output doesn't seem normal.
```
# restic -r b2:bucketname:repo -o b2.connections=64 init
enter password for new repository:
enter password again:
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
created restic repository b17d3f2daf at b2:bucketname:repo
```

**Comment by MichaelEischer** [comment]
The unexpected 404 warnings are just debug output and can be safely ignored. I've opened https://github.com/kurin/blazer/pull/84 to fix it in the blazer library which we use to access B2.

**Comment by akrabu** [comment]
I'm running the latest beta as of yesterday, and I'm getting this error on nearly any command.  It shows up at the end of listing snapshots, and multiple times when using the find command.  Just thought I'd mention it since everything I could find pointed to just initializing new repositories!

**Comment by paudley** [comment]
Is it worth forking the library?  This makes restic output really hard to read.

**Comment by greatroar** [comment]
Or maybe the B2 backend should connect using the [S3 protocol](https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API) instead?

**Comment by MichaelEischer** [comment]
> Is it worth forking the library? This makes restic output really hard to read.

Not really, it's probably better to just switch to the S3 backend.

The documentation for the next restic version will include a remark to use the S3 backend to connect to B2: https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#backblaze-b2

**Comment by greatroar** [comment]
Apparently only new buckets on B2 support S3, so it wouldn't work anyway.

**Comment by twkonefal** [comment]
I'm getting this error still, too:

```
# restic -r b2:<REPO_NAME> init
b2_download_file_by_name: 404: : b2.b2err
b2_download_file_by_name: 404: : b2.b2err
created restic repository <REPO_ID> at b2:<REPO_NAME>

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
```
It's not really a big deal, however, the updated documentation is very unclear about how to use the S3 backend.

Firstly, the linked [documenation](https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API) does not mention how to generate the AWS compatible keys. I ended up creating a key the way I normally do via the Backblaze [website](https://secure.backblaze.com/app_keys.htm).

If, for Backblaze, you intend for people to use:
```
export AWS_ACCESS_KEY_ID=<MY_ACCESS_KEY>
export AWS_SECRET_ACCESS_KEY=<MY_SECRET_ACCESS_KEY>
```
and
```
restic -r s3:s3.us-west-001.backblazeb2.com/bucket_name init
```

Then you should just update the Backblaze documentation instead of pointing to the AWS documentation, which is quite confusing.  It's really not clear whether the Backblaze export should be B2_ACCOUNT_ID and B2_ACCOUNT_KEY, because the documentation is all mixed up.

Sorry for the slight segue, but I feel it's relevant to the discussion in this bug.

Thanks,
  Tomasz

**Comment by MichaelEischer** [comment]
@twkonefal  Please open a new issue. The `b2.b2err` error probably mean that you're using an outdated version of restic.

Feel free to open a PR to improve the documentation.
