### ISSUE TITLE
Compression leads to content mismatch after restore!

### ISSUE THREAD

**Issue by FATruden** [restic/restic#3783]
Output of `restic version`
--------------------------

This one works well:
```
/root/restic version
restic 0.13.1 compiled with go1.18 on linux/amd64
```

This one is current master compiled for compression tests:
```
/root/restic2 version
restic 0.13.1-dev (compiled manually) compiled with go1.18 on linux/amd64
```

How did you run restic exactly?
-------------------------------

Simple backup with content comparing after restore.

source file:
```
dd if=/dev/sde of=/mnt/img1 bs=1M count=128
```

Current master WITH compression:

backup:
```
cat /mnt/img1 | /root/restic2 -r rest:http://dc15s3:8000/repo2/  --verbose backup --compression auto --stdin --stdin-filename img1 --password-file ./pass
open repository
repository 193651e2 opened (repo version 2) successfully, password is correct
lock repository
load index files
read data from stdin
start scan on [/img1]
start backup on [/img1]
scan finished in 2.952s: 1 files, 0 B

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:     87 new
Tree Blobs:      1 new
Added to the repo: 128.006 MiB

processed 1 files, 128.000 MiB in 0:12
snapshot b727ac47 saved
```

```
/root/restic2 -r rest:http://dc15s3:8000/repo2/ --password-file ./pass snapshots
repository 193651e2 opened (repo version 2) successfully, password is correct
ID        Time                 Host        Tags        Paths
------------------------------------------------------------
b727ac47  2022-06-03 15:04:38  dc15                    /img1
------------------------------------------------------------
1 snapshots
```

restore:
```
/root/restic2 --verbose -r rest:http://dc15s3:8000/repo2/ dump b727ac47 /img1 --password-file ./pass | dd of=/mnt/img1_out 
```

compare:
```
md5sum /mnt/img1
d9a8853a50fedd618f3f361a913bac26  /mnt/img1
md5sum /mnt/img1_out
43f55c95aa1f3f951d62f917eedf2974  /mnt/img1_out
```

I use cat and stdin/stdout because i try to simulate backup and restore of block devices.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

i use rest-server in append only mode

Expected behavior
-----------------

current tagged version WITHOUT compression works well:

backup:
```
cat /mnt/img1 | /root/restic -r rest:http://dc15s3:8000/repo1/  --verbose backup --stdin --stdin-filename img1 --password-file ./pass
open repository
repository 0376e109 opened successfully, password is correct
lock repository
load index files
read data from stdin
start scan on [/img1]
start backup on [/img1]
scan finished in 0.254s: 1 files, 0 B

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:     92 new
Tree Blobs:      1 new
Added to the repo: 128.006 MiB

processed 1 files, 128.000 MiB in 0:01
snapshot 3a5bd550 saved
```

```
/root/restic -r rest:http://dc15s3:8000/repo1/ --password-file ./pass snapshots
repository 0376e109 opened successfully, password is correct
ID        Time                 Host        Tags        Paths
------------------------------------------------------------
3a5bd550  2022-06-03 14:58:28  dc15                    /img1
------------------------------------------------------------
1 snapshots
```

restore:
```
/root/restic --verbose -r rest:http://dc15s3:8000/repo1/ dump 3a5bd550 /img1 --password-file ./pass | dd of=/mnt/img1_out bs=1M
```
compare:
```
md5sum /mnt/img1
d9a8853a50fedd618f3f361a913bac26  /mnt/img1
md5sum /mnt/img1_out
d9a8853a50fedd618f3f361a913bac26  /mnt/img1_out
```

Actual behavior
---------------

content mismatch

**Comment by fd0** [comment]
Huh, thanks for the report! I'm unable to reproduce this issue with the latest master (74f7fe2b984e1becafa0fe784fa2eed34e0f884e), so in order to dig down I'd like you to do the following with your repo:

 * Run `restic check --read-data`, paste the complete output
 * Have a look at the file sizes: `ls -al /mnt/img*`, do both files have exactly the same size?
 * Look at the differences in the two files, e.g. using `vbindiff`. Are they at the beginning or the end? Is there anything else in the file that should not belong there (e.g. messages printed by restic)?
 * Does the issue reproduce with a local repo, or only with the REST server?
 * Can you mount the repo and run `md5sum` on the file via the mount?
 * Can you use `restic restore` to restore the file and run `md5sum` on it?

I'd like to find out if it's an internal issue (which should be reported by `restic check`), or if it is something that's caused by `restic dump` or something else entirely :)

**Comment by MichaelEischer** [comment]
Hmm, the `dump` command uses `LoadBlob` internally which verifies the sha256 hash of a data blob (after decompression) before returning it. Thus dump should only be able to output data that matches the expected data of the snapshot. During backup the file content is first chunked, then hashed and compressed afterwards. This means that each blob is hashed before compression and hashed again after decompressing it, which ensures that the blob content hasn't changed inbetween. That should make silent data corruption due to the compression itself impossible...

Does the data corruption also occur when using the restic2 binary with repository version 1?

**Comment by FATruden** [comment]
@fd0 yes, i'm on same commit.

> Run restic check --read-data, paste the complete output

```
./restic2 --verbose -r /mnt/restic/repo2 check --read-data --password-file ./pass
using temporary cache in /tmp/restic-check-cache-1440528908
repository 193651e2 opened (repo version 2) successfully, password is correct
created new cache in /tmp/restic-check-cache-1440528908
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
[0:00] 100.00%  1 / 1 snapshots...
read all data
[0:01] 100.00%  8 / 8 packs...
no errors were found
```

> Have a look at the file sizes: ls -al /mnt/img*, do both files have exactly the same size?

```
ls -al /mnt/img1
-rw-r--r-- 1 root root 134217728 Jun  4 20:55 /mnt/img1
ls -al /mnt/img1_out
-rw-r--r-- 1 root root 134217728 Jun  4 21:01 /mnt/img1_out
```

> Look at the differences in the two files, e.g. using vbindiff. Are they at the beginning or the end? Is there anything else in the file that should not belong there (e.g. messages printed by restic)?

Files are so different. The most part of the file is different.

> Does the issue reproduce with a local repo, or only with the REST server?

Today i used repo directly (without rest-server) and i didn't see any changes.

> Can you use restic restore to restore the file and run md5sum on it?

Hm, restore works well:

```
./restic2 -r /mnt/restic/repo2 restore 69279fab --password-file ./pass --target /mnt/restore
```

```
md5sum /mnt/img1
d9a8853a50fedd618f3f361a913bac26  /mnt/img1
md5sum /mnt/restore/img1
d9a8853a50fedd618f3f361a913bac26  /mnt/restore/img1
```

> Can you mount the repo and run md5sum on the file via the mount?


```
md5sum /mnt/img1
d9a8853a50fedd618f3f361a913bac26  /mnt/img1
...
md5sum /mnt/restic-mount/snapshots/latest/img1
d9a8853a50fedd618f3f361a913bac26
```

**Comment by fd0** [comment]
Thanks for the feedback! I'm at a loss what happened here.

Can you still reproduce it (=get the wrong data) using `restic dump`?

I don't think this is an issue in restic. The code has many safeguards against such issues (restoring data is its primary purpose after all). It may be a hardware issue though.

Which kernel/OS do you run on the machine restic runs on?

**Comment by greatroar** [comment]
Might be worthwhile building restic with -race, too, to find out if this is a concurrency bug.

**Comment by FATruden** [comment]
@fd0 I have reproduced this on another server and another local file system with fresh repo

and I have another md5 sum of restored file)

> Which kernel/OS do you run on the machine restic runs on?

CentOS Linux release 7.8.2003 (Core)
3.10.0-1127.19.1.el7.x86_64

Maybe you can give me your build of current master and i will try to reproduce this in my env.

**Comment by fd0** [comment]
Hm, the kernel version sounds innocent, we had some issue with data corruption due to a [kernel bug](https://forum.restic.net/t/troubleshooting-unreproducible-consistency-errors/3372/15?u=cyounkins), but that was Kernel 5.2+.

It'd be great if you could write up what you did exactly (with all the commands and output) so that (ideally) we can reproduce it and dig into the issue. Please use the binaries from here: https://beta.restic.net/restic-v0.13.0-182-g7d64aa7f/

**Comment by FATruden** [comment]
Hm, i think the problem in my source file: https://fatruden.s3.amazonaws.com/img1 (128MB)

I can't reproduce this behavior using another file. But with this one it happens every time on new version of restic (with compression).

I can't reproduce it on latest tagged version with this file. Looks like something has changed in new version.

Can you try to use my example file?

**Comment by fd0** [comment]
My notes as the bug hunting proceeds (all on restic master with commit 7d64aa7f57c1b15a2c81105ef3d85fd649ae90fc):
 * It does not depend on how the file was saved, it happens both for files read from stdin as well as when restic reads the file
 * It only happens for v2 repos, v1 repos are not affected 
 * `restic restore` always produces the correct file, `restic dump` always the wrong one
 * The data returned by `restic dump` depends on the repo, for the same repo the same data is returned, on a newly initialized repo other data is returned. Maybe depends on the block boundaries (chunker)?

**Comment by fd0** [comment]
This is very exciting! Thanks so much for reporting the bug! :)

**Comment by fd0** [comment]
Ah! that explains why it didn't happen for my tests: I used `/dev/urandom` as the data source, which returns data with high entropy that does not compress well, so the compressed blob is likely as large as the source data.

**Comment by fd0** [comment]
@greatroar would you do us the honor of submitting a PR and the fuzz test? :)

**Comment by greatroar** [comment]
Working on it.

**Comment by fd0** [comment]
I'm still working at understanding the bug. Why doesn't it happen on `restore`, but only on `dump`? odd...
