### ISSUE TITLE
Restic on oldish 386 hardware

### ISSUE THREAD

**Issue by lenneis** [restic/restic#3801]
Hi,

I try to run restic compiled for OpenBSD on a pretty ancient embedded system with a 386 class cpu. Immediately at startup I get 

Illegal instruction (core dumped)

plus a coredump, as stated in the message. I think it is not a OpenBSD issue, on a OpenBSD system with a more modern 64 bit cpu everything is fine. I rather suspect, that the compiled code does contain an "Illegal instruction" for the cpu it tries to run on. This is the cpu from dmesg:

cpu0: Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class) 499 MHz, 05-0a-02
cpu0: FPU,DE,PSE,TSC,MSR,CX8,SEP,PGE,CMOV,CFLUSH,MMX,MMXX,3DNOW2,3DNOW

This is the exact specification for that class of embedded mainboards:

https://pcengines.ch/alix.htm

I still got a couple of those systems out in the field, they just refuse to die. Any chance for a working binary? I can provide access to such a box if needed.

best,

**Comment by lenneis** [comment]
Well, after reading up on how to compile restic from source (all three lines of it) I went ahead and did just that. It was not fast by any means, but I eventually got a working binary. Looking a bit more closely at the differences between the result and the  available download, it seems the download is not statically linked after all:

ldd /usr/local/sbin/restic       
/usr/local/sbin/restic:
        Start    End      Type  Open Ref GrpRef Name
        08048000 09080000 exe   2    0   0      /usr/local/sbin/restic
        3eba9000 5ebba000 rlib  0    1   0      /usr/lib/libc.so.96.0
        270e3000 470e5000 rlib  0    1   0      /usr/lib/libpthread.so.26.1
        39f76000 39f76000 ld.so 0    1   0      /usr/libexec/ld.so

Whereas the compiled code is statically linked:

ldd restic                                                                                                                                                                   
restic:
not a dynamic executable

So, maybe there is a shortcoming in the build process?

**Comment by MichaelEischer** [comment]
Which go version did you use for compiling? I think the binaries have libc and libpthread as dependencies to be more portable, but it shouldn't matter much, because depending on a minimal set of libraries should cause an "Illegal instruction" error.

The release binaries are built using `go build-o outputFile -ldflags -s -w -tags selfupdate ./cmd/restic`. The two `-ldflags` options are according to the documentation only supposed to remove debug symbols.

The likely cause is probably described at https://github.com/golang/go/wiki/MinimumRequirements#386 :

> GO386=sse2 (default): Any processor with at least SSE2

As the ancient hardware does apparently does not yet support SSE2, this will cause the Illegal instruction error. However, if you compile it locally, go probably automatically picks the soft-float emulation.

As far as I remember, this is the first time I've seen that particular problem, so I think the use case to run restic on hardware without SSE2 is just too rare to switch the release binaries to soft-float emulation. So you'll have to build your own version.

**Comment by greatroar** [comment]
The binary may be dynamically linked because of golang/go#36435, where they're working to drop static binaries on OpenBSD altogether. Mac and Solaris binaries are also dynamically linked, so we should rephrase the docs.

Also @lenneis if the build is really slow, try cross-compiling:

```
$ uname
Linux
$ go run build.go --goos openbsd --goarch 386
$ file restic
restic: ELF 32-bit LSB executable, Intel 80386, version 1 (OpenBSD), dynamically linked, interpreter /usr/libexec/ld.so, for OpenBSD, Go BuildID=zo6bDlvKTkQfn4QK_i0h/p6xNSGDOB7nwqnSJ5b8D/wu91PwJ2Jr_aGEl8RB5Z/BoCaMgz-6br6XS0d9qet, stripped
$ scp restic targethost:path
```

This should work on any machine.

**Comment by MichaelEischer** [comment]
Although for the problem here it's probably also necessary to set `GO386=softfloat`?

**Comment by greatroar** [comment]
Yes. Sorry, thinko.

```
GO386=softfloat go run build.go --goos openbsd --goarch 386
```

Come to think of it, it might be an option to turn that on for the downloadable binaries. Floating point is mostly used for the progress display and statistics, right? zstd doesn't use it, AES doesn't, and very little of the networking code does.

**Comment by lenneis** [comment]
> Which go version did you use for compiling? I think the binaries have libc and libpthread as dependencies to be more portable, but it shouldn't matter much, because depending on a minimal set of libraries should cause an "Illegal instruction" error.
> 

This is go1.15.2

> The release binaries are built using `go build-o outputFile -ldflags -s -w -tags selfupdate ./cmd/restic`. The two `-ldflags` options are according to the documentation only supposed to remove debug symbols.
> 
> The likely cause is probably described at https://github.com/golang/go/wiki/MinimumRequirements#386 :
> 
> > GO386=sse2 (default): Any processor with at least SSE2
> 

Yes, that sounds very likely.


> As the ancient hardware does apparently does not yet support SSE2, this will cause the Illegal instruction error. However, if you compile it locally, go probably automatically picks the soft-float emulation.
> 
> As far as I remember, this is the first time I've seen that particular problem, so I think the use case to run restic on hardware without SSE2 is just too rare to switch the release binaries to soft-float emulation. So you'll have to build your own version.

I don't mind doing that.

**Comment by lenneis** [comment]
> 
> Also @lenneis if the build is really slow, try cross-compiling:
> 


The build is slow, but then there is time enough between releases to do it. I find it quite interesting, that go can cross compile out of the box though. Did not know that one.

**Comment by lenneis** [comment]
> Come to think of it, it might be an option to turn that on for the downloadable binaries. Floating point is mostly used for the progress display and statistics, right? zstd doesn't use it, AES doesn't, and very little of the networking code does.

If there is really no performance penalty, which you seem to imply, why not? Otherwise, I think recompiling on non SSE2 capable hardware is perfectly fine.

**Comment by MichaelEischer** [comment]
I took a slightly closer look at the effects of softfloats and apparently enabling that mode would also affect functions like memmove/memclr/equal/cmp (search for `GO386_softfloat` in the go source code). So this has the potential for a considerable performance regression, so I'd rather prefer to just stick with the default.
