### ISSUE TITLE
Follow up: Release strategy (#556)

### ISSUE THREAD

**Issue by EngelPika32** [restic/restic#3867]
Output of `restic version`
--------------------------
restic 0.13.1 compiled with go1.18.1 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
There have been over 350 commits since the last release (0.13.1) in early April (and the number of entries in changelog/unreleased rises). Great work has been done^^.
But, I'm wondering: When is the next release? or should I build restic myself regularly?

And well… maybe a release schedule should be created, especially for minor releases fixing bugs. (as cut on in #556)
Right now the releases are more semi-regular.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Tweaking my backup configuration for more performance and running into "unknown option" errors. I didn't notice for almost an hour, that I was looking at the docs of the current master, and not the last release x) 
[And my issue was fixed in late April.]

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic has not yet failed with me killing it so far, nor does it care about the lousy scheduling causing multiple backups into the same repository simultaneously. Only my HDDs complain noisily sometimes. :p 
Though, my HDD problem is probably fixed by setting `-o local.connection=1` (merged PR 3475)

**Comment by rawtaz** [comment]
It's quite likely that there will be a release later this year. See https://forum.restic.net/t/compression-support-has-landed-in-master/4997/54?u=rawtaz for a recent comment from Michael.

Personally I use the master branch version of restic all the time, and it hasn't failed me a single time yet. But I would of course recommend staying on the latest release unless you have a reason to be on master.

I can relate to being on the wrong "version" over at restic.readthedocs.io, I guess that happened to everyone at some point 😄 

Releases are not about the amount of commits since last release, as I'm sure you know. It's about a lot of other factors, and for restic it's more about when there's stable and well tested material in master to justify a release, as well as of course what type of changes, features and corrections are in there. I don't think it would be very useful for the project to set a schedule, and this is something that has been considered before.

I'm closing this issue as there's nothing really actionable in it (it's more of a question that should have been posted in the forum). Thanks!
