### ISSUE TITLE
Why version 0.14 everywhere in Documention when it is not even released

### ISSUE THREAD

**Issue by afzl-wtu** [restic/restic#3870]
It make me very confused. There is no any release of 0.14 but in repository version it is mentioned. How we can convert or create a repository to version 2 with 0.13.1 when 0.14 version which really can read v2 version of repo is not yet released. I am creating repository with 0.13.1 but how to check its version wether it is v1 or v2. Also there is a lot of documentation for repo migration and still I could not find how to check my repo version there is no command I could find. Also I tried to open config file but it is encrypted.

**Comment by rawtaz** [comment]
Please, this is not something you open an issue for. It's a question that belongs in [the forum](https://forum.restic.net/).

Regardless, I'm guessing (since you didn't even tell us where you are actually looking/reading when you see the 0.14 version) that the reason for your observation is that you are looking at the [latest](https://restic.readthedocs.io/en/latest/) version over at restic.readthedocs.io, rather than the [stable](https://restic.readthedocs.io/en/stable/) version.

The former corresponds to the master branch for restic here on GitHub and for that reason contains the documentation for the yet-to-be-released version of restic, which is 0.14. The latter corresponds to the latest stable release, which is 0.13.1. I agree that calling the master one "latest" is an unfortunate thing to do by RTD, it would be better if they just used "master" instead, or maybe "unreleased".

You can get the latest (to-be 0.14) restic binary from the build site here: https://beta.restic.net/latest/ - this should indeed match the documentation you have read.

**Comment by afzl-wtu** [comment]
> Please, this is not something you open an issue for. It's a question that belongs in [the forum](https://forum.restic.net/) 🙂
> 
> Regardless, I'm guessing (since you didn't even tell us where you are actually looking/reading when you see the 0.14 version) that the reason for your observation is that you are looking at the [latest](https://restic.readthedocs.io/en/latest/) version over at restic.readthedocs.io, rather than the [stable](https://restic.readthedocs.io/en/stable/) version.
> 
> The former corresponds to the master branch for restic here on GitHub and for that reason contains the documentation for the yet-to-be-released version of restic, which is 0.14. The latter corresponds to the latest stable release, which is 0.13.1. I agree that calling the master one "latest" is an unfortunate thing to do by RTD, it would be better if they just used "master" instead, or maybe "unreleased".
> 
> You can get the latest (to-be 0.14) restic binary from the build site here: https://beta.restic.net/latest/ - this should indeed match the documentation you have read.

Thanks for the response, the link https://beta.restic.net/latest contains restic binary version 0.13 it is not even 0.13.1 . I could not find any binary of 0.14 there. Also please tell me how to check repository version.

**Comment by rawtaz** [comment]
It is the latest master branch build, the version number is not updated because it's not been released yet. I agree that's a bit misleading, but if you want to be sure you can look at the git commit ID which is [f0bb4f8](https://github.com/restic/restic/commit/f0bb4f8708b1e09e09897463d70b5c89b20eec01) and present in the name of the files I linked you to. Either way, it is the one you want.

To check the repository version, use `restic cat config` and look at the `version` value in the output.
