### ISSUE TITLE
What to do with "repository contains errors"

### ISSUE THREAD

**Issue by yatesco** [restic/restic#399]
Hi,

I have a number of repositories ranging in size from 5GB to 300GB (repo size, not source) and `restic check` frequently states "pack ..... not referenced in any index" and finishes with "repository contains errors".

Subsequent backups work as do copying files out of mounted repos (I have only tried to copy some, not all).

My question is: should I be worried? Is this an _integrity_ issue or a _house keeping_ issue? `restic fsck` gives an "Unknown command" so I guess that wasn't in 0.1.0.

I am hesitant to track head and 0.1.0 was the latest release - what should I do next?

[EDIT] Each repository is only ever accessed by one client only.

**Comment by yatesco** [comment]
Ah, reading https://github.com/restic/restic/issues/359#issuecomment-167758422 suggests that it is more _house keeping_ and I can safely ignore?

**Comment by fd0** [comment]
The error message from `check` is a bit unfortunate and misleading. When restic outputs `pack not referenced in any index`, it means that there is additional data stored in the repository that is not referenced anywhere, so the data is mostly duplicate. We had a few bugs that produced these un-referenced packs. It also means that all the data that is stored in such not-referenced packs is also stored in other packs (that are referenced), that's why you don't see any errors during restore or fuse mount.

Mostly, this just means your repository is bigger than necessary, nothing more. Housekeeping is a good way to describe it.

**Comment by yatesco** [comment]
Thanks fd0 ;-).

**Comment by fd0** [comment]
Once #359 is fixed, you can use the `optimize` command to remove the unneeded packs, so you might want to subscribe that issue. :)

**Comment by yatesco** [comment]
Any idea when 0.2.0 will be cut?

**Comment by fd0** [comment]
Probably this weekend, stay tuned :)

**Comment by yatesco** [comment]
Excellent - I look forward to it!
Alexander Neumann writes:

**Comment by yatesco** [comment]
fd0 you tease: "Probably this weekend, stay tuned :)" ;-). 

Any idea when the new release will appear? I am debating tracking `master` but would rather wait for a formal release.

(as ever, very appreciative of `restic`!).

**Comment by fd0** [comment]
Thanks for the reminder, I was too busy travelling to and from FOSDEM, and other things occupied my evenings. No promises, but I'll try to find a specific bug, and then release 0.2.0 within the next couple of days. You can track my progress by observing the issues which have been assigned to the 0.2.0 milestone: https://github.com/restic/restic/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.2.0

**Comment by yatesco** [comment]
What - you mean you have a life outside of restic - how dare you :-)
