### ISSUE TITLE
Cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by landrix** [restic/restic#4005]
This issue also relates to https://github.com/restic/restic/issues/3922

Output of `restic version`
--------------------------

restic 0.14.0 compiled with go1.19 on windows/amd64

How did you run restic exactly?
-------------------------------

commands
SET RESTIC_PASSWORD=xyz

SET RESTIC_CACHE_DIR=C:\cache

restic_0.14.0_windows_amd64.exe -o sftp.command="plink.exe -s -C -l user -P 22 -pw mypwd sftp.hidrive.strato.com sftp" backup -r sftp:user@sftp.hidrive.strato.com:/users/user --use-fs-snapshot --host server --exclude-file=excludes.txt y:\

output:

Fatal: unable to open repository at sftp:user@sftp.hidrive.strato.com:/users/user: cmd.Start: cmd.Start: exec: "plink.exe": cannot run executable found relative to current directory

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

run cmd plink.exe

Actual behavior
---------------

plink.exe wasn't startet

Steps to reproduce the behavior
-------------------------------

Just start a similar call.

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

version [restic 0.13.1](https://github.com/restic/restic/releases/tag/v0.13.1) works fine

**Comment by rawtaz** [comment]
This has been fixed in https://github.com/restic/restic/pull/3938 - if you use the latest build from https://beta.restic.net/latest/ you will get a better error message :)

You can read a little more about it in the blue "Note" box here (this is about rclone but the same should apply to plink as well): https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone

So, the problem you are having is due to a security measure introduced in a recent Go version. To deal with this we had two choices - either sidestep that security measure, or instead provide a better error message and explain how to explicitly tell restic that all is fine. We chose the latter, because security first.

The fix is simple. If you know that the plink.exe you want to use is secure, simply add `./` before it, as this tells Go that you intend to use that relative binary. So your command would be `restic_0.14.0_windows_amd64.exe -o sftp.command='./plink.exe -s -C -l user -P 22 -pw mypwd sftp.hidrive.strato.com sftp' backup -r sftp:user@sftp.hidrive.strato.com:/users/user --use-fs-snapshot --host server --exclude-file=excludes.txt y:\`. Can you try that and report back?

**Comment by landrix** [comment]
yes, thanks, if i add ./ before plink.exe with 0.14.0, it works
