### ISSUE TITLE
Restoring a specific file with a defined name

### ISSUE THREAD

**Issue by Daniel-Nashed** [restic/restic#4027]
Hi all,

I am running **restic 0.14.0 compiled with go1.19 on windows/amd64** and I am trying to extract a single file to a distinct directory and file name.

The use case around it is a restore for an application, which needs to restore a file to a different directory with a different file extension.

For example the file was `c:\notesdata\mydatabase.nsf`

The restored database should be something like `c:\notesdata\restore\mydatabase.nsf.DAD`

I tried all kind of different options. On Linux I could use a mount and copy the files back on my own.
But on Windows there isn't a mount option. 

Having a way to explicitly specify the file, would be really helpful.
If also the directory would be created automatically, would be a bonus option helping to create a restore command, without an extra step.

Maybe there is an existing option I missed. But I tried everything including the dump command. 

With the `dump` command and a redirect to file I could rename the file. But I would still create the directory separately. And it is more a work-around than the right way to go.

**Comment by MichaelEischer** [comment]
The `restore` command is designed to restore directory trees. I don't think a method to dynamically rename files while restoring belongs in there. That use case is just too rare to warrant the major complexity of such a feature. Just rename the file afterwards.

> With the `dump` command and a redirect to file I could rename the file. But I would still create the directory separately. And it is more a work-around than the right way to go.

You're use case sounds like what the `dump` command is suited for. Just create a script to create the missing directory if necessary.

Mount support on Windows will be available once someone finished #2862.

**Comment by AlBundy33** [comment]
you could try `dump` and redirect the output to the new file.
something like `restic -r /srv/restic-repo dump 098db9d5 somefile.nsf > somefile.nsf.DAD`

Maybe a cp-command would be nice for restic - this should be similar to dump but instead of writing to stdout it should write to the specified file or folder

**Comment by MichaelEischer** [comment]
It's probably better to extend the `restore` command to allow restoring sub-trees or even just individual files. And additional command just complicates the CLI.

**Comment by AlBundy33** [comment]
Just an idea:

maybe thinking about renaming restore to cp for a syntax like docker
`restic cp 84883:/etc/foobar.conf ~/test/foobar_test.conf`
and `restic cp 84883 ~/test/` would be the same as `restic restore 84883 --target-dir ~/test`

I've seen some issues and forum-posts where users are wondered about the additional files in the target-dir where not deleted automatically and maybe cp would make the function much clearer.

restore sounds indeed that I have exactly the directory as i did the backup but this isn't true unless I use an empty target-dir.

**Comment by rawtaz** [comment]
> maybe thinking about renaming restore to cp for a syntax like docker

@AlBundy33 We don't go and rename the command for things like this. Realize that there are a lot of restic users in the world and renaming commands is something we don't take lightly. The `restore` command currently does exactly what it's name implies - it restores files (from a snapshot into the filesystem). Arguably a better name than `cp` for this process.

> I've seen some issues and forum-posts where users are wondered about the additional files in the target-dir where not deleted automatically and maybe cp would make the function much clearer.

I guess it's open to interpretation and definition. Personally I'd say that if one has already existing files in the target directory that is being restored to, then it's rather expected that one will end up with a mix of restored files and the existing files. It would be remarkable if restic erased everything else it found in the target directory by default and without confirmation. If one want to keep those separate, simply restore to an empty and possibly temporary directory, then move the relevant files or use a sync tool that suits the use case (in my experience most people have quite different use cases when they restore files and it's generally wise for restic to stay rather generic/neutral and focus on the restore part of the workflow). You can of course also use the various options to the `restore` command to include/exclude files to control what is actually restored.

Regardless, the bottom line is that since there are so many different use cases and expectations in the use of restic and e.g. the `restore` command, it's generally better if restic focuses on one thing and does not at the same time try to become a filesystem tool for things like erasing directories/contents before restore, renaming things along with or after restore, etc. These are all things that can *easily* be done in relation to the restore, and then in a highly controlled manner, with more featureful tooling and in ways that fully matches one's individual use case. It would be different with things that are not easily done by other standard tooling in relation to the restore, but again, things like renaming some file(s), deleting existing ones, etc, that's just so simple that it takes more time to think about it than just do it in relation to your restore.

**Comment by Daniel-Nashed** [comment]
Nothing should be overwritten and no existing functionality should be changed.
My request is pretty simple:

Single file restore with a different name. The main reason is that the file needs to be changed before it can be used and the file extension cannot be the same, because the application would find it.

- Restore with myfile.txt to myfile.txt.DEAD
- Have the application make changes and rename it

Usually single file restores are not for disaster recovery or failure.
They are used to get data back from a file before the changes.
It's almost never about overwriting existing data.

I don't see that this is a rare use case and it would be very helpful having a single file restore with a different target name.

**Comment by rawtaz** [comment]
So restore the file and run a single command to rename it?

**Comment by Daniel-Nashed** [comment]
The flow is a bit different:

- Restore application identifies the file to restore
- It invokes a Restic restore to a temp file
- Then it performs recovery operations and finally renames the file

**Comment by rawtaz** [comment]
Looks fine to me. It's one single command to rename the file. So why would this be implemented in restic, when it's inevitable that it will only meet some of the renaming use cases and others will follow saying it's not good enough?

**Comment by Daniel-Nashed** [comment]
not sure what you mean. we just need the file that is restored has a different name.
this can be relevant for multiple use cases. My use case is just one.

**Comment by rawtaz** [comment]
The point is this: Renaming a file to the name you want it after restore is one single command and takes hardly no time at all. For that reason, it makes no sense to implement that in restic.

**Comment by Daniel-Nashed** [comment]
the file takes some time to be written if this is a larger file.
the application this restore is for is a server which would potentially see the file with the original extension and would start to use it. therefore the restore must be a different file name. 
why do you know my use case better than I? 

The file really needs to be stored with a different name.
One the file is there and completely written, there are recovery operations needed on the temporary file, before it can be rename to a file with an extension the server application uses.

**Comment by rawtaz** [comment]
> the file takes some time to be written if this is a larger file.

Sure, but we're not talking about the time it takes to write the file, we're talking about simply moving or renaming the file after it has been restored to disk.

> why do you know my use case better than I?

I never said that I do, so I'm not sure why you think I do. You on the other hand seem to completely ignore the other reasons I mention for why this is not as straight forward as you seem to think from the perspective of implementing features that are applicable to as much of the user base as possible. It's not only about your use case, it's about the bigger picture.

> The file really needs to be stored with a different name.

Restore it outside whatever directory your application automatically picks up new files in? Restoring files to a place where they are automatically picked up and used *before you verified that the restore was successful* is not a very good idea if you ask me. The exception would be if the application itself did the verification instead of restic, but even when you'd have to make sure it doesn't look at the file too early in the process.

I'm not trying to dismiss your use case, but there hasn't been much clarity in why moving/renaming the file is an *actual problem* to do for you, and as I mentioned there's the aspect of this not being about this single use case in the first place, but a bigger picture.

**Comment by AlBundy33** [comment]
IMHO it would be nice to have such helper functions in restic because it would avoid the need of wrappers/scripts/additional commands.
The goal of restic is to keep it simple but where is the simplicity if everyone has to script around it?
just my two cents...

@Daniel-Nashed have you tried `restic -r /srv/restic-repo dump 098db9d5 somefile.nsf > somefile.nsf.DAD`

**Comment by rawtaz** [comment]
For gods sake, @AlBundy33..

**Comment by AlBundy33** [comment]
no reason to get rude... 🤔 
as far as I understand the request was only to copy/write from backup to a specified target-file and nothing about fancy renaming of files.

but maybe I misunderstood the request...

**Comment by MichaelEischer** [comment]
After reading through this issue again, I still don't understand why `restic dump` (which will be faster in the next release) or `restic restore` to a temporary location are not sufficient for the use case. After all the linked domino issue shows that there's already a substantial amount of scripting in use.

**Comment by Daniel-Nashed** [comment]
A dump could work. But scripting would be still complicated.
I had to give up on Restic for Domino backup even I love it for my Windows notebook backup.

On Windows we are missing application aware processing. For the restore on Windows scripting is not a feasible option.

On Linux other applications like Borg Backup provide a stable interface using the tar format for backup and restore with full transparency [import-tar / export-tar](https://borgbackup.readthedocs.io/en/stable/usage/tar.html)

So I came up with a [full Borg Backup integration](https://github.com/nashcom/domino-borg) with a native C application controlling the backup process.

Backing up Domino as an application is more challenging than backing up just files or one large relational database.
Domino consists of many NSF files where each is a database which can be in use at time of the backup.

For Linux Restic would be too difficult to integrate with Domino. 
For Windows the VSS integration isn't providing application consistent snapshots, which make the flow of the backup for us too complicated too.

I implemented a [Domino native VSS Writer](https://help.hcltechsw.com/domino/12.0.2/admin/admn_vsssnapshots.html) in Domino 12.0.2 a while ago and integrated it with applications like Veeam.
But with application aware snapshots it would be too complex to implement With Restic -- specially if for restore we can't fully control the resulting file extension.

Again I love Restic for what it does. And I can understand you can't please every use case.
