### ISSUE TITLE
Change the backup time for an existing backup // Setting the backup time for a backup run?

### ISSUE THREAD

**Issue by ewasser** [restic/restic#4061]
Hello,

would it be possible to change the backup time for an existing backup or setting the backup time for a backup run?

Background:

In the past, I've made backups with `rsync` and the option `--link-dest=DIR` and I want to convert these hard link farms to `restic`. The backup directory structure look like this:
```
2011-01-20 (inital backup)
+ file1

2011-01-21 (new backup with changes)
+ file1 (hard link to ../2011-01-20/file1)
+ file2 (new file)

2011-01-22 (new backup without changes)
+ file1 (hard link to ../2011-01-21/file1)
+ file2 (hard link to ../2011-01-21/file1)

2011-01-23 (new backup with change)
+ file1 (changed, so it's a new file)
+ file2 (hard link to ../2011-01-22/file1)
```
These backups are years old, and I don't want to lose them. I can redo the backup time with `restic`, but I wish to convert the backup time stamp into `restic`.

Is this easy to implement?

**Comment by MichaelEischer** [comment]
It is currently not possible to change the backup time for existing snapshots. But the `backup` command has a `--time` which allows you to set the timestamp use for the snapshot.

As restic also includes the absolute paths of the backed up files in the snapshot you'll probably have to rename each folder temporarily to a fixed name (e.g.  `rsync-backup`). Otherwise the restic commands won't be able to detect which snapshots belong to the same backup data set. Also make sure to read the section on `--group-by` at https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy .

**Comment by ewasser** [comment]
Thanks for you answer. That was quite helpful. I totally missed the option `--time`. That will do the trick.

> As restic also includes the absolute paths of the backed up files in the snapshot you'll probably have to rename each folder temporarily to a fixed name (e.g. `rsync-backup`). Otherwise the restic commands won't be able to detect which snapshots belong to the same backup data set.

Can you elaborate on this point?

So backing up `/foo/2011-01-01` would be a totally different backup data set than `/foo/2011-01-02`? Why is the "same" backup data set necessary? What are the consequences when I'm using a different path? Will this increase the backup size?

**Comment by MichaelEischer** [comment]
> Why is the "same" backup data set necessary? What are the consequences when I'm using a different path? Will this increase the backup size?

When using different paths for each backup, then `forget` will consider each of them as a completely independent backup. Normally `forget` groups backups with the same path together. That way, it is possible to e.g. only keep a certain amount of daily / monthly snapshots for a certain backup path. If each backup has a different path, then there is only a single backup for each path and thus the options of `forget` to only keep a certain amount of backups won't work as expected (it will just keep everything).

Using `forget --group-by host` it would still be possible to use the mentioned forget options. But then you have to be careful, not to mix these snapshots with some different backup data set.

Oh, and the backup command also won't be able to quickly check whether files have changed since the last snapshot, as it wouldn't know what to compare against. But that only causes somewhat slower backups, it won't make a difference for the backup size.
