### ISSUE TITLE
Make snapshot IDs stable

### ISSUE THREAD

**Issue by tbm** [restic/restic#4161]
Output of `restic version`
--------------------------

restic 0.15.0 compiled with go1.19.5 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I'd like snapshot IDs to be stable.  That is, after you make a backup, the ID of the snapshot should not change, so you can refer to it consistently by ID.

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I generated a list of snapshots IDs.  I then added tags to them.  Afterwards I wanted to make more changes to the tags but I noticed that the snapshot IDs changed in the meantime (apparently adding a tag changes the ID).  I thought snapshot IDs are stable.  IMHO they should be so people can refer to them by ID.

I found some previous discussion about this in https://github.com/restic/restic/issues/851 in which @fd0 says that snapshot IDs are not stable.  But why not?  I think form a user-perspective stable snapshot IDs would be useful.

If stable snapshot IDs are not possible, I think this should be documented somewhere.

**Comment by tbm** [comment]
@rawtaz thanks for your detailed explanation!

> This is why when you change the contents of a snapshot file, the hash changes and thereby also the ID of the snapshot.

I can see that, but it's not obvious why changing meta-data like tags should change the snapshot ID.  I think that's unfortunate.

Also, based on what you said, it sounds like "snapshot hash" may have been a better term since "snapshot ID" suggests some permanence, but I know it's much to late for such a change...

> I'm curious why you have a need to change the tags so much?

I recently started doing a partial and a full backup to the same repo and started using tags so I can apply different `forget` policies.  I added tags to my existing snapshots, then changed my mind about the tag name and changed it again - only to discover that all snapshot IDs have changed.

I accept this is a rare situation and agree with you that using tags to refer to things is better going forward.

In any case, I'm ok with this ticket being closed.  However:

* if it's not hard, I think changing tags shouldn't change the snapshot ID
* it would be good to add something to the docs that snapshot IDs are not permanent (and maybe even what actions cause snapshot IDs to change, e.g.  changing tags, `rewrite`).  I checked and couldn't find anything (although it's possible I missed it) and I suspect it might also surprise other users.  e.g. I could have seen myself writing a note to myself "snapshot XXX is the last before I started cleaning up some stuff" to make it easier to find things later.  Now I know that I should either use a tag or refer to it with a date "I cleaned up on XXX; if something is missing, take the snapshot before that day".

**Comment by rawtaz** [comment]
> I can see that, but it's not obvious why changing meta-data like tags should change the snapshot ID. I think that's unfortunate.

It is because tags are part of the snapshot's data/content, and thereby part of what the hash is based on. Hence, when you change the tags you change the content and effectively you are creating a new snapshot file (that however still references the same data as before). This new snapshot has a new ID.

> Also, based on what you said, it sounds like "snapshot hash" may have been a better term since "snapshot ID" suggests some permanence, but I know it's much to late for such a change...

Maybe, but an ID is still an ID. The fact that the ID of a snapshot happens to be the hash is also a design decision - besides other factors it provides a unique (as in extremely low probability of a collision, to the extent that it is practically not going to happen) ID generator, instead of having to use a counter or rely on some other generation of an ID which is much more likely to collide. The obvious alternative would be a UUID I guess. But as you say, it is what it is for now :)

> I accept this is a rare situation and agree with you that using tags to refer to things is better going forward.
> if it's not hard, I think changing tags shouldn't change the snapshot ID.

Sorry, probably not going to happen any time soon. The amount of code and workings of restic needed to do that is way more than the gains from it as I see it at least.

Yeah, I honestly don't see why you need to refer to IDs at all in the situation you have described. If you want to separate or "address" snapshots for your partial and full backups, just apply tags to them when backing up (and afterwards if you want), there's no need to refer to snapshots by ID. Not even when pruning, since you can group the snapshots by tags and your policies will be applied to each group separately. If I'm missing something here, let me know :)

> it would be good to add something to the docs that snapshot IDs are not permanent (and maybe even what actions cause snapshot IDs to change, e.g. changing tags, rewrite).

It's actually mentioned both in the reference that describes the restic design/format [here](https://restic.readthedocs.io/en/stable/100_references.html#snapshots) and in the reference for managing tags [here](https://restic.readthedocs.io/en/stable/manual_rest.html#manage-tags). But if you have any suggestions on improving it, feel free to open a PR! :)

I will close this issue though, but you can still reference it (#4161) in a PR if you were to open one.

**Comment by tbm** [comment]
Thanks @rawtaz!

**Comment by MichaelEischer** [comment]
Making snapshot IDs stable won't be possible before solving #523 and even then it would require a lot of additional work.

**Comment by tbm** [comment]
Thanks again for taking the time to reply with useful comments even to issues that may be nonsensical.

This community is very welcoming! I'm a happy restic user.
