### ISSUE TITLE
Provide statically linked binary without any dependencies

### ISSUE THREAD

**Issue by lathspell** [restic/restic#432]
I'd like to put a restic binary on the USB disk that serves as backup storage as I fear that next time my system crashes, I won't easily find a rescue CD (like Knoppix, Grml) that has Go installed.

Grep told me that there is a "-ldflags" option in build.go but I can't get it to pass "-static" or similar to the linker. It should be fairly easy for you to add a "make static" target in the Makefile, I guess.

**Comment by fd0** [comment]
Hi, thanks for asking. For once, installing Go on e.g. grml is easy, you should be able to install it via `apt-get install golang`. Otherwise, you could just extract a pre-compiled tar from `golang.org` and use that to compile restic.

I can understand your desire to have a pre-compiled version of restic, so that you don't have to fiddle around with compiling it when you urgently need to restore a backup. The binary produced by the Go compiler is by default already nearly static, only the most basic things like libc and libpthread are linked dynamically:
```
$ ldd restic 
	linux-vdso.so.1 (0x00007fff23df4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f872b0e3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f872ad38000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563622743000)
```

The binary was produced by just running `go run build.go`, without any extra parameters. It should run on any recent (< 5 years old) Linux without having to install any libraries.

I think that's enough for a USB stick for disaster recovery, do you agree?

**Comment by lathspell** [comment]
Your ldd output is indeed ok, mine shows a dependency to libgo.so.7 and I feared that that might not be available on a rescue disk in 1-2 years anymore:

    $ ldd restic 
        linux-vdso.so.1 (0x00007ffc299d5000)
        libgo.so.7 => /usr/lib/x86_64-linux-gnu/libgo.so.7 (0x00007f5e76914000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5e7660f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5e763f8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e76054000)
        /lib64/ld-linux-x86-64.so.2 (0x00005581c9009000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5e75e37000)

My system is a Debian unstable with gccgo 5.3.1:
   Linux james 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 (2016-01-19) x86_64 GNU/Linux

Ah, I read your comment and installed "aptitude install golang" and recompiled and now the binary looks better, no libgo and no libpthread anymore:

    $ ldd restic 
        linux-vdso.so.1 (0x00007ffff35aa000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0381ca5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0381901000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563a75aa3000)

Maybe add a comment to the README which compiler is the better/recommended one?

**Comment by fd0** [comment]
Good idea, thanks!
