### ISSUE TITLE
Error when using "check --read-data-subset=10G"

### ISSUE THREAD

**Issue by AlertSubject** [restic/restic#4344]
When i try to follow the [documentation](https://restic.readthedocs.io/en/latest/045_working_with_repos.html#checking-integrity-and-consistency) and use the example given (restic -r /srv/restic-repo check --read-data-subset=10G) it gives me an error:
"Fatal: check flag --read-data-subset must have two positive integer values or a percentage, e.g. --read-data-subset=1/2 or --read-data-subset=2.5%%"
Of course I have replaced the example with my own repository
But it seems like I cant even get the example from the documentation to work
Using 5% works fine, using 10G does not work

What am I doing wrong?

**Comment by rawtaz** [comment]
This is a usage question which belongs in the forum instead of as an issue here.

The message tells you what you need to do - you should specify either *two* positive integer values in the format `X/Y`, or a percentage. You instead specified one integer value with a suffix.

This option is meant to specify how big part of the entire repository restic should check, and which of those equally sized parts. If you want to check e.g. the first fifth of the repository you specify `--read-data-subset=1/5`, and `--read-data-subset=2/5` for the second fifth, and so on.

**Comment by rawtaz** [comment]
@AlertSubject Did this help?

**Comment by solracsf** [comment]
This can also means you restic is not up-to-date...

**Comment by AlertSubject** [comment]
Thanks everyone for all the help and sorry for not updating before!
I've upgraded and will try again soon :)
