### ISSUE TITLE
Feedback after entering the repo password

### ISSUE THREAD

**Issue by Mebus** [restic/restic#438]
Hi!

After entering a password restic does not give any feedback if the password was correct. 
Please print something like "password correct, starting".

Mebus

**Comment by fw42** [comment]
Isn't the fact that it doesn't say "password is wrong" feedback enough that it was right?

**Comment by Mebus** [comment]
How do I know then if it isn't waiting for my network connection or something else to tell me 15 minutes later, that the password was wrong.

**Comment by rawtaz** [comment]
I agree that there should be some confirmation that downloading the index has started. I am now and then on a connection where it takes like 5 minutes to download the index before the actual backup starts. I have with time learnt that unless is says something else, it's probably fine once I entered the repo password, but I have many times wondered about the current status, and checked the network monitor to make sure it appears to do something.

I definitely think there should be some feedback.

Regards, Leo

12 feb 2016 kl. 19:32 skrev Mebus <notifications@github.com>:

**Comment by fd0** [comment]
We can probably add a line saying `password is correct`, but only for interactive terminals and when `--quiet` is not specified.

If anybody want's to implement this, I'll gladly accept a PR.

**Comment by mholt** [comment]
I'm a first-time restic user tonight, and I typed my password wrong (on purpose, just for kicks), and this is the output:

```
$ restic -r /tmp/backup backup .
enter password for repository: 
unable to open repo: no key could be found
```

"no key could be found" scares me, because to me, that means that my key was deleted or something, and my data is inaccessible. I would rather see "incorrect password" with the ability to retry.

As for a "correct password" notice: so far haven't seen it being necessary (but I haven't gotten through the user guide yet either!). In fact I think it would be weird to see one since most programs I type a password for don't say that I typed it correctly; they just print some output when they start a slow or long-running process.

**Comment by rawtaz** [comment]
The last point you raise is what the issue is about; ‎after entering the password restic starts downloading the index or something, and this can take a while. In some cases it can take 5-10 minutes. But even If it takes just one minute, it's weird that one doesnt know what's going on after entering the password correctly (when there's no output).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Från: Matt HoltSkickat: torsdagen den 10:e mars 2016 04:03Till: restic/resticSvara till: restic/resticKopia: rawtazÄmne: Re: [restic] Feedback after entering the repo password (#438)I'm a first-time restic user tonight, and I typed my password wrong (on purpose, just for kicks), and this is the output:

$ restic -r /tmp/backup backup .
enter password for repository: 
unable to open repo: no key could be found


"no key could be found" scares me, because to me, that means that my key was deleted or something, and my data is inaccessible. I would rather see "incorrect password" with the ability to retry.

As for a "correct password" notice: so far haven't seen it being necessary (but I haven't gotten through the user guide yet either!). In fact I think it would be weird to see one since most programs I type a password for don't say that I typed it correctly; they just print some output when they start a slow or long-running process.

—Reply to this email directly or view it on GitHub.

**Comment by fd0** [comment]
Thanks for your valuable feedback, I think we should make this more user friendly. So I propose changing the code so that
 * When a terminal is available (i.e. restic is run interactively), print a success message when the repo could be opened with the supplied password
 * Change the error message to something more appropriate like "unable to open repo: wrong password?"
Anybody up for a PR?

**Comment by CalderWhite** [comment]
@fd0 I'm up for a PR. Just understand the infrastructure.
