### ISSUE TITLE
--pack-size=4 Some packs are too oversized

### ISSUE THREAD

**Issue by opticoder** [restic/restic#4412]
Output of `restic version`
--------------------------
restic 0.15.2 compiled with go1.20.3 on linux/amd64

How did you run restic exactly?
-------------------------------
restic backup --pack-size=4 -o rclone.args="-v <...>" <...>

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone WebDAV

Expected behavior
-----------------
Pack sizes are less or slightly greater than 4MB

Actual behavior
---------------
Some pack sizes exceed 10MB (i.e. more than 2.5 times)

Do you have any idea what may have caused this?
-----------------------------------------------
packer_manager.go SaveBlob doesn't check future pack size before adding a blob

Do you have an idea how to solve the issue?
-------------------------------------------
Check future pack size before adding a blob and flush pack in case of oversize
I'm preparing a patch

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Great tool! I use it on a daily basis

**Comment by MichaelEischer** [comment]
What is the motivation for changing the current behavior? What problem should it solve? (I don't mean "the pack size might be larger than expected" here, that is only the technical implementation detail, but not the underlying motivation).

For full packs the PR would result in pack sizes between `[max(1, target_size - max_chunk_size), max(target_size, max_chunk_size)]` instead of the current `[target_size, target_size+max_chunk_size]`. With `--pack-size=4` this results in `[1B, 8MB]` instead of `[4MB, 12MB]` or a reduction of the maximum by 33%. The average file size likely shrinks by about 1MB (the average chunk size) (that's not a stochastically sound estimate), so I guess by about 20%. This will increase the number of files in the repository and likely also slow down data transfers due to a higher overhead.

Thus, I'm wondering what benefit you expect from changing the current packing strategy?

As a side remark: until #2446 is solved, there's nothing that will prevent restic from creating pack files that are hundreds of MB in size, even when `--pack-size=4` is specified.

**Comment by opticoder** [comment]
Thank you for your reply @MichaelEischer!

Let me explain the motivation from the particular to the general.
`As personally me`
The backend I use for a personal project (about 20GB of GitLab data) doesn't let uploading files exceed 10 MB over WebDAV (for free account). I used restic with it about a year successfully (thanks to restic compression great feature!): I just read in restic documentation about option --pack-size, set it to the minimal value (4MB) and as a plain user I was sure that pack files cannot exceed this value signifacally.
Until recently restic decided to make a pack size greater than 10MB.
`As a developer`
I see in the documentation that max blob size is 8MB and I make a logical conclusion that max pack size is 8MB given that --pack-size < 8.  But actually I get 12MB.
`As a user`
I want to control file sizes restic uploads to my backend. The only parameter I have is --pack-size and I hope it controls max pack size as gradually as possible: file sizes do not exceed it's value, if I want to have bigger files I just increase the value, and if I want file sizes less I lower the value.
`Outputs`
This patch helps to meet users expectations about file sizes restic uploads to a backend (considering with fixing https://github.com/restic/restic/issues/2446), makes the behaviour of the --pack-size more logical and lowers requirement to backend max file sizes from 12MB to 8MB.

As for the average file size I guess it can be tuned by increasing --pack-size

**Comment by MichaelEischer** [comment]
> As for the average file size I guess it can be tuned by increasing --pack-size

It could, however, that requires everyone using `--pack-size` to update the pack size or miraculously end up with more pack files than expected (which can be a problem with limits on the number of files) and slower up/downloads. So there's a cost to changing the interpretation of the parameter.

> The backend I use for a personal project doesn't let uploading files exceed 10 MB over WebDAV (for free account).

That looks like a very, very unusual use case. There's currently no way for the PR to guarantee that pack files don't exceed a specific size. Thus, I don't see the value of redefining `--pack-size` for everyone.

**Comment by MichaelEischer** [comment]
Until #2446 is merged, there's no way to guarantee any bounds on pack file size. Thus, there's no real benefit, but there are costs due to changed behavior. Therefore, I'm closing this issue for now.

**Comment by opticoder** [comment]
I've noticed your PR https://github.com/restic/restic/pull/4486, it addresses this issue also: fully solves my personal case and partially meets the described developer's expectation. I've switched from my patched to last restic version - work fine with my setup. Thanks a lot!
