### ISSUE TITLE
fuse mount losing sticky bit

### ISSUE THREAD

**Issue by MatthiasFoerste** [restic/restic#4481]
```
# mkdir r; dd if=/dev/random bs=32 count=1 of=p status=none; ./restic-0.16.0 version; ./restic-0.16.0 -q init -r r -p p; ./restic-0.16.0 -q -r r -p p backup /tmp; ./restic-0.16.0 -q -r r -p p mount /mnt
restic 0.16.0 compiled with go1.20.6 on linux/amd64
Now serving the repository at /mnt
Use another terminal or tool to browse the contents of this folder.
When finished, quit with Ctrl-c here or umount the mountpoint.

```

```
# rm -rf foo; cp -a /mnt/snapshots/latest/tmp foo; ls -lahd /tmp /mnt/snapshots/latest/tmp foo
drwxrwxrwx 14 root root 4,0K Sep 27 10:18 foo
drwxrwxrwx  2 root root    0 Sep 27 10:18 /mnt/snapshots/latest/tmp
drwxrwxrwt 14 root root 4,0K Sep 27 10:18 /tmp

```

I expected the sticky bit to be present on the /tmp directory in the fuse mount, but it wasn't.

**Comment by greatroar** [comment]
Clearly a defect in restic mount. The tarball from restic dump does have the sticky bit on the directory.

**Comment by gautammenghani** [comment]
I would like to help with this issue
@greatroar can you tell me how did you check with `restic dump` ? I don't see the sticky bit even with dump command
```
batman@fedora:~/fun/restic$ ./restic -r ../test dump latest tmp > dumpp.tar
enter password for repository: 
batman@fedora:~/fun/restic$ ls -lahd dumpp.tar 
-rw-r--r--. 1 batman batman 247K Dec 24 01:34 dumpp.tar
batman@fedora:~/fun/restic$ rm -rf tmp/
batman@fedora:~/fun/restic$ tar -xf dumpp.tar 
batman@fedora:~/fun/restic$ ls
build.go      cmd              doc     dumpp      go.mod         helpers   Makefile   restic  VERSION
changelog     contrib          doc.go  dumpp.tar  go.sum         internal  README.md  steps
CHANGELOG.md  CONTRIBUTING.md  docker  foo        GOVERNANCE.md  LICENSE   res        tmp
batman@fedora:~/fun/restic$ ls -lahd tmp/
drwxr-xr-x. 1 batman batman 1.1K Dec 24 01:35 tmp/
batman@fedora:~/fun/restic$ 

```

**Comment by gautammenghani** [comment]
I did RCA of this issue

1. This issue existed because in anacrolix/fuse@v0.2.0, sticky bit was silently just being dropped (SUID and SGID were maintained just fine). This issue was fixed in the commit - https://github.com/anacrolix/fuse/commit/d711f1e6391d975060229ebcd53168d6c012e74a
2. Restic is currently using v2 of this fuse library but the fix above is there in v3
3. I tried upgrading to v3 but it seems that it had issues working on linux (NOTE: The latest master of fuse works fine - https://github.com/anacrolix/fuse/commit/c6729d8bb2af377b5df04d4efdc425526cb764f3)
4. With the latest master, I can see the sticky bit persisting in the mounted directory

**Comment by MichaelEischer** [comment]
I've taken a closer look at the changes in v0.3 of the fuse library and found a few problems that are fixed in https://github.com/anacrolix/fuse/pull/6. These changes untested so far, as I don't have a mac anymore. Once the bugfixes (in particular the crash fix) have been merged, we could just go forward and bump the dependency.

**Comment by MichaelEischer** [comment]
Restic 0.17.0 will include version 0.3.1 of anacrolix/fuse, which includes the bugfix for the sticky bit.
