### ISSUE TITLE
Please add SHA512 support

### ISSUE THREAD

**Issue by rkarlsba** [restic/restic#4483]
Output of `restic version`
--------------------------
restic 0.16.0 compiled with go1.20.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
Please add support for SHA512. It's way faster than SHA256 on 64bit platforms.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Speed up backups

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Generally it works well, but it can always be improved upon.

**Comment by MichaelEischer** [comment]
> It's way faster than SHA256 on 64bit platforms.

This is not correct if hardware acceleration comes into play. One a AMD Ryzen 7 PRO 5850U CPU, sha256 can process 2GB/s (accelerated) whereas sha512 is limited to 800 MB/s.

Has anything changed since https://github.com/restic/restic/issues/372 to warrant another discussion?

> Speed up backups

How fast/slow is your backup? Without any numbers I have no way to assess whether it's worth the effort to think about this in more detail.

**Comment by rkarlsba** [comment]
There are a *lot* of machines out there with a less modern CPU than what you are referring to.

**Comment by MichaelEischer** [comment]
> There are a _lot_ of machines out there with a less modern CPU than what you are referring to.

Which just brings us back to #372 . Has anything changed since then, that would warrant another look?

**Comment by MichaelEischer** [comment]
Closing this issue as it's not worth breaking compatibility of the repo format.
