### ISSUE TITLE
Backup file owner and ACL on windows

### ISSUE THREAD

**Issue by Sch-Tim** [restic/restic#4509]
Output of `restic version`
--------------------------

restic 0.16.0 compiled with go1.20.6 on windows/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

According to the docs, restic isn't able to backup/restore file owners and ACL on windows. After a simple test, I can confirm that. 
I think that this would be an important and useful feature. 

The reasons for that are that as long as you aren't storing only user data on a single user machine, restoring after a disaster could be more time consuming than it needs to be as every user has to restore the data on himself. 
If it could be done by the person who reinstalls the system, it's a one step and even possibly automatic process. 

The other use case would be to restore data owned by the system or administrator user. 

What are you trying to do? What problem would this solve?
---------------------------------------------------------

I didn't try anything since the documentation says it's not possible. 

The question how to keep this kind of information when copying a file is not new and the standard answer seems to be using "robocopy.exe". 

I have to admit that I'm rather new to go, but I tried to understand the backup process a bit and it seems that the file isn't simply copied into the repository but somehow bitwise read and rewritten, so using robocopy won't be a solution. 

Extra information
---------------------------------------------------------
This is not meant as a simple feature request. I'd like to participate to this project and out of egoistic reasons this could be my first try. 
My question is if there are already ideas how one could tackle this or even failed attempts. 
Looking through the open issues, I couldn't find anything pointing in that direction.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm using restic on my Linux server since a while and I'm pretty happy with it. 
Now I want to convert from my current somehow sh'tty backup software on windows to restic and I have some trouble to adjust it to my needs.

**Comment by hgraeber** [comment]
I am interested in this, too, and willing to help. Here some hints:

My idea is to store the SDDL for each directory and file item (File taken from the small-repo test data file):
```pwsh
❯ get-acl .\testdir\bar | Format-List -Property PSPath, Sddl
PSPath : Microsoft.PowerShell.Core\FileSystem::C:\Users\Myself\restore\testdir\bar
Sddl   : O:S-1-5-21-2235380413-24826354-127642980-1104G:DUD:AI(A;ID;FA;;;S-1-5-21-2235480413-24
         826354-127632980-1104)(A;ID;FA;;;SY)(A;ID;FA;;;BA)
```
The SDDL contains owners (as SID) and the ACL in a compact text form.

Looking into the restic data, this can look like this:

```pwsh
❯ restic -r repo cat blob 5aa546ea2d35a48be6e10096b4fa8814804579232b428f83a6fdc33db1d839a9 | jq
enter password for repository:
{
  "nodes": [
    {
      "name": "bar",
      "type": "file",
      "mode": 420,
      "mtime": "2015-11-10T22:10:02.241109978+01:00",
      "atime": "2015-11-10T22:10:02.241109978+01:00",
      "ctime": "2015-11-10T22:10:02.241109978+01:00",
      "uid": 1000,
      "gid": 100,
      "user": "fd0",
      "sddl": "O:S-1-5-21-2235380413-24826354-127642980-1104G:DUD:AI(A;ID;FA;;;S-1-5-21-2235480413-24
         826354-127632980-1104)(A;ID;FA;;;SY)(A;ID;FA;;;BA)",
      "inode": 336378303,
      "size": 4,
      "links": 1,
      "content": [
        "7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730"
      ]
    },
    # ...
}
```
For this the FS interface has to be extended with functions to get and set the SDDL. Those are no ops for most file systems and access the SDDL of files and folders for file systems that know about them.

On Backup, if a SDDL is available it shall be stored additional to uid, gid etc. On restore the SDDL shall be preferred for restore, if it is possible to set one, else the uid, gid, etc will be restored like it is now. 

You see, I am half way to implement this but haven't found time yet.

**Comment by Sch-Tim** [comment]
That's nice and goes in a similar direction like my idea. But yours is much more sophisticated. 
Did you write any code yet you could share with me?

**Comment by hgraeber** [comment]
Yes. This is the package "golang.org/x/sys/windows". With the functions `GetNamedSecurityInfo` it is easy to get the SDDL. With `SecurityDescriptorFromString` and `SetNamedSecurityInfo` one can restore the SDDL for some file.

The latter needs the components (owner, group, DACL, and SACL) separately. I take that as a hint that we shall add an option to `restic restore`, which makes it possible to select those components from command line.

**Comment by MichaelEischer** [comment]
Fixed by https://github.com/restic/restic/pull/4708

**Comment by luyaozou** [comment]
Hello, I am new to restic. This software is great with its deduplication and backup capabilities! I want to use it to synchronize my files between computers and also create cold backups.
I encountered a problem related to this issue. Actually, it is the opposite to what was proposed and added to restic in this PR. I do not want to restore file owners and ACL on windows. I fully support adding this feature as it is useful in other cases. I simply want to know how to not be restoring these metadata when I need to. 
I have this need because I am synchronizing files between two computers, which are of different username and user group (because one is from my working group and another one is personal). The files are the same. But when I restore from S to D, by default the metadata of source S overwrite the ones of destination D, which causes the restored files on D inaccessible (owner becomes an unrecognized one on the S system). 
I can run 
`takeown  /R /F D:\workdir
icacls   D:\workdir /T /C /Q /RESET`
under administrator mode to restore ownership. By doing so every time seems not to be an ideal practice. 
I tried to use `--exclude-xattr=` option to exclude some attributes. I tried `system.*`, `user.*`, `group.*`, `security.*`. None of them worked. 
A related problem to this is that since none of these options worked, the files were first restored with the ownership from the source computer S, and then an error would occur saying restic is unable to update the timestamp of the restored files, access denied (which is logical, because now i am using owner D to access files from owner S). This problem also marks the failure of a complete restorage, as even I can reset the file ownership to D, the timestamps of these files became the time of the restorage, not the original timestamps. This will cause problems in incremental backup and synchronization (with the option `--overwrite if-new` for example).

I am on Windows computer. I can also imagine if one wants to synchronize files between computers from different OS, this would occur as well. Things will only be more complicated. 

I wish someone in the community can help me answer this question. A solution may have already existed, but I cannot find it.

**Comment by zumm** [comment]
@luyaozou Did you find a solution?

**Comment by luyaozou** [comment]
@zumm No I did not find a solution, unfortunately. Do you have any ideas ?

**Comment by zumm** [comment]
> Do you have any ideas ?

From what i see in source, only option here is to use unprivileged user to make backups. This prevents security descriptors from backing up. This is not ideal tho, since we need privileges to use vss.

I guess best solution is described here #3572
