### ISSUE TITLE
Restic 0.16.3 issue on Windows 7

### ISSUE THREAD

**Issue by tiker** [restic/restic#4636]
Did the new version of Restic 0.16.3 drop support for Windows 7?

Running 0.16.2 worked fine.  Updated to 0.16.3 with ``restic self-update``:
```
C:\Users\tiker>c:\apps\restic\restic.exe self-update
writing restic to c:\apps\restic\restic.exe
find latest release of restic at GitHub
latest version is 0.16.3
download SHA256SUMS
download SHA256SUMS.asc
GPG signature verification succeeded
download restic_0.16.3_windows_amd64.zip
downloaded restic_0.16.3_windows_amd64.zip
saved 25019392 bytes in c:\apps\restic\restic.exe
successfully updated restic to version 0.16.3
```

After this, all attempts to run restic.exe fail with an error which would appear to be related to compiling issues or dropping support for Windows 7 (which I don't see mentioned in the release notes).

I have manually downloaded the file from the Github release page and attempted to run it, still fails with the following:
```
C:\Users\tiker>c:\apps\restic\restic_0.16.3_windows_amd64.exe version
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /usr/local/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x
22fc80 pc=0x46d335
rax     0x0
rbx     0x1b5e300
rcx     0x1bb4100
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x1b855b8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x1b5da60
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```
Previous version:
```
C:\Users\tiker>c:\apps\restic\restic.exe version
restic 0.16.2 compiled with go1.21.3 on windows/amd64
```

**Comment by DRON-666** [comment]
It's not `restic` but a `go` compiler. You can recompile `restic` with old `go1.21.3` or recompile `go1.21.6` compiler itself, but revert [this](https://go-review.googlesource.com/c/go/+/545355) commit.

**Comment by DRON-666** [comment]
@tiker You can try this `cmd/bat` script:

```cmd
@echo off
set RESTIC_URL=https://github.com/restic/restic/releases/download/v0.16.3/restic-0.16.3.tar.gz
set GO_BIN_URL=https://go.dev/dl/go1.21.3.windows-amd64.zip
set GO_SRC_URL=https://go.dev/dl/go1.21.6.src.tar.gz
set BAD_COMMIT_URL=https://github.com/golang/go/commit/9e43850a3298a9b8b1162ba0033d4c53f8637571.diff
set BUSYBOX_URL=https://frippery.org/files/busybox/busybox64.exe
set BUSYBOX="%~dp0busybox64.exe"
if not exist %BUSYBOX% powershell -Command (New-Object System.Net.WebClient^).DownloadFile('"%BUSYBOX_URL%"','"%BUSYBOX%"'^)
if not exist go1.*.windows-amd64.zip (%BUSYBOX% wget %GO_BIN_URL% || exit)
if not exist go (%BUSYBOX% unzip -q go1.*.windows-amd64.zip || exit)
if not exist go1.*.src.tar.gz (%BUSYBOX% wget %GO_SRC_URL% || exit)
if not exist src (md src && %BUSYBOX% tar x -z --strip-components 1 -C src -f go1.*.src.tar.gz || exit)
pushd src
if not exist *.diff (%BUSYBOX% wget %BAD_COMMIT_URL% && %BUSYBOX% patch -p 1 -R -i *.diff || exit)
pushd src
if not exist ..\bin\go.exe (set GOROOT_BOOTSTRAP=%~dp0go&& call make.bat || exit)
popd && popd
if not exist restic-0.*.tar.gz (%BUSYBOX% wget %RESTIC_URL% || exit)
if not exist restic (md restic && %BUSYBOX% tar x -z --strip-components 1 -C restic -f restic-0.*.tar.gz || exit)
pushd restic && set path=%~dp0\src\bin&& go.exe run build.go && move /y restic.exe .. && popd
```

Just put it in `C:\restic`, run it and in about 15 minutes you will get `restic.exe`.

**Comment by stunndard** [comment]
try this if you don't want to build it from source every time: https://github.com/stunndard/golangwin7patch

**Comment by DRON-666** [comment]
@stunndard unfortunately fixing `ProcessPrng` is not enough: you should fix `exec_windows.go` (need for at least `rclone` backend support) and `dir_windows.go` (need for FAT formatted flash drive support). I think you can achieve this by hooking `CreateProcess` and `GetFileInformationByHandleEx` from you library.
See [this gist](https://gist.github.com/DRON-666/6e29eb6a8635fae9ab822782f34d8fd6) for details.

**Comment by stunndard** [comment]
@DRON-666 thanks! I'm willing to implement this, just need to find a decent hooking library that is public and free. Meanwhile, could you please provide (if possible) a minimal Go test program that fails on Win7 for both cases: https://github.com/stunndard/golangwin7patch/issues/1 and https://github.com/stunndard/golangwin7patch/issues/2

**Comment by mchvs** [comment]
If it helps, before commit `b5c28a7ba`, one can just run `git revert ad48751ad --no-commit` to get restic 0.17.1 cross compiled to Windows 7 using Go 1.20.

**Comment by flawrist** [comment]
> @MichaelEischer
> However, as the go compiler has dropped support for Windows 7 and does not intend to change that, there's not much we can do.

<details>
  <summary>Yes, you can! (click to read how)</summary>
  
You, active contributors and maintainers with famous names and starred repos, could stand up for your user base. For all those simple chaps over the globe who depend on Restic for secure backup. You could collectively say "F* you, Go team, you're traitors" via their issue tracker, via Reddit, via HackerNews. Those golden boys and girls should travel outside the rich ghettos of US & EU more often in order to see the [sad state](https://en.wikipedia.org/wiki/Favela) of the world where upgrades don't happen regularly. You did not stand up for us, you swallowed.
    
</details>

### Download [Restic v0.18.0 for Windows 7 x64](https://github.com/user-attachments/files/19527508/restic_v0180_wiin7x64.zip)

**Comment by rawtaz** [comment]
@sergeevabc Look, I get that you are frustrated. Fine. But the restic developers are not responsible for the deprecation of Windows support in Golang (which I recognize is not what you are saying).

I also understand that you feel that as part of the Golang ecosystem, the restic project should put more pressure on the Golang project to make a change in the status quo regarding the Golang project's decision to stop supporting Windows 7. Fine.

But please - the developers of restic does not deserve the words that you just threw at them. They have spent countless days, weeks, months working on this software, year after year. Hence, the way you put forth the criticism is uncalled for.

It is indeed sad that there is no longer any Windows 7 support in current Golang versions, but I kindly ask that you try not to take out the frustration over decisions made in other projects on this project, even if you think more could have been done to affect the outcome.

On a positive note, thanks to someone else's hard work the Golang patches you used can build restic for Windows 7, as you showed above. Your post could have focused more on that, and the splendid instructions you provided in your example above.

Let's all be friends, and try to make the best of things. Sometimes that includes using additional tooling to work around situations originating upstream. Thank you for showing how easy it seems to be to do that.

**Comment by sergeevabc** [comment]
@rawtaz Sweetening the communication and glossing over the lack of balls is exactly why this situation happened. Some people live in ignorance of the fact that a person plays multiple roles throughout his or her life. And, of course, they are shocked when suddenly someone reminds them of this, much less rebukes them for not doing well in a particular role. For example, you can be a diligent student and obedient son, but a unfaithful husband. It's exactly the same here: professional coders share great programs for free, but they chose to bury theirs heads in the sand (when they need to prove themselves in a different role — defender of common sense and justice. And I didn't learn to speak and write in order to to keep silent about how their indifference contributes to suffering. We can't stop wars, but surely we can say NO when Go team releases a compiler that cuts thousands poor souls from apps. If you need Windows 3000 and DirectX12-capable GPU to drive it to launch a backup program or even a calculator, this is not progress, because because you could run a calculator even in DOS on an 80286 with 2MB of memory. And someone has to stand up and say: WTF is going on?

**Comment by MichaelEischer** [comment]
@sergeevabc As you've already been told in the past, this style of communication is not acceptable. I absolutely don't object to pointing out that some decisions cause problems for certain users, but not in this tone.

> You, active contributors and maintainers with famous names and starred repos, could stand up for your user base.

Even after reading this several times, I'm unsure whether this just takes being direct to the extreme or whether it is a poorly disguised insult. Either way, if you want someone to join your cause this won't help.

> but they prefer to bury their heads in the sand when they need to prove themselves in a different role — the defender of common sense.

"common sense" is not some objective universal criteria. In countries that depend more and more on their IT infrastructure it's becoming common sense to properly secure their systems by keeping them up to date and by replacing or isolating legacy systems. Whether certain operating systems should bump their system requirements as aggressively as they do is a different question though.

**Comment by DRON-666** [comment]
@deajan Unfortunately, your "legacy" build does not work on `Win7`, because your script just downloads original `go1.23`, but not patched `go1.21` (see official docs and [this blog post](https://kokada.dev/blog/quick-bits-go-automatically-downloads-a-newer-toolchain-if-needed/) for details).
But [here](https://gist.github.com/DRON-666/6e29eb6a8635fae9ab822782f34d8fd6) you can find latest version (`go1.24.2`) of the script.

**Comment by deajan** [comment]
@DRON-666 I actually just followed your old recipe script.
I have a hard time understanding what your current script does. Why do you need go 1.23 __AND__ go 1.24 sources ?

**Comment by DRON-666** [comment]
>Why do you need go 1.23 AND go 1.24 sources ?

You [cannot use](https://tip.golang.org/doc/go1.24#bootstrap) `go1.21` for bootstrap `go1.24`.

This script designed to work on `Win7`, if you run it on `Win10/11` you can remove bootstrap from `go1.21` to `go1.23` and even replace `powershell` and `wget` by `curl` (supported since `Win10` build 17063).

**Comment by deajan** [comment]
@DRON-666 Thank you for the details.
So I took your current script and updated it again to build both 386 and amd64 targets, add restic version support, logging, and confining everything in a build root.

Results can be seen here:
https://github.com/netinvent/npbackup/blob/main/RESTIC_SOURCE_FILES/legacy_restic_builder.cmd

I've had fun time adapting it. Thank you for your effort, must have been quite fun writing it.

Built executables will be kept uptodate in https://github.com/netinvent/npbackup/tree/main/RESTIC_SOURCE_FILES
Current executables direct links:
https://github.com/netinvent/npbackup/raw/refs/heads/main/RESTIC_SOURCE_FILES/restic_0.18.0_windows_legacy_386.exe
https://github.com/netinvent/npbackup/raw/refs/heads/main/RESTIC_SOURCE_FILES/restic_0.18.0_windows_legacy_amd64.exe

Hopefully this might help other "old" restic customers.

**Comment by deajan** [comment]
Well, someone at my work with better Go Skills(TM) than mine has pointed out that using go1.21 to build go1.23 to build go1.25 is only necessary if you plan to build from Windows 7.
Hence, I've modified my restic builder script in https://github.com/netinvent/npbackup/blob/main/RESTIC_SOURCE_FILES/legacy_restic_builder.cmd to just download latest go1.25 compiler and make restic binaries for Win7.
This should obviously speed up compilation by an order of magnitude.
Of course, the script needs to run on Windows 10 or better.

Yet, another solution he has pointed out is to build on any linux with target Windows 7 since go does cross compiling.
Here's another script for linux: https://github.com/netinvent/npbackup/blob/main/RESTIC_SOURCE_FILES/legacy_restic_builder.sh

Both scripts do build byte identical restic versions.
I'll keep restic legacy builds uptodate as long as I can support Windows 7 in my project at https://github.com/netinvent/npbackup/tree/main/RESTIC_SOURCE_FILES

**Comment by wplapper** [comment]
Since this PR is closed as "not planned", why is it still pinned at the top of all the issues? Just a question.

**Comment by flawrist** [comment]
> @wplapper
Since this PR is closed as "not planned", why is it still pinned at the top of all the issues? Just a question.

Perhaps this is pinned so Windows 7 users can find links to unofficial builds by enthusiasts like me instead of opening duplicate issues. By the way, it is time to share the latest version.

### Download [Restic v0.19.1 for Windows 7 x64](https://github.com/user-attachments/files/31523658/restic_v0.19.1_win7x64.zip)
[VirusTotal](https://www.virustotal.com/gui/file/5fe49db9882cc25cf87d358915bf1f5be89d23a0d0e65708ae0e8770d310aa03?nocache=1): 0/66, [VirScan](https://www.virscan.org/report/5fe49db9882cc25cf87d358915bf1f5be89d23a0d0e65708ae0e8770d310aa03): 0/48, [Jotti](https://virusscan.jotti.org/en-US/filescanjob/u9uqsqdkuf): 0/13
