### ISSUE TITLE
Error create backup restic

### ISSUE THREAD

**Issue by petrealiviu** [restic/restic#4791]
Files: 46678 new, 44211 changed, 4844618 unmodified
Dirs: 0 new, 0 changed, 0 unmodified
Added to the repo: 2.244 GiB
processed 4935507 files, 232.646 GiB in 10:49
snapshot t1de2f721 saved
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at https://github.com/restic/restic/issues/new

**Comment by MichaelEischer** [comment]
You're using a very old restic version (probably 0.9.6), we've rewritten the `prune` command to be both much faster and more reliable since then. Please upgrade to a newer version. If the problem persists, open a new issue and fill out the template at https://github.com/restic/restic/issues/new?assignees=&labels=&projects=&template=Bug.md .

**Comment by petrealiviu** [comment]
Thanks!

ср, 1 мая 2024 г. в 13:37, Michael Eischer ***@***.***>:
