### ISSUE TITLE
Backup to B2 locks up - `Save() returned error: Copy: context canceled`

### ISSUE THREAD

**Issue by pfych** [restic/restic#4797]
Output of `restic version`
--------------------------
`restic 0.16.4 compiled with go1.21.6 on darwin/amd64`

What backend/service did you use to store the repository?
---------------------------------------------------------
Backblaze B2

Problem description / Steps to reproduce
----------------------------------------

Running the following script on a 2TB directory:

```sh
restic --pack-size 128 -r b2:bucket:/ -i b2.connections=200 --read-concurency 16 backup /Volumes/storage
```

After about 10 minutes restic gets stuck on a group of files and no longer progresses any further.

Occasionally the following is printed to the console:

```
Save(<data/fada57369e>) returned error, retrying after 361.405234ms: Copy: context canceled
Save(<data/64362a6e44>) returned error, retrying after 479.441064ms: Copy: context canceled
Save(<data/a5dce8f26e>) returned error, retrying after 579.562512ms: Copy: context canceled
Save(<data/5dfe5ab906>) returned error, retrying after 274.800222ms: Copy: context canceled
```

_**Edit:**_ Reducing `-i b2.connections` to `100` makes the lockup happen earlier (at about 800 files in vs at about 1585 files in)

Expected behavior
-----------------

The backup should continue though all files

Actual behavior
---------------

The backup gets stuck on some files

Do you have any idea what may have caused this?
-----------------------------------------------

I'm unsure what the issue may be - Restic has full access to this directory and originally worked when I was using `rclone` to google drive. This is only occurring now that I'm attempting to swap to B2.

From a quick glance of other tickets it could potentially be a timeout issue? I increased `--read-concurency` from `8` to `16` and it made it 3 files further. It seems to hang on the same group of files after canceling and trying again.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

When it's working my backups are set and forget! Only fiddling with it since I ran out of google drive space 😅

**Comment by MichaelEischer** [comment]
> _**Edit:**_ Reducing `-i b2.connections` to `100` makes the lockup happen earlier (at about 800 files in vs at about 1585 files in)

That sounds like your upload to B2 doesn't work at all. Are you able to upload a file to B2 using rclone? We've seen similar problems a few times when the DNS records of some B2 servers were redirected/filtered.

```
restic --pack-size 128 -r b2:bucket:/ -i b2.connections=200 --read-concurency 16 backup /Volumes/storage
```

There's a typo in that command line (probably only in the description here?), it should be `-o` instead of `-i`. It doesn't make sense to increase the number of B2 connections this much (the default is 5 (!) ), just remove that setting.  With your current settings restic can require about 30GB of temporary disk space during backups. Please also remove `--read-concurrency`;  it doesn't help here and unless you have a multi gigabit upload link to B2 it won't help in any way.

> Occasionally the following is printed to the console:

There's too much context missing to interpret that log output. Please provide all log output before and including the _first_ occurrence of `context canceled`.

> Backblaze B2

The recommendation by now is to use the S3 interface of B2, see also https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#backblaze-b2 . There are unfortunately several issues in the library we use  for B2 which are unlikely to be resolved.

**Comment by pfych** [comment]
I made those suggested changes to the command and its working now. 
I think I mistakenly assumed that the output of `--verbose=2`:
```sh
new       /storage/DSCF0011.RAF, saved in 155.316s (155.907 MiB added)
new       /storage/DSCF0013.JPG, saved in 154.123s (11.442 MiB added)
new       /storage/DSCF0012.RAF, saved in 168.602s (155.253 MiB added)
new       /storage/DSCF0017.JPG, saved in 14.630s (13.804 MiB added)
new       /Vstorage/DSCF0013.RAF, saved in 31.757s (156.158 MiB added)
new       /storage/DSCF0017.RAF, saved in 53.001s (157.586 MiB added)
new       /storage/DSCF0018.JPG, saved in 52.920s (12.139 MiB added)
```
 meant the file had uploaded to remote and that when it got "stuck" it was really just waiting on the upload.

Is there any way to potentially show upload progress of chunks so it doesn't look like the backup is "stuck"? Restic sitting on two files for 5-10 minutes while an upload happens and the ETA rises can seem like somethings broken:
```
new       /storage/DSCF0017.RAF, saved in 53.001s (157.586 MiB added)
new       /storage/DSCF0018.JPG, saved in 52.920s (12.139 MiB added)
[6:26] 0.75%  776 files 1.934 GiB, total 11194 files 257.565 GiB, 0 errors ETA 14:11:09
/backup/DSCF0020.RAF
/backup/DSCF0023.RAF
```

Regardless I'm glad that my backups are working now - thank you for your help and apologies for the confusion!
