### ISSUE TITLE
Document what to do when `restic check` finds errors

### ISSUE THREAD

**Issue by e00E** [restic/restic#4801]
Apologies if this more suited for the forum. I feel this is a bug with the documentation. I am not looking for help with my specific repository. I am reporting that the documentation is lacking.

When I recently ran `restic check --read-data` I got error messages like:
- Pack ID does not match, want {pack-id}, got {other-pack-id}
- pack {pack-id} contains 1 errors: [blob {blod-id}: ciphertext verification failed]

From the context of the check command, I can understand that some data in the repository is corrupted. I do not understand the following things:

- How serious is this?
- What should I do about it?
- What will happen when I try to restore files that belong to these packs?
- Can I continue to use my repository?

I could not find more information about these questions on the docs website. I feel that in order for `restic check` to be useful, these questions should be addresses. The only related page is [this](https://restic.readthedocs.io/en/stable/045_working_with_repos.html#checking-integrity-and-consistency) but it does not contain enough information to answer these questions for a user not familiar with restic internals.

**Comment by MichaelEischer** [comment]
There's already quite a bit of documentation at https://restic.readthedocs.io/en/stable/077_troubleshooting.html . Although some of your high-level question remain unanswered.

> When I recently ran `restic check --read-data` I got error messages like:
> 
>     * Pack ID does not match, want {pack-id}, got {other-pack-id}
> 
>     * pack {pack-id} contains 1 errors: [blob {blod-id}: ciphertext verification failed]

In the next restic version, `check` will provide instructions on how to run `restic repair packs ...` to fix those errors. The code to fix these problems semi-automatically only exists since restic 0.16.4, at which point it was still somewhat experimental and therefore barely documented.

> * How serious is this?

As long as check states that "repository contains errors" then restoring some files/folders won't work. Depending on the exact damage it may even be impossible to restore anything. The repository can usually be repaired (see the troubleshooting docs) but until then it may or not be possible to restore the data you need from the backup. The damaged parts can obviously end up being unrecoverable, but everything else in a snapshot will remain accessible.

**Comment by e00E** [comment]
Thanks for your answer! It's a good idea to make the Check command explain this. When I was looking through the documentation website, it didn't occur to me to click on the Troubleshooting page. It would be nice to link to that page from the [Check page](https://restic.readthedocs.io/en/stable/045_working_with_repos.html#checking-integrity-and-consistency).
