### ISSUE TITLE
restic cat snapshot latest not working

### ISSUE THREAD

**Issue by AlBundy33** [restic/restic#4943]
restic 0.17.0

currently only "real" snapshot-ids are supported
```
r cat snapshot latest
repository 66fd5f9c opened (version 2, compression level auto)
Fatal: could not find snapshot: no matching ID found for prefix "latest"
```

**Comment by MichaelEischer** [comment]
`cat` currently does not support filtering by hostname etc. So the snapshot name `latest` isn't particularly useful here. In addition, `cat` by design returns the file content stored in the repository without modifications. This means that it would be impossible to know which snapshot was returned (no, you can't simply calculate the sha256 of the snapshot content to get its ID).

You can use `restic snapshots latest --json` instead. That also includes the full snapshot metadata, but also adds the snapshot ID to it. As a bonus the command  can also return multiple snapshots at once.
