### ISSUE TITLE
[Regression] restic 0.17.0 on Windows: cannot backup using network drive

### ISSUE THREAD

**Issue by SommerEngineering** [restic/restic#4955]
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
A network share mounted as drive H

Problem description / Steps to reproduce
----------------------------------------
On my employer's computer, I need to back up my data to a network drive, which is mounted locally as drive `H`. My `restic` command backs up files from both my local hard drive and the target drive itself. So, in addition to the backup, other data is also stored on the network drive. This worked flawlessly with `restic` up to version 0.16.x. However, since version 0.17.0, the following error message appears:

```
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
``` 

My command:
```
restic --repo H:\Backup backup --exclude-caches --iexclude-file="c:\Users\xxx\backup-ignore.txt" --files-from="c:\Users\xxx\backup-resources.txt" --tag main --tag data --compression=auto --read-concurrency=6
```

The entire output looks like this:
```
pattern "c:\\Users\\xxx\\AppData\\Roaming\\Sublime Text 3\\Local\\" does not match any files, skipping
enter password for repository:
repository 6b02e3c8 opened (version 2, compression level auto)
found 1 old cache directories in C:\Users\xxx\AppData\Local\restic, run `restic cache --cleanup` to remove them
using parent snapshot 9e08dbd0
[0:00] 100.00%  13 / 13 index files loaded
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
```

Expected behavior
-----------------
The backup to and from the network drive should work.

Actual behavior
---------------
No snapshot will be created, Instead, we got this error:
```
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
``` 

Do you have any idea what may have caused this?
-----------------------------------------------
@MichaelEischer mentioned on the [forum](https://forum.restic.net/t/backing-up-data-on-windows-from-smb-share-to-local-drive/8095): `This looks like a potential bug in the new metadata collection changes in restic 0.17.0`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic makes me happy: Finally a reliable backup software I can rely on. It also runs on all my systems: Linux, Windows, and macOS. Thank you very much for your work and all the time you have invested in the software.

**Comment by phil737** [comment]
I have exactly the same problem, had to revert to 0.16

**Comment by LinderNet** [comment]
- same problem with WinFSP mounted drives (as restic backup source)
- same problem with Dokan(y) mounted drives (as restic backup source)

**Comment by MichaelEischer** [comment]
I've tried to reproduce this issue on Windows 10 but did not run into issues. My network share is hosted on a Raspberrypi using Samba 4.17 mounted via SMB2/3. What servers are used in your cases to provide the network share?

> Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.

If the problem is limited to reading extended attributes from `h:\` then we could just ignore them. There's not much point in keeping them for the drive itself. Please try the following: navigate to a folder within `h:\` and then run `restic backup .` to backup the current folder. By using a relative path, restic won't try to read information from the drive. Is restic then able to complete the backup? Or does the same error show up again?

I'm wondering whether this might also be a case like on other operating systems where network shares tend to return very weird error codes if they don't support some feature.

**Comment by aneesh-n** [comment]
I was able to reproduce this on a Windows 11 system by trying to back up a folder from an SMB share.
However, in my case the cause of the error was different -
Fatal: unable to save snapshot: nodeFromFileInfo \\...\: get EA failed for path \\...\, with: get file EA failed with: Element not found.
This error has errno windows.E_NOT_SET and I think "Incorrect function" has errno windows.ERROR_INVALID_FUNCTION.
One option would be to ignore such errors and skip EA, but instead of eating such errors we could initially determine if the volume supports EA and skip EA processing if it does not. 
I have created for PR for this implementation. 

It would be great if you could test this PR on your end as well, as it's hard to catch such errors without extending our integration tests to cover such scenarios as well.

**Comment by drequeary** [comment]
Using a UNC path like \\nas\videos works with 0.17.0.

**Comment by aut0** [comment]
> Using a UNC path like \nas\videos works with 0.17.0.

Doesn't work for me:
```
C:\Users\redacted\Desktop\restic>restic.exe -r D:\local_repo backup \\192.168.178.1\fritz.nas\folder_to_backup
enter password for repository:
repository 1abe79a7 opened (version 2, compression level auto)
no parent snapshot found, will read all files
[0:01] 100.00%  81 / 81 index files loaded
Fatal: unable to save snapshot: nodeFromFileInfo \\192.168.178.1\fritz.nas\: get EA failed while opening file handle for path \\192.168.178.1\fritz.nas\, with: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
```

**Comment by LinderNet** [comment]
Everythin works fine with "restic_v0.17.2-257-g408ec41a1_windows_amd64.exe".
Thanks!
