### ISSUE TITLE
restic doing local backup on MacOS with a disk that sometimes disconnects then reconnects just after has a strange behavior

### ISSUE THREAD

**Issue by stephane-archer** [restic/restic#4972]
restic doing local backup on MacOS with a disk that sometimes disconnects then reconnects just after has a strange behavior 

The backup gets block but the timer continues to be updated and when you control C it cleanup for ever.

Restic should detect the files are gone and should:
- stop with an error message 
- or sleep a bit and retry the file access to continue 

It should not stay blocked forever waiting for a file that will never finish been fetched 

I hope this description is understandable, please feel free to ask questions

**Comment by stephane-archer** [comment]
The files are local (main drive) and the Restic repository is on an external hard drive that sometimes disconnects (the joy of usb-c hubs)

**Comment by MichaelEischer** [comment]
Judging from your description, it's actually macOS that is to blame for restic being blocked. 

> Restic should detect the files are gone and should:
> 
>     * stop with an error message
> 
>     * or sleep a bit and retry the file access to continue

restic iteratively asks the OS to return the content of folders and the contained files. If those folders/files suddenly become inaccessible, then the OS has to return an error instead of hanging indefinitely. So I don't think there's anything we can do here.

> restic doing local backup on MacOS with a disk that sometimes disconnects then reconnects just after has a strange behavior

Honestly, that really sounds like a bad cable.

**Comment by MichaelEischer** [comment]
Closing as I don't think there's anything we can do here.
