### ISSUE TITLE
sftp on windows

### ISSUE THREAD

**Issue by flibustenet** [restic/restic#505]
I'm sorry to ask a maybe not related question to restic.
What is the simplest way to use sftp on windows ? I know putty i cannot make it work with restic.

Maybe it's on the roadmap to don't need any external ssh cmd ?

**Comment by fd0** [comment]
Hey, thanks for the suggestion. At the moment, restic depends on an external command `ssh` so that we do not have to manage the ssh configuration, which is rather complex. It's not planned, but there is the possibility to use an internal ssh implementation. but we'll tackle that problem later.

**Comment by burritts** [comment]
I'd like to share some information regarding using plink.exe (from the Putty family) for sftp on Windows:

I hacked src/restic/backend/sftp/sftp.go to look for a couple of environment variables that give the location of the plink executable and my private key ppk file, and if they are defined construct the ssh command line like so:

/path/to/plink.exe -s -l username -i /path/to/myprivatekey.ppk hostname sftp

I have not done extensive testing, but listing snapshots, backup, and restore seem to work.  "restic init" fails with "ssh": executable not found, so obviously there's another spot that needs some work to use plink.exe instead of the hardcoded "ssh".
