### ISSUE TITLE
AWS Access Keys

### ISSUE THREAD

**Issue by MatthewVance** [restic/restic#521]
I really like what you've done on the security front based on what I've read in the documentation and the little bit I've looked at the code. One concern I have though is the requirement to store AWS access keys for the S3 bucket in environment variables. Environment variables don't seem like a safe place to store secrets like credentials. Would you consider adding a feature like a more storage mechanism (a file with strict access permissions) or provide a prompt for users to manually input the keys when run so they're only ever stored in memory?

**Comment by fd0** [comment]
Thanks for your concern. We had a similar discussion in https://github.com/restic/restic/issues/278.

I'm not convinced that storing a secret in an environment variable is such a bad thing. The only valid case (from the discussion of #278) in my opinion is when you have a logging/monitoring system which regularly dumps the environment of all processes.

Otherwise, let's consider the attackers that are relevant here:
 * System admin: Attackers with root privileges can not only read the environment of all processes, but also the memory of each process and all files on the system. Reading the password from a file won't help here, since the file itself can just be read.

 * Attackers running code as the same user: In case the system user is compromised, but the attackers did not manage to elevate to root. They can read the environment of the restic process (via `/proc/pid/environ`) and the memory (via `/proc/pid/mem`, ptrace, and possibly by crashing the process). If the password is read from a file, the user running restic needs to be able to access this file, so the attackers can also read it.

 * Attackers running code as a different user on the same machine: Here, it is not possible to either read a password file or read the environment (because of the default access permissions of `/proc/pid/environ`, which are 0400). The memory can also not be read, nor can a signal be sent to the restic process.

From the list above I conclude that reading a password from a file is as secure as reading the password from the environment is (from a security-focused viewpoint). The only exception is the monitoring system logging the environment, but I think that's rather uncommon.

From a usability perspective I think it's valuable to be able to read the password from a file.

Did I miss anything? Do you agree?

**Comment by MatthewVance** [comment]
Thank you for the detailed response. You made some good points, and I believe AWS even recommends using Environment Variables. All that being said, I'm still not a fan of storing passwords on disks in an unencrypted form but concede the environment variable in this case is as secure as storing it in a file. I know it's more code to maintain, but having both multiple password options might be a good future enhancement.  

I originally brought this up because I became familiar with this concern when researching it after seeing some Docker images recommend it and not being sure it was good idea. This [Docker issue] (https://github.com/docker/docker/issues/13490) outlines some of the concerns. To be fair though, those concerns don't readily map to restic because it's nothing like a container use case (i.e., not a system designed for portability and isolation).

Also, sorry for missing #278. I must have missed it when looking through existing issues.

**Comment by MatthewVance** [comment]
Here's a couple of more links that talk about the security implications of environmental variables and passwords if you're interested:
- http://movingfast.io/articles/environment-variables-considered-harmful/
- https://superuser.com/questions/708355/is-it-safe-to-store-critical-passwords-in-server-environment-variables

For this narrow use case, they're probably still okay.

**Comment by fd0** [comment]
Okay, then I'll close this issue. #278 tracks adding a convenient option to read the password from a file.

**Comment by anarcat** [comment]
are you certain that all operating systems supported by restic isolate environment variables between users? i certainly grew up with the idea that leaking passwords in the environment was just a really bad idea... i wouldn't assume that every OS out there does the right thing regarding this, personnally, and allow for credentials to be passed through another mechanism.

**Comment by fd0** [comment]
Hey, thanks for adding another comment. I appreciate your concern. Are you aware of any OS which makes passing passwords etc via environment variables insecure?

If you are concerned you can just read the password from a file. For S3, supplying the access credentials via environment variables seems to be pretty standard.

**Comment by anarcat** [comment]
i am not aware of any such OS at the moment, and I did research this a bit through web search engine. next step would, for me, to look into *BSDs and Mac (or, to be more accurate, all golang-supported platforms) to see what happens there.

i suspect you are correct in your assumption, but it's a bit too broad for me to be comfortable with... and yes, i know that S3 env practices are pretty standard, but it doesn't make it right. ;) the cloud stuff often assumes single user containers...
