### ISSUE TITLE
restic should respect GOMAXPROCS env var

### ISSUE THREAD

**Issue by viric** [restic/restic#535]
In current master, and since long, restic overrides GOMAXPROCS to NumCPU().

It would be nice to just respect GOMAXPROCS env var, if it is present. And going for NumCPU() is already the default in recent go versions, iirc.

**Comment by fd0** [comment]
I agree, and I'd accept a PR. Are you interested in submitting one?

**Comment by fd0** [comment]
For the record: Dave Cheney agrees: https://twitter.com/davecheney/status/744492187941928960

Anyone up for a PR?

**Comment by damekr** [comment]
I can do that, as I wrote on the irrc would be good to set restic own variable or maybe consider using config file?

**Comment by viric** [comment]
I think that code brevety is the best, and I would not care on go below 1.5. So I'd just remove the lines.

**Comment by damekr** [comment]
@viric I agree about support below 1.5

**Comment by fd0** [comment]
I'd like to not drop support for Go 1.3, that's the version that is in Debian stable at the moment.

@damekr cool that you want to give it a try! From my point of view, the following needs to be done:
 Change the function `init()` in `src/cmds/restic/main.go`:
 * For Go >= 1.5, do nothing
 * For Go < 1.5, read the environment variable `$GOMAXPROCS`, if it is set do nothing, otherwise run the old code (`runtime.GOMAXPROCS(runtime.NumCPU())`

Do this in a fork of the restic repo in a new branch. Push this branch to GitHub, then create a pull-request.

Let me know if you need more assistance.

**Comment by fd0** [comment]
@damekr Hey, are you still interested in contributing code to this issue?

**Comment by damekr** [comment]
Yes, of course. But now I'm on on vacations so...:) I will take care of this after 1st of August...

**Comment by fd0** [comment]
Oh, have a nice vacation then! :)
