### ISSUE TITLE
Evaluate minio/sha256-simd implementation

### ISSUE THREAD

**Issue by fd0** [restic/restic#551]
The guys from @minio developed an optimized version of the sha256 hash, which is heavily used within restic: https://github.com/minio/sha256-simd

Evaluate the performance gains in comparison to stock `crypto/sha256`.

**Comment by rumpelsepp** [comment]
The syncthing folks did some tests: https://forum.syncthing.net/t/faster-hashing-package/8186?u=rumpelsepp

**Comment by fd0** [comment]
Thanks for the hint, that looks helpful.

**Comment by rumpelsepp** [comment]
Also note, that there are some issues on some devices: https://github.com/syncthing/syncthing/issues/3613

**Comment by xor-gate** [comment]
I have poked the syncthing authors to have a look at the `minio/sha257-simd` package and for some systems it can improve by `100MByte/sec`. But as @rumpelsepp mentions it needs to be protected for devices which don't support it correctly (see https://github.com/minio/sha256-simd/issues/6)

**Comment by xor-gate** [comment]
Probably this can be closed due to better SHA3, Blake2(a/b). Which are much faster.

**Comment by fd0** [comment]
I don't think so. Changing the hash algorithm requires changing the repo format, because otherwise it breaks existing repos. So I still think it's valuable to look into a faster SHA2 implementation.

**Comment by xor-gate** [comment]
Yes I understand, but we could postpone faster hashing into format v2

**Comment by bwmarrin** [comment]
Just a note, the minio team, I believe, is now using the blake2b package here : https://github.com/golang/crypto/tree/master/blake2b

This includes the Assembler optimizations, and a few fixes.  On my system the x/crypto version is a bit faster than the minio package.  It however is a bit of a simplier implementation of it because it doesn't include the Salt and Personalization flags and doesn't allow you to pick any random bit length you want.

I have been testing this a good bit recently because I'm working on a related package.  I tested all the different SHA version and blake2b.  The performance of the blake2b was better than everything else by a pretty good percentage.

**Comment by bwmarrin** [comment]
For example, even on the minio/sha256-simd page, it shows blake2b more than twice as fast as their sha256. https://github.com/minio/sha256-simd#comparison-to-other-hashing-techniques

**Comment by fd0** [comment]
Thanks for pointing it out, I'm aware of this. I had an in-depth chat with the main people from Minio at FOSDEM about this ;)
