### ISSUE TITLE
Bundle small files together for storage

### ISSUE THREAD

**Issue by fd0** [restic/restic#56]
Transfer of blobs is much more efficient for large blobs, but restic stores small files into their own blob.

Implement bundling of small files into larger blobs.

**Comment by fd0** [comment]
Need more discussion how to handle this.

**Comment by cfcs** [comment]
How are you looking to structure this? By finding the largest incomplete (<8MB) chunk that fits with the file size and adding it to the end, and storing an index / offset + length with the filename/inode information?
By using dedicated chunks for small files you could avoid storing offset / lengths for regular chunks (used to store chunks of large files).

You said you'd like discussion about this feature, do you have any problems in mind which you'd like to discuss?

**Comment by fd0** [comment]
Packing of small blobs into larger ones and storing the offset in the map structure in a tree currently interferes with the archiver pipeline, as the tree structure of a directory depends on the exact location of all data blobs and all subtrees.

Therefore I think that packing must be done on a lower layer and the tree structure shouldn't include any information if blobs are packed. This could e.g. be realised by introducing pack-files with the extension ".pack" that include an encrypted and signed header which lists the chunks that are packed together in this file. For each chunk, the header lists the storage hash, offset and length. This information can be cached locally. If the cache is not available, restic has to read the header of all pack files to find out which blocks are stored within.

That's a rough draft on how this might be implemented. Any thought on that?

**Comment by andrewchambers** [comment]
You need an unencrypted index file if you want fast random access for fuse etc. Though the decrypted index file could be held in memory by the file server I suppose.

**Comment by cfcs** [comment]
Ah, right, that makes sense @ one-pass pipeline.

The index / header you're describing would have linear access times, don't you think a hash table or similar data structure allowing more efficient random access would be better?
Perhaps you already do this for the normal chunks? Or do you just scan the entire thing and put it in a hash map in memory when restoring the backup? (That would work too).

Potential small optimization: If you store the length of the pack-file and the offsets, you don't need to store the length of each individual chunk in the file since you can calculate that by subtracting the current offset from the next offset (or the length of the file, if it's the last chunk).

ON THE OTHER HAND, if you keep the (length + offset) fields, and you make those fields constant size, you can sort the index alphabetically and find blobs efficiently through a binary search of the index, which may be a useful feature to have.

You're much more familiar with the internals of restic, so I'm not sure whether my suggestions are of any use, but I think that what you proposed sounds reasonable, and relatively clean.

I'm a little concerned about the privacy aspects of this, I'm not convinced the convenience of having ".pack" files justifies sacrificing the privacy benefit of third parties being unable to pry on the ratio of large vs small files in a backup dataset. How about packing the small files into opaque ~8MB chunks and referencing those as belonging to a special "small / pack files" entry in the large file index? (Injected at the end, for example). Would that be too expensive?

**Comment by fd0** [comment]
If this is implemented the way I have it in mind right now (and if that turns out to be a viable solution), the privacy aspect even benefits from the implementation. This way, attackers who are able to observe and read the repository only see a bunch of big files (some with the extension ".pack"), that's it. If no packing is used, attackers can deduce the number and size of all the data blobs in the file. This is a lot of information, especially as long as the chunker isn't seeded yet.

But thanks a lot for your thoughts! I really appreciate it!

**Comment by cfcs** [comment]
Perfect :) Why the .pack extension though? Is that strictly necessary (the ability for thirdparties to be able to distinguish chunks consisting of small files from regular chunks? why not put this information - which chunks are packed, that is - in an encrypted index?)

Completely off-topic, but interesting: What do you do to prevent length-extension attacks on SHA-256?
I'm probably missing some implementation detail. Is is this a case of me having not RTFM properly?

**Comment by fd0** [comment]
The .pack extension is used to distinguish packed blobs from normal blobs which just contain one chunk of data. This is used to rebuild the cache when it is lost so that only the header of those blobs marked as packed need to be read by restic. If normal blobs and packed blobs look the same from the outside, restic has to read all headers of all blobs in order to reconstruct the cache. I'll do some tests and benchmarks when this is implemented.

Regarding your second question: I'm not doing anything against length-extension attacks as there is no need to. From an attacker's point of view, there is only one hash observable: Data is stored in a filename that is the hex representation of the SHA256 hash of its content. The complete data that was used to compute the hash is available to the attacker, so there is no need to extend something.

When a blob is accessed it is first read into memory and the hash of the data is computed and compared to the requested hash. If these do not match, restic aborts. Afterwards the Poly1305-AES signature on the data is checked. If this fails, restic aborts. Security here is guaranteed by the signature, the outer hash is just used for content-addressable storage.

If an attacker modifies a file, this is detected by the first check for the storage hash. In addition, this would also be detected in the signature check (e.g. when the attacker is able to find a SHA256 collision, which is not impossible but rather unlikely at the moment).

An attacker can copy a file, modifies or appends data and stores it under the new hash. When restic reads this file into memory, the first check succeeds (filename == sha256(content)), but the signature check fails and restic aborts. Nothing gained here.

I hope you can understand the structure better now. The basics are described in the file `doc/Design.md`. Do you feel there is something missing?

**Comment by cfcs** [comment]
.pack: IF you had a single file with an index of the .pack files, or included this index somewhere else, you would not have to scan blobs individually. This index could be generated at the time of archiving.
This index could in turn be padded to conceal number of pack files (if stored as an individual file), but that might be a bit overkill.

Re: length-extension attacks: Ah -- I was missing the poly1305 MAC. That's all good then! :)
SHA256 "collisions" are actually possible in this scenario (although made useless by your checking of the poly1305-aes tag), by extending the file, see:
- http://en.wikipedia.org/wiki/Length_extension_attack
- https://github.com/bwall/HashPump

Re: Docs: Not really, actually, I should just learn to read before I type. :-)
I think in general it would be nice to have a document with examples of restic use (+ use-cases), listing the commands to use specific features and explaining what is going on behind the scenes. But perhaps that should wait until you have decided on a stable format for the storage backend.

**Comment by fd0** [comment]
I think you misunderstood the difference between a hash collision and a length extension attack, these are quite different things:

Finding a hash collision means finding two different streams of bytes so that sha256(data1) == sha256(data2). In restic, we use the hash of the content of a data blob to derive the filename. If an attacker is able to find a different data blob that still has the same sha256-hash and exchanges this for the original data in a repository, the first check restic does will pass (checking if filename == hash(data)), but checking the MAC will fail.

A length extension attack on the other hand means continuing a hash function whose internal state is exposed in the hash. This works for most hash functions. In this case the attacker has some data and sha256(secret || data) but no the secret. The attacker then tries to continue the hash, i.e. to compute sha256(secret || data || moredata). This construction is bad and not used in restic anywhere. The only place where this is remotely related to actual functions in restic storing the data in the repository. But there is no secret involved in the hash calculation, just the raw data that is complete contained in the file and therefore readable by the attacker. There is no hash to continue here, since the attackers sees data and sha256(data), therefore it's really easy to compute sha256(foo||data||moredata||dataagain) etc.

**Comment by rakoo** [comment]
Just so you know, [bup](https://github.com/bup/bup) is using packs as its data format (I'm so much more accustomed to bup that I thought restic was somehow inspired by it... turns out I was wrong)

Their design is [here](https://github.com/bup/bup/blob/master/DESIGN). It's _really_ similar to how restic works, except a file isn't a list of all its data, it's another tree that goes down to the data. More details in the DESIGN doc.

They store data in git packs

**Comment by fd0** [comment]
Thanks for the hint, I'

**Comment by cfcs** [comment]
I personally think I understand length-extension attacks perfectly well, hence the quotes around "collision" :-)
I fail to see what the difference between sha256(known amount of unknown bytes + known data) and sha256(known data) is in this case. "known data" would imply knowing the length, so you may choose any leading substring of "known data" as your "secret". Since sha256 (and not sha224 or sha384) is used, the state variables required to compute an extension is part of the resulting 256-bit string.
Attackers can compute sha256(data + more data) matching sha256(data) regardless. However, it doesn't really matter whether the "collision" consists of random bytes or a partially-valid, partially MAC'ed data stream -- data MAC checking will fail, and the blob will be marked as corrupt when read.
Length-extension attacks don't work on the newer families of cryptographic hashes -- keccak (sha3) and blake2b/2s don't suffer from this problem.
In any case this discussion is a bit pointless since we both agree that there is no actual problem here! :)))


Restic uses blocks of ~1mb, instead of 8k, meaning you'll have somewhere between 2,1 million (worst case, 512k chunks) and 131.000 (best case, 8mb chunks) chunks per terabyte consisting of large files. With those numbers, block indexes in the gigabyte range will be few.
As far as indexing goes, using byte-sharding using files amounts to cheating: You're relying on the filesystem to do the indexing for you instead of creating a searchable and maintainable data structure yourself. ;-)
I think fd0's suggestion seems quite maintainable, I don't see why it should prevent purgeable snapshots. Further indexing can be added later if required, if it becomes a problem?

**Comment by fd0** [comment]
FYI: I've added some documentation for my plan to implement this in b99474154c6ef37304bde5e7d6e24e6d4f3bb26c.

**Comment by andrewchambers** [comment]
@cfcs 
"I fail to see what the difference between sha256(known amount of unknown bytes + known data) and sha256(known data)"

They are totally different.

**Comment by fd0** [comment]
Progress update: I'v implemented packing blobs, sorry it took me so long to give you an update. It's a huge change because I had to refactor the repository structure too, I'll publish my preliminary code in a PR this evening (trying a new workflow as suggested by @fw42 in #146), so you can have a look at it before merging it into master.

**Comment by cfcs** [comment]
Off-topic, but necessary:

@andrewchambers @fd0 
Turns out that my insisting on having a clear recollection of the workings of length extension attacks was, well, a bit of a far stretch, so to speak. ;-)
After consulting my notes and realizing you were both entirely correct, I must apologize for the bickering, and for any confusion this might have caused.
Good day to you, gentlemen!

**Comment by fd0** [comment]
I've created a pull request which contains my code for this issue, have a look at #151.

**Comment by fd0** [comment]
Fixed in #151.
