### ISSUE TITLE
Backup also files on windows with longer pathnames than 255 chars (e.g. from node).

### ISSUE THREAD

**Issue by stuertz** [restic/restic#567]
## Output of `restic version`
restic.exe version
restic 0.2.0 (v0.2.0-8-ge4a9905)
compiled at 2016-08-08 17:37:01 with go1.6.3

## Expected behavior
Backup also files on windows with longer pathnames than 256 chars (e.g. from node).

## Actual behavior
> restic backup c:\work
[...]
work\applications\cs.activitystream\trunk\cs\activitystream\web\base\node_modules\autolinker\node_modules\gulp-header\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\read-pkg-up\node_modules\find-up\node_modules\path-exists\readme.md: GetFileAttributesEx c:\work\applications\cs.activitystream\trunk\cs\activitystream\web\base\node_modules\autolinker\node_modules\gulp-header\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\read-pkg-up\node_modules\find-up\node_modules\path-exists\readme.md: Das System kann den angegebenen Pfad nicht finden.
[...]

Files are not backuped, but logged.

## Steps to reproduce the behavior
Generate a path with long pathnames and try to backup it on Windows.

## Estimated solution
Use the right windows API Funtion, that is aware of (Unicode) Long Pathnames

**Comment by stuertz** [comment]
see also https://github.com/golang/go/issues/3358

**Comment by fd0** [comment]
Thanks for reporting this issue. It was already known, but buried deep in the comments of another issue: https://github.com/restic/restic/issues/339#issuecomment-211831435

A workaround is mentioned in https://github.com/restic/restic/issues/339#issuecomment-226207599

I'll repeat my statement from the other issue so that we can track progress here:
Properly handling long paths on Windows is not easy to do with Go. I don't have a Windows development environment, and the Go stdlib does not yet support long paths, see https://github.com/golang/go/issues/3358

So, if someone wants to step up implementing this for restic, I'm glad to assist.

**Comment by stuertz** [comment]
Hi, I would like to help out with the issue, as far as I do have such an environment :-)
But I'm currently very new into go and also with restic (did a lot of python and c/c++ before). I tried already a bit around with patching the os.FileOpen in src/restic/fs/file_all.go. But that didn't help here.

The first error I guess comes from some stat call, as it occurs while analyzing the file system. If you could give me some hints pointing to the right places in restic code base I think it would be easy to patch the code. Beside I will also try to improve my debugging skills with go ;-)

IMHO the solution to fix this would be to patch the path as described in the mentioned workaround (start pathes with \\?\) before every filesystem call, but not generally. Prepending \\?\ should be transparently done. So if one looks at a snapshot, you wouldn't see \\?\.

**Comment by fd0** [comment]
Hi, thanks for offering help, we appreciate it! Until there is support for long paths in the Go stdlib, we need to apply a workaround and use an UNC path. I found the following description from @klauspost (who already contributed to restic): https://blog.klauspost.com/long-windows-paths-unc-paths-in-go/

So, as far as I can see, we need to have custom methods for all functions that accept a path, so that on Windows we can substitute the normal (possibly relative) path used within restic by an (absolute) UNC path, and only then call the underlying functions like `os.Stat()`, `os.Lstat()`, `os.Open()` and so on.

I've already thought about adding a generic abstraction for the file system (so we can mock this easier in tests), and this looks like a good opportunity to build it. Unfortunately, this will be a larger task. If you are interested, I'm glad to assist. Otherwise you'll need to wait until I get around to working on this ;)

**Comment by fd0** [comment]
Fixed in #570
