### ISSUE TITLE
Typos in S3 backend?

### ISSUE THREAD

**Issue by justinclift** [restic/restic#649]
Looking through the S3 backend code, these two seem potentially not quite right:

* https://github.com/restic/restic/blob/master/src/restic/backend/s3/s3.go#L97-L100
* https://github.com/restic/restic/blob/master/src/restic/backend/s3/s3.go#L194-L196

Comparing those with this, which seems like it's ok:

* https://github.com/restic/restic/blob/master/src/restic/backend/sftp/sftp.go#L348

Is not checking the value of `e` needed for the S3 backend?

Note - still getting into Golang though, so it's completely possible I'm not seeing something. :smile:

**Comment by fd0** [comment]
Hi, thanks for bringing this up. I think the code is correct, and I'll explain why:

The check for `e != nil` in the sftp backend code is unneeded and could be removed:
```go
func (r *SFTP) Load(h restic.Handle, p []byte, off int64) (n int, err error) {
[...]
	defer func() {
		e := f.Close()
		if err == nil && e != nil {
			err = errors.Wrap(e, "Close")
		}
	}()
[...]
}
```

When `err != nil` at the time the deferred function runs, `f.Close()` is called but anything returned from that call is not used any further, since there was already an error before.

On the other hand when `err == nil` at the time the deferred function runs, `f.Close()` is called and the returned error is saved to the variable `e`. If `e` is `nil`, the value of `err` is not changed (it remains `nil`). if `e` is not `nil`, `err` is set to the wrapped `e` error.

For the S3 code the additional `e != nil` check isn't there:
```go
func (be s3) Load(h restic.Handle, p []byte, off int64) (n int, err error) {
[...]
	defer func() {
		e := obj.Close()
		if err == nil {
			err = errors.Wrap(e, "Close")
		}
	}()

[...]
}
```

The only different case compared to the other code before is when `err == nil` and `e == nil`. In this case, `err` is set to `errors.Wrap(nil, "Close")`. When the error passed to `errors.Wrap()` already is nil, this function will just [return `nil` again](https://godoc.org/github.com/pkg/errors#Wrap). So the check for `e == nil` doesn't change the behavior of the function.

Does that answer your question? If so, please close this issue, or leave a comment.

**Comment by justinclift** [comment]
Yep, that answers things well, thanks for the in-depth explanation. :smile:

Should I submit a PR removing the `e != nil` from the sftp backend code? (it's no problem if it's better left alone for now, or if you guys want to get it done instead :wink:)

**Comment by fd0** [comment]
I'd accept a PR if you'd like to do one ;)

**Comment by justinclift** [comment]
Cool.  I'll get done tonight. :smile:
