### ISSUE TITLE
suggestion: hardening the forget command (avoid prune abuse)

### ISSUE THREAD

**Issue by stuntsman** [restic/restic#653]
We'd like to implement a backup workflow which is as secure as possible. 

We have a backup server which uses rsync to pull the restic backup which is created locally on the live server. This way we can have a separate backup location while owners, permissions etc. are still stored with the data, and we don't have to open SSH on the backup server for the restic push. A separate and safe backup location, we really like this concept.

There's one question left though: is there any way we can avoid data loss by some user abusing the forget command of restic? (eg by pruning most/all of the snapshots). As the password is stored on the server, the risk of a sabotage is high, isn't it?

We can ofcourse tell rsync not to remove files on the backup server during sync, but I guess that won't help much against forget: as the indexes will change, we will lose the "connection" to the orphaned blobs in the filesystem.

We can easily run integrity/consistency check to detect if something was physically deleted from the repo - in that case we won't sync that to the backup server. However the forget command is not a simple physical deletion, that's exactly why it's a risk.

Our best idea/suggestion is having an option to hardcode the policy attributes (keep parameters) during repo init into the configuration, and make it non-changeable and non-overrideable by command line parameters. If the policy needs to be changed, users should create a new repo this way - maybe there's a better solution for that, but we've found it to be a fair compromise. 

We were also thinking of alternative solutions (like monitoring the list of snapshots) but most of them were just too fragile.

What do you think?

**Comment by fd0** [comment]
Hi, thanks for contributing this question and usage scenario. Let me summarise what I understood so far: Server A runs restic to create a backup in a local repository and this repository is copied via rsync to a central backup server B (via pull, a process running on the backup server logs into the server and no the other way around).

You are concerned about "a user" abusing the forget command. Who is that, exactly? What's the scenario you're expecting? Attackers who gained access to server A? Or B? Or both?

**Comment by stuntsman** [comment]
You're right about the server setup.

Think of a web server hosting the entire software stack of a business and a group of developers having access to it (=server A). The developers have r or rw access to many things on the server: logs, /etc configuration and so on. As restic runs on this server, they may find a way to access the backup repo too.

Server B (backup server) is the black box of the business: a very secure server in a remote location, only one or two users has access to it.

The use case is that a user has (or gains) access to server A, finds the repo password on the server (stored in configuration or envvar somewhere), and removes snapshots from the backup to hide traces of malicious activity (might be a coworker with bad intentions), or even destroy the business by deleting server A and emptying the backup repo too using forget.

As rsync will blindly pull the shrunk backup repo to server B, there'll be no other way to protect the backup history (creating complete copies is on server B is not an effective option - that's exactly why we'd use restic in the first place).

We'd like to build a setup where no user can tamper a backup repo. Currently forget is the only entry point where the user can easily do this without even losing backup integrity/consistency.

(As a workaround we were even thinking of using _another_ restic repo on server B too to store the rsync'd backup repo files... That sounds pretty sick though. That's 3x the backup size too - the original repo on server A, the rsynced copy on server B and the new repo created on server B).

**Comment by ar-jan** [comment]
This reminds me of [S3QL](https://bitbucket.org/nikratio/s3ql), which has "Immutable Trees": `Directory trees can be made immutable, so that their contents can no longer be changed in any way whatsoever. This can be used to ensure that backups can not be modified after they have been made.`

**Comment by fd0** [comment]
I'm sorry to say that but: I don't think that restricting the `forget` command will help at all. If attackers (e.g. a malicious coworker) with access to the server can run `restic` means that the attackers already have write access to the local repository (otherwise restic wouldn't be able to store files there). Even without the password for the repository, as long as the attackers can remove files, they can just empty the `snapshots` directory and remove all files there. Or the `data` directory. After all, that's what restic does when `forget` and `prune` is run.

I think this isn't solvable with a local repository if you assume an attacker that has the same privileges as the restic  binary on the machine. On the other hand you can use the `sftp` backend to save a backup and on that server configure (e.g. via cron) the file permissions so that the user the restic process is logging in cannot remove files for all directories except `locks`. This way, new data can be added, but no data can be removed (except lock files).

In this scenario, you can run `forget` and `prune` either locally on the backup server (that'd need the password there, though), or from another, more trusted machine which uses a different user to log into the server via sftp and has write/remove permissions on the repo files.

Am I missing something?

**Comment by Niondir** [comment]
In my opinion it's not about to prevent an attacker from changing any data on server A (you can't) but about detecting corrupt backups / attacks before they override important data on server B.

I would rather suggest some monitoring of the data / snapshots in server B. You could have a 3rd copy of the restic repo on server B. After reach RSync you make a diff between the 3rd copy and the just synced data. Only if "restic check" is successful and no important snapshots got removed on the just synced restic repository you refresh the 3rd copy. If anything goes wrong you notify the Admins of server B.

This way no attacker can ever do harm to your system, since no one can manipulate the 3rd copy in a harmful way without you getting noticed. Plus you get noticed in case of an attack.

**Comment by fd0** [comment]
I'm going to close this issue since I don't think restricting the `forget` or `prune` command will help here. Please fell free to add comments. We can also reopen the issue at any time.
