### ISSUE TITLE
multi-repository endpoints for high-availability (enhancement)

### ISSUE THREAD

**Issue by yhafri** [restic/restic#679]
## Output of `restic version`

```
$ restic version                                                
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-11-30 04:53:47 with go1.7.3 on darwin/amd64

$ restic version
restic 0.3.0 (v0.3.0-38-g505a209)
compiled at 2016-11-30 04:39:06 with go1.6.2 on linux/amd64
```
## Actual behavior

The env variable RESTIC_REPOSITORY works just fine with [Minio](https://www.minio.io/).
One can use it like this:

`export RESTIC_REPOSITORY=s3:http://srv1.com:9001:`

## Expected behavior

It'll be great if we can extend the meaning of this env variable to use multiple endpoints instead of one. Something like:

`export RESTIC_REPOSITORY="s3:http://srv1.com:9001":"s3:http://srv2.com:9002":"s3:http://srv3.com:9003"`

In case of failure of the first endpoint `s3:http://srv1.com:9001`, restic will try with the second one `s3:http://srv2.com:9002`, then with the third one `s3:http://srv3.com:9003`, etc.
If all fail, then it can give up.

Minio [distributed feature](https://docs.minio.io/docs/distributed-minio-quickstart-guide) is already available. Restic can benefit from it and offer high-availability for endpoints (i.e. shares).

**Comment by fd0** [comment]
Hi, thanks for the suggestion. I think it's already possible to do this: When restic returns an error code, just run it again with the second repo, when that also fails with the third (e.g. in a shell script). What do you think?

**Comment by yhafri** [comment]
Hey,
Sure, it's very doable to wrap it indeed. 
The whole point is about usability. What you can do under Linux/Unix shell script maybe harder on other OSes.
It'll be fantasy if restic can simply check for "connection timeout", and apply this logic underneath.
Much cleaner, portable, and usable.
What do you think 😁?

**Comment by zcalusic** [comment]
Tread carefully. Seeing multiple repositories in the variable, I'd always first expect that restic would use them all, simultaneously, and unconditionally. IMHO, setting it like that would even be more useful. But, that's just my opinion. Anyways, if there are any semantic changes like this, do it carefully, it's much harder to unwind it later, when another great idea pops out, and is suddenly incompatible with the old one. :)

**Comment by yhafri** [comment]
Zlatko: what do you suggest then?

**Comment by zcalusic** [comment]
I'll let @fd0 sort it out. 😆

I'm pretty sure I will get interested in parallel backup some time in the future, but not right now.

**Comment by shibumi** [comment]
Heyho, do you have any update on this? I am highly interested in this feature and this would be one of the killer features for restic against borg.

**Comment by mholt** [comment]
I think this is feature creep for restic. This can already be done with a for loop, on every OS. And it's not confusing, whereas the ability to specify multiple repositories is too ambiguous.

**Comment by dimejo** [comment]
> I think this is feature creep for restic. This can already be done with a for loop, on every OS. And it's not confusing, whereas the ability to specify multiple repositories is too ambiguous.

Some people on the forums already had difficulties installing restic on Unix systems, hence I doubt that all restic users know how to write scripts.

IMHO, every good backup solution should be able to use an alterntive repository. But I'm unsure if this should be handled by restic itself or by a GUI.

**Comment by fd0** [comment]
I'm not sure if this feature would be good for restic or not, but for now there exist at least two different solutions (running restic multiple times in a row for each backend, or using `rclone` to mirror a repository somewhere else). So, overall we don't have a decision yet, and this is rather low on the todo list for restic.

**Comment by shibumi** [comment]
How well, does running in it in a loop work? And will I have the same backup revision on all targets? What happens when I don't run it in a loop for a specific time and then decide to run it in a loop again. Will all backups have the same state? 

There are a lot of open questions about "you can run that in a for loop". What I want to address is a **reliable** way to backup data to multiple **different (like usb, S3 storage, remote server)** endpoints. And what I want to have is the same backup on every of those endpoints. I was especially asking for this, because I know other solutions where it's proposed to be easy, but in the end they fail to keep the data identical, secure and distributed. Note: I am talking about data multiplication (Raid 1). I am not talking about clustered data for faster backups (Raid 0).

**Comment by fd0** [comment]
> What I want to address is a reliable way to backup data to multiple different (like usb, S3 storage, remote server) endpoints. And what I want to have is the same backup on every of those endpoints.

Make a backup to one endpoint, then use rsync or rclone to mirror the files to the other endpoints. Make sure to include file deletes on the source endpoint, then you'll get a byte-identical copy of all snapshots and data in all endpoints. restic's file format for the repository supports this.

**Comment by andreasnuesslein** [comment]
I also see an advantage in having restic put the same backup to multiple repositories, instead of the `rclone`/`rsync` or shell-script-looping - "hacks". 
The improvement over the loop-it-with-a-script: if it was implemented in restic, there would be no looping of the same `restic backup` command. But rather for each file/block that restic looks at, it only needs to write it to multiple locations but not look at the same file twice.
Also you'd end up with identical backups in one run (nicer than the rsync/rclone-way).

I understand the concerns whether multiple repositories should be AND'ed or OR'ed and I think there could be a cli-switch along the lines of `--mutli-repo-behaviour [all|at-least-one]` with `all` being the default as it is the safer way.
If I meant `at-least-one` and `all` is the default, it will error on flakey locations and the user will be informed with an error; if it was the other way round it would silently error on one repo and not tell me, leading to possible data loss.

**Comment by MichaelEischer** [comment]
After thinking a bit about this issue, I don't think it is a good idea to implement it:
- Trying different backup locations can easily be handled outside of restic. Specifying e.g. two different S3 repositories won't work anyways (at least for now).
- Storing to multiple repositories at once is far more wasteful than it seems at first glance: we'd have to open all repositories (with a full copy of the index of each one!). All other steps of the backup pipeline, that is pack assembly and uploading, also have to be duplicated. It won't help if the individual repositories started as copies of each other as they can diverge over time. Oh, and using different repositories would only work if they use identical chunker parameters.

So this would only work together with some serious restrictions, and we haven't even spoken about other commands besides `backup` yet. In short: use the `copy` command instead or use a distributed repository storage.
