### ISSUE TITLE
"error <f> has changed", still ends in "0 errors"

### ISSUE THREAD

**Issue by bep** [restic/restic#696]
```
restic 0.3.0
compiled at 2016-12-13 11:43:09 with go1.7.4 on darwin/amd64
```

```
error for <filename>: file has changed
```

I get this error for a handful files. I understand the error, but I have no program with those files open. And even still, I get this report at the end:

```
[1:12:28] 100.00%  34.648 MiB/s  147.134 GiB / 147.134 GiB  18259 / 18259 items  0 errors  ETA 0:00
```
Either there is an error or there isn't.

**Comment by fd0** [comment]
Hey, thanks for the report. This was changed just a few days ago in the master branch in #691 ([here](https://github.com/restic/restic/pull/691/commits/e6a40af06d979cf2ad36f861b002ae3559f8e35f)), restic now prints `warning for <file>: file has changed`.

When restic emits this message, the file modification timestamp in the file system has changed, which means the file was written to recently (since the start of the backup process) or the timestamp was modified manually. It is very likely the former.

Can you be a bit more specific what the files are you see this warning for?

In the package `inotify-tools` there's a great program called `inotifywait` which can be used to track access and modification for a set of files, like this:
```
$ inotifywait -m ~/.zshhistory
/home/fd0/.zshhistory OPEN 
/home/fd0/.zshhistory ACCESS
[...]
/home/fd0/.zshhistory CLOSE_NOWRITE,CLOSE 
/home/fd0/.zshhistory OPEN 
/home/fd0/.zshhistory ACCESS 
/home/fd0/.zshhistory CLOSE_NOWRITE,CLOSE 
/home/fd0/.zshhistory OPEN 
/home/fd0/.zshhistory CLOSE_WRITE,CLOSE 
[...]
```

For now, I'm going to close this as fixed in #691, this is now a warning only and not counted as an error.

If you have additional information, please leave a comment!
