### ISSUE TITLE
Support Amazon S3 Infrequent Access Storage

### ISSUE THREAD

**Issue by arvatoth-vcc** [restic/restic#706]
## Output of `restic version`
```
restic 0.3.2 (v0.3.2-4-gb0997d0)
compiled with go1.7 on linux/amd64
```

Hi,

It would be great if restic supports S3 Infrequent Access Storage.

https://aws.amazon.com/s3/faqs/#sia_anchor

There is a huge price difference between Standard Storage and Infrequent Access Storage. If I read correctly this setting valid for per object and not per bucket. 

> You can directly PUT into Standard – IA by specifying STANDARD_IA in the x-amz-storage-class header. 

Thank you,
Mihaly

**Comment by fd0** [comment]
Thanks for the suggestion!

**Comment by sedlund** [comment]
You can set a lifecycle policy in your S3 bucket in the new S3 console.  You would want to have it automatically move files that have not been accessed in 30 days to 'Infrequent Access'.  Per the documentation 'There is a retrieval fee associated with STANDARD_IA objects which makes it most suitable for infrequently accessed data'.  So you would not want to do this to all files as it would get pricey if your indexes were in IA and you were paying to access them every backup for example.

**Comment by johan-smits** [comment]
@sedlund 
> move files that have not been accessed in 30 days to 'Infrequent Access'.

This is since the date is it stored and not since last accessed.
https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex4
> Transition objects to the STANDARD_IA storage class 30 days after creation.

Be able to set this STANDARD_IA should only be done to the objects that are really infrequent. The files that are accessed frequently restic should not set the flag.

**Comment by tomwaldnz** [comment]
My understanding is since [Restic v0.8](https://github.com/restic/restic/issues/524) there is a local cache of the indexes stored on S3, so the indexes probably aren't going to be downloaded and used regularly. 

You can set a lifecycle policy that applies only to data files as per [this example](https://github.com/restic/restic/issues/524). 

If you have a bucket that contains a restic backup you should use a prefix

`data/`

If you have a bucket with a subfolder called "PhotosBackup" that has a restic backup inside the prefix would be

`PhotosBackup/data/`

With this information it's fairly simple to have S3 change data files to IA class, leaving indexes and everything else standard class.

**Costs**

Assumptions (I don't know Restic internals at all):

- Files on S3 are immutable. Once a file is uploaded it's never changed (why would you when you have the source file?)
- We're not restoring data regularly. If you are then then there will be extra costs.

S3 standard currently costs $0.023 per GB, S3-IA costs $0.0125 per GB. Transitions to IA class cost $0.01 per 1,000 requests. You can go to single IA but the saving isn't great and you lose reliability. Glacier storage class is 1/3 the price of S3IA, but it takes a few hours to retrieve the files, they're in cold storage - I'm not sure how practical that is. I'm interested in comments though, as it would make this a lot cheaper.

If you have 1TB of data that's going to be around 100,000 files. S3 standard is $23.56 per month, IA $12.80. Transitioning 1M objects costs $10. So even in your first month you come out ahead, and in a year you save around $120 by using IA class.

If you can use Glacier class it'd be $4.10 per month. As above I'm not sure if that's going to work with Restic.

**Comment by JusticeForMikeBrown** [comment]
Hi

I am using lifecycle policies to move data from S3 to Glacier.

I have setup permissions so that my account can access both S3 and Glacier.

The data now backed up with restic has been moved to Glacier.

I try to list snapshots though get this error:

```
[user@server ~]$ restic list snapshots
Load(<key/3039516f24>, 0, 0) returned error, retrying after 696.958435ms: The operation is not valid for the object's storage class 
```

Does restic support restoring data after it's been moved from S3 to Glacier?

**Comment by rickard-von-essen** [comment]
You can't read data from glacier, you need to restore it to S3 first.

**Comment by JusticeForMikeBrown** [comment]
Thanks @rickard-von-essen though how can I make `restic backup` still work?

It looks like a file called `config` while folder called `snapshots` was moved from S3 to Glacier.

Do I need to ensure these are never moved out of S3?

**Comment by rickard-von-essen** [comment]
@tomwaldnz depends on you need, for me this is the offsite copy of a site backup solution so it very  unlikely I ever need it unless there is a break-in or the house burns down.

**Comment by tomwaldnz** [comment]
@rickard-von-essen what I do for that situation is every six months I zip up my new or changed files and store them directly in Glacier. I keep the much smaller set of "recently changed" files in a backup system stored on S3 in IA class. It's more manual, but it's not so bad.

I suspect to use the S3 Glacier class would probably require Restic to support it directly, setting storage classes on upload with defined lifecycle polices.

**Comment by tomwaldnz** [comment]
A new feature that could be helpful is [AWS S3 Auto Tiering](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-intelligent-tiering/). In short, any objects not accessed within 30 days are moved to infrequent access class. You can have a lifecycle rule modify the storage class to intelligent tiering on upload - it may take a few hours.

To move objects to Glacier storage class you still need a lifecycle rule. If you need to restore your data it will take a day or so to be ready, and I've never done it so not sure how difficult it us. I tend to just use Glacier directly for that archiving.

[Glacier Deep Archive](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-glacier-deep-archive/) is another new feature that will let you store data for $1 / TB / month. It's not available quiet yet, check for that later this year. I don't know if S3 will support it or if you'll have to use Glacier directly. Restic won't work with Glacier, Glacier is a tape backup replacement and is a bit fiddly.
