### ISSUE TITLE
Prune performance

### ISSUE THREAD

**Issue by zcalusic** [restic/restic#738]
## Output of `restic version`

restic 0.3.3 (v0.3.3-21-g36276c4)
compiled with go1.8rc2 on linux/amd64

## Expected behavior

Prune command is quite slow. It could use some parallelism I think, especially for remote repos, where latency dominates.

## Actual behavior

For a 50GB remote repo, it takes 1h to check, but 16-24h hours to prune. I suppose prune should last somewhat longer than check, hopefully not that much longer eventually. :)

## Steps to reproduce the behavior

Just run prune on a big remote repo.

**Comment by fd0** [comment]
Thanks, that needed to be said. ;)

**Comment by zcalusic** [comment]
It is interesting that even 3 times bigger repo can do prune task quite fast. The difference is, it doesn't have so many blobs. It seems that prune command performance depends most on the number of blobs, and much less on other parameteres like the size, number of packs, amount of data to be pruned etc... Hope it helps.

**Comment by fd0** [comment]
Most time in `prune` is spent traversing the tree structures in the snapshots, so more snapshots/dirs/changes in files the longer `prune` runs...

**Comment by lloeki** [comment]
Some more data over here 260GB, 23 snapshots from four hosts.

Seems like there's a slight display bug too: `found 751864 of 0 data blobs still in use, removing -751864 blobs`.

```
# restic version
restic 0.6.0-rc.1 (v0.6.0-rc.1-0-g17ff41af)
compiled with go1.8.3 on linux/amd64
# time restic prune
counting files in repo
building new index for repo
[0:03]   0 / 0 packs
repository contains 0 packs (0 blobs) with 0B bytes
processed 0 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 15 snapshots
[2:38:56] 100.00%  15 / 15 snapshots
found 751864 of 0 data blobs still in use, removing -751864 blobs
will delete 0 packs and rewrite 0 packs, this frees 0B
counting files in repo
[0:03]   0 / 0 packs
finding old index files
saved new index as 32b3e7c3
remove 59 old index files
done

real    159m20.871s
user    8m4.504s
sys     1m12.728s
```

**Comment by zcalusic** [comment]
This is now a bug number one for me, at least for my most important repo. It still takes 17h to prune, so I don't even run it except occasionally (and manually), and then I typically have to skip nightly backup run, because prune still holds the lock by that time.

With a little help of a brand new access log feature in the rest-server, I collected the log of all transactions during prune run. Actually that backup is local, but the mount is from the remote server. So I used rest-server just to see what's going on.

So, for this repo:
```
repository contains 16525 packs (3204137 blobs) with 73.688 GiB bytes
```
and for this obviously problematic stage of the prune command:
```
find data that is still in use for 24 snapshots
[15:30:03] 100.00%  24 / 24 snapshots
found 2742654 of 3204137 data blobs still in use, removing 461483 blobs
```

I carefully counted 1634129 API calls (GET /data calls) just for that stage.

So, where does that number come from? It's less than the total number of blobs, but more than the number of blobs that are unused?

I'll continue analyzing the access log file and eventually enter the code to try to understand what is going on. In any case, for such a large number of API calls, I'm obviously killed by the latency, the available network bandwith is utilized at only 1%. The average time to serve one request can be calculated as 34ms, which is just about the RTT of the remote server.

Then again, I wouldn't just splash some heavy concurrency to speed it all up, I think there's lots of room to improve the algorithm first, and then add concurrency as the last step, to achieve optimal performance eventually.

**Comment by fd0** [comment]
At that stage restic and for each snapshot, restic recursively loads all tree objects and makes notes of all blobs that are referenced there. Each tree object is fetched individually from the repo, which causes the requests you're observing. The code is here: https://github.com/restic/restic/blob/master/src/restic/find.go#L6

A slight optimization has already been introduced: A tree is only traversed once, restic makes a note which trees have been traversed already.

Several thoughts on this:
 * At the moment restic does not have any local state, but I think we need local state in order to improve `prune`.
 * We could cache the list of referenced blobs for each snapshot, because this list won't change. So for subsequent runs of `prune` we only need to traverse new snapshots
 * We could traverse trees/snapshots in parallel
 * We could list all trees, traverse them in parallel and build a (potentially huge) list of `treeID -> bloblist` associations. When we have that computing the set of still referenced blobs is easy (and fast).
 * Building a local cache of all tree objects is also possible and will speed up other operations as well, but the cache must be handled (and kept up to date and so on)
 * I've also thought about having a cache file for each snapshot, which contains all tree objects concatenated in depths-first order. We could use that to compute what's needed for `prune`, and it will probably also speed up a subsequent backup
 * On the other hand, having a cache of `filename -> [mtime, blobs]` is probably event better for improving backup speed, because that will handle more cases (compare see #856)
