### ISSUE TITLE
cat pack does not decrypt pack

### ISSUE THREAD

**Issue by oysols** [restic/restic#757]
## Output of `restic version`
restic 0.3.3 (v0.3.3-0-g4d93da9)
compiled with go1.7.4 on linux/386

## Expected behavior
`restic cat pack` returns decrypted pack file

## Actual behavior
`restic cat pack` returns the pack as stored on disk.

**Comment by fd0** [comment]
Thanks for raising this issue. I'm afraid that you understood something wrong: A pack file is a collection of encrypted blobs, followed by a header, followed by the header length. The definition can be found [in the file Design.md](https://github.com/restic/restic/blob/master/doc/Design.md#pack-format). There is no "decrypted pack file".

So, I'm going to close this issue since `restic cat pack` should indeed only write a pack file to stdout, without decrypting anything.

If you need any further explanation or have an idea on how to improve the documentation, please leave a comment.

**Comment by oysols** [comment]
There isn't really any use for decrypting the pack file in day to day operations, but I was curious of the internals. I'm new to Go, so I made a quick tool in Python for inspecting/decrypting the pack files. (https://github.com/oysols/restic-python) I agree with you that there really isn't any good reason to include this in restic.

Anyways; Keep up the good job. :)
