### ISSUE TITLE
Test TestNodeComparison tree_test.go not clear

### ISSUE THREAD

**Issue by jgfrm** [restic/restic#774]
Can someone explain me the following test code (file tree_test.go):
```
func TestNodeComparison(t *testing.T) {
	fi, err := os.Lstat("tree_test.go")

	OK(t, err)

	node, err := restic.NodeFromFileInfo("foo", fi)

	OK(t, err)

	n2 := *node

	Assert(t, node.Equals(n2), "nodes aren't equal")

	n2.Size--

	Assert(t, !node.Equals(n2), "nodes are equal")
}
```

To supported extended atributes, 
```
NodeFromFileInfo
```
calls a function to read the extended attributes of a file
For 
```
foo
```
the test fails.

What is not clear to me:

1. 
```
fi, err := os.Lstat("tree_test.go")
	OK(t, err)
```
Why passes the above code the test? I would say the file tree_test.go is not present on the filesystem (at least in the dir the test is run).

2. My code really needs to access the file having the extended attributes exposed. The test code passes the LStat info to NodeFromFileInfo, and that code does not access the file (but only the LStat info). Therefore my question is if the test should be revised for the case of extended attributes?

**Comment by fd0** [comment]
Hey, thanks for asking:

1. Go always executes the test with the current directory set to the directory that contains the test files, so the file `tree_test.go` (in which the function `TestNodeComparison()` is defined) is present in the current directory during the test run

2. The test needs to be changed in order to support extended attributes. That's fine with me.

**Comment by jgfrm** [comment]
Done
