### ISSUE TITLE
Security of unattended remote backups

### ISSUE THREAD

**Issue by sanmai** [restic/restic#781]
So I set up unattended backups over sftp for a bunch of servers.

    restic -p secret -r sftp:user@host:/mnt/backups backup /home

Now an adversary gains access to one of the servers. From there he could readily access backups over the very same sftp. If an adversary can delete backups, and indeed he can, we're in trouble.

What are measures there in restic to prevent such undesired situations from happening?

([Borg handles this with append-only mode of backups.](https://borgbackup.readthedocs.io/en/stable/usage.html#append-only-mode))

**Comment by fd0** [comment]
Hey, thanks for raising this issue. It is one of the places where borgbackup is more mature than restic: We do not yet have anything built in to handle this situation. I've tried to document the [threat model](https://github.com/restic/restic/blob/master/doc/Design.md#threat-model) for restic, and it is still very basic. Among others, it is assumed that the host making the backups is trusted, and the situation where such a host is compromised is not yet addressed. So the threat model needs to be extended to cover this.

A remote server mode, including a read-only option such as the one provided by borgbackup, solves this nicely.

At the moment only two things that you can do to mitigate this come to my mind:
 * Using the sftp backend: Have a script on the server that is run via cron regularly which removes writing+deleting files from the `data`, `snapshot` and `index` directories and on the `config` file. It is necessary that new files can still be added, but no existing files can be modified or deleted. Then use restic as usual. The backup process is designed in such a way that files are only added, never deleted or changed.
 * Using the REST backend: Implement your own server (or modify the [REST server](https://github.com/restic/rest-server)) so that some users can only add `data`, `index` and `snapshot` files, but not delete them.

I'll close this issue for now since your question has been answered, you can still add comments (and people can find this issue). Please add another issue requesting a remote server mode and an option for add-only access, but be aware that it will take time to add this.

This issue is connected to #187.

**Comment by sanmai** [comment]
Just leaving this here because it's about what can be used: https://github.com/natefinch/pie

**Comment by fd0** [comment]
Oh, that's neat, I didn't know this library. Thanks!

**Comment by sanmai** [comment]
Other option is to `rsync` everything to a remote server, then run the backup there locally. Twice as much space will be used, but the job done.

**Comment by sanmai** [comment]
So far I decided to trade bandwidth for security.

    tar c /home | ssh backup.example.com

backup.example.com is configured in `.ssh/config` like so:

    Host backup.example.com
      User backup-incoming
      Hostname backup.example.com
      IdentityFile .ssh/id_ed25519_passwordless

On the backup server there's a forced command for this special password-less key, which command is basically equivalent to:

    from="test.example.com",command="restic backup --stdin --stdin-filename test.example.com.tar" ssh-ed25519 AAAA...

This scheme can be similarly used with other sources:

    mysqldump --single-transaction --all-databases | ssh backup.example.com restic backup --stdin --stdin-filename $HOSTNAME.sql

Obviously with this scheme it is way more difficult to extract specific files from a backup, but at least I save on disk space.

**Comment by fd0** [comment]
That is actually a pretty nice idea :)
