### ISSUE TITLE
Add remote server mode and an option for add-only access

### ISSUE THREAD

**Issue by sanmai** [restic/restic#784]
As discussed in #781, please add remote server mode with an option for add-only access.

This mode of operation assumes inverse [threat model](https://github.com/restic/restic/blob/master/doc/Design.md#threat-model): 
 - The host system where a backup is created on is **not** trusted.
-  The remote location where backups are stored on is trusted.

Therefore, the host system (source of backups) shall be only allowed to add files to the repository, never delete or change. The host system may not choose own encryption keys.

For better host separation while retaining best de-duplication it is desired that the host system is only allowed read an portion of a repository essential to the job on hand. (In no cases the host system shall be allowed to read files belonging to other hosts.)

A server is supposed to be configured in `.ssh/authorized_keys` with a forced `command` not unlike [it is done with Borg](https://borgbackup.readthedocs.io/en/stable/usage.html#append-only-mode):

    command="restic serve ..." ssh-rsa <untrusted client key>

Contrary to the common threat model, encryption is not required in this mode of operation.

Other that re-implementing own protocol, it may be also sufficient to:

- Read source files for backups from tar archives. [Go has means to read them.](https://golang.org/pkg/archive/tar/) In this case backups could proceed as following:

      tar c /path | restic backup --from-tar

  Or, in case of network backup:

       sudo tar c /home | ssh backup.example.com restic backup --from-tar --hostname=$HOSTNAME
    In this case we're trading bandwidth for security, which is an obvious drawback. 

- Implement rsync protocol and read source files from a rsync client. There is librsync and there could be bingings for it, or even a number of reimplementation. [One that I found.](https://github.com/smtc/rsync) Yet whole rsync protocol isn't just librsync, so it may take more effort than just implementing own protocol. 

  Backup proceeds like following:

      rsync -a -e "ssh backup.example.com restic --hostname=$HOSTNAME" /path/to/backup

  (Note that rsync will append own command, calling `restic rsync ...`)
  
  This option has major, if not great, benefit of not having restic installed on all and every target server. One doesn't have to hack some vintage CentOS servers to get restic version updates.

Either way we must add an explicit option for a hostname because restic could not know it otherwise.

**Comment by sanmai** [comment]
I was thinking of cloning `ArchiveReader` and altering to work with `tar.Reader` instead of single file. For each file in an archive we can have `os.FileInfo`. Am I on the right way?

Should I add additional command, or extend `cmd_backup` further?

**Comment by fd0** [comment]
You are on the right way I think, I'm willing to merge a PR that adds creating a backup from a tar archive. It's probably a good idea to copy tho code in `ArchiveReader` and make it read a `tar` archive from an `io.Reader`. The incremental mode will be hard to implement, I think.

Please create a new issue for this, we can discuss the user interface there.

**Comment by mholt** [comment]
I'm also interested in this threat model, as I have a use case that requires it. However, I would rather like to proxy restic's requests to a given backend through my trusted server, where I replace the credentials and then forward the request to the appropriate backend.

I looked at rest-server and rewriting its handlers to support pluggable backends rather than just file systems. Do either of you @fd0 or @sanmai have any thoughts on this? I'm willing to write code. :smile:

**Comment by sanmai** [comment]
That could be a nice idea if you could tell for sure that nothing could slip through. 

So far I decided to make backups an old-fashioned way (read `tar --listed-incremental`), then transfer ready-made archives with rsync, and merge them in a trusted backend be it restic or what.

**Comment by fd0** [comment]
@mholt thanks for the offer to contribute code. It's on my list of things to do medium-term, but the pieces are not in place yet. Please hold for a bit longer :)

**Comment by matthijskooijman** [comment]
I really like the `restic serve` proposal in the original post, since that allows good access control. If such a command can also serve data from a non-local backend, you could also create a lightweight "gateway backup server", whose purpose is to protect storage credentials and forwards all backup data from clients to the storage backend. I believe this equally applies to the current REST server as well?

> For better host separation while retaining best de-duplication it is desired that the host system is only allowed read an portion of a repository essential to the job on hand. (In no cases the host system shall be allowed to read files belonging to other hosts.)

This also seems like a great implementation. I don't know the details of the restic repository format, but based on my experience with git and a quick scan of the design document, I suspect this would be a matter of adding access control to the snapshot list? AFAIU, a client needs the snapshot object to know the root tree object and from there can figure out what objects it needs to read to reconstruct the original files. If:
 - The backup server only exposes blobs and trees when a client request them by hash (which implies pack files and index files should not be exposed),
 - The backup server only exposes snapshots that the client is entitled to
You should have perfect host separation.

One question is when is a client entitled to a snapshot, which could be done by tagging snapshots with the key that created them (or otherwise linking keys to snapshots). You probably also need master keys which can read all snapshots (or perhaps different keys for backup and restore?). This also needs a way for a client to prove knowledge of a key to the server, which might need assymmetric keys?

An even stronger version of this would be to have a write-only mode, where you cannot read snapshots and objects at all. AFAIU you would still need a allow a query like "does an object with this hash exist" for deduplication the transfer. Note that this is a stronger limitation than, the current `--append-only` flag of the REST server, which (AFAICS) only prevents overwriting and deleteing files, it does not prevent reading them.

**Comment by colans** [comment]
The original point of this issue, _Add remote server mode and an option for add-only access_, is now fully supported.  See [Preparing a new repository: Other Services via rclone](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) (the SSH section) for remote server support.  For add-only access, you can write an SSH forced command wrapper script that injects `--append-only` into the `restic serve` command as discussed in #187.  (For more general information on that, see [OpenSSH: Going flexible with forced commands](https://binblog.info/2008/10/20/openssh-going-flexible-with-forced-commands/).)

However, I don't believe that we solved the problem of hosts getting access to only their own data.

I propose that we either:
1. Repurpose this issue for that, or
2. Close this one, and open a new issue for it.

Thoughts @fd0 ?

**Comment by colans** [comment]
I created the `--write-only` one in the Rclone queue as I believe that makes the most sense, and the other one here as it's not yet clear to me where that should be handled.  (Let's continue these discussions in those issues.)

This issue can now be closed, unless I'm missing something.

**Comment by matthijskooijman** [comment]
I wonder if making a write-only option work would need changes to the repository format? It should at least be possible to know if an object exist, which might involve reading index files when these objects are inside packs?

**Comment by matthijskooijman** [comment]
I added a comment to the rclone issue, which seems like a better place. Sorry for the noise.

**Comment by colans** [comment]
@matthijskooijman I suppose here is fine as that's a restic question (unless we open a new one specifically for that here).  Plus, I think you may have posted that in the wrong issue.

**Comment by fd0** [comment]
You're right, this issue can be closed because it has been implemented in the REST server and in rclone. Thanks!
