### ISSUE TITLE
Restic on mac: don't use an smb mount

### ISSUE THREAD

**Issue by jussihuotari** [restic/restic#823]
I set up Restic on my Mac and noticed that it's very slow over an SMB connection. I have 400+GB of data to backup and the daily backup took well over 2 hours to run even when no files were changed. And it made my wifi slow.

For some reason, using `--force` didn't help (but in addition rendered my Mac slow). referring: https://github.com/restic/restic/issues/386#issuecomment-247751400 

After investigating, I'd say this is probably an issue with Apple's SMB implementation and/or my network drive. I switched the repository access from an smb-mount to sftp, and things sped up significantly. Now the daily `backup` takes ~5 mins when the files are (mostly) unchanged: 

```
...
[4:20] 76.55%  1.235 GiB/s  321.004 GiB / 419.338 GiB  130504 / 162423 items  0 errors  ETA 1:19 
[4:30] 76.65%  1.191 GiB/s  321.441 GiB / 419.338 GiB  133528 / 162423 items  0 errors  ETA 1:22 
[4:40] 88.13%  1.320 GiB/s  369.574 GiB / 419.338 GiB  152324 / 162423 items  0 errors  ETA 0:37 
[4:47] 100.00%  1.320 GiB/s  419.338 GiB / 419.338 GiB  162423 / 162423 items  0 errors  ETA 0:37 

duration: 4:47, 1491.71MiB/s
``` 

So, it seems to me that the way Restic communicates with the repository does not work well with Apple's SMB. For me, a valid workaround was to use sftp. For someone else, a metadata cache might be helpful https://github.com/restic/restic/issues/29.

(not sure if adding an issue is correct for this kind of nice-to-know-info, but I was so astonished to find the speed difference that had never occurred to me in other use. please feel free to close this issue)

For the sake of documentation, I wrote down notes about my Restic-setup: http://www.jussihuotari.com/2017/01/14/computer-backup-using-restic-on-mac/

**Comment by fd0** [comment]
Hey, thanks for reporting this odd behavior! Let's make sure I understood your setup correctly: You're creating a backup of local data stored on your machine to a repository located on a network drive mounted via SMB. That is slow. Accessing the same data via SFTP is much faster. Correct?

In this case I suspect it's indeed Apple's SMB implementation. During a non-initial backup restic accesses a lot of small parts of the pack files stored in the repo at random. So that's something which stresses the SMB implementation a bit.

I suggest closing this issue so that people can find it, apart from adding the metadata cache (which will surely speed this up a bit) there's nothing we can do. What do you think?

**Comment by jussihuotari** [comment]
Yes, that's a correct description of the setup. FWIW my network drive does SMB2 (not smb3). 

And yes, agreed, this issue can be closed. Thanks!
