### ISSUE TITLE
Support cloud storage as repository location

### ISSUE THREAD

**Issue by TamalSaha** [restic/restic#830]
Hi,
We, AppsCode, provision Kubernetes cluster on various cloud provider. I came across restic, as we are looking for a tool for data backup. We have tried Bacula before. Compared to Bacula, Restic seems much simpler operationally, written in Go making it extensible for us. But one main limitation of restic is it does support major cloud providers as repository locations. We are particularly interested in Google Cloud Storage in the short term. I have seen the existing discussions regarding GCS. We are interested in helping with GCS support. I have seen the discussions in #211 . My question is:

What do you think about using a library like https://github.com/graymeta/stow that provides a thin unifying layer on top of various providers?

**Comment by fd0** [comment]
Hi, that's a very interesting idea, thanks for opening this issue! I haven't seen the library yet, from a first glance at the API I saw that unfortunately it isn't directly compatible with our [backend interface](https://godoc.org/github.com/restic/restic/src/restic#Backend): Our `Load()` method takes an offset and a length, so that parts of files can be read without downloading the complete file. I'm not sure how to handle this, maybe we need to wait until a local metadata cache (#29) is implemented so that it's less likely we'll need many small parts of files.

**Comment by TamalSaha** [comment]
@fd0 , Do you have a timeline for implementing #29 . I think we could add the Load() support as long the underlying cloud storage providers support it.
