### ISSUE TITLE
[FR] Add a new command to manipulate tags on existing snapshots.

### ISSUE THREAD

**Issue by middelink** [restic/restic#851]
Sometimes it is handy to manipulate snapshots based on their tags, however to make that universal useful we need a way to change them on existing snapshots.

Example I was thinking about was progressive insight into snapshots are managed by some enterprising sysadmin. Without the possibility to change tags retroactively, they would have to make exceptions to their newly thought of schema, till the old snapshots are forgotten.

Unavoidable implementation detail, due to the tags changing, and therefore the sha256 hash, the snapshots will get a new ID assigned. All other data stays the same however.

Possible cmdline:
```console
$ ../../../bin/restic -r rest:http://qnap.********:8000 tag --help
The "tag" command allows you to modify tags on existing snapshots.

You can either set/replace the entire set of tags on a snapshot, or
add tags to/remove tags from the existing set.

When no snapshot-ID is given, all snapshots matching the host, tag and path filter criteria are modified.

Usage:
  restic tag [flags] [snapshot-ID ...]

Flags:
      --add tag       tag which will be added to the existing tags, can be given multiple times
  -H, --host string   only consider snapshots for this host, when no snapshot ID is given
      --path path     only consider snapshots which include this (absolute) path, when no snapshot-ID is given
      --remove tag    tag which will be removed from the existing tags, can be given multiple times
      --set tag       tag which will replace the existing tags, can be given multiple times
      --tag tag       only consider snapshots which include this tag, when no snapshot-ID is given


Global Flags:
      --json                   set output mode to JSON for commands that support it
      --no-lock                do not lock the repo, this allows some operations on read-only repos
  -p, --password-file string   read the repository password from a file
  -q, --quiet                  do not output comprehensive progress report
  -r, --repo string            repository to backup to or restore from (default: $RESTIC_REPOSITORY)
```

**Comment by fd0** [comment]
Good point, I like it!

I've thought about how to address the problem with the changing snapshot ID, we can either just leave it and accept that sometimes snapshot IDs change. At the moment (as far as I remember) there's nothing in the code that depends on static snapshot IDs.

I have plans for adding a local cache which uses snapshot IDs to cache things (e.g. the list of referenced blobs, so that we can speed up `prune` a lot by not traversing a snapshot again). We can mitigate this by adding the original snapshot ID to the changed snapshot as a new field. What do you think?

**Comment by middelink** [comment]
I think that would be asking for problems, first off, we can have multiple tag changes, so the definition of original snapshot id becomes murky fast. Secondly we don't know at what point the user caches the metadata, so we have no idea where the "original-id" should point at. Preferably the one they have cached :) but we can have multiple users with caches at different times...

**Comment by fd0** [comment]
Hm, at the moment there's no metadata cache yet, so defining one (and the proper semantics of caching) is up to us. Maybe an example is better suited to explain what I had in mind:

Let's say we have a snapshot without any tags, like this (from `doc/Design.md`), saved as id `22a5af1b`:
```json
{
  "time": "2015-01-02T18:10:50.895208559+01:00",
  "tree": "2da81727b6585232894cfbb8f8bdab8d1eccd3d8f7c92bc934d62e62e618ffdf",
  "dir": "/tmp/testdata",
  "hostname": "kasimir",
  "username": "fd0",
  "uid": 1000,
  "gid": 100
}
```

Then, a tag `foo` is added, the original snapshot is deleted and a new document is stored in the repo, with the storage ID `4af9501b`:
```json
{
  "time": "2015-01-02T18:10:50.895208559+01:00",
  "tree": "2da81727b6585232894cfbb8f8bdab8d1eccd3d8f7c92bc934d62e62e618ffdf",
  "dir": "/tmp/testdata",
  "hostname": "kasimir",
  "username": "fd0",
  "uid": 1000,
  "gid": 100,
  "tags": ["foo"],
  "id": "22a5af1bdc6e616f8a29579458c49627e01b32210d09adb288d1ecda7c5711ec"
}
```

When the tags `bar` and `baz` are added and the `foo` tag is removed, the snapshot document is deleted from the repo and a new one is stored, e.g. with storage ID `ec25006c`:
```json
{
  "time": "2015-01-02T18:10:50.895208559+01:00",
  "tree": "2da81727b6585232894cfbb8f8bdab8d1eccd3d8f7c92bc934d62e62e618ffdf",
  "dir": "/tmp/testdata",
  "hostname": "kasimir",
  "username": "fd0",
  "uid": 1000,
  "gid": 100,
  "tags": ["bar", "baz"],
  "id": "22a5af1bdc6e616f8a29579458c49627e01b32210d09adb288d1ecda7c5711ec"
}
```

So for the first snapshot (which does not have an `id` field), the ID is the storage hash (this is how it's handled in restic today), for the second and third snapshot the ID is the contents of the `id` field, so we know that this is the same snapshot as the first one, module metadata.

For caching of the snapshots themselves we can just use the storage hashes, they will change whenever metadata changes (e.g. the tags). For caching of other data related to the snapshot, we can use the original snapshot ID (if it has one), otherwise the storage hash.

Was that clearer?

**Comment by middelink** [comment]
Clearer and more scarier :) I'll make the necessary changes to my PR

Nit: Should it be called persistent_id?

**Comment by fd0** [comment]
Hm, there's no non-persistent ID, or any other ID for that matter, so I think `id` is better. Why is it scarier? What do you have in mind that can go wrong? Even if the same snapshot (with different tags) is cached somewhere, the ID field allows restic to group the same snapshots together...

**Comment by middelink** [comment]
Ok, `id` it is.

Scarier in the sense that we now have data we depend on, which is not really discoverable/recoverable by re-indexing or what every means of recovery we apply. Then again, if we lose the `id` field somehow, we can invalidate the cache and it would index using the new snapshot id. So as long that will be the only dependency we're good. I just fear creeping featurism.

**Comment by middelink** [comment]
Not cool. `type Shapshot` already has an non-exported `id` field. Guess we will have a `originalID` fieldname afterall (which I will expose in json as `id`).

**Comment by fd0** [comment]
Hm, let me check if we need the `id` field for `Snapshot` at all...

**Comment by fd0** [comment]
Uh, yes, it's needed. Never mind.

**Comment by middelink** [comment]
Actually, grumble. I can't even expose it as `id`. cmd_snapshot creates it's own `type Snapshot` to expose as such.

**Comment by fd0** [comment]
Then maybe the other field name you suggested is the better choice after all. Some parts of the restic code are not as polished as they could be, I'm afraid.
