### ISSUE TITLE
Decide json field names

### ISSUE THREAD

**Issue by fd0** [restic/restic#89]
From the first release on it will be guaranteed that repositories created with older versions of restic are still readable, eventually a command for migration is offered. Therefore we should decide on all json field names before the first release.

**Comment by fd0** [comment]
Ah, this is too late anyway. We'll keep the current field names for now.

**Comment by rawtaz** [comment]
Isn't it better to settle on field names now before the release, instead of later? Im not sure why it'd be too late. The software is not even beta, so it should be natural to everyone having the slightest understanding of software versioning that the software might change and break BC at this stage.

Better settle on good naming now than having to live with bad naming later, unless it's easy to change later on.

**Comment by fd0** [comment]
This just applies to the naming of the json fields stored in the backend, it's rather unlikely that users will get in contact with it at all. Any ideas for better field names? All the fields are documented here:
https://github.com/restic/restic/blob/master/doc/Design.md

**Comment by rawtaz** [comment]
I think most of it looks fine, but the key file fields has names like "N" which for the sake of consistency (over possible technical terminology) might be better off as "n".

I'm also thinking that maybe fields representing parameters to the KDF algorithm should perhaps not be named with just a character like now? What when there's a parameter named "salt", or is there never? Would it perhaps be a good idea to put the "N", "r", and "p" fields in their own object with a field name like "params" or similar? That way they won't ever collide with any other fields in case the KDF is changed.

In general, should any of the "length" and/or "size" field names be changed to one another, to be more coherent?

Personally I'd use "chunkerPolynomial" rather than "chunker_polynomial", but I guess you made a choice on that part already :+1:

**Comment by fd0** [comment]
> I think most of it looks fine, but the key file fields has names like "N" which for the sake of consistency (over possible technical terminology) might be better off as "n".

Ah, that was intentional: The parameter is called `N` throughout the paper describing scrypt, so I'd like to keep it that way.

>  What when there's a parameter named "salt", or is there never?

The `salt` is precisely a parameter to the KDF :)

>  Would it perhaps be a good idea to put the "N", "r", and "p" fields in their own object with a field name like "params" or similar? That way they won't ever collide with any other fields in case the KDF is changed.

I've thought about that and discarded it. The key object contains two types of things: KDF parameters and optional information about the key (e.g. hostname, timestamp, etc). I tried to keep it as simple as possible.

> In general, should any of the "length" and/or "size" field names be changed to one another, to be more coherent?

For a file/node it's definitely `size`, for the blobs I think the field name came from the `len()` function used in Go to determine the length of a slice. I could also live with `size` for both, but I don't think that this is so important to warrant a change.

> Personally I'd use "chunkerPolynomial" rather than "chunker_polynomial", but I guess you made a choice on that part already :+1:

I'm under the impression that most JSON field names e.g. in APIs are written with underscore characters instead of camel case, so I went for it.
