### ISSUE TITLE
ftp backend

### ISSUE THREAD

**Issue by rhauptmann** [restic/restic#928]
Feature request: plain ftp backend

I'm happy to help in testing code if needed.

**Comment by fd0** [comment]
Huh, FTP is still a thing? ;)

**Comment by rhauptmann** [comment]
yes, some provider support support only ftp or webdav (i think webdav is complex to integrate). ftp is an easy and simple solution (for me)

**Comment by rmalayter** [comment]
My vote for this would be "won't fix". The only way to kill insecure legacy protocols is to stop using them in all new development. This would force providers who offer only insecure FTP to upgrade.

Plain http should support should also be removed IMHO.

**Comment by fd0** [comment]
I'm closing this issue, we won't implement this (at least not for now).

**Comment by jpic** [comment]
@rmalayter correction, this stucks people with ftp backup servers on duplicity :joy: :joy: :joy:
Jokes apart, I though the point of encrypting backups was also to move them on unsecure channels ...

**Comment by dimejo** [comment]
> Jokes apart, I though at least one of the points of encrypting backups was also to move them on unsecure channels ...
> I'll just make a local backup and secure it with the secure ftp my provider provides, which is firewalled to be useable from my server only ...

You are assuming that no-one ever gets access to your data. Can you guarantee that your hosting provider doesn't read your data and that your account never gets hacked (e.g. via bruteforce attacks)?

**Comment by sijad** [comment]
in a private network FTP do the job, can I look around to see if I can add FTP backend support?

**Comment by rawtaz** [comment]
@sijad I'm not the one to make the call on what you're asking, but what I can say is that #1561 is progressing pretty nicely, so I would think that sometime soon (note: I'm not suggesting any time expectations by saying that) you should be able to use FTP as backend once restic and rclone work together (rclone as a backend to restic).

Perhaps that's a better path forward in terms of FTP support, than to start doing work to support FTP in restic (it hasn't been viewed as a really good thing in the context of killing off a legacy protocol such as FTP).

I understand your use case though.

**Comment by giordy** [comment]
I would like to add to what @sijad said, that another aspect to consider is that often home NAS devices provide FTP as the *only* real option for backup (other than using their own tools such as QSync).

I was thinking to migrate my parents/brothers computers to Restic but I'll have to wait that #1561 gets released because of this reason.

**Comment by rawtaz** [comment]
What home NAS is it that doesn't support anything but FTP for file sharing? I never encountered such a NAS.

**Comment by giordy** [comment]
I'm using a QNap TS-212. 

In the internal network I could use NFS or SMB besides FTP. However some laptops are frequently outside the home network and I need to ensure that they get backuped as well. NFS and SMB are not really an option over the internet and the QNap leaves me with 2 options only: SSH that can be used by admin users only and FTP. And since I don't want to distribute admin credentials for everyday use the only truly viable solution left is FTP.

I must admit though that tonight while researching more about my model I found a page in a wiki that explains that it's possible to install openssh and overcome this limitation. So I guess that it's a bit less of a problem now 🤷🏻‍♂️

**Comment by gliptak** [comment]
Many tp-link routers have only FTP shares (out-of-the-box). An example:

https://www.tp-link.com/en/support/faq/781/

So while FTP is obsolete, users might find it the easiest to configure/use within their setup.

**Comment by fd0** [comment]
You can use it via the `rclone` backend, which supports ftp: https://rclone.org/ftp/

**Comment by dkmbw** [comment]
We use FTP and FTPS (FTP over SSL) at work (really, both...). It would be really cool if restic would support that, too.

**Comment by dimejo** [comment]
Looks like the guys at rclone have started working on FTPS support: ncw/rclone#3150

**Comment by BB-999** [comment]
I wanted to comment just to explain how I got round this problem.  My NAS does sftp and ftp, but ftp is more the ten times faster,  Backups with restic's sftp backend were too slow compared to duplicity using ftp and I **so** wanted to switch!

rclone looked to be the way forward, but even though a direct `rclone copy bigfile nas:` command ran at 15MiB/s, restic was still running at 1.2MiB/s.  It truns out the leaving the two TLS parameters balnk in rclone's config is not the same a setting them to "false".  With them set to false (which is supposed to be the default) results in `restic backup rclone:nas:repo` running at nearly 15MiB/s.

Aside: I tried mounting the nas with `curlftpfs` and using restic with a "local" repo, but restic init failed being unable to create the key file.  I can go back and recreate the exact error ig anyone wants to know, but I doubt that fixing this rather convoluted way of using an old protocol is a concern.

**Comment by Xavron** [comment]
> My NAS does sftp and ftp, but ftp is more the ten times faster

That's more complicated than that. SFTP/SCP can both transfer faster, just not by default, just not easily with Restic. Some speed tests I did on 2.5 Gig LAN. These tests are all in Megabytes and the speed difference isn't much. Tests done with single multi GB file.

- SCP 263 MB/sec using "scp -c aes128-gcm@openssh.com -X buffer=256000 file user:file" see also https://unix.stackexchange.com/questions/48399/fast-way-to-copy-a-large-file-on-a-lan

- SFTP 248 MB/sec using "sftp -P port -c aes256-gcm@openssh.com -B 256000 user@ip"

- FTP plain 290MB/sec

There's some problems for speed though with Restic.

- Restic splits files. [--pack-size](https://restic.readthedocs.io/en/stable/047_tuning_backup_parameters.html#pack-size) is of limited help here. Could make a difference https://github.com/restic/restic/issues/4371

- SFTP buffer isn't something Restic seems to allow to set.

- May make sense to add, that in comparison, there is backup software that can create files without splitting. I use one that can make a 64GB file really fast, sending it can saturate 2.5 Gig no problem since its one big file. Hasn't been a problem at all for the SSD its on. (Clarification: It creates one big file for first backup, then adds variable sized files after, so it doesn't repack the same file, and keeps file counts to a minimum: one file per backup.)

There's a lot of things that drastically affect speed that are outside the scope of this post.

I just wanted to add a reference that SFTP can make use of speed much the same as FTP. Its easy to think it can't because of how things are.

- More or less there can be some reasons to use FTP(S). But, that's a complicated topic. Such as ease of use, limitation of device, limitation of search, limitation of documentation, battery use, electricity use, and more. There's a lot of possibilities and reasons.
