### ISSUE TITLE
Please provide a docker container that's empty besides a restic binary with the latest version

### ISSUE THREAD

**Issue by pandrew** [restic/restic#931]
I think it would be great if we could have an official, really small docker image using scratch as a base. Switching to tar and set exec permission for the release binaries would be a step in that direction. That would solve docker unpacking the binary using ADD. Thoughts on this?

**Comment by fd0** [comment]
Hm, I'm not sure I understand what you're suggesting, so I'm trying to paraphrase: "Please provide a docker container that's empty besides a restic binary with the latest version". Is that correct?

We're already providing pre-compiled binaries, just not as a tar file, but as a `.bz2`. I don't see the need for a tar at all...

**Comment by pandrew** [comment]
Thats correct. I  I know you provide the binary compressed using bzip2 however docker can't extract it using the ADD instruction  as it will only extract if its a tar archive and then compressed.

**Comment by fd0** [comment]
I've thought about this:

 * Providing a `tar` file: I'm not convinced that the effort is worth it, sorry. You can easily build a minimal docker container by downloading and decompressing a restic release and then using the `ADD restic /usr/bin` instruction in the `Dockerfile` with a local file as the source.

 * Providing a docker container: I'm not using docker and I'm not sure that this is the right way to use and distribute restic. Could you elaborate on how such a container would be used?

So I'm going to close this issue for now, please feel free to add further comments.

**Comment by pandrew** [comment]
I only see docker as an alternative way to use restic not your only option to the end user. There is plenty of people using docker, just saying. So i built a makefile that pulls restic, and builds a container from "scratch". However restic panics when im using it this way. 

```
docker run -it --volumes-from c4bb72af26fd -v $PWD/backup:/backup restic init --repo /backup
*setting password*...
paul@16:~$ docker run -it --volumes-from c4bb72af26fd -v $PWD/backup:/backup --rm restic -r /backup backup /var/jenkins_home
enter password for repository:
scan [/var/jenkins_home]
scanned 1199 directories, 3829 files in 0:00
panic: ioutil.TempFile: open /tmp/restic-temp-pack-606249968: no such file or directory

goroutine 16 [running]:
restic/archiver.(*Archiver).dirWorker(0xc4200c7540, 0xc4200c4620, 0xc42018c000, 0xc4202682a0, 0xc4202685a0)
        /tmp/restic-build-913727173/src/restic/archiver/archiver.go:403 +0xc7b
created by restic/archiver.(*Archiver).Snapshot
        /tmp/restic-build-913727173/src/restic/archiver/archiver.go:712 +0x67d

```
I guess restic needs /tmp directory then.

**Comment by fd0** [comment]
You're right, restic will need a temporary directory. There will be other things, like a user/group database (otherwise the `user` and `group` fields in the backup will be empty, only the UID/GID field is filled)...

**Comment by Niondir** [comment]
Not exactly empty but maybe I could add it as a special build:
https://github.com/Lobaro/restic-backup-docker

I would accept pull requests, if I find time I might just implement it.

https://github.com/Lobaro/restic-backup-docker

**Comment by tyranron** [comment]
Another implementation here (just raw `restic` Docker image):  
https://github.com/instrumentisto/restic-docker-image

Advantages:
- `alpine` based (as slim as possible)
- simple tests included

@fd0 can I pretend to make it an official `restic` Docker image and move the repo into your org? I will continue to maintain it.

**Comment by fd0** [comment]
Uhm, how is that different from the official image we provide at https://hub.docker.com/r/restic/restic/?

Source is here: https://github.com/restic/restic/blob/master/docker/Dockerfile

**Comment by rawtaz** [comment]
@tyranron Bonan verko! Curious though, could FUSE be added?

@fd0 Who maintains the current restic Docker image?

**Comment by tyranron** [comment]
@rawtaz [done](https://github.com/instrumentisto/restic-docker-image/commit/c8395b8ba377bb6e188d56e46af795e3110ffac1).

**Comment by fd0** [comment]
I'm trying to maintain the image, which has been contributed by somebody else. It'd be great if we could merge the images! Maybe we should have a dedicated repo for that, similar to the `restic/builder` repo (which is another image I maintain...)?

I'm not using restic via docker myself though.

**Comment by rawtaz** [comment]
I agree a separate repo is a good idea. And if @tyranron is happy to maintain the image it would be a nice addition to manpower :)

**Comment by tyranron** [comment]
@fd0 yup... +1 for separate repo. Actually, I can transfer my repo into `restic/docker-image`, and update the stuff. Would you be so kind to invite me into restic org?

**Comment by fd0** [comment]
I'm swamped with a bunch of other stuff, this might take a few days. For a start, I'd like to work with you via pull requests, is that okay for you?

**Comment by tyranron** [comment]
@fd0 yup, totally.

**Comment by tyranron** [comment]
@fd0 ping. Is this still intact?

Since 4 years, I've reworked image toolchain quite a bit:
- Now it's built via GitHub Actions and is published to 3 registries ([Docker Hub](https://hub.docker.com/r/instrumentisto/restic), [GitHub Container Registry](https://github.com/instrumentisto/restic-docker-image/pkgs/container/restic), [Quay.io](https://quay.io/repository/instrumentisto/restic))
- It has now [immutable tags in form of `<version>-r<revision>`](https://github.com/instrumentisto/restic-docker-image/tree/0.14.0-r1#xyz-rn).
- All the changes to the image are carefully [logged](https://github.com/instrumentisto/restic-docker-image/blob/0.14.0-r1/CHANGELOG.md).

If you're still interested in merging our efforts, I can start working towards it. There is no need for a separate repo for this. It could be naturally integrated into this one, with its separate `Docker CI` pipeline (so solving #3547). I have already nice experience of doing this [for Coturn](https://github.com/coturn/coturn/tree/docker/4.6.0-r1/docker/coturn).

Also, I have a ready solution for maintaining multi-arch Docker images, so solving #2359 would be quite easy for me.

Once all the work is done, and I deprecate `instrumentisto/restic` image, it would be easy for me to continue maintaining the image here, as I do for Coturn. You may add me as a collaborator, or if you mind, I can do that via PRs (thus, requiring a little bit more effort from you).

**Comment by tyranron** [comment]
@fd0 ping
