### ISSUE TITLE
recommended backup strategy

### ISSUE THREAD

**Issue by rupat** [restic/restic#934]
Note: This is more a question than an error report or issue
the recommended way to backup files in documentation is to run restic on the machine to backup and let connect it to a remote repo or local mounted filesystem. 

lets assume i want to use one repo for:
lokal system,
a remote server
a virtual machine

how i do this

lokal system -> trivial 

a remote server
- A) remoteserver runs restic to vpn connected repo (nfs) or Rest server or so
- B) backup machine runs restic and mounts remote server per nfs 

Variant A has the problem that an infiltrated remote server opens the door for the attacker to also delete all of my backups. so that is not an option. best would be to make the backup on remote server and let the backup machine get this backup 
Or how can i safe backup a remote_server without giving access to the "need to be safe last stage"-backup_repository

is there a possibility to have cascaded backup repositories like in git ?

the virtual machine filesystem
adding files from the mounted filesystem of another host, is there an --host attribut ?

**Comment by fd0** [comment]
At the moment, restic is "push only", which means that it writes the backups to some location. There's issue #299 which tracks a pull mode that may be implemented eventually.

You can solve this for example by using the sftp backend and regularly (e.g. with a cron job) chown the files and dirs in the repo so that new files can be added but old ones cannot be removed. For the `backup` command, restic will only ever create new files, never delete files (except in the `locks` directory).

Another possibility would be to use the `s3` backend with Amazon s3 and configure the user credentials used for accessing it in such a way that only new files can be created.

Regarding your other question, please have a look at the help: `restic backup --help`, there's the `--hostname` option.

I'm going to close this issue for now as your question is answered. Feel free to add further comments.
