### ISSUE TITLE
S3 repo data subdirectory keyspace doesn't match sftp/filesystem, impacting performance/compatibility

### ISSUE THREAD

**Issue by vsivsi** [restic/restic#940]
Thanks for Restic. This is a bit of a quibble, but...

## Output of `restic version`

restic 0.5.0
compiled with go1.8 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)

Normal operation, per documentation

## What backend/server/service did you use?

S3 / Minio 
 
## Expected behavior

Repo layout (specifically the data directory) will be as documented here: 
https://restic.readthedocs.io/en/stable/Design/

```
/tmp/restic-repo
├── config
├── data
│   ├── 21
│   │   └── 2159dd48f8a24f33c307b750592773f8b71ff8d11452132a7b2e2a6a01611be1
│   ├── 32
│   │   └── 32ea976bc30771cebad8285cd99120ac8786f9ffd42141d452458089985043a5
│   ├── 59
│   │   └── 59fe4bcde59bd6222eba87795e35a90d82cd2f138a27b6835032b7b58173a426
│   ├── 73
│   │   └── 73d04e6125cf3c28a299cc2f3cca3b78ceac396e4fcf9575e34536b26782413c
│   [...]
├── index
│   ├── c38f5fb68307c6a3e3aa945d556e325dc38f5fb68307c6a3e3aa945d556e325d
│   └── ca171b1b7394d90d330b265d90f506f9984043b342525f019788f97e745c71fd
├── keys
│   └── b02de829beeb3c01a63e6b25cbd421a98fef144f03b9a02e46eff9e2ca3f0bd7
├── locks
├── snapshots
│   └── 22a5af1bdc6e616f8a29579458c49627e01b32210d09adb288d1ecda7c5711ec
└── tmp
```

## Actual behavior

S3 repos do not implement the git-like "prefix fanout" subdirectories in the data directory. 

Here's why this is a problem.  

1) Performance. AWS S3 is not the only S3 implementation. While I'm sure that Amazon's AWS S3 implementation doesn't care whether or not you "fan out" your S3 key paths in this way, in turns out that it can make a big difference to Minio. Minio's filesystem directories replicate the S3 bucket/key paths. So if you use S3 / Minio as the storage backend and you use restic to back-up TBs of data, you end up with a `data` directory on the server that contains over 100,000 subdirectories. This is bad for performance for the same reason that it is for filesystem and sftp restic repos. The performance of most filesystems really suffers when a directory contains more than 100K entries.
  
2) Compatibility.  I expect to be able to easily mirror a filesystem Restic repo to S3 and vice-versa without any complications. The fact that the S3 backend does something different means that I can't pull a Restic Repo out of S3 and onto a normal filesystem and expect restic to work properly with it (even if restic recognized the repo in this case, the performance would be terrible).

So I guess my question is... Why doesn't restic just use the same paths for the S3 keyspace as it uses for directories on sftp and the filesystem?  It would solve the potential compatibility issues, and the performance problems that occur when the S3 compatible backend isn't AWS.

Maybe at least make it an option to use the standard layout for S3 backed repos?

Thanks for listening!

**Comment by vsivsi** [comment]
Another note: implementing the change required for this was really simple (ignoring backward compatibility, etc...)  

See: https://github.com/vsivsi/restic/commit/03c9dd607c365c5cafe36e8566ea3ffdd0249cdd

I'm going to use this change to do some large repo benchmarking with minio and see if there's a noticable performance difference.

I've already done a compatibility test of mirroring the resulting S3 repo to a filesystem and then running restic against it.  The only catch was that the `locks` path doesn't typically exist in S3, and so that subdirectory isn't automatically created in the FS. restic is brittle in this respect, a filesystem repo without a `locks` subdirectory results in a Panic/Segfault in restic:

```sh
./bin/restic check -r /Volumes/RAID1/restic_test/repo3/
# Create exclusive lock for repository
# Load indexes
# Check all packs
# Check snapshots, trees and blobs

rmdir /Volumes/RAID1/restic_test/repo3/locks

./bin/restic check -r /Volumes/RAID1/restic_test/repo3/
# Create exclusive lock for repository
# panic: runtime error: invalid memory address or nil pointer dereference
# [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1240462]
# 
# goroutine 4 [running]:
# restic/backend/local.isFile(0x0, 0x0, 0x0)
# 	/Users/vsi/restic/src/restic/backend/local/local.go:203 +0x22 
# restic/backend/local.(*Local).List.func1.1(0xc42007a300, 0x26, 0x0, 0x0, 0x1761020,  0xc42007a360, 0x0, 0xc42007a300)
# 	/Users/vsi/restic/src/restic/backend/local/local.go:218 +0x5f
# path/filepath.Walk(0xc42007a300, 0x26, 0xc4200d0de0, 0x1, 0xc4200d0de0)
#	/usr/local/Cellar/go/1.8.1/libexec/src/path/filepath/path.go:396 +0x8f
# restic/fs.Walk(0xc42007a300, 0x26, 0xc4200d0de0, 0xc42007a300, 0x26)
# 	/Users/vsi/restic/src/restic/fs/file.go:117 +0x3f
# restic/backend/local.(*Local).List.func1(0xc4200743c0, 0xc4201acab0, 0x153ccc2, 0x4, 0xc420074300)
# 	/Users/vsi/restic/src/restic/backend/local/local.go:229 +0xfb
# created by restic/backend/local.(*Local).List
#	/Users/vsi/restic/src/restic/backend/local/local.go:230 +0x103
```

**Comment by fd0** [comment]
Hi, thanks for bringing it up. This issue (or at least a part of it) was already discussed in a few times in other issues. In PR #898 I've added a layer called `Layout` and clarified the documentation. The code from the PR is not yet part of any released version, you can find it in the master branch here https://github.com/restic/restic/blob/master/src/restic/backend/layout.go and in the documentation here: https://restic.readthedocs.io/en/latest/references.html#object-storage-based-repositories

The different directory names for the s3 backend and the local backend have been introduced accidentally. This will be corrected in the near term (while keeping backwards compatibility).

The new code will (when using the local or sftp backend) automatically detect the used layout, so syncing from an s3 repo to local disk allows using the repo directly. You don't need any code for that. At the moment there's no layout auto detection code for the s3 backend, so the other way around (creating a local repository, syncing that to s3 and accessing it over s3) won't work. 

As for your other suggestion, adding the intermediate directories also for s3, I'm not convinced that this is a good idea. The local/sftp storage format uses exactly one level of intermediate directories. That's an implementation detail, as viewed from restic. On the s3 side, we're just accessing URLs/objects in a cloud service we don't know anything about. After all, minio is no the only s3 compatible cloud service out there. I think leaking such an implementation detail for one backend into the specification of a different backend is not a good idea.

I acknowledge the need for opening e.g. s3 repositories locally, e.g. via a fuse file system or when you download the repo and try to restore from it. That's why I implemented the layout and auto detection code.

I've said it in other issues but I'll repeat it again here (we need to move this to the faq sometime): The absolutely most important thing in the whole project is neither code, nor usability, nor interoperability or supporting all kinds of workflows: It's the stability of the repository format. We assure our users that it'll be possible to restore from a repo (via the same access mechanism/backend), no matter what. So we (as a project) are **very** conservative regarding **any** changes in the repository format and/or data structures. :smile:  

Thanks for reporting the panic when the `locks` directory does not exist, that's something we can (and should) fix easily.

I'm going to close this issue for now, please feel free to add further comments.

**Comment by vsivsi** [comment]
> As for your other suggestion, adding the intermediate directories also for s3, I'm not convinced that this is a good idea. The local/sftp storage format uses exactly one level of intermediate directories. That's an implementation detail, as viewed from restic. On the s3 side, we're just accessing URLs/objects in a cloud service we don't know anything about. After all, minio is no the only s3 compatible cloud service out there. I think leaking such an implementation detail for one backend into the specification of a different backend is not a good idea.

The problem isn't that you are leaking the "file system" implementation detail into S3, the problem is actually the reverse... By assigning a layout to S3 that we know only *some* implementations of S3 can handle (and virtually no mounted filesystems), you are allowing the "AWS S3" implementation determine what is possible on other backends. 

This will never be more true than the first time you try to mirror a valid restic repo with over 1 million files in the `/data` directory to a local filesystem. It will choke. Please keep in mind that 50-100TB repos will be commonplace within the useble lifespan of Restic. Repos of this size will create approximately 6-12 million files in the `/data` directory. Local file system are not designed to deal with directories that large.

Please at least allow the *option* to create fanned out data directory layouts on S3. It does zero harm to the AWS case, requires zero additional code, and solves all of the issues I raise above.

**Comment by fd0** [comment]
Let me think about this. Is using minio/s3 a hard requirement for you? Did you maybe have a look at the REST server at https://github.com/restic/rest-server? The protocol is much more lightweight and does the right thing in terms of local data storage...

**Comment by vsivsi** [comment]
> We also need to be able to detect the proper layout (which is easier for a local file system, but may be hard for s3)

I believe you already need to solve this problem if you are serious about being able to mirror an existing filesystem repo directly into S3 and having it "just work". It's unfortunate that the S3 repo layout already differs from the filesystem layout for no good apparent reason. I'm sure there some history there...

Yes, minio/s3 is a hard requirement. We are building a storage cluster to collect data from scientific instruments deployed on research ships at sea. The satellite internet on such ships is intermittent, slow and very expensive, so AWS will not work, and we have hard fault-tolerance requirements for both data-integrity and service availability. I've looked at the REST solution, but it does not satisfy these requirements in the way that distributed minio does.

**Comment by vsivsi** [comment]
Just to add: I understand well your conservatism with regards to changes in the repository format.

As an outsider to the project what I see here is that the S3 support appears to have been added before all of these interoperability questions surfaced.

Unsolicited advice: Personally, if I were in your shoes, I would standardize on the filesystem layout and deprecate the existing "old" S3 layout, supporting it for several releases with a warning while providing a "migration tool" to easily update a repo to the standard format. This way you can eventually get to one layout and contain all of the associated code to the "migration" codebase and not have it cruft-up your main codebase forever.

I think it is wasted effort to make your filesystem backends directly recognize the old S3 format that will complicate your codebase forever. Provide a migration path and move on...

My 2c

**Comment by vsivsi** [comment]
Here is another reason, the current naive implementation of `List` in the S3 code will lead to heavy memory demands as repos grow into the TB range.  So in this code:

https://github.com/restic/restic/blob/master/src/restic/backend/s3/s3.go#L296

In this code, `Listresp` will require the allocation of hundreds of megabytes of RAM for repos holding 10 or more TB of data.  And the S3 APIs will probably groan under the weight of moving around millions of key names in this way.  For scalability, and to keep memory use reasonable, you are going to need to batch up requests in List operations like this, and a prefixed keyspace as used in the filesystem layout is a natural way to accomplish that.

**Comment by fd0** [comment]
So, I've thought about this and I think we need to do something mid-term. I'm not yet sure what that is exactly, so I'll write down my thoughts. Maybe we can figure it out together. :)

Here are several different things to consider (in no particular order):
 1) Not using subdirs will slow down operations a lot when used with s3/minio
 2) There's the (implicit?) assumption that copying over files from different backends works
 3) With the current code, listing a large s3 repo will use much memory

-----

To 1: I'm really not sure how to proceed here. Do you know if there are other s3 implementations (including AWS S3) that are harmed by adding one level of subdirs?

I've settled on the structure for the local backend (one subdir level below `data/`, with the two chars of the filename for a name) after experimenting with it for a bit, but I'm not at all sure that this is the best choice. What happens when we later find out that using four chars for the filename works best with minio, and two chars works best with a local file system? Any idea how to proceed further here? Sure, we could just standardize on the local filesystem layout for all backends, but that may just buy us a little time...

-----

To 2: Is this mentioned somewhere at all? I don't think so. Where does the assumption come from? Maybe make it explicit, either by saying "it works" or "it does not work, and if it works it's by accident and you cannot rely on it"? Is it even necessary? I've outlined a few thoughts here (I forget that issue completely, just rediscovered it): https://github.com/restic/restic/issues/654

To 3: Keyspace partitioning can be used to accomplish that (no subdirs needed, as far as I know), but a better solution is to use pagination in `List()`. We should probably already done that.

**Comment by middelink** [comment]
@vsivsi can you explain this comment?
> Here is another reason: the current naive implementation of List in the S3 code will lead to heavy memory demands as repos grow into the TB range

As far as i can tell it is using a channel into https://github.com/minio/minio-go/blob/master/api-list.go#L259 , so there should be at most 1000 objects in flight, no? Still not nothing, but I'm not seeing 100ths of MBs either.

BTW having subdirectories under /data won't alleviate this memory problem, right? restic asks for a recursive search, so `ListObjects()` will still find a gazillion number of files.

**Comment by vsivsi** [comment]
@middelink   You are correct.  I haven't used the `minio-go` package before, so I didn't know what type was being returned by `listObjects()`. 

One wrinkle with reading golang code is that such important underlying implementation details can be obscured in code like this...

Defining `listresp` as:

`listresp := be.client.ListObjects(be.bucketname, prefix, true, done)`

hides its type.

Which is then further obscured by `listresp` only being consumed as:

`for obj := range listresp {  ...  }`

Where `range` can accept any interable.

Thanks for the clarification!

**Comment by vsivsi** [comment]
@fd0  Thanks for your response/thoughts.

> 1) Not using subdirs will slow down operations a lot when used with s3/minio

I believe this is a medium-term problem with using minio.  If the minio team are serious about making it a "drop-in" replacement for AWS S3, then they are going to need to properly support buckets with an essentially unlimited number of files on top of all supported backing file systems.

File systems themselves are slowly getting better in this respect too. Notably ext4 and zfs now do proper indexing of directories by filename to support such cases. But the filesystems themselves aren't the only issue. Tons of other software breaks when directories get so large.  A prominent example being shell globbing, which is entirely broken for directories with more than ~10,000 files in bash and many other shells. Backup systems are another worry.  Have you tried pointing restic at a directory with 10 million files in it? What happens?

This stackoverflow topic is a pretty good resource:  http://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory

I guess the takeaway is that this remains a real issue for the lifetime of packages like restic and minio. If you want to support older filesystems like FAT32/NTFS/ext2/ext3 then you can't safely write more than about 50K files/subdirs per directory. Someday it won't matter, but today it still does.

> 2. There's the (implicit?) assumption that copying over files from different backends works

Yes, I at least have this expectation when the backend in question uses a "filepath" like organization and there are tools that support easily mirroring repos between the two backends, as is clearly the case for S3 and local filesystems.

And I think there are important use cases that will cause issues to arise again and again if this isn't the case. Here's a simple one:

I use restic in a small office to perform machine backups to a RAIDed NAS device on the local network. I don't control its OS/filesystem, and I just want it to work. Then, at some point it become desriable to migrate or mirror those backups to the cloud, and using AWS S3 or a compatible hosted service seems like a good bet. How do I copy the office's entire restic repo, with all of its history, from the NAS to S3 and have it *Just work*™?  

Today it won't, because if I just `mc mirror /local/nas/mount myminio/backupbucket`, the repo will be in the wrong layout for S3, and restic it won't recognize it. Game over.

If the storage backend is some kind of KV store that doesn't support "paths" analogous to a local filesystem, then there is no obvious way to "mirror" the data, and this expectation can be relaxed. But I argue that there should be an easy way to mirror a complete working restic repo from any supported backend to any other. As far as I can tell, that doesn't exist right now.

> 3.   Keyspace partitioning can be used to accomplish that (no subdirs needed, as far as I know)...

Correct.

**Comment by fd0** [comment]
@vsivsi thank you very much for raising this issue, and being persistent about it! I've thought about this for a bit, and the scaling issue wasn't on my radar at all. The only solution that I can think of is implementing the same strategy like git: Allow pack files to be arbitrary large. In addition, maybe we can move towards a unified naming scheme/layout. Turns out one of my reservations against that was that in the back of my mind I always thought that we may need to change the layout for the local backend, in order to allow more files. But after having spent some time to think about it I'm confident that this is not the way to go. So, thanks!

**Comment by vsivsi** [comment]
Restic is a great project and we are committed to using it now, so I'm happy to help in any way I can to contribute ideas/improvements.

**Comment by fd0** [comment]
I'm going to close this issue for now, the move towards a unified layout is tracked/discussed in #965 (so this issue is superseded by it).
