### ISSUE TITLE
Dedup not working

### ISSUE THREAD

**Issue by andrewchambers** [restic/restic#95]
```
[andrew@blackheart ~]$ restic init
created restic backend at /home/andrew/restic/
[andrew@blackheart ~]$ 
[andrew@blackheart ~]$ du -sh ~/restic/
36K	/home/andrew/restic/
[andrew@blackheart ~]$ restic backup ~/Desktop/10-million-combos.zip 
scan [/home/andrew/Desktop/10-million-combos.zip]
[0:00] 0 directories, 1 files, 84.732 MiB
Done in 0:00
[0:01] 100.00%  76.534 MiB/s  84.732 MiB / 84.732 MiB  1 / 1 items  ETA 0:00
duration: 0:01, 84.73MiB/s
snapshot 1123c2d6 saved
[andrew@blackheart ~]$ du -sh ~/restic/
86M	/home/andrew/restic/
[andrew@blackheart ~]$ restic backup ~/Desktop/10-million-combos.zip 
scan [/home/andrew/Desktop/10-million-combos.zip]
[0:00] 0 directories, 1 files, 84.732 MiB
Done in 0:00
[0:01] 100.00%  76.534 MiB/s  84.732 MiB / 84.732 MiB  1 / 1 items  ETA 0:00
duration: 0:01, 84.73MiB/s
snapshot 8169b203 saved
[andrew@blackheart ~]$ du -sh ~/restic/
171M	/home/andrew/restic/

```

The entire file is stored twice. Each time the blobs in ~/restic/data are different.

Also, why the name restic?

**Comment by lImbus** [comment]
On Thu, Mar 5, 2015 at 11:10 AM, andrewchambers
<notifications@github.com> wrote:
> [andrew@blackheart ~]$ restic init
> created restic backend at /home/andrew/restic/
> [andrew@blackheart ~]$
> [andrew@blackheart ~]$ du -sh ~/restic/
> 36K /home/andrew/restic/
> [andrew@blackheart ~]$ restic backup ~/Desktop/10-million-combos.zip
> scan [/home/andrew/Desktop/10-million-combos.zip]
> [0:00] 0 directories, 1 files, 84.732 MiB
> Done in 0:00
> [0:01] 100.00%  76.534 MiB/s  84.732 MiB / 84.732 MiB  1 / 1 items  ETA 0:00
> duration: 0:01, 84.73MiB/s
> snapshot 1123c2d6 saved
> [andrew@blackheart ~]$ du -sh ~/restic/
> 86M /home/andrew/restic/
> [andrew@blackheart ~]$ restic backup ~/Desktop/10-million-combos.zip
> scan [/home/andrew/Desktop/10-million-combos.zip]
> [0:00] 0 directories, 1 files, 84.732 MiB
> Done in 0:00
> [0:01] 100.00%  76.534 MiB/s  84.732 MiB / 84.732 MiB  1 / 1 items  ETA 0:00
> duration: 0:01, 84.73MiB/s
> snapshot 8169b203 saved
> [andrew@blackheart ~]$ du -sh ~/restic/
> 171M    /home/andrew/restic/
>
> The entire file is stored twice. Each time the blobs in ~/restic/data are
> different.

I suppose you are using environment variables for the location of the password ?

I do not remember exactly, but would you not have to specify the
snapshot ID of the frist run to the second run ?
It could be that restic now has just created two different backups
without noticing that it is the same file. That would arguably be a
bug.

>
> Also, why the name restic?

I happen to know that there is no official answer to that question yet :)

**Comment by andrewchambers** [comment]
The fundamental reasons for using rabbin hashes and content addressable blob store is that cases like this are automatically deduplicated automatically.

It defeats the purpose of restic if this is not a bug.

**Comment by kamudadreieck** [comment]
You have to specify the id of the prior backup to enable deduplication. 
If I remember correctly, restic uses a new IV and key for each backup and blob, so the deduplication cannot work, unless you say that it should use the prior key.

Unfortunately the incremental backup feature is deactivated since its broken after memory-optimizations.
https://github.com/restic/restic/issues/90#issuecomment-74443936

**Comment by andrewchambers** [comment]
I forgot to mention that i did specify a parent on other runs, thanks for the info.
I think the docs on duplication need to be updated. 

I would think a single key per repo would be fine, if a user cares about that, it makes more sense to create a new repo in my opinion. Each to their own.

**Comment by fd0** [comment]
Thanks @andrewchambers for opening this issue, it is indeed a bug. Even if no parent snapshot is specified, restic should load all known blobs from the repository before creating a backup in order to maximize deduplication. Ultimately, restic should figure out a matching parent snapshot by itself, but this hasn't been implemented so far.

I'm currently refactoring/reworking the internal processing pipeline for the backup process itself, this is probably the cause. I'll have a look at it this evening and also add a test for it. @andrewchambers which git commit did you test (use `git show` or run `cmd/restic/version.sh`)?

For clarification: At the moment there is one master encryption key and one master signing key per repository. All data is encrypted and signed using these keys. The master keys can be decrypted with a repository password. A repository can have multiple passwords, but in the end the same master keys are decrypted with each password.

**Comment by andrewchambers** [comment]
Sorry, forgot to write it down, will update when I am back at my pc tomorrow.

**Comment by fd0** [comment]
I found the bug: during development I commented out loading all the blobs from a repository, shame on me for not having read the diff before commiting. Deduplication should work again (I also added a test to make sure this gets tested from now on), without specifying an old snapshot. Please have a look!
