### ISSUE TITLE
backup size should not include excluded dirs

### ISSUE THREAD

**Issue by legrostdg** [restic/restic#958]
The excluded dirs should not be included in the total scanned/remaining/backuped sizes.

**Comment by fd0** [comment]
They aren't.

**Comment by fd0** [comment]
```
$ tree
.
├── a
│   └── file
└── b
    └── file

$ du -sh *
100M	a
100M	b

$ restic backup --exclude a .                              
scan [/tmp/test]
scanned 2 directories, 1 files in 0:00
[0:00] 100.00%  0B/s  100.000 MiB / 100.000 MiB  3 / 3 items  0 errors  ETA 0:00 
duration: 0:00, 154.18MiB/s
snapshot 297d3a73 saved
```

**Comment by legrostdg** [comment]
OK, so I have a weird issue there. The excluded dirs are included in the backup size:

## Output of `restic version`

    $ restic version
    restic 0.5.0
    compiled with go1.7.4 on linux/amd64

## How did you start restic exactly? (Include the complete command line)

    $ restic -r sftp:user@myserver:/backup/laptop.restic --password-file password.txt --one-file-system --exclude=/var/cache --exclude=/var/tmp --exclude=/home/user/tmp --exclude=/home/user/.cache backup / /var /usr /home /boot /boot/efi

## What backend/server/service did you use?

sftp

## Expected behavior

around 100Gib in the backup size

## Actual behavior

    scan [/ /var /usr /home /boot /boot/efi]
    [2:45] 375041 directories, 4248360 files, 202.878 GiB     <- there should only be around 100GiB there, 202.878 GiB is the side including excluded dirs.
    scanned 375041 directories, 4248360 files in 2:45
    ...

## Steps to reproduce the behavior

not sure

## Do you have any idea what may have caused this?

no idea

**Comment by fd0** [comment]
Thanks for the report. First: Do you maybe have docker installed? It is known to leave a sparse file of 100GiB somewhere in `/var`, you can check with `du -sh /var` vs. `du -sh --apparent-size /var`.

If that's not it: Can you please create a debug log file while running a backup and have a look if you can spot anything out of the ordinary? Excluded paths [will have a log entry](https://github.com/restic/restic/blob/master/src/cmds/restic/cmd_backup.go#L444) there, so you should be able to spot them. Also paths excluded because they are on other file systems [will be logged](https://github.com/restic/restic/blob/master/src/cmds/restic/cmd_backup.go#L468).

**Comment by legrostdg** [comment]
You spoted the issue, `du -sh /var/lib/docker/``reported 166Go...

Is there a way restic could be improved to hide these sparse files from the total size?

**Comment by legrostdg** [comment]
(feel free to close this issue or change the title, my original problem is fixed. Thanks!)

**Comment by fd0** [comment]
Yeah, that'd be #79, when we start supporting sparse files at all. You can follow that issue if you'd like to be notified. At the moment it's just a cosmetic/UI issue, because saving the data is fast (restic only reads blocks of nullbytes and realizes very fast that it doesn't need to store anything).
