### ISSUE TITLE
Slow "restic prune" on Amazon s3 bucket

### ISSUE THREAD

**Issue by jncss** [restic/restic#973]
## Output of `restic version`
restic 0.5.0 (v0.5.0-162-gc5ae552)
compiled with go1.8.1 on freebsd/amd64

## How did you start restic exactly? (Include the complete command line)
restic prune -r s3:s3.amazonaws.com/... 

## What backend/server/service did you use?
Amazon s3

## Expected behavior
Be faster

## Actual behavior
$ restic prune -r s3:s3.amazonaws.com/...         

counting files in repo
building new index for repo
[28:12] 100.00%  42058 / 42058 packs
repository contains 42058 packs (800144 blobs) with 196.926 GiB bytes
processed 800144 blobs: 0 duplicate blobs, 0B duplicate
load all snapshots
find data that is still in use for 1 snapshots
[2:20:17] 100.00%  1 / 1 snapshots
found 744370 of 800144 data blobs still in use, removing 55774 blobs
will delete 48 packs and rewrite 3514 packs, this frees 759.835 MiB
[4:05:01] 59.22%  2081 / 3514 packs rewritten

2:20 hours finding data still in use, then almost 8 hours! to delete 48 packs and rewrite 3514, more than 10 hours to prune 760MB on a 200GB repository, is it normal?

To upload all the new data, 200GB, first "restic backup" did  take  4 hours.

## Steps to reproduce the behavior
"forget" some snapshots and then "prune" the repository

## Do you have any idea what may have caused this?
No, We have a very fast internet connection (fiber 1Gb. symmetric download/upload)

**Comment by fd0** [comment]
Thanks for the report. Since the 0.5.0 release, we've done a lot to improve the s3 backend, could you please try again with the [0.6.0-rc.1 version](https://github.com/restic/restic/releases/tag/v0.6.0-rc.1) we've released a few minutes ago?

Apart from that, the prune code (especially the part which detects which blobs are still referenced by snapshots) is not yet fully optimized, this is tracked in #738.

**Comment by fd0** [comment]
I'm going to close this issue for now, feel free to add further comments. Thanks!
